/////////// Wardring (+1 AC) ////////////

COPY ~IATweaks\resources\bam\s!ring20.bam~ ~override~
COPY ~IATweaks\resources\itm\s!ring20.itm~ ~override~
  SAY NAME2 @7002
  SAY IDENTIFIED_DESC @7003

// Kalah

COPY_EXISTING ~KALAH.cre~ ~override~
  ADD_CRE_ITEM ~s!ring20~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~LRING~

COPY_EXISTING ~KALAH2.cre~ ~override~
  ADD_CRE_ITEM ~s!ring20~ #0 #0 #0 ~NONE~ ~LRING~

// Tolgerias

COPY_EXISTING ~KALAH2.cre~ ~override~
  ADD_CRE_ITEM ~s!ring20~ #0 #0 #0 ~NONE~ ~LRING~

//////////// Blood Red Ioun Stone

COPY ~IATweaks\resources\bam\s!ioun01.bam~ ~override~
COPY ~IATweaks\resources\itm\s!ioun01.itm~ ~override~
  SAY NAME2 @7006
  SAY IDENTIFIED_DESC @7007

// Thief from Mencar's party

COPY_EXISTING ~SEVPAT05.cre~ ~override~     
  ADD_CRE_ITEM ~s!ioun01~ #0 #0 #0 ~NONE~ ~HELMET~

//////////// Symbol of Sehanine Moonbow

ACTION_IF(FILE_EXISTS_IN_GAME ~SPPR205.2da~) BEGIN
  COPY ~IATweaks\resources\bam\s!amul20.bam~ ~override~
  COPY ~IATweaks\resources\itm\s!amul20.itm~ ~override~
    SAY NAME2 @7009
    SAY IDENTIFIED_DESC @7010

  // Slaver Ship Priest of Cyric
  COPY_EXISTING ~SLAPRI.cre~ ~override~
    ADD_CRE_ITEM ~S!AMUL20~ #2 #2 #0 ~NONE~ ~INV12~
END

//////////// Snow Leopard Charm

COPY ~IATweaks\resources\bam\s!leopar.bam~ ~override~
COPY ~IATweaks\resources\bam\s!leopab.bam~ ~override~
COPY ~IATweaks\resources\itm\s!leopar.itm~ ~override~
  SAY NAME2 @7019
  SAY IDENTIFIED_DESC @7020

// Thax

COPY_EXISTING ~SHADRA01.cre~ ~override~     
  ADD_CRE_ITEM ~s!leopar~ #0 #0 #0 ~NONE~ ~INV16~

//////////// Improved Snow Leopard Charm

COPY ~IATweaks\resources\itm\s!amul21.itm~ ~override~
  SAY NAME2 @7021
  SAY IDENTIFIED_DESC @7022


//////////// Night Club

COPY ~IATweaks\resources\spl\s!clubni.spl~ ~override~
COPY ~IATweaks\resources\bam\s!clubni.bam~ ~override~
COPY ~IATweaks\resources\itm\s!clubni.itm~ ~override~
  SAY NAME2 @7014 
  SAY IDENTIFIED_DESC @7013 

// Damien from evil Underdark party

COPY_EXISTING ~GPTHIEF1.cre~ ~override~
  ADD_CRE_ITEM ~s!clubni~ #0 #0 #0 ~NONE~ ~INV12~

//////////// Sure Strike Club

COPY ~IATweaks\resources\bam\s!surehi.bam~ ~override~
COPY ~IATweaks\resources\itm\s!surehi.itm~ ~override~
  SAY NAME2 @7017 
  SAY IDENTIFIED_DESC @7018 

// Rengaard from Tarnor's party

COPY_EXISTING ~RENGAA.cre~ ~override~
  ADD_CRE_ITEM ~s!surehi~ #0 #0 #0 ~NONE~ ~INV12~

//////////// Backwhacker

COPY ~IATweaks\resources\spl\s!backwh.spl~ ~override~
COPY ~IATweaks\resources\bam\s!backwh.bam~ ~override~
COPY ~IATweaks\resources\itm\s!backwh.itm~ ~override~
  SAY NAME2 @7015
  SAY IDENTIFIED_DESC @7016
// TODO ADD THIS ITEM SOMEWHERE!

//////////// Girdle of Beatification

COPY ~IATweaks\resources\bam\s!belt10.bam~ ~override~
COPY ~IATweaks\resources\itm\s!belt10.itm~ ~override~
  SAY NAME2 @7025
  SAY IDENTIFIED_DESC @7026
// TODO ADD THIS ITEM SOMEWHERE!

//////////// Insulated Arcs of Disredain

COPY ~IATweaks\resources\bam\s!bel11b.bam~ ~override~
COPY ~IATweaks\resources\bam\s!belt11.bam~ ~override~
COPY ~IATweaks\resources\itm\s!belt11.itm~ ~override~
  SAY NAME2 @7027
  SAY IDENTIFIED_DESC @7028

// Librarian

COPY_EXISTING ~S!BOLICH.cre~ ~override~     
  ADD_CRE_ITEM ~s!belt11~ #0 #0 #0 ~NONE~ ~INV16~

//////////// Lucky Coin of Tymora

COPY ~IATweaks\resources\bam\s!misc90.bam~ ~override~
COPY ~IATweaks\resources\bam\s!mis90b.bam~ ~override~
COPY ~IATweaks\resources\itm\s!misc90.itm~ ~override~
  SAY NAME1 @7031
  SAY NAME2 @7032
  SAY UNIDENTIFIED_DESC @7033
  SAY IDENTIFIED_DESC @7034

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 330
      match_parameter1 = 1
      parameter1 = RESOLVE_STR_REF (@5045)
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 330
      match_parameter1 = 2
      parameter1 = RESOLVE_STR_REF (@5046)
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 330
      match_parameter1 = 3
      parameter1 = RESOLVE_STR_REF (@5047)
  END
// TODO ADD THIS ITEM SOMEWHERE!

//////////// Cloverleaf

COPY ~IATweaks\resources\bam\s!belt12.bam~ ~override~
COPY ~IATweaks\resources\bam\s!bel12b.bam~ ~override~
COPY ~IATweaks\resources\itm\s!belt12.itm~ ~override~
  SAY NAME2 @7029
  SAY IDENTIFIED_DESC @7030
// TODO ADD THIS ITEM SOMEWHERE!

//////////// Cloak of Mystra

COPY ~IATweaks\resources\bam\s!clck30.bam~ ~override~
COPY ~IATweaks\resources\itm\s!clck30.itm~ ~override~
  SAY NAME2 @7035
  SAY IDENTIFIED_DESC @7036

// Conster

COPY_EXISTING ~FIRMAG01.cre~ ~override~     
  ADD_CRE_ITEM ~S!CLCK30~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~

// Perth

COPY_EXISTING ~PPCOWLED.cre~ ~override~     
  ADD_CRE_ITEM ~S!CLCK30~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~

COPY ~IATweaks\resources\itm\s!clck31.itm~ ~override~
  SAY NAME2 @7035
  SAY IDENTIFIED_DESC @7037

/////////////// New Recipes

COMPILE ~IATweaks/resources/dlg/crom_new_items.d~
  USING ~%LANGUAGE%crom_new_items.tra~

COMPILE ~IATweaks/resources/dlg/cespy_new_items.d~
  USING ~%LANGUAGE%crom_new_items.tra~ ~%LANGUAGE%cespy_new_items.tra~
