PRINT @5096

SILENT

/////////// Wardring (+1 AC) ////////////

COPY ~IATweaks\resources\bam\s!ring20.bam~ ~override~
COPY ~IATweaks\resources\itm\s!ring20.itm~ ~override~
  SAY NAME2 @7002
  SAY IDENTIFIED_DESC @7003

// Kalah

COPY_EXISTING ~KALAH.cre~ ~override~
  ADD_CRE_ITEM ~s!ring20~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~LRING~

COPY_EXISTING ~KALAH2.cre~ ~override~
  ADD_CRE_ITEM ~s!ring20~ #0 #0 #0 ~NONE~ ~LRING~

// Tolgerias

COPY_EXISTING ~TOLGER2.cre~ ~override~
  ADD_CRE_ITEM ~s!ring20~ #0 #0 #0 ~NONE~ ~LRING~

// Rilloa Jae'llat

COPY_EXISTING ~JAEL02.cre~ ~override~
  ADD_CRE_ITEM ~s!ring20~ #0 #0 #0 ~NONE~ ~RRING~

// Theshal

COPY_EXISTING ~THESHAL.cre~ ~override~
  ADD_CRE_ITEM ~s!ring20~ #0 #0 #0 ~NONE~ ~RRING~

//////////// Blood Red Ioun Stone

COPY ~IATweaks\resources\bam\s!ioun01.bam~ ~override~
COPY ~IATweaks\resources\itm\s!ioun01.itm~ ~override~
  SAY NAME2 @7006
  SAY IDENTIFIED_DESC @7007

// Thief from Mencar's party

COPY_EXISTING ~SEVPAT05.cre~ ~override~     
  ADD_CRE_ITEM ~s!ioun01~ #0 #0 #0 ~NONE~ ~HELMET~

//////////// Symbol of Sehanine Moonbow

ACTION_IF(FILE_EXISTS_IN_GAME ~SPPR205.2da~) BEGIN
  COPY ~IATweaks\resources\bam\s!amul20.bam~ ~override~
  COPY ~IATweaks\resources\itm\s!amul20.itm~ ~override~
    SAY NAME2 @7009
    SAY IDENTIFIED_DESC @7010

  // Slaver Ship Priest of Cyric
  COPY_EXISTING ~SLAPRI.cre~ ~override~
    ADD_CRE_ITEM ~S!AMUL20~ #2 #2 #0 ~NONE~ ~INV12~
END

//////////// Snow Leopard Charm

COPY ~IATweaks\resources\bam\s!leopar.bam~ ~override~
COPY ~IATweaks\resources\bam\s!leopab.bam~ ~override~
COPY ~IATweaks\resources\itm\s!leopar.itm~ ~override~
  SAY NAME2 @7019
  SAY IDENTIFIED_DESC @7020

// Thax

COPY_EXISTING ~SHADRA01.cre~ ~override~     
  ADD_CRE_ITEM ~s!leopar~ #0 #0 #0 ~NONE~ ~INV16~

//////////// Improved Snow Leopard Charm

COPY ~IATweaks\resources\itm\s!amul21.itm~ ~override~
  SAY NAME2 @7021
  SAY IDENTIFIED_DESC @7022


//////////// Night Club

COPY ~IATweaks\resources\spl\s!clubni.spl~ ~override~
COPY ~IATweaks\resources\bam\s!clubni.bam~ ~override~
COPY ~IATweaks\resources\itm\s!clubni.itm~ ~override~
  SAY NAME2 @7014 
  SAY IDENTIFIED_DESC @7013 

// Damien from evil Underdark party

COPY_EXISTING ~GPTHIEF1.cre~ ~override~
  ADD_CRE_ITEM ~s!clubni~ #0 #0 #0 ~NONE~ ~INV12~

//////////// Sure Strike Club

COPY ~IATweaks\resources\bam\s!surehi.bam~ ~override~
COPY ~IATweaks\resources\itm\s!surehi.itm~ ~override~
  SAY NAME2 @7017 
  SAY IDENTIFIED_DESC @7018 

// Rengaard from Tarnor's party

COPY_EXISTING ~RENGAA.cre~ ~override~
  ADD_CRE_ITEM ~s!surehi~ #0 #0 #0 ~NONE~ ~INV12~

//////////// Backwhacker

COPY ~IATweaks\resources\eff\s!staba1.eff~ ~override\s!backwh.eff~
  WRITE_ASCII 0x30 ~S!BACKWH1~ #8

COPY ~IATweaks\resources\spl\S!backstab_146_base.SPL~ ~override\s!backw1.spl~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 146
    STR_VAR
      resource = ~S!BACKW2~
  END
COPY ~IATweaks\resources\spl\S!backstab_326_base.SPL~ ~override\s!backw2.spl~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 326
      parameter1 = %successfully_backstabbed%
    STR_VAR
      resource = ~S!BACKWH~
  END

COPY ~IATweaks\resources\spl\s!backwh.spl~ ~override~
COPY ~IATweaks\resources\bam\s!backwh.bam~ ~override~
COPY ~IATweaks\resources\itm\s!backwh.itm~ ~override~
  SAY NAME2 @7015
  SAY IDENTIFIED_DESC @7016

// Unseeing Eye

COPY_EXISTING ~BHEYE.cre~ ~override~
  ADD_CRE_ITEM ~s!backwh~ #0 #0 #0 ~NONE~ ~INV12~

////////////// Blightwood +5

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~AREA_TYPE~
    stat                  = ~0x106~
    value                 = ~-1~
    relation              = ~1~
  RET
    area_type = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~CRUSHING_RES>=100~
    stat                  = ~22~
    value                 = ~100~
    relation              = ~4~
  RET
    crushing_no_less_than_100 = new_line_number
END

COPY ~IATweaks\resources\spl\s!bligh1.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      match_parameter2 = 0
      parameter2 = crushing_no_less_than_100
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 139
      parameter1 = RESOLVE_STR_REF (@5190)
  END
COPY ~IATweaks\resources\spl\s!bligh2.spl~ ~override~
COPY ~IATweaks\resources\spl\s!bligh3.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 326
      match_parameter2 = 0
      parameter1 = 32 // Dungeon
      parameter2 = area_type
  END
COPY ~IATweaks\resources\spl\s!bligh4.spl~ ~override~

COPY ~IATweaks\resources\eff\s!staba1.eff~ ~override\s!blight.eff~
  WRITE_ASCII 0x30 ~S!BLIGH1~ #8

COPY ~IATweaks\resources\spl\S!backstab_146_base.SPL~ ~override\s!bligh5.spl~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 146
    STR_VAR
      resource = ~S!BLIGH6~
  END
COPY ~IATweaks\resources\spl\S!backstab_326_base.SPL~ ~override\s!bligh6.spl~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 326
      parameter1 = %successfully_backstabbed%
    STR_VAR
      resource = ~S!BLIGH1~
  END
COPY ~IATweaks\resources\bam\s!blight.bam~ ~override~
COPY ~IATweaks\resources\itm\s!blight.itm~ ~override~
  SAY NAME2 @7040
  SAY IDENTIFIED_DESC @7041

//////////// Girdle of Beatification

COPY ~IATweaks\resources\bam\s!belt10.bam~ ~override~
COPY ~IATweaks\resources\itm\s!belt10.itm~ ~override~
  SAY NAME2 @7025
  SAY IDENTIFIED_DESC @7026
// TODO ADD THIS ITEM SOMEWHERE!

//////////// Bracers of Brute Force

COPY ~IATweaks\resources\bam\s!brac20.bam~ ~override~
COPY ~IATweaks\resources\bam\s!brc20b.bam~ ~override~
COPY ~IATweaks\resources\itm\s!brac20.itm~ ~override~
  SAY NAME2 @7066
  SAY IDENTIFIED_DESC @7067

// Insane Dwarf from the Underdark

COPY_EXISTING ~UDDWARF.cre~ ~override~
  ADD_CRE_ITEM ~s!brac20~ #0 #0 #0 ~NONE~ ~GLOVES~

//////////// Insulated Arcs of Disredain

COPY ~IATweaks\resources\bam\s!bel11b.bam~ ~override~
COPY ~IATweaks\resources\bam\s!belt11.bam~ ~override~
COPY ~IATweaks\resources\itm\s!belt11.itm~ ~override~
  SAY NAME2 @7027
  SAY IDENTIFIED_DESC @7028

// Librarian

COPY_EXISTING ~S!BOLICH.cre~ ~override~     
  ADD_CRE_ITEM ~s!belt11~ #0 #0 #0 ~NONE~ ~INV16~

//////////// Lucky Coin of Tymora

COPY ~IATweaks\resources\bam\s!misc90.bam~ ~override~
COPY ~IATweaks\resources\bam\s!mis90b.bam~ ~override~
COPY ~IATweaks\resources\itm\s!misc90.itm~ ~override~
  SAY NAME1 @7031
  SAY NAME2 @7032
  SAY UNIDENTIFIED_DESC @7033
  SAY IDENTIFIED_DESC @7034

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 330
      match_parameter1 = 1
      parameter1 = RESOLVE_STR_REF (@5045)
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 330
      match_parameter1 = 2
      parameter1 = RESOLVE_STR_REF (@5046)
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 330
      match_parameter1 = 3
      parameter1 = RESOLVE_STR_REF (@5047)
  END

// add the item to a merchant in Trademeet
COPY_EXISTING ~trmer02.sto~ ~override~
  ADD_STORE_ITEM ~s!misc90~ LAST #3 #0 #0 ~IDENTIFIED&UNSTEALABLE~ #1

//////////// Cloverleaf

COPY ~IATweaks\resources\bam\s!belt12.bam~ ~override~
COPY ~IATweaks\resources\bam\s!bel12b.bam~ ~override~
COPY ~IATweaks\resources\itm\s!belt12.itm~ ~override~
  SAY NAME2 @7029
  SAY IDENTIFIED_DESC @7030
  
// add the item to a Drow merchant in Ust Natha
COPY_EXISTING ~uddrow23.sto~ ~override~
  ADD_STORE_ITEM ~s!belt12~ LAST #0 #0 #0 ~IDENTIFIED&UNSTEALABLE~ #1

//////////// Cloak of Mystra

COPY ~IATweaks\resources\bam\s!clck30.bam~ ~override~
COPY ~IATweaks\resources\itm\s!clck30.itm~ ~override~
  SAY NAME2 @7035
  SAY IDENTIFIED_DESC @7036

// Conster

COPY_EXISTING ~FIRMAG01.cre~ ~override~     
  ADD_CRE_ITEM ~S!CLCK30~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~

// Perth

COPY_EXISTING ~PPCOWLED.cre~ ~override~     
  ADD_CRE_ITEM ~S!CLCK30~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~

// Vithal

COPY_EXISTING ~UDVITH.cre~ ~override~     
  ADD_CRE_ITEM ~S!CLCK30~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~

// Kaol

COPY_EXISTING ~KAOL.cre~ ~override~     
  ADD_CRE_ITEM ~S!CLCK30~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~

COPY ~IATweaks\resources\itm\s!clck31.itm~ ~override~
  SAY NAME2 @7035
  SAY IDENTIFIED_DESC @7037

///////////// Stalker Gauntlets

COPY ~IATweaks\resources\bam\s!brc21a.bam~ ~override~
COPY ~IATweaks\resources\bam\s!brc21b.bam~ ~override~
COPY ~IATweaks\resources\eff\s!brac21.eff~ ~override~
COPY ~IATweaks\resources\itm\s!brac21.itm~ ~override~
  SAY NAME2 @7069
  SAY IDENTIFIED_DESC @7068

// Merella the Ranger

COPY_EXISTING ~UHRANG01.cre~ ~override~
  ADD_CRE_ITEM ~s!brac21~ #0 #0 #0 ~NONE~ ~INV1~

///////////// Ring of Vitality

COPY ~IATweaks\resources\bam\s!rng21c.bam~ ~override~
COPY ~IATweaks\resources\bam\s!rng21i.bam~ ~override~
COPY ~IATweaks\resources\itm\s!ring21.itm~ ~override~
  SAY NAME2 @7070
  SAY IDENTIFIED_DESC @7071

// Umar

COPY_EXISTING ~RUMAR01.cre~ ~override~
  ADD_CRE_ITEM ~s!ring21~ #0 #0 #0 ~NONE~ ~RRING~

//////////// Silent Gale Treads

COPY ~IATweaks\resources\bam\s!boot20.bam~ ~override~
COPY ~IATweaks\resources\itm\s!boot20.itm~ ~override~
  SAY NAME2 @7083
  SAY IDENTIFIED_DESC @7084

//////////// Ring of Enduring Heart

COPY ~IATweaks\resources\bam\s!rng22i.bam~ ~override~
COPY ~IATweaks\resources\itm\s!ring22.itm~ ~override~
  SAY NAME2 @7085
  SAY IDENTIFIED_DESC @7086

// Orcus

COPY_EXISTING ~S!ORCUS.cre~ ~override~
  ADD_CRE_ITEM ~s!ring22~ #0 #0 #0 ~UNSTEALABLE~ ~INV10~

//////////// Cloak of the Second Strike

COPY ~IATweaks\resources\itm\s!clck32.itm~ ~override~
  SAY NAME2 @7087
  SAY IDENTIFIED_DESC @7088

// Thief from Mencar's party

COPY_EXISTING ~SEVPAT05.cre~ ~override~
  ADD_CRE_ITEM ~S!CLCK32~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~

//////////// The Martyr's Answer +4~

COPY ~IATweaks\resources\bam\s!blun10.bam~ ~override~
COPY ~IATweaks\resources\itm\s!blun10.itm~ ~override~
  SAY NAME2 @7126
  SAY IDENTIFIED_DESC @7127

/////////////// New Recipes

COMPILE ~IATweaks/resources/dlg/crom_new_items.d~
USING ~%LANGUAGE%crom_new_items.tra~

COMPILE ~IATweaks/resources/dlg/cespy_new_items.d~
USING ~%LANGUAGE%crom_new_items.tra~ ~%LANGUAGE%cespy_new_items.tra~

COMPILE ~IATweaks/resources/dlg/maheer_new_items.d~
USING ~%LANGUAGE%maheer_new_items.tra~
