
SILENT

INCLUDE "IATweaks/lib/components/IA_rebalancing/helper_functions.tph"
INCLUDE "IATweaks/lib/components/IA_rebalancing/helper_functions_GUI.tph"

// Class and Kit description

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_rows = 2da_rows_to_ids_mapping
END

// update class description for Bards
COPY_EXISTING ~clastext.2da~ ~override/clastext.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $clastext_cols("DESCSTR")
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $clastext_rows("BARD") description_col RESOLVE_STR_REF (@5106)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $clastext_rows("BLADE") description_col RESOLVE_STR_REF (@5103)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $clastext_rows("JESTER") description_col RESOLVE_STR_REF (@5104)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $clastext_rows("SKALD") description_col RESOLVE_STR_REF (@5105)
  SET_2DA_ENTRIES_NOW ~s!bard_desc~ ~colcount~
  PRETTY_PRINT_2DA

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  INT_VAR
    col_with_names = 1
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~kitlist.2da~ ~override/kitlist.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $kitlist_cols("HELP")
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $kitlist_rows("BLADE") description_col RESOLVE_STR_REF (@5103)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $kitlist_rows("JESTER") description_col RESOLVE_STR_REF (@5104)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $kitlist_rows("SKALD") description_col RESOLVE_STR_REF (@5105)
  SET_2DA_ENTRIES_NOW ~s!bard_desc~ ~colcount~
  PRETTY_PRINT_2DA

// Improve thac0 table for Bards

COPY_EXISTING ~thac0.2da~ ~override~
  REPLACE_EVALUATE
    ~BARD.*~
    BEGIN
    END
    ~BARD 20 19 18 18 17 16 16 15 14 14 13 12 12 11 10 10 9 8 8 7 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5~
  PRETTY_PRINT_2DA

// Vastly improve Bard spell progression

COPY ~IATweaks\resources\2da\mxsplbrd.2da~ ~override~

// Rework weapon proficiencies for Bards

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~weapprof.2da~  ~override/weapprof.2da~
  COUNT_2DA_COLS ~colcount~
  SET bard_column = $weapprof_cols("BARD")
  SET blade_column = $weapprof_cols("BLADE")
  SET jester_column = $weapprof_cols("JESTER")
  SET skald_column = $weapprof_cols("SKALD")
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("BASTARDSWORD") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("LONGSWORD") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SHORTSWORD") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("KATANA") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SCIMITARWAKISASHININJATO") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("DAGGER") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SWORDANDSHIELD") %bard_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2WEAPON") %bard_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2HANDED") %bard_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SINGLEWEAPON") %bard_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SWORDANDSHIELD") %jester_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2WEAPON") %jester_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2HANDED") %jester_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SINGLEWEAPON") %jester_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SWORDANDSHIELD") %skald_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2WEAPON") %skald_column% ~1~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2HANDED") %skald_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SINGLEWEAPON") %skald_column% ~2~
  SET_2DA_ENTRIES_NOW ~_#_#_#weapprof~ ~colcount~
  PRETTY_PRINT_2DA

