
SILENT

INCLUDE "IATweaks/lib/components/IA_rebalancing/helper_functions.tph"
INCLUDE "IATweaks/lib/components/IA_rebalancing/helper_functions_GUI.tph"

// Class and Kit description

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_rows = 2da_rows_to_ids_mapping
END

// update class description for Bards
COPY_EXISTING ~clastext.2da~ ~override/clastext.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $clastext_cols("DESCSTR")
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $clastext_rows("BARD") description_col RESOLVE_STR_REF (@5106)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $clastext_rows("BLADE") description_col RESOLVE_STR_REF (@5103)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $clastext_rows("JESTER") description_col RESOLVE_STR_REF (@5104)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $clastext_rows("SKALD") description_col RESOLVE_STR_REF (@5105)
  SET_2DA_ENTRIES_NOW ~s!bard_desc~ ~colcount~
  PRETTY_PRINT_2DA

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  INT_VAR
    col_with_names = 1
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~kitlist.2da~ ~override/kitlist.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $kitlist_cols("HELP")
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $kitlist_rows("BLADE") description_col RESOLVE_STR_REF (@5103)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $kitlist_rows("JESTER") description_col RESOLVE_STR_REF (@5104)
  SET_2DA_ENTRY_LATER ~s!bard_desc~ $kitlist_rows("SKALD") description_col RESOLVE_STR_REF (@5105)
  SET_2DA_ENTRIES_NOW ~s!bard_desc~ ~colcount~
  PRETTY_PRINT_2DA

// Improve thac0 table for Bards

COPY_EXISTING ~thac0.2da~ ~override~
  REPLACE_EVALUATE
    ~BARD.*~
    BEGIN
    END
    ~BARD 20 19 18 18 17 16 16 15 14 14 13 12 12 11 10 10 9 8 8 7 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5~
  PRETTY_PRINT_2DA

// Vastly improve Bard spell progression

COPY ~IATweaks\resources\2da\mxsplbrd.2da~ ~override~

// Rework weapon proficiencies for Bards

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~weapprof.2da~  ~override/weapprof.2da~
  COUNT_2DA_COLS ~colcount~
  SET bard_column = $weapprof_cols("BARD")
  SET blade_column = $weapprof_cols("BLADE")
  SET jester_column = $weapprof_cols("JESTER")
  SET skald_column = $weapprof_cols("SKALD")
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("BASTARDSWORD") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("LONGSWORD") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SHORTSWORD") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("KATANA") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SCIMITARWAKISASHININJATO") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("DAGGER") %blade_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SWORDANDSHIELD") %bard_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2WEAPON") %bard_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2HANDED") %bard_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SINGLEWEAPON") %bard_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SWORDANDSHIELD") %jester_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2WEAPON") %jester_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2HANDED") %jester_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SINGLEWEAPON") %jester_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SWORDANDSHIELD") %skald_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2WEAPON") %skald_column% ~1~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("2HANDED") %skald_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SINGLEWEAPON") %skald_column% ~2~
  SET_2DA_ENTRIES_NOW ~_#_#_#weapprof~ ~colcount~
  PRETTY_PRINT_2DA

//////////////////// Abilities //////////////////

// Cast while wearing Armor

COPY ~IATweaks\resources\spl\s!leathe.spl~ ~override~
COPY ~IATweaks\resources\eff\s!leathe.eff~ ~override~

ACTION_FOR_EACH bard_clab IN ~CLABBA01.2da~ ~CLABBA02.2da~ ~CLABBA03.2da~ ~CLABBA04.2da~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%bard_clab%~
      row_desc = ~CAST_IN_LEATHER~
      level1 = ~AP_S!LEATHE~
  END
END

//////////////////// SONGS ///////////////////

// Base ability that triggers sequencer with name S!SONG every 6s, if Bard is conscious and not silenced

COPY ~IATweaks\resources\spl\s!songin.spl~ ~override~
COPY ~IATweaks\resources\spl\s!song00.spl~ ~override~
COPY ~IATweaks\resources\eff\s!song00.eff~ ~override~
COPY ~IATweaks\resources\bam\s!sngaab.bam~ ~override~
COPY ~IATweaks\resources\bam\s!sngbab.bam~ ~override~

// Add it to all Bard kits

ACTION_FOR_EACH bard_clab IN ~CLABBA01.2da~ ~CLABBA02.2da~ ~CLABBA03.2da~ ~CLABBA04.2da~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%bard_clab%~
      row_desc = ~AUTOMATIC_SONG_TRIGGER~
      level1 = ~AP_S!SONG00~
  END
END

COPY ~IATweaks\resources\spl\s!song01.spl~ ~override~
COPY ~IATweaks\resources\eff\s!song01.eff~ ~override~

ACTION_DEFINE_ASSOCIATIVE_ARRAY bard_song_trigger_to_effect_mapping BEGIN
  "S!SONGBA"=>"S!SONG02"
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY bard_song_trigger_bam_mapping BEGIN
  "S!SONGBA"=>"S!SNGBAB"
END

ACTION_PHP_EACH bard_song_trigger_to_effect_mapping AS _ => song_effect BEGIN
  COPY_EXISTING ~s!song01.eff~ ~override/%song_effect%.eff~
    WRITE_ASCIIE 0x30 EVAL ~%song_effect%~
END

COPY ~IATweaks\resources\spl\s!songaa.spl~ ~override~
  PHP_EACH bard_song_trigger_to_effect_mapping AS song_trigger => _ BEGIN
    LPF ~CLONE_EFFECT~
      INT_VAR
        match_opcode = 321
        multi_match = 1
      STR_VAR
        match_resource = ~S!SONGAA~
        resource = EVAL ~%song_trigger%~
    END
  END

ACTION_PHP_EACH bard_song_trigger_to_effect_mapping AS song_trigger => song_effect BEGIN
  COPY_EXISTING ~s!songaa.spl~ ~override/%song_trigger%.spl~
    SPRINT song_bam $bard_song_trigger_bam_mapping(~%song_trigger%~)
    WRITE_ASCIIE 0x3a ~%song_bam%~
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 177
      STR_VAR
        resource = EVAL ~%song_effect%~
    END
    LPF ~ALTER_EFFECT~
      INT_VAR
        check_headers = 0
      STR_VAR
        match_resource = ~S!SONGAA~
        resource = EVAL ~%song_trigger%~
    END
    LPF ~ALTER_SPELL_HEADER~
      STR_VAR
        icon = EVAL ~%song_bam%~
    END
END

ACTION_FOR_EACH standard_duration_song IN ~S!SONG01~ ~S!SONG02~ BEGIN
  
  COPY ~IATweaks\resources\spl\%standard_duration_song%.spl~ ~override~
    SET song_duration = 7
    PATCH_FOR_EACH song_level IN 10 12 14 16 18 20 BEGIN
      LPF ~S!CLONE_SPELL_HEADER~
        INT_VAR
          level_req = song_level
      END
      LPF ~ALTER_EFFECT~
        INT_VAR
          header = song_duration - 6
          duration = song_duration
      END
      SET song_duration = song_duration + 1
    END
END

OUTER_SET song_name_strref = RESOLVE_STR_REF (@6302)
COPY_EXISTING ~S!SONGAA.spl~ ~override~
  SAY NAME1 @6302
  SAY UNIDENTIFIED_DESC @6303
COPY_EXISTING ~S!SONG01.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 139
      parameter1 = song_name_strref
  END

OUTER_SET song_name_strref = RESOLVE_STR_REF (@6304)
COPY_EXISTING ~S!SONGBA.spl~ ~override~
  SAY NAME1 @6304
  SAY UNIDENTIFIED_DESC @6305
COPY_EXISTING ~S!SONG02.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 139
      parameter1 = song_name_strref
  END

///////////// General

// Scholar's Verse (Nahal for Bards)

COPY ~IATweaks\resources\bam\s!brd01d.bam~ ~override~

OUTER_SET scholar_verse_desc_str_ref = RESOLVE_STR_REF (@6301)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %scholar_verse_desc_str_ref%
  STR_VAR
    bam_file = ~S!BRD01D~
  RET
    scholar_verse_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\spl\s!brd01.spl~ ~override~
  SAY NAME1 @6299
  SAY UNIDENTIFIED_DESC @6300
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %scholar_verse_icon_id%
  END

// Add Scholar's Verse to all Bards

ACTION_FOR_EACH bard_clab IN ~CLABBA01.2da~ ~CLABBA02.2da~ ~CLABBA03.2da~ ~CLABBA04.2da~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%bard_clab%~
      row_desc = ~SCHOLARS_VERSE~
      level19 = ~GA_S!BRD01~
  END
END

// Allow Bards to get APR from levels and specialization

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clswpbon.2da~
  RET_ARRAY
    clswpbon_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clswpbon.2da~
  RET_ARRAY
    clswpbon_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~clswpbon.2da~ ~override/clswpbon.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $clswpbon_cols("GETS_PROF_APR")
  SET_2DA_ENTRY_LATER ~s!bard_apr~ $clswpbon_rows("BARD") description_col 1
  SET_2DA_ENTRY_LATER ~s!bard_apr~ $clswpbon_rows("BLADE") description_col 1
  SET_2DA_ENTRY_LATER ~s!bard_apr~ $clswpbon_rows("JESTER") description_col 1
  SET_2DA_ENTRY_LATER ~s!bard_apr~ $clswpbon_rows("SKALD") description_col 1
  SET_2DA_ENTRIES_NOW ~s!bard_apr~ ~colcount~
  PRETTY_PRINT_2DA

///////////////// Bard ///////////////////

// Base song assignment

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABBA01.2da~
    row_desc = ~GET_BARD_SONG~
    level1 = ~GA_S!SONGAA~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABBA01.2da~
    row_desc = ~SET_DEFAULT_BARD_SONG~
    level1 = ~AP_S!SONGAA~
END

///////////////// Skald ///////////////////

// Cast in chain mail

COPY ~IATweaks\resources\spl\s!chainm.spl~ ~override~
COPY ~IATweaks\resources\eff\s!chainm.eff~ ~override~

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABBA04.2da~
    row_desc = ~CAST_IN_CHAIN~
    level12 = ~AP_S!CHAINM~
END

// Base song assignment

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABBA04.2da~
    row_desc = ~GET_BARD_SONG~
    level1 = ~GA_S!SONGAA~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABBA04.2da~
    row_desc = ~GET_SKALD_SONG~
    level1 = ~GA_S!SONGBA~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABBA04.2da~
    row_desc = ~SET_DEFAULT_SKALD_SONG~
    level1 = ~AP_S!SONGBA~
END

// 20% longer song

COPY ~IATweaks\resources\spl\s!brd02.spl~ ~override~

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABBA04.2da~
    row_desc = ~LONGER_BARD_SONG~
    level1 = ~AP_S!BRD02~
END

///////////////// Blade ///////////////////

// Defensive Spin

COPY ~IATweaks\resources\spl\s!brd04.spl~ ~override~
COPY ~IATweaks\resources\eff\s!brd04.eff~ ~override~

COPY_EXISTING ~spcl522.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6306
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 2 3 4 5 6 7 8 9 10 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      duration_high = 30
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 176
      parameter1 = 50
      parameter2 = 2
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 0
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 282
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 321
      multi_match = 1
    STR_VAR
      resource = ~S!BRD05~
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 321
      multi_match = 1
      timing = 3
      duration = 30
    STR_VAR
      resource = ~S!BRD04~
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 142
      opcode = 177
      multi_match = 1
      parameter1 = 0
      parameter2 = 2
    STR_VAR
      resource = ~S!BRD04~
  END

///////////////// Jester ///////////////////
