PRINT @5095

SILENT

// Simbja, the Goblin from Underdark evil party

COPY_EXISTING ~GPSIMB.cre~ ~override~

    REMOVE_MEMORIZED_SPELL ~SPPR210~ // Resist Fire/Cold

    ADD_MEMORIZED_SPELL ~SPPR212~ #1 ~priest~ ( 1 ) // Slow Poison

// Boz, the Ogre from Underdark evil party

COMPILE ~IATweaks\scripts\controversial\S!BOZ.BAF~

// Ist'tar Jae'llat

COPY_EXISTING ~JAEL03.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS
  ADD_MEMORIZED_SPELL ~SPCL144~ #0 ~innate~ ( 6 ) // Kai
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL908~ #0 ~innate~ ( 1 ) // War Cry

COMPILE ~IATweaks\scripts\controversial\S!JAEL03.BAF~

// Boz the Ogre from Underdark evil party

COPY_EXISTING ~GPFIGHT1.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS
  ADD_MEMORIZED_SPELL ~SPCL321~ #0 ~innate~ ( 4 ) // Enrage
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL908~ #0 ~innate~ ( 1 ) // War Cry

COMPILE ~IATweaks\scripts\controversial\S!BOZ.BAF~

// Hindra Jae'llat

COPY_EXISTING ~JAEL01.cre~ ~override~
  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR101~ #0 ~priest~ ( 1 ) // Bless
  ADD_MEMORIZED_SPELL ~SPPR102~ #0 ~priest~ ( 1 ) // Command
  ADD_MEMORIZED_SPELL ~SPPR107~ #0 ~priest~ ( 1 ) // Protection from Evil
  ADD_MEMORIZED_SPELL ~SPPR108~ #0 ~priest~ ( 1 ) // Remove Fear
  ADD_MEMORIZED_SPELL ~SPPR109~ #0 ~priest~ ( 2 ) // Sanctuary
  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 3 ) // Doom
  ADD_MEMORIZED_SPELL ~SPPR201~ #1 ~priest~ ( 1 ) // Aid
  ADD_MEMORIZED_SPELL ~SPPR203~ #1 ~priest~ ( 1 ) // Chant
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 1 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR208~ #1 ~priest~ ( 4 ) // Hold Person
  ADD_MEMORIZED_SPELL ~SPDR201~ #1 ~priest~ ( 3 ) // Web
  ADD_MEMORIZED_SPELL ~SPPR214~ #1 ~priest~ ( 1 ) // DUHM
  ADD_MEMORIZED_SPELL ~SPPRI02~ #2 ~priest~ ( 2 ) // Dispel Magic caster-friendly
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 1 ) // Protection From Fire
  ADD_MEMORIZED_SPELL ~SPPR312~ #2 ~priest~ ( 1 ) // Strength of One
  ADD_MEMORIZED_SPELL ~SPPR314~ #2 ~priest~ ( 4 ) // Unholy Blight
  ADD_MEMORIZED_SPELL ~SPPR318~ #2 ~priest~ ( 2 ) // Zone of Sweet Air
  ADD_MEMORIZED_SPELL ~SPPR403~ #3 ~priest~ ( 1 ) // Free Actions
  ADD_MEMORIZED_SPELL ~SPPR406F~ #3 ~priest~ ( 2 ) // Defensive Harmony
  ADD_MEMORIZED_SPELL ~SPPR407~ #3 ~priest~ ( 1 ) // Protection from Lightning
  ADD_MEMORIZED_SPELL ~SPPR409~ #3 ~priest~ ( 1 ) // Death Ward
  ADD_MEMORIZED_SPELL ~SPPR411~ #3 ~priest~ ( 1 ) // Poison
  ADD_MEMORIZED_SPELL ~SPPR412~ #3 ~priest~ ( 1 ) // Holy Power
  ADD_MEMORIZED_SPELL ~SPPR418~ #3 ~priest~ ( 1 ) // Acid Shield
  ADD_MEMORIZED_SPELL ~SPPR420~ #3 ~priest~ ( 1 ) // Resist Fire and Cold
  ADD_MEMORIZED_SPELL ~SPPR505~ #4 ~priest~ ( 1 ) // True Seeing
  ADD_MEMORIZED_SPELL ~SPPR508~ #4 ~priest~ ( 1 ) // Chaotic Commands
  ADD_MEMORIZED_SPELL ~SPPR510~ #4 ~priest~ ( 1 ) // Cause Critical Wounds
  ADD_MEMORIZED_SPELL ~SPPR511~ #4 ~priest~ ( 1 ) // Slay Living
  ADD_MEMORIZED_SPELL ~SPPR512~ #4 ~priest~ ( 3 ) // Greater Command
  ADD_MEMORIZED_SPELL ~SPPR513~ #4 ~priest~ ( 1 ) // Righteous Magic
  ADD_MEMORIZED_SPELL ~SPPR514~ #4 ~priest~ ( 1 ) // Mass Cure
  ADD_MEMORIZED_SPELL ~SPPR601~ #5 ~priest~ ( 1 ) // Aerial Servant
  ADD_MEMORIZED_SPELL ~SPPR607~ #5 ~priest~ ( 1 ) // Heal
  ADD_MEMORIZED_SPELL ~SPPR608~ #5 ~priest~ ( 3 ) // Harm
  ADD_MEMORIZED_SPELL ~SPPR613~ #5 ~priest~ ( 1 ) // Protection from Missiles
  ADD_MEMORIZED_SPELL ~SPPR617~ #5 ~priest~ ( 1 ) // Heavenly Shield
  ADD_MEMORIZED_SPELL ~SPPR618~ #5 ~priest~ ( 1 ) // Champion's Might
  ADD_MEMORIZED_SPELL ~SPPR698~ #5 ~priest~ ( 1 ) // Blade Barrier
  ADD_MEMORIZED_SPELL ~SPPR701~ #6 ~priest~ ( 1 ) // Shield of Archons
  ADD_MEMORIZED_SPELL ~SPPR711~ #6 ~priest~ ( 1 ) // Regeneration
  ADD_MEMORIZED_SPELL ~SPPR713~ #6 ~priest~ ( 1 ) // Greater Restoration
  ADD_MEMORIZED_SPELL ~SPPR729~ #6 ~priest~ ( 1 ) // Foreknowledge
  ADD_MEMORIZED_SPELL ~SPPRI26~ #6 ~priest~ ( 1 ) // Continual Cure
  ADD_MEMORIZED_SPELL ~SPCLI24~ #0 ~innate~ ( 1 ) // Summon Fallen Archdeva
  ADD_MEMORIZED_SPELL ~S!AEGIS~ #0 ~innate~ ( 1 ) // Aegis of Faith

// Rilloa Jae'llat

COPY_EXISTING ~JAEL02.cre~ ~override~
  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR101~ #0 ~priest~ ( 1 ) // Bless
  ADD_MEMORIZED_SPELL ~SPPR102~ #0 ~priest~ ( 1 ) // Command
  ADD_MEMORIZED_SPELL ~SPPR107~ #0 ~priest~ ( 1 ) // Protection from Evil
  ADD_MEMORIZED_SPELL ~SPPR108~ #0 ~priest~ ( 1 ) // Remove Fear
  ADD_MEMORIZED_SPELL ~SPPR109~ #0 ~priest~ ( 2 ) // Sanctuary
  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 3 ) // Doom
  ADD_MEMORIZED_SPELL ~SPPR201~ #1 ~priest~ ( 1 ) // Aid
  ADD_MEMORIZED_SPELL ~SPPR203~ #1 ~priest~ ( 1 ) // Chant
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 1 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR208~ #1 ~priest~ ( 4 ) // Hold Person
  ADD_MEMORIZED_SPELL ~SPDR201~ #1 ~priest~ ( 4 ) // Web
  // ADD_MEMORIZED_SPELL ~SPPR210~ #1 ~priest~ ( 2 ) // Resist Fire and Cold
  ADD_MEMORIZED_SPELL ~SPPR214~ #1 ~priest~ ( 1 ) // DUHM
  ADD_MEMORIZED_SPELL ~SPPRI02~ #2 ~priest~ ( 2 ) // Dispel Magic caster-friendly
  // ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 2 ) // Protection From Fire
  ADD_MEMORIZED_SPELL ~SPPR312~ #2 ~priest~ ( 1 ) // Strength of One
  ADD_MEMORIZED_SPELL ~SPPR314~ #2 ~priest~ ( 4 ) // Unholy Blight
  ADD_MEMORIZED_SPELL ~SPPR318~ #2 ~priest~ ( 2 ) // Zone of Sweet Air
  ADD_MEMORIZED_SPELL ~SPPR403~ #3 ~priest~ ( 2 ) // Free Actions
  ADD_MEMORIZED_SPELL ~SPPR406F~ #3 ~priest~ ( 1 ) // Defensive Harmony
  ADD_MEMORIZED_SPELL ~SPPR407~ #3 ~priest~ ( 1 ) // Protection from Lightning
  ADD_MEMORIZED_SPELL ~SPPR409~ #3 ~priest~ ( 2 ) // Death Ward
  ADD_MEMORIZED_SPELL ~SPPR412~ #3 ~priest~ ( 1 ) // Holy Power
  ADD_MEMORIZED_SPELL ~SPPR418~ #3 ~priest~ ( 1 ) // Acid Shield
  ADD_MEMORIZED_SPELL ~SPPR420~ #3 ~priest~ ( 2 ) // Resist Fire and Cold
  ADD_MEMORIZED_SPELL ~SPPR505~ #4 ~priest~ ( 1 ) // True Seeing
  ADD_MEMORIZED_SPELL ~SPPR508~ #4 ~priest~ ( 2 ) // Chaotic Commands
  ADD_MEMORIZED_SPELL ~SPPR510~ #4 ~priest~ ( 1 ) // Cause Critical Wounds
  ADD_MEMORIZED_SPELL ~SPPR511~ #4 ~priest~ ( 1 ) // Slay Living
  ADD_MEMORIZED_SPELL ~SPPR512~ #4 ~priest~ ( 2 ) // Greater Command
  ADD_MEMORIZED_SPELL ~SPPR513~ #4 ~priest~ ( 1 ) // Righteous Magic
  ADD_MEMORIZED_SPELL ~SPPR514~ #4 ~priest~ ( 1 ) // Mass Cure
  ADD_MEMORIZED_SPELL ~SPPR607~ #5 ~priest~ ( 1 ) // Heal
  ADD_MEMORIZED_SPELL ~SPPR608~ #5 ~priest~ ( 2 ) // Harm
  ADD_MEMORIZED_SPELL ~SPPR613~ #5 ~priest~ ( 1 ) // Protection from Missiles
  ADD_MEMORIZED_SPELL ~SPPR617~ #5 ~priest~ ( 1 ) // Heavenly Shield
  ADD_MEMORIZED_SPELL ~SPPR618~ #5 ~priest~ ( 1 ) // Champion's Might
  ADD_MEMORIZED_SPELL ~SPPR698~ #5 ~priest~ ( 1 ) // Blade Barrier
  ADD_MEMORIZED_SPELL ~SPPR701~ #6 ~priest~ ( 1 ) // Shield of Archons
  ADD_MEMORIZED_SPELL ~SPPR729~ #6 ~priest~ ( 1 ) // Foreknowledge
  ADD_MEMORIZED_SPELL ~SPPR735~ #6 ~priest~ ( 1 ) // Spare the Dying
  ADD_MEMORIZED_SPELL ~SPPRI26~ #6 ~priest~ ( 1 ) // Continual Cure
  ADD_MEMORIZED_SPELL ~S!AEGIS~ #0 ~innate~ ( 1 ) // Aegis of Faith

// Troll King

COMPILE ~IATweaks\scripts\controversial\S!TROLLK.BAF~


// Kuo Toa Battlepriest

COPY_EXISTING ~S!KUOBPR.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR101~ #0 ~priest~ ( 1 ) // Bless
  ADD_MEMORIZED_SPELL ~SPPR102~ #0 ~priest~ ( 2 ) // Command
  ADD_MEMORIZED_SPELL ~SPPR108~ #0 ~priest~ ( 1 ) // Protection from Evil
  ADD_MEMORIZED_SPELL ~SPPR108~ #0 ~priest~ ( 1 ) // Remove Fear
  ADD_MEMORIZED_SPELL ~SPPR109~ #0 ~priest~ ( 2 ) // Sanctuary
  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 3 ) // Doom

  ADD_MEMORIZED_SPELL ~SPPR201~ #1 ~priest~ ( 1 ) // Aid
  ADD_MEMORIZED_SPELL ~SPPR203~ #1 ~priest~ ( 2 ) // Chant
  ADD_MEMORIZED_SPELL ~SPPR208~ #1 ~priest~ ( 7 ) // Hold Person
  // ADD_MEMORIZED_SPELL ~SPPR210~ #1 ~priest~ ( 1 ) // Resist Fire and Cold
  ADD_MEMORIZED_SPELL ~SPPR214~ #1 ~priest~ ( 2 ) // DUHM

  ADD_MEMORIZED_SPELL ~SPPRI02~ #2 ~priest~ ( 4 ) // Dispel Magic caster-friendly
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 1 ) // Protection From Fire
  ADD_MEMORIZED_SPELL ~SPPR314~ #2 ~priest~ ( 4 ) // Unholy Blight
  ADD_MEMORIZED_SPELL ~SPPR315~ #2 ~priest~ ( 2 ) // Cure Medium Wounds

  ADD_MEMORIZED_SPELL ~SPPR403~ #3 ~priest~ ( 1 ) // Free Actions
  ADD_MEMORIZED_SPELL ~SPPR404~ #3 ~priest~ ( 1 ) // Neutralize Poison
  ADD_MEMORIZED_SPELL ~SPPR406F~ #3 ~priest~ ( 2 ) // Defensive Harmony
  ADD_MEMORIZED_SPELL ~SPPR407~ #3 ~priest~ ( 1 ) // Protection from Lightning
  ADD_MEMORIZED_SPELL ~SPPR409~ #3 ~priest~ ( 1 ) // Death Ward
  ADD_MEMORIZED_SPELL ~SPPR411~ #3 ~priest~ ( 2 ) // Poison
  ADD_MEMORIZED_SPELL ~SPPR418~ #3 ~priest~ ( 1 ) // Acid Shield
  ADD_MEMORIZED_SPELL ~SPPR445~ #3 ~priest~ ( 1 ) // Spiritual Weapon
  ADD_MEMORIZED_SPELL ~SPPR420~ #1 ~priest~ ( 1 ) // Resist Fire and Cold

  ADD_MEMORIZED_SPELL ~SPPR505~ #4 ~priest~ ( 1 ) // True Seeing
  ADD_MEMORIZED_SPELL ~SPPR506~ #4 ~priest~ ( 3 ) // Iron Skins
  ADD_MEMORIZED_SPELL ~SPPR508~ #4 ~priest~ ( 2 ) // Chaotic Commands
  ADD_MEMORIZED_SPELL ~SPPR509~ #4 ~priest~ ( 1 ) // Magic Resistance
  ADD_MEMORIZED_SPELL ~SPPR511~ #4 ~priest~ ( 1 ) // Slay Living
  ADD_MEMORIZED_SPELL ~SPPR512~ #4 ~priest~ ( 1 ) // Greater Command
  ADD_MEMORIZED_SPELL ~SPPR513~ #4 ~priest~ ( 1 ) // Righteous Magic

  ADD_MEMORIZED_SPELL ~SPPR601~ #5 ~priest~ ( 1 ) // Aerial Servant
  ADD_MEMORIZED_SPELL ~SPPR607~ #5 ~priest~ ( 2 ) // Heal
  ADD_MEMORIZED_SPELL ~SPPR608~ #5 ~priest~ ( 3 ) // Harm
  ADD_MEMORIZED_SPELL ~SPPR613~ #5 ~priest~ ( 1 ) // Protection from Missiles
  ADD_MEMORIZED_SPELL ~SPPR618~ #5 ~priest~ ( 1 ) // Champion's Might
  ADD_MEMORIZED_SPELL ~SPPR698~ #5 ~priest~ ( 1 ) // Blade Barrier
  // TUTAJ DAWAĆ SMASHING WAVE

  ADD_MEMORIZED_SPELL ~SPPR701~ #6 ~priest~ ( 1 ) // Shield of Archons
  ADD_MEMORIZED_SPELL ~SPPR704~ #6 ~priest~ ( 1 ) // Nature's Beauty
  ADD_MEMORIZED_SPELL ~SPPR717~ #6 ~priest~ ( 1 ) // Creeping Doom
  ADD_MEMORIZED_SPELL ~SPPR729~ #6 ~priest~ ( 1 ) // Foreknowledge
  ADD_MEMORIZED_SPELL ~SPPRI26~ #6 ~priest~ ( 1 ) // Continual Cure

  ADD_MEMORIZED_SPELL ~S!AEGIS~ #0 ~innate~ ( 1 ) // Aegis of Faith
  ADD_MEMORIZED_SPELL ~SPCL943~ #0 ~innate~ ( 3 ) // Purify Aura
  ADD_MEMORIZED_SPELL ~SPCLI15~ #0 ~innate~ ( 2 ) // Natural Restoral
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL908~ #0 ~innate~ ( 1 ) // War Cry
  // The last HLA are Foreknowledge and Continual Cure, in Controversial we'll use GWW and War Cry

// Insane Dwarf in the Underdark

COPY_EXISTING ~UDDWARF.cre~ ~override~

  LPF ~ALTER_EFFECT~
    STR_VAR
      match_opcode = 16
      parameter2 = 0
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL321~ #0 ~innate~ ( 4 ) // Enrage
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 3 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 4 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL908~ #0 ~innate~ ( 1 ) // War Cry

COMPILE ~IATweaks\scripts\controversial\S!UDDWAR.BAF~

// Archer from North Forest party

COPY_EXISTING ~AR18ARCH.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 2 ) // Doom
  ADD_MEMORIZED_SPELL ~SPPR202~ #1 ~priest~ ( 1 ) // Barkskin
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 2 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR209~ #1 ~priest~ ( 1 ) // Know Alignment
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 1 ) // Protection from Fire
  ADD_MEMORIZED_SPELL ~SPPR312~ #2 ~priest~ ( 1 ) // Strength of One
  ADD_MEMORIZED_SPELL ~SPPR315~ #2 ~priest~ ( 1 ) // Cure Medium Wounds
  ADD_MEMORIZED_SPELL ~SPCL121~ #0 ~innate~ ( 5 ) // Called Shot
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL908~ #0 ~innate~ ( 1 ) // War Cry
  ADD_MEMORIZED_SPELL ~SPCL922~ #0 ~innate~ ( 1 ) // Contact with Nature

// Maferan, the Minotaur from Guarded Compound

COPY_EXISTING ~HLMAFER.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL321~ #0 ~innate~ ( 5 ) // Enrage
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL908~ #0 ~innate~ ( 1 ) // War Cry
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  
// Olaf, the Orc from Guarded Compound

COPY_EXISTING ~HLOLAF.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL152~ #0 ~innate~ ( 5 ) // Barbarian Rage
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL908~ #0 ~innate~ ( 1 ) // War Cry
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

// Koshi, the Kensai from Guarded Compound

COPY_EXISTING ~HLKOSHI.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL144~ #0 ~innate~ ( 6 ) // Kai
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 2 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL908~ #0 ~innate~ ( 1 ) // War Cry

// Troll King

COPY_EXISTING ~S!TROLLK.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPINI34~ #0 ~innate~ ( 3 ) // Risk Decrement
  ADD_MEMORIZED_SPELL ~SPINI51~ #0 ~innate~ ( 2 ) // Chain Breaker Stance
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 2 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 2 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 5 ) // Critical Strike

COMPILE ~IATweaks\scripts\controversial\S!TROLLK.BAF~

// Troll Queen

COMPILE ~IATweaks\scripts\controversial\S!TROLLQ.BAF~
// Chak from Samia's party

COPY_EXISTING ~CHAK.cre~ ~override~

  REMOVE_KNOWN_SPELLS
  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR101~ #0 ~priest~ ( 1 ) // Bless
  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 5 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 3 ) // Doom

  ADD_MEMORIZED_SPELL ~SPPR202~ #1 ~priest~ ( 2 ) // Barkskin
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 1 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR209~ #1 ~priest~ ( 1 ) // Know Alignment
  // ADD_MEMORIZED_SPELL ~SPPR210~ #1 ~priest~ ( 2 ) // Resist Fire and Cold
  ADD_MEMORIZED_SPELL ~SPPR212~ #1 ~priest~ ( 4 ) // Slow Poison

  ADD_MEMORIZED_SPELL ~SPPRI02~ #2 ~priest~ ( 2 ) // Dispel Magic caster-friendly
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 2 ) // Protection From Fire
  ADD_MEMORIZED_SPELL ~SPPR315~ #2 ~priest~ ( 2 ) // Cure Medium Wounds
  ADD_MEMORIZED_SPELL ~SPPR318~ #2 ~priest~ ( 1 ) // Zone of Sweet Air

  ADD_MEMORIZED_SPELL ~SPPR403~ #3 ~priest~ ( 1 ) // Free Actions
  ADD_MEMORIZED_SPELL ~SPPR407~ #3 ~priest~ ( 2 ) // Protection from Lightning
  ADD_MEMORIZED_SPELL ~SPPR409~ #3 ~priest~ ( 1 ) // Death Ward
  ADD_MEMORIZED_SPELL ~SPPR411~ #3 ~priest~ ( 1 ) // Poison
  ADD_MEMORIZED_SPELL ~SPPR418~ #3 ~priest~ ( 1 ) // Acid Shield
  ADD_MEMORIZED_SPELL ~SPPR420~ #1 ~priest~ ( 1 ) // Resist Fire and Cold

  ADD_MEMORIZED_SPELL ~SPPR505~ #4 ~priest~ ( 1 ) // True Seeing
  ADD_MEMORIZED_SPELL ~SPPR506~ #4 ~priest~ ( 2 ) // Iron Skins
  ADD_MEMORIZED_SPELL ~SPPR508~ #4 ~priest~ ( 1 ) // Chaotic Commands
  ADD_MEMORIZED_SPELL ~SPPR509~ #4 ~priest~ ( 1 ) // Magic Resistance

  ADD_MEMORIZED_SPELL ~SPPR604~ #5 ~priest~ ( 1 ) // Conjure Animals
  ADD_MEMORIZED_SPELL ~SPPR607~ #5 ~priest~ ( 1 ) // Heal
  ADD_MEMORIZED_SPELL ~SPPR613~ #5 ~priest~ ( 1 ) // Protection from Missiles

  ADD_MEMORIZED_SPELL ~SPPR701~ #6 ~priest~ ( 1 ) // Shield of Archons
  ADD_MEMORIZED_SPELL ~SPPR717~ #6 ~priest~ ( 1 ) // Creeping Doom

  ADD_MEMORIZED_SPELL ~SPCLI12~ #0 ~innate~ ( 1 ) // Smilodon
  ADD_MEMORIZED_SPELL ~SPCLI15~ #0 ~innate~ ( 1 ) // Natural Restoral
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\controversial\S!CHAK.BAF~
// Legdoril from Samia's party

COPY_EXISTING ~LEGDOR.cre~ ~override~

  REMOVE_KNOWN_SPELLS
  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR101~ #0 ~priest~ ( 1 ) // Bless
  ADD_MEMORIZED_SPELL ~SPPR102~ #0 ~priest~ ( 2 ) // Command
  ADD_MEMORIZED_SPELL ~SPPR108~ #0 ~priest~ ( 2 ) // Remove Fear
  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 3 ) // Doom

  ADD_MEMORIZED_SPELL ~SPPR201~ #1 ~priest~ ( 1 ) // Aid
  ADD_MEMORIZED_SPELL ~SPPR203~ #1 ~priest~ ( 1 ) // Chant
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 1 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR208~ #1 ~priest~ ( 3 ) // Hold Person
  ADD_MEMORIZED_SPELL ~SPPR209~ #1 ~priest~ ( 1 ) // Know Alignment
  ADD_MEMORIZED_SPELL ~SPPR214~ #1 ~priest~ ( 2 ) // DUHM

  ADD_MEMORIZED_SPELL ~SPPRI02~ #2 ~priest~ ( 3 ) // Dispel Magic caster-friendly
  ADD_MEMORIZED_SPELL ~SPPR308~ #2 ~priest~ ( 2 ) // Remove Paralysis
  ADD_MEMORIZED_SPELL ~SPPR317~ #2 ~priest~ ( 2 ) // Cure Disease
  ADD_MEMORIZED_SPELL ~SPPR318~ #2 ~priest~ ( 2 ) // Zone of Sweet Air

  ADD_MEMORIZED_SPELL ~SPPR403~ #3 ~priest~ ( 3 ) // Free Actions
  ADD_MEMORIZED_SPELL ~SPPR406F~ #3 ~priest~ ( 1 ) // Defensive Harmony
  ADD_MEMORIZED_SPELL ~SPPR407~ #3 ~priest~ ( 1 ) // Protection from Lightning
  ADD_MEMORIZED_SPELL ~SPPR408~ #3 ~priest~ ( 1 ) // Protection from Evil
  ADD_MEMORIZED_SPELL ~SPPR409~ #3 ~priest~ ( 2 ) // Death Ward
  ADD_MEMORIZED_SPELL ~SPPR412~ #3 ~priest~ ( 1 ) // Holy Power

  ADD_MEMORIZED_SPELL ~SPPR503~ #4 ~priest~ ( 2 ) // Flame Strike
  ADD_MEMORIZED_SPELL ~SPPR508~ #4 ~priest~ ( 3 ) // Chaotic Commands
  ADD_MEMORIZED_SPELL ~SPPR509~ #4 ~priest~ ( 1 ) // Magic Resistance
  ADD_MEMORIZED_SPELL ~SPPR511~ #4 ~priest~ ( 1 ) // Slay Living
  ADD_MEMORIZED_SPELL ~SPPR513~ #4 ~priest~ ( 1 ) // Righteous Magic
  
  ADD_MEMORIZED_SPELL ~SPPR607~ #5 ~priest~ ( 2 ) // Heal
  ADD_MEMORIZED_SPELL ~SPPR613~ #5 ~priest~ ( 1 ) // Protection from Missiles
  ADD_MEMORIZED_SPELL ~SPPR617~ #5 ~priest~ ( 1 ) // Heavenly Shield
  ADD_MEMORIZED_SPELL ~SPPR618~ #5 ~priest~ ( 1 ) // Champion's Might
  ADD_MEMORIZED_SPELL ~SPPR698~ #5 ~priest~ ( 1 ) // Blade Barrier

  ADD_MEMORIZED_SPELL ~SPPR701~ #6 ~priest~ ( 1 ) // Shield of Archons
  ADD_MEMORIZED_SPELL ~SPPR727~ #6 ~priest~ ( 1 ) // Fallen Deva

// Ferric from Samia's party

COMPILE ~IATweaks\scripts\controversial\S!DESHAR.baf~

// Samia

COPY_EXISTING ~SAMIA.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\controversial\SAMIA.BAF~

// Archer from Illithid Hideout

COPY_EXISTING ~hlarch.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 2 ) // Doom
  ADD_MEMORIZED_SPELL ~SPPR202~ #1 ~priest~ ( 1 ) // Barkskin
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 2 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR209~ #1 ~priest~ ( 1 ) // Know Alignment
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 1 ) // Protection from Fire
  ADD_MEMORIZED_SPELL ~SPPR312~ #2 ~priest~ ( 1 ) // Strength of One
  ADD_MEMORIZED_SPELL ~SPPR315~ #2 ~priest~ ( 1 ) // Cure Medium Wounds
  ADD_MEMORIZED_SPELL ~SPCL121~ #0 ~innate~ ( 5 ) // Called Shot
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL922~ #0 ~innate~ ( 1 ) // Contact with Nature
// Cleric from Illithid Compound

COPY_EXISTING ~HLCLERIC.cre~ ~override~ 
  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR101~ #0 ~priest~ ( 1 ) // Bless
  ADD_MEMORIZED_SPELL ~SPPR102~ #0 ~priest~ ( 3 ) // Command
  ADD_MEMORIZED_SPELL ~SPPR108~ #0 ~priest~ ( 1 ) // Remove Fear
  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 4 ) // Doom

  ADD_MEMORIZED_SPELL ~SPPR201~ #1 ~priest~ ( 1 ) // Aid
  ADD_MEMORIZED_SPELL ~SPPR203~ #1 ~priest~ ( 1 ) // Chant
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 1 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR208~ #1 ~priest~ ( 6 ) // Hold Person
  ADD_MEMORIZED_SPELL ~SPPR214~ #1 ~priest~ ( 2 ) // DUHM

  ADD_MEMORIZED_SPELL ~SPPRI02~ #2 ~priest~ ( 2 ) // Dispel Magic caster-friendly
  ADD_MEMORIZED_SPELL ~SPPR308~ #2 ~priest~ ( 2 ) // Remove Paralysis
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 2 ) // Protection From Fire
  ADD_MEMORIZED_SPELL ~SPPR317~ #2 ~priest~ ( 2 ) // Cure Disease
  ADD_MEMORIZED_SPELL ~SPPR318~ #2 ~priest~ ( 2 ) // Zone of Sweet Air

  ADD_MEMORIZED_SPELL ~SPPR403~ #3 ~priest~ ( 2 ) // Free Actions
  ADD_MEMORIZED_SPELL ~SPPR406F~ #3 ~priest~ ( 2 ) // Defensive Harmony
  ADD_MEMORIZED_SPELL ~SPPR407~ #3 ~priest~ ( 2 ) // Protection from Lightning
  ADD_MEMORIZED_SPELL ~SPPR408~ #3 ~priest~ ( 1 ) // Protection from Evil
  ADD_MEMORIZED_SPELL ~SPPR409~ #3 ~priest~ ( 1 ) // Death Ward
  ADD_MEMORIZED_SPELL ~SPPR412~ #3 ~priest~ ( 1 ) // Holy Power
  // ADD_MEMORIZED_SPELL ~SPPR420~ #1 ~priest~ ( 2 ) // Resist Fire and Cold

  ADD_MEMORIZED_SPELL ~SPPR502~ #4 ~priest~ ( 1 ) // Cure Critical Wounds
  ADD_MEMORIZED_SPELL ~SPPR502~ #4 ~priest~ ( 2 ) // Flame Strike
  ADD_MEMORIZED_SPELL ~SPPR508~ #4 ~priest~ ( 1 ) // Chaotic Commands
  ADD_MEMORIZED_SPELL ~SPPR509~ #4 ~priest~ ( 1 ) // Magic Resistance
  ADD_MEMORIZED_SPELL ~SPPR510~ #4 ~priest~ ( 2 ) // Cause Critical Wounds
  ADD_MEMORIZED_SPELL ~SPPR511~ #4 ~priest~ ( 1 ) // Slay Living
  ADD_MEMORIZED_SPELL ~SPPR513~ #4 ~priest~ ( 1 ) // Righteous Magic

  ADD_MEMORIZED_SPELL ~SPPR607~ #5 ~priest~ ( 2 ) // Heal
  ADD_MEMORIZED_SPELL ~SPPR608~ #5 ~priest~ ( 2 ) // Harm
  ADD_MEMORIZED_SPELL ~SPPR613~ #5 ~priest~ ( 1 ) // Protection from Missiles
  ADD_MEMORIZED_SPELL ~SPPR617~ #5 ~priest~ ( 1 ) // Heavenly Shield
  ADD_MEMORIZED_SPELL ~SPPR618~ #5 ~priest~ ( 1 ) // Champion's Might
  ADD_MEMORIZED_SPELL ~SPPR698~ #5 ~priest~ ( 1 ) // Blade Barrier

  ADD_MEMORIZED_SPELL ~SPPR701~ #6 ~priest~ ( 1 ) // Shield of Archons
  ADD_MEMORIZED_SPELL ~SPPR722~ #6 ~priest~ ( 1 ) // Storm of Vengeance
  ADD_MEMORIZED_SPELL ~SPPR729~ #6 ~priest~ ( 1 ) // Foreknowledge
  ADD_MEMORIZED_SPELL ~SPPRI26~ #6 ~priest~ ( 1 ) // Continual Cure
  
  ADD_MEMORIZED_SPELL ~SPCLI24~ #0 ~innate~ ( 1 ) // Summon Fallen Archdeva


//////////////// Alhoon

// Increase APR to keep it at 6 under Improved Haste

COPY_EXISTING ~mindal01.cre~ ~override~
  WRITE_BYTE 0x53 4  // APR
  
// Revanek from Twisted Rune

COMPILE ~IATweaks\scripts\controversial\S!REVAN.BAF~

// Shyressa from Twisted Rune

COPY_EXISTING ~HLSHYR.cre~ ~override~
  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 3 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 2 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 3 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\controversial\S!HLSHYR.BAF~

// Shangalar

COPY_EXISTING ~HLSHANG.cre~ ~override~

  ADD_MEMORIZED_SPELL ~SPINI39~ #0 ~innate~ ( 1 ) // Grave Silence

COMPILE ~IATweaks\scripts\controversial\S!SHANG.BAF~

// Valeria from Squirreled Away

COPY_EXISTING ~DEMFIG02.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 2 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\controversial\S!DEMFI2.BAF~

// Exterminator from Squirreled Away

COPY_EXISTING ~DEMFIG02.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 3 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\controversial\S!DEMARC.BAF~

// Falahar from Squirreled Away

COPY_EXISTING ~DEMFIG01.cre~ ~override~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 2 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\controversial\S!DEMFIG.BAF~

// Master Assassin

COMPILE ~IATweaks\scripts\controversial\S!RUNE2.baf~
COMPILE ~IATweaks\scripts\controversial\S!RUNEF2.baf~

// Guildmaster

COMPILE ~IATweaks\scripts\controversial\S!RUNE1.baf~

// Grandfather of Assassins

COMPILE ~IATweaks\scripts\controversial\S!RUNEF.baf~

// Saladrex

COPY_EXISTING ~GORSAL.cre~ ~override~

  ADD_MEMORIZED_SPELL ~SPIN692~ #0 ~innate~ ( 5 ) // Greater Silence

COMPILE ~IATweaks\scripts\controversial\GORSAL.BAF~

// Ancient Dragon

COPY_EXISTING ~fsdragon.cre~ ~override~

  ADD_MEMORIZED_SPELL ~SPIN692~ #0 ~innate~ ( 5 ) // Greater Silence

COMPILE ~IATweaks\scripts\controversial\s!fsdrag.BAF~

