SILENT

INCLUDE "%MOD_FOLDER%/lib/components/IA_rebalancing/helper_functions.tph"

///////// Change elemental bonuses to 75 ////////////

// Resist Fire/Cold

COPY_EXISTING ~sppr210.spl~ ~override/sppr420.spl~
  SAY UNIDENTIFIED_DESC @6101
  WRITE_BYTE 0x34 4 // Level
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      match_power = 2
      power = 4
  END

COPY_EXISTING ~hidespl.2da~ ~override~
  COUNT_2DA_COLS ~colcount~
  COUNT_2DA_ROWS ~colcount~ ~rowcount~
  INSERT_2DA_ROW ~rowcount~ ~colcount~ ~SPPR210 1 0 0~
  PRETTY_PRINT_2DA

COPY_EXISTING ~spell.ids~ ~override~
  REPLACE_EVALUATE ~1210[ %TAB%]*CLERIC_RESIST_FIRE~ BEGIN
  END ~1420 CLERIC_RESIST_FIRE~

COPY_EXISTING_REGEXP GLOB ~.+\.cre~ ~override~
  REMOVE_KNOWN_SPELL ~SPPR210~
  REMOVE_MEMORIZED_SPELL ~SPPR210~
  BUT_ONLY

// Patch all spells that grant resistances

ACTION_FOR_EACH res_spell IN ~sppr306.spl~ ~spwi319.spl~ ~spdr302.spl~ ~spwi320.spl~ ~sppr420.spl~ ~sppr407.spl~ ~spwi512.spl~ ~sppri12.spl~ ~spwi517.spl~ ~spwi606.spl~ ~spdr702.spl~ ~spwi702.spl~ ~spwii02.spl~ ~spwi803.spl~ ~spwish10.spl~ ~spcl721.spl~ BEGIN
  COPY_EXISTING ~%res_spell%~ ~override~
    SET is_ally_only_opcode_added = 0
    PATCH_FOR_EACH res_opcode IN 27 28 29 30 31 84 85 BEGIN
      LPF ~S!SPELL_USES_OPCODE~
        INT_VAR
          match_opcode = %res_opcode%
        RET
          is_found opcode_target
      END
      PATCH_IF ~%is_found%~ STR_EQ ~TRUE~ BEGIN
        LPF ~ALTER_EFFECT~
          INT_VAR
            match_opcode = %res_opcode%
            parameter1 = 75
            parameter2 = 1
        END
      END
      PATCH_IF (~%is_found%~ STR_EQ ~TRUE~ AND is_ally_only_opcode_added == 0) BEGIN
        is_ally_only_opcode_added = is_ally_only_opcode_added + 1
        LPF ~ADD_SPELL_EFFECT~
          INT_VAR
            insert_point = 0
            opcode = 318
            parameter2 = 50
            target = opcode_target
            timing = 10
            duration = 5
          STR_VAR
            resource = EVAL ~%SOURCE_RES%~
        END
      END
    END
END

COPY_EXISTING ~sppr306.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6107

COPY_EXISTING ~spwi319.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6108

COPY_EXISTING ~scrl6h.itm~ ~override~
  SAY IDENTIFIED_DESC @6108

COPY_EXISTING ~spwi320.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6109

COPY_EXISTING ~scrl6i.itm~ ~override~
  SAY IDENTIFIED_DESC @6109

COPY_EXISTING ~spdr302.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6110

COPY_EXISTING ~sppr407.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6111
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 8 9 10 11 12 13 14 15 16 17 18 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END

COPY_EXISTING ~spwi512.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6112
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 10 11 12 13 14 15 16 17 18 19 20 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END

COPY_EXISTING ~scrl5t.itm~ ~override~
  SAY IDENTIFIED_DESC @6112

COPY_EXISTING ~sppri12.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6113
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 10 11 12 13 14 15 16 17 18 19 20 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END

COPY_EXISTING ~spwi517.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6114
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 10 11 12 13 14 15 16 17 18 19 20 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END

COPY_EXISTING ~scrl6y.itm~ ~override~
  SAY IDENTIFIED_DESC @6114

COPY_EXISTING ~spwi606.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6115
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 13 14 15 16 17 18 19 20 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END

COPY_EXISTING ~scrl7j.itm~ ~override~
  SAY IDENTIFIED_DESC @6115

COPY_EXISTING ~spdr702.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6116
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 15 16 17 18 19 20 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 28
      opcode = 27
  END

COPY_EXISTING ~spwi702.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6116
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 15 16 17 18 19 20 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 28
      opcode = 27
  END

COPY_EXISTING ~scrl8e.itm~ ~override~
  SAY IDENTIFIED_DESC @6116

COPY_EXISTING ~spwii02.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6115
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END

COPY_EXISTING ~spwi803.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6117
    // Remove level progression from the spell
  PATCH_FOR_EACH min_lvl_val IN 17 18 19 20 BEGIN
    LPF ~DELETE_SPELL_HEADER~ 
      INT_VAR
        header_type = ~-1~
        min_level = min_lvl_val
    END
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END

COPY_EXISTING ~scrl8y.itm~ ~override~
  SAY IDENTIFIED_DESC @6117
  
COPY_EXISTING ~scrl9b.itm~ ~override~
  SAY IDENTIFIED_DESC @6117

COPY_EXISTING ~spwish10.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6115
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      duration_high = 300
  END

COPY_EXISTING ~spcl721.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6118

// Change description for Talos

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_rows = 2da_rows_to_ids_mapping
END

// update class description for Clerics
COPY_EXISTING ~clastext.2da~ ~override/clastext.2da~
  COUNT_2DA_COLS ~colcount~
  SET_2DA_ENTRY_LATER ~s!cleric_desc~ $clastext_rows("GODTALOS") $clastext_cols("DESCSTR") RESOLVE_STR_REF (@5023)
  SET_2DA_ENTRIES_NOW ~s!cleric_desc~ ~colcount~
  PRETTY_PRINT_2DA

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  INT_VAR
    col_with_names = 1
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~kitlist.2da~ ~override/kitlist.2da~
  COUNT_2DA_COLS ~colcount~
  SET_2DA_ENTRY_LATER ~s!cleric_desc~ $kitlist_rows("TALOS") $kitlist_cols("HELP")  RESOLVE_STR_REF (@5023)
  SET_2DA_ENTRIES_NOW ~s!cleric_desc~ ~colcount~
  PRETTY_PRINT_2DA

// Robe of Elemental Resistance

COPY_EXISTING ~s!robe02.itm~ ~override~
  SAY IDENTIFIED_DESC @7000
  PATCH_FOR_EACH res_opcode IN 28 29 30 BEGIN
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = %res_opcode%
        parameter1 = 75
        parameter2 = 1
    END
  END

////////// Reworked Improved Haste and Whirlwind Attack ////////////

ACTION_FOR_EACH improved_haste_spell IN ~SPINI33~ ~SPINI88~ ~SPWI613~ ~S!CHMPMZ~ ~SPWISH36~ ~SPWISH37~ ~SPWISH40~ BEGIN
  COPY_EXISTING ~%improved_haste_spell%.spl~ ~override~
    LPF ~S!SPELL_USES_OPCODE~
      INT_VAR
        match_opcode = 16
      RET
        opcode_target
    END
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 16
        parameter2 = 0
        silent = 1
    END
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 317
        parameter2 = 0
        silent = 1
    END
    LPF ~CLONE_EFFECT~ 
      INT_VAR
        match_opcode = 16
        opcode = 1
        parameter1 = 1
        parameter2 = 0
        silent = 1
    END
    LPF ~CLONE_EFFECT~ 
      INT_VAR
        match_opcode = 317
        opcode = 1
        parameter1 = 1
        parameter2 = 0
        silent = 1
    END
    PATCH_FOR_EACH improved_haste_spell_to_delete IN ~SPINI33~ ~SPINI88~ ~SPWI613~ ~S!CHMPMZ~ ~SPWISH36~ ~SPWISH37~ ~SPWISH40~ BEGIN
      LPF ~ADD_SPELL_EFFECT~ 
        INT_VAR
          opcode = 321
          insert_point = 0
          target = EVAL ~%opcode_target%~
          resist_dispel = 0
        STR_VAR
          resource = EVAL ~%improved_haste_spell_to_delete%~
      END
    END
  BUT_ONLY
  IF_EXISTS
END

COPY_EXISTING ~SPPR618.spl~ ~override~ // Champion's Might
  SAY UNIDENTIFIED_DESC @6124

COPY_EXISTING ~SPWI613.spl~ ~override~ // Improved Haste
  SAY UNIDENTIFIED_DESC @6125
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      target_count = 2
  END

COPY_EXISTING ~SPINI33.spl~ ~override~ // Improved Haste for Riskbreaker
  SAY UNIDENTIFIED_DESC @6125

COPY_EXISTING ~SPINI88.spl~ ~override~ // Flurry of Blows
  SAY UNIDENTIFIED_DESC @6125

// update Flurry of Blows description in class description for Monk

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~clastext.2da~ ~override/clastext.2da~
  COUNT_2DA_COLS ~colcount~
  SET_2DA_ENTRY_LATER ~s!monk_desc~ $clastext_rows("MONK") $clastext_cols("DESCSTR") RESOLVE_STR_REF (@5030)
  SET_2DA_ENTRIES_NOW ~s!monk_desc~ ~colcount~
  PRETTY_PRINT_2DA

////////// Non-stackable bonuses from rings and cloaks ////////////

COPY ~IATweaks\resources\spl\s!ac_st1.spl~ ~override~
COPY ~IATweaks\resources\spl\s!ac_st2.spl~ ~override~
COPY ~IATweaks\resources\spl\s!ac_st3.spl~ ~override~
COPY ~IATweaks\resources\spl\s!ac_st4.spl~ ~override~

COPY ~IATweaks\resources\eff\s!ac_st1.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ac_st2.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ac_st3.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ac_st4.eff~ ~override~

ACTION_DEFINE_ASSOCIATIVE_ARRAY item_to_enchantment_mapping BEGIN
  "CLCK01"=>1
  "CLCK02"=>2
  "CLCK06"=>1
  // "CLCK32" - +1 all, can be made +2
  "NPCLCK"=>1
  "s!clck01"=>4
  "s!clck02"=>3
  // "s!clck07" - +3 all 
  // "s!clck08"=>3 - probably make it a pure +1AC
  // "s!clck09"=>3 - probably make it a pure +2AC
  "s!clck11"=>1
  "s!clck12"=>2
  // "s!clck12" - +3 all
  "RING06"=>1
  "RING07"=>2
  "RING25"=>1
  "RING39"=>2
  "RING41"=>3
  "s!ring01"=>4
  "s!ring03"=>3
  "s!ring05"=>1
  // Samara Fruit
  // Holy Symbol of Lathander
  // 
END

ACTION_PHP_EACH item_to_enchantment_mapping AS item_file => enchantment BEGIN
  COPY_EXISTING ~%item_file%.itm~ ~override~
    PATCH_FOR_EACH opcode_to_delete IN 0 33 34 35 36 37 325 BEGIN
      LPF ~DELETE_EFFECT~
        INT_VAR
          match_opcode = opcode_to_delete
      END
    END
    FOR (i = 1; i <= enchantment; ++i) BEGIN
      LPF ~ADD_ITEM_EQEFFECT~
        INT_VAR
          insert_point = 0
          opcode = 272
          target = 1
          parameter1 = 1
          parameter2 = 0
          timing = 2
        STR_VAR
          resource = EVAL ~S!AC_ST%i%~
      END
    END
  BUT_ONLY
  IF_EXISTS
END

// Ray of Fragmentation

ADD_PROJECTILE ~IATweaks\resources\pro\s!roffra.pro~

COPY_EXISTING ~spwi413.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6141
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~%s!roffra%~
  END

COPY_EXISTING ~S!SCRL01.itm~ ~override~
  SAY IDENTIFIED_DESC @6141

// Change APR and dmg for Gem, Coin and Amber Golems

ACTION_FOR_EACH lesser_golem_weapon IN ~S!GEM.itm~ ~S!AMBER.itm~ BEGIN
  COPY_EXISTING ~%lesser_golem_weapon%~ ~override~
    LPF ~ALTER_ITEM_HEADER~
      INT_VAR
        dicesize = 8
        dicenumber = 3
        damage_bonus = 2
    END
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 221
        match_parameter2 = 3
    END
    LPF ~ADD_ITEM_EQEFFECT~
      INT_VAR
        target = 1
        timing = 2
        opcode = 1
        parameter1 = 1
        parameter2 = 0
    END 
END 

// Make Gem, Coin and Amber Golems polymorphable

ACTION_FOR_EACH lesser_golem_weapon IN ~S!GEM.itm~ ~S!AMBER.itm~ BEGIN
  COPY_EXISTING ~%lesser_golem_weapon%~ ~override~
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 101
        match_parameter2 = 135
    END
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 101
        match_parameter2 = 111
    END
    LPF ~ADD_ITEM_EQEFFECT~
      INT_VAR
        target = 1
        timing = 2
        opcode = 325
        parameter1 = 1
        parameter2 = 0
    END 
END

// Hand of Undoing

ACTION_FOR_EACH golem_cre IN ~S!ELEGOA~ ~S!ELEGOS~ ~S!GELEGO~ ~S!GELEGS~ ~S!GELEM1~ ~S!GEMPP~ BEGIN
  COPY_EXISTING ~%golem_cre%.cre~ ~override~
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 206
      STR_VAR
        match_resource = ~SPWI703~
    END
  BUT_ONLY
END

ACTION_FOR_EACH golem_weapon IN ~S!GTWIST~ ~S!MITGOL~ ~S!SUPGOL~ ~S!TWIST~ ~S!TWIST1~ ~S!ULTGOL~ ~S!WEBGOL~ BEGIN
  COPY_EXISTING ~%golem_weapon%.itm~ ~override~
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 206
      STR_VAR
        match_resource = ~SPWI703~
    END
  BUT_ONLY
END

COPY ~IATweaks\resources\spl\spwi703d.spl~ ~override~
COPY ~IATweaks\resources\spl\spwi703e.spl~ ~override~

COPY_EXISTING ~s!golem4.eff~ ~override~
  WRITE_LONG 0x1c 100 // 100 flat dmg

COPY_EXISTING ~S!SCRL02.itm~ ~override~
  SAY IDENTIFIED_DESC @6145

COPY_EXISTING ~SPWI703.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6145

  // Immunity to Golems when start casting
  LPF ~ADD_SPELL_CFEFFECT~
    INT_VAR
      opcode = 100
      target = 1
      parameter1 = 144
      parameter2 = 4
      duration = 4
      resist_dispel = 0
  END
  
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 318
      insert_point = ~0~
      target = 2
      power = 7
      parameter1 = 0
      parameter2 = 28
      duration = 1
      resist_dispel = 0
    STR_VAR
      resource = "SPWI703"
  END

  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 326
      insert_point = ~-1~
      target = 2
      power = 7
      parameter1 = 90
      parameter2 = %magic_damage_res_greater_equal_than_row%
      duration = 1
      resist_dispel = 0
    STR_VAR
      resource = "SPWI703D"
  END

// Remove immunity to Comet and Dragon's Breath from Ice Golems

ACTION_FOR_EACH golem_cre IN ~S!ICEGO1~ ~S!ICEGO2~ ~S!ICEGOA~ ~S!ICEGOL~ ~S!ICEGOR~ BEGIN
  COPY_EXISTING ~%golem_cre%.cre~ ~override~
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 206
      STR_VAR
        match_resource = ~SPWI922~
    END
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 206
      STR_VAR
        match_resource = ~SPWI925~
    END
  BUT_ONLY
END

