/// Add elemental spells

SILENT

// Whirlwind

ADD_PROJECTILE ~IATweaks\resources\pro\s!whirlw.pro~
COPY ~IATweaks\resources\spl\s!whirlw.spl~ ~override~
  SAY NAME1 @6147
  SAY UNIDENTIFIED_DESC @6148
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!whirlw~
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      power = 7
  END

COPY ~IATweaks\resources\bam\spells\whirlwind\WHIRLWX.BAM~ ~override~
COPY ~IATweaks\resources\bam\spells\whirlwind\S!WHIRLB.BAM~ ~override~
COPY ~IATweaks\resources\bam\spells\whirlwind\S!WHIRLC.BAM~ ~override~
COPY ~IATweaks\resources\wav\iwd_whirlwind\EFF_P105.WAV~ ~override~

// Ice Spikes

ADD_PROJECTILE ~IATweaks\resources\pro\s!spike.pro~
COPY ~IATweaks\resources\spl\s!spike.spl~ ~override~
  SAY NAME1 @6149
  SAY UNIDENTIFIED_DESC @6150
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!spike~
  END

COPY ~IATweaks\resources\bam\spells\ice_spike\s!spike.BAM~ ~override~
COPY ~IATweaks\resources\bam\spells\ice_spike\s!spikeb.BAM~ ~override~

// Fissure

ADD_PROJECTILE ~IATweaks\resources\pro\s!fissur.pro~
COPY ~IATweaks\resources\spl\s!fissur.spl~ ~override~
  SAY NAME1 @6151
  SAY UNIDENTIFIED_DESC @6152
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!fissur~
  END

COPY ~IATweaks\resources\bam\spells\magma_fissure\s!fissur.BAM~ ~override~
COPY ~IATweaks\resources\bam\spells\magma_fissure\s!fissub.BAM~ ~override~