/// Add elemental spells

PRINT @5090

SILENT

// Whirlwind

ADD_PROJECTILE ~IATweaks\resources\pro\s!whirlw.pro~
ADD_PROJECTILE ~IATweaks\resources\pro\s!whirl2.pro~
COPY ~IATweaks\resources\spl\s!whirlw.spl~ ~override~
  SAY NAME1 @6147
  SAY UNIDENTIFIED_DESC @6148
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!whirlw~
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      power = 7
  END

COPY ~IATweaks\resources\bam\spells\whirlwind\WHIRLWX.BAM~ ~override~
COPY ~IATweaks\resources\bam\spells\whirlwind\S!WHIRLB.BAM~ ~override~
COPY ~IATweaks\resources\bam\spells\whirlwind\S!WHIRLC.BAM~ ~override~
COPY ~IATweaks\resources\wav\iwd_whirlwind\EFF_P105.WAV~ ~override~

COPY_EXISTING ~s!whirlw.spl~ ~override/s!whirl2.spl~
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!whirl2~
  END

// Ice Spikes

ADD_PROJECTILE ~IATweaks\resources\pro\s!spike.pro~
COPY ~IATweaks\resources\spl\s!spike.spl~ ~override~
  SAY NAME1 @6149
  SAY UNIDENTIFIED_DESC @6150
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!spike~
  END

COPY ~IATweaks\resources\bam\spells\ice_spike\s!spike.BAM~ ~override~
COPY ~IATweaks\resources\bam\spells\ice_spike\s!spikeb.BAM~ ~override~

// Fissure

ADD_PROJECTILE ~IATweaks\resources\pro\s!fissur.pro~
COPY ~IATweaks\resources\spl\s!fissur.spl~ ~override~
  SAY NAME1 @6151
  SAY UNIDENTIFIED_DESC @6152
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!fissur~
  END

COPY ~IATweaks\resources\bam\spells\magma_fissure\s!fissur.BAM~ ~override~
COPY ~IATweaks\resources\bam\spells\magma_fissure\s!fissub.BAM~ ~override~

// Acid Wave

COPY ~IATweaks\resources\wav\iwd_wave\#FF_P110.WAV~ ~override~
COPY ~IATweaks\resources\wav\iwd_wave\TRA_56.WAV~ ~override~

ADD_PROJECTILE ~IATweaks\resources\pro\s!awave.pro~
COPY_EXISTING ~s!awave.pro~ ~override~
  SET acid_wave_ini = IDS_OF_SYMBOL (~animate~ ~ANVIL_ACID_WAVE~)
  WRITE_SHORT 0x134 acid_wave_ini // ID of .ini file with acid wave
ADD_PROJECTILE ~IATweaks\resources\pro\s!awavet.pro~
COPY_EXISTING ~s!awavet.pro~ ~override~
  WRITE_SHORT 0x21a ~%s!awave%~ // explosion projectile

COPY ~IATweaks\resources\spl\s!awave.spl~ ~override~
  SAY NAME1 @6153
  SAY UNIDENTIFIED_DESC @6154
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!awavet~
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      power = 7
      resist_dispel = 0
  END

COPY ~IATweaks\resources\vvc\S!WAVEH.VVC~ ~override~
COPY ~IATweaks\resources\bam\spells\acid_wave\s!awaveb.bam~ ~override~
COPY ~IATweaks\resources\bam\spells\acid_wave\s!awaveh.bam~ ~override~
COPY ~IATweaks\resources\bam\spells\acid_wave\s!awavex.bam~ ~override~

// Ice Explosion

COPY ~IATweaks\resources\pro\s!harm05.pro~ ~override/s!iceex5.pro~
ADD_PROJECTILE ~override/s!iceex5.pro~

COPY ~IATweaks\resources\spl\s!iceexp.spl~ ~override~
COPY ~IATweaks\resources\spl\s!iceexb.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!iceex5~
  END

COPY ~IATweaks\resources\bam\spells\ice_explosion\s!iceexp.bam~ ~override~

// Acid Circle

ADD_PROJECTILE ~IATweaks\resources\pro\s!acidci.pro~

COPY ~IATweaks\resources\spl\s!acidci.spl~ ~override~
  SAY NAME1 @6155
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!acidci~
  END

COPY ~IATweaks\resources\bam\spells\acid_circle\s!acidci.bam~ ~override~