PRINT @5094

SILENT

/////// Suna Seni encounter ///////

COPY_EXISTING ~RESUNA.cre~ ~override~
  WRITE_SHORT 0x24 99 // HP
  WRITE_SHORT 0x26 99 // HP

COPY_EXISTING ~REELDAR.cre~ ~override~
  WRITE_SHORT 0x24 96 // HP
  WRITE_SHORT 0x26 96 // HP
    
  LPF ~ALTER_EFFECT~ // ** in Sword and Shield
    INT_VAR
      match_opcode = 233
      match_parameter2 = 112
      parameter1 = 2
  END

COPY_EXISTING ~REMAGE01.cre~ ~override~
  WRITE_SHORT 0x24 40 // HP
  WRITE_SHORT 0x26 40 // HP
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC

COPY_EXISTING ~RETHUG02.cre~ ~override~
  WRITE_SHORT 0x24 40 // HP
  WRITE_SHORT 0x26 40 // HP
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC

COPY_EXISTING ~REFIGH01.cre~ ~override~
  WRITE_BYTE 0x54 8  // Saves
  WRITE_BYTE 0x55 10 // Saves
  WRITE_BYTE 0x56 9  // Saves
  WRITE_BYTE 0x57 9  // Saves
  WRITE_BYTE 0x58 11 // Saves
    
  LPF ~ALTER_EFFECT~ // ***** in 2h Sword
    INT_VAR
      match_opcode = 233
      match_parameter2 = 93
      parameter1 = 5
  END

// Postpone Suna Seni till PC has 250000 exp

ACTION_FOR_EACH suna_seni_area_script IN ~AR0041.BCS~ ~AR0045.BCS~ ~AR0046.BCS~ BEGIN
  COPY_EXISTING ~%suna_seni_area_script%~ ~override~
    DECOMPILE_AND_PATCH BEGIN
      REPLACE_EVALUATE
        ~\([ %TAB%]+\)\(Global("RandomEncounters","GLOBAL",0)\)\([ %TAB%%LNL%%MNL%%WNL%]+\)~
      BEGIN
      END
      ~%MATCH1%%MATCH2%%MATCH3%%MATCH1%XPGT(Player1,249999)%MATCH3%~
    END
END

/////////// Rework Vampires ///////////

ACTION_FOR_EACH vampire_weapon IN ~VAMP~ ~VAMP1~ ~VAMP2~ ~VAMP3~ ~S!VLORD~ ~S!BODHI~ BEGIN
  COPY_EXISTING ~%vampire_weapon%.itm~ ~override~
    READ_LONG 0x64 headers_offset
    WRITE_BYTE (headers_offset + 0x18) (THIS - 1)
    WRITE_BYTE (headers_offset + 0x1a) (THIS + 2)
    PATCH_FOR_EACH spl_to_dispel IN ~SPPR413~ ~SPIN738~ ~SPPR508~ ~SPWI725E~ BEGIN
      LPF ~CLONE_EFFECT~
        INT_VAR
          match_opcode = 221
          opcode = 321
          parameter1 = 0
          parameter2 = 0
        STR_VAR
          insert = ~above~
          resource = EVAL ~%spl_to_dispel%~
      END
    END
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 221
        match_parameter2 = 2
    END
    LPF ~ADD_ITEM_EFFECT~
      INT_VAR
        type = 1
        opcode = 12
        insert_point = 0
        target = 2
        timing = 9
        dicenumber = 1
        dicesize = 8
        special = 1 // Drain HP
    END
END

// 41495 - One level drained
ACTION_FOR_EACH vampire_weapon IN ~VAMP~ ~VAMP1~ BEGIN
  COPY_EXISTING ~%vampire_weapon%.itm~ ~override~
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 216
        parameter1 = 1
    END
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 139
        parameter1 = 41495
    END
  END

ACTION_FOR_EACH vampire_weapon IN ~VAMP2~ ~VAMP3~ BEGIN
  COPY_EXISTING ~%vampire_weapon%.itm~ ~override~
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 216
        parameter1 = 2
    END
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 139
        parameter1 = 40968
    END
  END

ACTION_FOR_EACH vampire_weapon IN ~S!VLORD~ ~S!BODHI~ BEGIN
  COPY_EXISTING ~%vampire_weapon%.itm~ ~override~
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 216
        parameter1 = 3
    END
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 139
        parameter1 = 40969
    END
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 12
        match_parameter2 = 0
        dicenumber = 2
    END
  END

// Vampiric Mist

COPY_EXISTING ~MISTVA.itm~ ~override~
  READ_LONG 0x64 headers_offset
  WRITE_BYTE (headers_offset + 0x18) (THIS - 1)
  WRITE_BYTE (headers_offset + 0x1a) (THIS + 1)
  PATCH_FOR_EACH spl_to_dispel IN ~SPPR413~ ~SPIN738~ ~SPPR403~ BEGIN
    LPF ~CLONE_EFFECT~
      INT_VAR
        match_opcode = 221
        opcode = 321
        parameter1 = 0
        parameter2 = 0
      STR_VAR
        insert = ~above~
        resource = EVAL ~%spl_to_dispel%~
    END
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 221
      match_parameter2 = 2
  END
  LPF ~ADD_ITEM_EFFECT~
    INT_VAR
      type = 1
      opcode = 12
      insert_point = 0
      target = 2
      timing = 9
      dicenumber = 1
      dicesize = 8
      special = 1 // Drain HP
  END

// Eminent Vampires //

ACTION_FOR_EACH eminent_vamp_cre IN ~s!vamemi~ ~s!vamemr~ ~VAMEMI01~ ~VAMPAT01~ ~VAMPIF01~ ~VAMPIM01~ BEGIN
  COPY_EXISTING ~%eminent_vamp_cre%.cre~ ~override~
    WRITE_BYTE 0x59 25  // Fire Resistance
    WRITE_BYTE 0x5c 25  // Acid Resistance
    WRITE_BYTE 0x5e 25  // Magic Fire Resistance
END

// scripts of Vampires

COMPILE ~IATweaks\scripts\creatures\S!ORVAM.BAF~
COMPILE ~IATweaks\scripts\creatures\S!nevm4.BAF~
COMPILE ~IATweaks\scripts\creatures\S!vamp1.BAF~
COMPILE ~IATweaks\scripts\creatures\S!vamp2.BAF~
COMPILE ~IATweaks\scripts\creatures\S!vamp3.BAF~
COMPILE ~IATweaks\scripts\creatures\S!vamp4.BAF~
COMPILE ~IATweaks\scripts\creatures\S!mfvamp.BAF~
COMPILE ~IATweaks\scripts\creatures\S!vlord.BAF~
COMPILE ~IATweaks\scripts\creatures\mage16c.BAF~
COMPILE ~IATweaks\scripts\creatures\S!bguard.BAF~

/////////// Rayic (Cowled Wizard that Edwin orders us to kill) ////////////

COPY_EXISTING ~DCOWL1.CRE~ ~override~
  WRITE_SHORT 0x24 43 // HP
  WRITE_SHORT 0x26 43 // HP
  WRITE_BYTE  0x23d 16 // Constitution
  REMOVE_MEMORIZED_SPELL ~spwi609~ ~spwi899~ ~spwi601~
  REMOVE_KNOWN_SPELL ~spwi609~

COPY_EXISTING ~rayic.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_EVALUATE
      ~\([ %TAB%]+\)\(ReallyForceSpellRES("SPWII41",Myself)\)\([ %TAB%%LNL%%MNL%%WNL%]+\)~
    BEGIN
    END
    ~%MATCH1%%MATCH2%%MATCH3%%MATCH1%ReallyForceSpellRES("SPWI618",Myself)%MATCH3%~
  END

////////// Galvery encounter /////////////

COPY_EXISTING ~JAGA4.cre~ ~override~ // Iko
  WRITE_BYTE 0x56 10  // Save vs Poly
  WRITE_BYTE 0x57 14  // Save vs Breath
  WRITE_LONG 0x244 0 // Kit = None (was some unknown value)

  LPF ~ADD_CRE_EFFECT~ // * in Single Weapon
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 1
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // * in Short Sword
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 1
      parameter2 = 91
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // * in Crossbow
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 1
      parameter2 = 103
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~DELETE_CRE_EFFECT~ // Unknown AC bonus
    INT_VAR
      opcode_to_delete = 0
  END
    
  LPF ~DELETE_CRE_EFFECT~ // Unknown thac0 bonus
    INT_VAR
      opcode_to_delete = 54
  END

COPY_EXISTING ~JAGALVAR.cre~ ~override~ // Galvarey
  WRITE_BYTE 0x53 1  // APR
  WRITE_BYTE 0x54 5  // Saves
  WRITE_BYTE 0x55 7  // Saves
  WRITE_BYTE 0x56 6  // Saves
  WRITE_BYTE 0x57 5  // Saves
  WRITE_BYTE 0x58 8  // Saves
  WRITE_LONG 0x244 0 // Kit = None
    
  LPF ~ADD_CRE_EFFECT~ // * in 2h Weapon
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 1
      parameter2 = 111
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ***** in 2h Sword
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 93
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ** in Long Bow
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 2
      parameter2 = 104
      resist_dispel = 0
      timing = 9
  END

COPY_EXISTING ~JAGA2.cre~ ~override~ // Kail
  WRITE_BYTE 0x53 1  // APR
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC
  WRITE_BYTE 0x52 11 // Thac0
  WRITE_BYTE 0x54 8  // Saves
  WRITE_BYTE 0x55 10 // Saves
  WRITE_BYTE 0x56 9  // Saves
  WRITE_BYTE 0x57 9  // Saves
  WRITE_BYTE 0x58 11 // Saves
    
  LPF ~ADD_CRE_EFFECT~ // *** in Single Weapon
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ***** in Katanas
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 94
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Melee thac0 bonus
    INT_VAR
      opcode = 284
      target = 1
      parameter1 = 3
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL141~
  END

  LPF ~ADD_CRE_EFFECT~ // Melee damage bonus
    INT_VAR
      opcode = 285
      target = 1
      parameter1 = 3
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL141~
  END

  LPF ~ADD_CRE_EFFECT~ // AC
    INT_VAR
      opcode = 0
      target = 1
      parameter1 = 2
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL142~
  END

  LPF ~ADD_CRE_EFFECT~ // Weapon speed
    INT_VAR
      opcode = 190
      target = 1
      parameter1 = 3
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL143~
  END

COPY_EXISTING ~JAGA1.cre~ ~override~ // Bessen
  WRITE_SHORT 0x24 73 // HP
  WRITE_SHORT 0x26 73 // HP
  WRITE_BYTE 0x52 7 // Thac0
  WRITE_BYTE 0x234 14 // Level 1
  WRITE_BYTE 0x235 14 // Level 2
  WRITE_BYTE 0x23d 16 // constitution
  WRITE_LONG 0x244 0 // Kit = None (was Invoker but still used Enchantment spells)

////////// Greater Crawler //////////

COPY_EXISTING ~SEWCC.cre~ ~override~
  WRITE_BYTE 0x5a 50  // Cold Resistance
  WRITE_BYTE 0x5b 75  // Electricity Resistance
  WRITE_BYTE 0x5f 50  // Magic Cold Resistance

////////// Shadow Lover //////////

COPY_EXISTING ~S!SHADOS.cre~ ~override~
  WRITE_BYTE 0x5c 75  // Acid Resistance

///////// Haegan ///////////

COPY_EXISTING ~HAEGAN.cre~ ~override~
  WRITE_SHORT 0x24 111 // HP
  WRITE_SHORT 0x26 111 // HP
  WRITE_BYTE 0x60 0 // Resist Slashing
  WRITE_BYTE 0x61 0 // Resist Crushing
  WRITE_BYTE 0x62 0 // Resist Piercing
  WRITE_BYTE 0x63 0 // Resist Missile
  WRITE_BYTE 0x23d 19 // Constitution
  WRITE_LONG 0x244 0x40010000 // Kit = Berserker

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!IMMUNE~
  END

  PATCH_IF(FILE_EXISTS_IN_GAME ~POTN11.spl~) BEGIN
    ADD_CRE_ITEM ~POTN11~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~INV15~
  END

  PATCH_IF(FILE_EXISTS_IN_GAME ~POTN56.spl~) BEGIN
    ADD_CRE_ITEM ~POTN56~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~INV14~
  END

COPY_EXISTING ~s!haegan.itm~ ~override~
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 101
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 106
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 267
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 233
      match_parameter2 = 92
      parameter1 = 2
  END

COMPILE ~IATweaks\scripts\creatures\HAEGAN.BAF~

///////// Slaver Wizard ///////////

COPY_EXISTING ~SLMAGE1.cre~ ~override~
  WRITE_SHORT 0x24 44 // HP
  WRITE_SHORT 0x26 44 // HP
  WRITE_BYTE 0x60 0 // Resist Slashing
  WRITE_BYTE 0x61 0 // Resist Crushing
  WRITE_BYTE 0x62 0 // Resist Piercing
  WRITE_BYTE 0x63 0 // Resist Missile
  WRITE_BYTE 0x23d 16 // Constitution

  ADD_CRE_ITEM ~POTN33~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~INV14~
  ADD_CRE_ITEM ~POTN33~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~INV15~

COMPILE ~IATweaks\scripts\creatures\S!SLMAGE.BAF~

////////// Guild Contact ///////////

COPY_EXISTING ~BODFGT03.cre~ ~override~ // Gracen
  WRITE_SHORT 0x24 123 // HP
  WRITE_SHORT 0x26 123 // HP
    
  LPF ~ADD_CRE_EFFECT~ // ***** in 2h Sword
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 93
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // *** in 2h Weapon Style
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 111
      resist_dispel = 0
      timing = 9
  END

COPY_EXISTING ~s!gracen.itm~ ~override~
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 233
  END
  
////////// Keep Viper ///////////

COPY_EXISTING ~S!KPVIPE.cre~ ~override~
  WRITE_BYTE 0x5b 60  // Electricity Resistance

////////// Mutated Spider ///////////

ACTION_FOR_EACH mutated_spider_cre_file IN ~s!spidr2.cre~ ~spidsm02.cre~ BEGIN
  COPY_EXISTING ~%mutated_spider_cre_file%~ ~override~
    WRITE_BYTE 0x59 75  // Fire Resistance
    WRITE_BYTE 0x5a 75  // Cold Resistance
    WRITE_BYTE 0x5b 75  // Electricity Resistance
    WRITE_BYTE 0x5e 75  // Magic Fire Resistance
    WRITE_BYTE 0x5f 75  // Magic Cold Resistance
    WRITE_BYTE 0x62 80 // Resist Piercing
    WRITE_BYTE 0x63 80 // Resist Missile
    WRITE_BYTE 0x238 18 // Strength
END

//////////// Mencar's Party /////////////

COPY_EXISTING ~SEVPAT01.cre~ ~override~ // Mencar
  WRITE_SHORT 0x24 123 // HP
  WRITE_SHORT 0x26 123 // HP
    
  LPF ~ADD_CRE_EFFECT~ // ***** in Warhammers
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 97
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // *** in Single Weapon Style
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END

COPY_EXISTING ~SEVPAT04.cre~ ~override~ // Smaeluv
  WRITE_SHORT 0x24 138 // HP
  WRITE_SHORT 0x26 138 // HP
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_LONG 0x244 0x00004000 // Kit = Barbarian
    
  LPF ~ADD_CRE_EFFECT~ // ** in 2h Sword
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 2
      parameter2 = 93
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // *** in 2h Weapon Style
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 111
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // +2 movement speed
    INT_VAR
      opcode = 126
      target = 1
      parameter1 = 2
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL151~
  END

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 0
  END

  ADD_CRE_ITEM ~POTN11~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~INV14~
  ADD_CRE_ITEM ~CHAN05~ #0 #0 #0 ~NONE~ ~ARMOR~
  
COMPILE ~IATweaks\scripts\creatures\SEVPAT04.BAF~

//////////////// Planar Hounds ///////////////

COPY ~IATweaks\resources\spl\s!-resho.spl~ ~override~

ACTION_FOR_EACH planar_hound_cre IN ~s!phound~ ~s!phounr~ ~s!phoun3~ ~s!phoun2~ BEGIN
  COPY_EXISTING ~%planar_hound_cre%.cre~ ~override~
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 146
        target = 1
        parameter2 = 1
        timing = 9
        resist_dispel = 0
      STR_VAR
        resource = ~S!-RESHO~
    END
END

//////////////// Planar Warden ///////////////////

COPY_EXISTING ~PWARDEN.cre~ ~override~
  WRITE_BYTE 0x5b 50 // Resist Electricity
  WRITE_BYTE 0x5c 25 // Resist Acid
  ADD_MEMORIZED_SPELL ~SPWI925~ #8 ~wizard~ (2)

COMPILE ~IATweaks\scripts\creatures\s!warden.baf~

//////////////// Tazok //////////////////

COPY_EXISTING ~TAZOK.cre~ ~override~
  WRITE_LONG 0x244 0x40010000 // Kit = Berserker

COMPILE ~IATweaks\scripts\creatures\s!tazok.baf~

///////////////// Tarnor's Sewer Party ////////////////

// Tarnor

COPY_EXISTING ~TARNOR.cre~ ~override~
  WRITE_SHORT 0x24 150 // HP
  WRITE_SHORT 0x26 150 // HP
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5a 0 // Resist Cold
  WRITE_BYTE 0x5b 0 // Resist Electricity
  WRITE_BYTE 0x5c 0 // Resist Acid
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x5f 0 // Resist Magic Cold
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_SHORT 0x246 0x4022 // Kit = Dwarven Defender

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 0
  END

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 31
  END

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 193
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 233
      match_parameter1 = 5
      parameter1 = 4
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!PASHA2~
  END

  ADD_CRE_ITEM ~POTN06~ #0 #0 #0 ~NONE~ ~INV15~

COMPILE ~IATweaks\scripts\creatures\S!TARNOR.BAF~

// Draug Fea

COPY_EXISTING ~DRAUG.cre~ ~override~
  WRITE_SHORT 0x24 127 // HP
  WRITE_SHORT 0x26 127 // HP
  WRITE_BYTE 0x52 1 // Thac0
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5a 0 // Resist Cold
  WRITE_BYTE 0x5b 0 // Resist Electricity
  WRITE_BYTE 0x5c 0 // Resist Acid
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x5f 0 // Resist Magic Cold
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x234 20 // Level 1
  WRITE_BYTE 0x23d 19 // Constitution
  WRITE_SHORT 0x246 0x4022 // Kit = Dwarven Defender
  WRITE_ASCII 0x248 ~S!DRAUG~ #8

  LPF ~ADD_CRE_EFFECT~ INT_VAR
    opcode = 233
    timing = 9
    target = 1
    parameter1 = 2
    parameter2 = 112 // Sword and Shield
  END

  LPF ~ADD_CRE_EFFECT~ INT_VAR
    opcode = 233
    timing = 9
    target = 1
    parameter1 = 4
    parameter2 = 100 // Flails
  END

COMPILE ~IATweaks\scripts\creatures\S!DRAUG.BAF~

// Gallchobhair

COPY_EXISTING ~GALL.cre~ ~override~
  WRITE_SHORT 0x24 123 // HP
  WRITE_SHORT 0x26 123 // HP
  WRITE_BYTE 0x52 1 // Thac0
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5a 0 // Resist Cold
  WRITE_BYTE 0x5b 0 // Resist Electricity
  WRITE_BYTE 0x5c 0 // Resist Acid
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x5f 0 // Resist Magic Cold
  WRITE_BYTE 0x60 0 // Resist Slashing
  WRITE_BYTE 0x61 0 // Resist Crushing
  WRITE_BYTE 0x62 0 // Resist Piercing
  WRITE_BYTE 0x63 0 // Resist Missile
  WRITE_BYTE 0x234 20 // Level 1
  WRITE_LONG 0x244 0x40010000 // Kit = Berserker

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 31
  END

COMPILE ~IATweaks\scripts\creatures\S!GALL.BAF~

///////////////////// Turmish Leader ////////////////////

COPY_EXISTING ~BDTURM01.cre~ ~override~
  WRITE_SHORT 0x24 123 // HP
  WRITE_SHORT 0x26 123 // HP
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x23d 19 // Constitution
  WRITE_LONG 0x244 0x40010000 // Kit = Berserker
    
  LPF ~ADD_CRE_EFFECT~ // *** in 2h Weapon
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 111
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ***** in 2h Sword
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 93
      resist_dispel = 0
      timing = 9
  END

COMPILE ~IATweaks\scripts\creatures\S!TURM01.BAF~

/////////////////////// Galvena ////////////////////

COPY_EXISTING ~PIRMUR01.cre~ ~override~
  WRITE_BYTE 0x53 1 // APR
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x60 0 // Resist Slashing
  WRITE_BYTE 0x61 0 // Resist Crushing
  WRITE_BYTE 0x62 0 // Resist Piercing
  WRITE_BYTE 0x63 0 // Resist Missile

  ADD_CRE_ITEM ~POTN33~ #0 #0 #0 ~NONE~ ~INV14~
  ADD_CRE_ITEM ~POTN33~ #0 #0 #0 ~NONE~ ~INV15~
  ADD_CRE_ITEM ~POTN34~ #0 #0 #0 ~NONE~ ~INV16~

  LPF ~ADD_CRE_EFFECT~ INT_VAR
    opcode = 233
    timing = 9
    target = 1
    parameter1 = 2
    parameter2 = 112 // Sword and Shield
  END

  LPF ~ADD_CRE_EFFECT~ INT_VAR
    opcode = 233
    timing = 9
    target = 1
    parameter1 = 2
    parameter2 = 100 // Flails
  END

COMPILE ~IATweaks\scripts\creatures\PIRMUR01.BAF~

////////////////////// Cat O'Nine Lives /////////////////////

COPY_EXISTING_REGEXP GLOB ~s\!cat[1-9]\.cre~ ~override~
  READ_BYTE 0x60 phys_res // Resist Slashing
  WRITE_BYTE 0x5b phys_res + 5 // Resist Electricity
  WRITE_BYTE 0x5c phys_res + 5 // Resist Acid
  WRITE_SHORT 0x24 125 // HP
  WRITE_SHORT 0x26 125 // HP

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 101
      match_parameter2 = 166
  END
  BUT_ONLY

/////////////////////// Kobold from Crystal fight in Spellhold ////////////////

COMPILE ~IATweaks\scripts\creatures\S!KOBOLD.BAF~

///////////////////////// Noble Trolls /////////////////////////

ACTION_FOR_EACH noble_troll_file IN ~TROLDE01~ ~S!NTROL2~ ~S!NTROLL~ ~S!NTROLR~ BEGIN
  COPY_EXISTING ~%noble_troll_file%.cre~ ~override~
    WRITE_BYTE 0x59 50 // Resist Fire
    WRITE_BYTE 0x5c 50 // Resist Acid
    WRITE_BYTE 0x5e 50 // Resist Magic Fire
    WRITE_BYTE 0x60 30 // Resist Slashing
    WRITE_BYTE 0x61 30 // Resist Crushing
    WRITE_BYTE 0x62 30 // Resist Piercing
    WRITE_BYTE 0x63 55 // Resist Missile

  // +25 MDR
  LPF ~ADD_CRE_EFFECT~ INT_VAR
    opcode = 31
    timing = 9
    target = 1
    parameter1 = 25
    parameter2 = 0
  END

    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = 0
    END
END

///////////////////////// Mithril Golem /////////////////////////

COPY_EXISTING ~S!MITGOL.cre~ ~override~
  WRITE_BYTE 0x62 95 // Resist Piercing

///////////////////////// Drow Ambushes in the Underdark /////////////////////////

COPY ~IATweaks\resources\cre\S!GSPID1.cre~ ~override~
  SAY NAME1 @5048
  SAY NAME2 @5048

COPY ~IATweaks\resources\cre\S!GSPID2.cre~ ~override~
  SAY NAME1 @5048
  SAY NAME2 @5048

ADD_PROJECTILE ~IATweaks\resources\pro\s!llothb.PRO~

COPY ~IATweaks\resources\spl\s!lloth1.spl~ ~override~
  SAY NAME1 @6157
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR
      projectile = ~%s!llothb%~
  END

COPY ~IATweaks\resources\spl\s!lloth2.spl~ ~override~
  SAY NAME1 @6157
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR
      projectile = ~%s!llothb%~
  END

COMPILE ~IATweaks\scripts\others\S!TRP104.BAF~
COMPILE ~IATweaks\scripts\others\CUT44A.BAF~

// Drow Fighters

COPY_EXISTING ~UDDROW27.cre~ ~override~
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5a 0 // Resist Cold
  WRITE_BYTE 0x5b 0 // Resist Electricity
  WRITE_BYTE 0x5c 0 // Resist Acid
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x5f 0 // Resist Magic Cold
  WRITE_BYTE 0x60 0 // Resist Slashing
  WRITE_BYTE 0x61 0 // Resist Crushing
  WRITE_BYTE 0x62 0 // Resist Piercing
  WRITE_BYTE 0x63 0 // Resist Missile
  WRITE_BYTE 0x238 18 // Strength
  WRITE_BYTE 0x239 76 // Exceptional Strength
  WRITE_BYTE 0x23c 19 // Dexterity

  LPF ~ADD_CRE_EFFECT~ // ** in Sword and Shield
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 2
      parameter2 = 112
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // ***** in Flails
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 100
      resist_dispel = 0
      timing = 9
  END

COPY_EXISTING ~S!DROWW.cre~ ~override~
  WRITE_SHORT 0x24 117 // HP
  WRITE_SHORT 0x26 117 // HP
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5a 0 // Resist Cold
  WRITE_BYTE 0x5b 0 // Resist Electricity
  WRITE_BYTE 0x5c 0 // Resist Acid
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x5f 0 // Resist Magic Cold
  WRITE_BYTE 0x60 0 // Resist Slashing
  WRITE_BYTE 0x61 0 // Resist Crushing
  WRITE_BYTE 0x62 0 // Resist Piercing
  WRITE_BYTE 0x63 0 // Resist Missile
  WRITE_BYTE 0x238 18 // Strength
  WRITE_BYTE 0x239 100 // Exceptional Strength
  WRITE_BYTE 0x23d 15 // Constitution

  LPF ~ADD_CRE_EFFECT~ // ** in Sword and Shield
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 2
      parameter2 = 112
      resist_dispel = 0
      timing = 9
  END

///////////////////////// Mind Flayers ///////////////////////////////

// Make Psionic Domination and Psionic Blast bypass Magic Resistance and set its power to 0
COPY_EXISTING ~SPIN974.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      resist_dispel = 2
      power = 0
  END

COPY_EXISTING ~SPIN975.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      resist_dispel = 2
      power = 0
  END

// Add spell which has a chance to grant protection from opcode 12 when hit

COPY ~IATweaks\resources\spl\s!mfprot.spl~ ~override~

ACTION_DEFINE_ASSOCIATIVE_ARRAY id_to_damage_reduction_state_mapping BEGIN
  1=>EVAL ~%damage_reduction_1_state%~
  2=>EVAL ~%damage_reduction_2_state%~
  3=>EVAL ~%damage_reduction_3_state%~
  4=>EVAL ~%damage_reduction_4_state%~
END

ACTION_PHP_EACH id_to_damage_reduction_state_mapping AS current_id => damage_reduction_state BEGIN
  LAF ~S!ADD_7EYES_ROW~
    INT_VAR
      strref        = RESOLVE_STR_REF (@5049)
    STR_VAR
      row_desc      = EVAL ~DMG_PROT_%current_id%~
      spellstate    = EVAL ~%damage_reduction_state%~
      eff1          = ~12~ // Damage
    RET new_row_id 
  END
  COPY_EXISTING ~s!mfprot.spl~ ~override~
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_parameter1 = current_id
        parameter1 = damage_reduction_state
        parameter2 = new_row_id
    END
END

COPY_EXISTING ~MINDFLAY.itm~ ~override~
  // Lower int drain to 3
  LPF ~S!ALTER_EFFECT~
    INT_VAR
      match_opcode = 19
      parameter1 = ~-3~
  END
  // Grant +5 saving throws against Enchantment spells
  LPF ~ADD_ITEM_EQEFFECT~
    INT_VAR
      opcode = 346
      target = 1
      parameter1 = 5
      parameter2 = 0
      timing = 2
      resist_dispel = 0
      special = 4
  END

// Mind Flayer Focused Mind Blast

COPY_EXISTING ~BIGNAREA.pro~ ~override/S!MFAREA.pro~
  WRITE_BYTE 0x0c 18 // Ignore caster
  WRITE_SHORT 0x200 192 // Affect only allies

ADD_PROJECTILE ~override/S!MFAREA.pro~
COPY ~IATweaks\resources\spl\s!mfblst.spl~ ~override~
  SAY NAME1 @6158
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~S!MFAREA~
  END
  PATCH_FOR_EACH header_num IN 1 2 3 BEGIN
    SET min_level = (header_num + 3) * 5
    LPF ~S!CLONE_SPELL_HEADER~
      INT_VAR
        level_req = min_level
    END
    LPF ~S!ALTER_EFFECT~
      INT_VAR
        header = header_num
        match_opcode = 148
    END
  END

COPY_EXISTING ~s!mindbl.pro~ ~override/s!mfblst.pro~
  WRITE_SHORT 0x200 64 // Affect only enemies

ADD_PROJECTILE ~override/s!mfblst.pro~
COPY ~IATweaks\resources\spl\s!mfbls1.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!mfblst~
  END
  PATCH_FOR_EACH header_num IN 1 2 3 BEGIN
    SET min_level = (header_num + 3) * 5
    SET dice_thrown = (header_num * 2) + 6
    LPF ~S!CLONE_SPELL_HEADER~
      INT_VAR
        level_req = min_level
    END
    LPF ~S!ALTER_EFFECT~
      INT_VAR
        header = header_num
        match_opcode = 12
        dicenumber = dice_thrown
    END
  END

COPY ~IATweaks\resources\spl\s!mfbls2.spl~ ~override~
  SAY NAME1 @6160
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!mfblst~
  END
  PATCH_FOR_EACH header_num IN 1 2 3 BEGIN
    SET min_level = (header_num + 3) * 5
    SET dice_thrown = header_num + 3
    LPF ~S!CLONE_SPELL_HEADER~
      INT_VAR
        level_req = min_level
    END
    LPF ~S!ALTER_EFFECT~
      INT_VAR
        header = header_num
        match_opcode = 12
        dicenumber = dice_thrown
    END
  END

// Soften Mind

ADD_PROJECTILE ~IATweaks\resources\pro\s!mfsoft.pro~
COPY ~IATweaks\resources\spl\s!mfsoft.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~S!MFAREA~
  END

COPY ~IATweaks\resources\spl\s!mfsof1.spl~ ~override~
  SAY NAME1 @6159
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~s!mfsoft~
  END

ACTION_FOR_EACH mind_flayer_cre IN ~DAMIND1~ ~DAMIND2~ ~ELEILL01~ ~ELMIND01~ ~MINDFL01~ ~UDILL01~ ~UDMIND10~ BEGIN
  COPY_EXISTING ~%mind_flayer_cre%.cre~ ~override~
    READ_LONG 0x14 exp
    PATCH_IF (exp > 0) BEGIN
      WRITE_LONG 0x14 THIS + 3000 // Exp for creature
    END
    WRITE_SHORT 0x24 THIS + 15 // HP
    WRITE_SHORT 0x26 THIS + 15 // HP
    WRITE_BYTE 0x52 6 // Thac0
    WRITE_BYTE 0x54 6  // Saves
    WRITE_BYTE 0x55 8 // Saves
    WRITE_BYTE 0x56 7  // Saves
    WRITE_BYTE 0x57 8  // Saves
    WRITE_BYTE 0x58 9 // Saves
    WRITE_BYTE 0x59 0 // Resist Fire
    WRITE_BYTE 0x5a 0 // Resist Cold
    WRITE_BYTE 0x5b 0 // Resist Electricity
    WRITE_BYTE 0x5c 0 // Resist Acid
    WRITE_BYTE 0x5d 90 // Resist Magic
    WRITE_BYTE 0x5e 0 // Resist Magic Fire
    WRITE_BYTE 0x5f 0 // Resist Magic Cold
    WRITE_BYTE 0x234 15 // Level 1
    WRITE_BYTE 0x240 2 // Morale Break
    WRITE_BYTE 0x272 124 // Race

    // Cast S!MFPROT each time the damage is dealt
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 232
        target = 1
        parameter1 = 0
        parameter2 = 11
        timing = 1
        resist_dispel = 0
      STR_VAR
        resource = ~S!MFPROT~
    END
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 146
        target = 1
        parameter2 = 1
        timing = 9
        resist_dispel = 0
      STR_VAR
        resource = ~S!MFPROT~
    END
    BUT_ONLY
    IF_EXISTS
END

COMPILE ~IATweaks\scripts\creatures\FLAYER01.BAF~

ACTION_FOR_EACH ulitharid_cre IN ~GORMIND~ ~MINDUL01~ ~PPMIND01~ BEGIN
  COPY_EXISTING ~%ulitharid_cre%.cre~ ~override~
    READ_LONG 0x14 exp
    PATCH_IF (exp > 0) BEGIN
      WRITE_LONG 0x14 THIS + 3000 // Exp for creature
    END
    WRITE_SHORT 0x24 THIS + 15 // HP
    WRITE_SHORT 0x26 THIS + 15 // HP
    WRITE_BYTE 0x52 2 // Thac0
    WRITE_BYTE 0x59 0 // Resist Fire
    WRITE_BYTE 0x5a 0 // Resist Cold
    WRITE_BYTE 0x5b 0 // Resist Electricity
    WRITE_BYTE 0x5c 0 // Resist Acid
    WRITE_BYTE 0x5e 0 // Resist Magic Fire
    WRITE_BYTE 0x5f 0 // Resist Magic Cold
    WRITE_BYTE 0x234 20 // Level 1
    WRITE_BYTE 0x240 0 // Morale Break
    WRITE_BYTE 0x272 124 // Race

    // Cast S!MFPROT each time the damage is dealt
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 232
        target = 1
        parameter1 = 0
        parameter2 = 11
        timing = 1
        resist_dispel = 0
      STR_VAR
        resource = ~S!MFPROT~
    END
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 146
        target = 1
        parameter2 = 1
        timing = 9
        resist_dispel = 0
      STR_VAR
        resource = ~S!MFPROT~
    END
    BUT_ONLY
    IF_EXISTS
END

COMPILE ~IATweaks\scripts\creatures\FLAYER02.BAF~

COMPILE ~IATweaks\scripts\others\S!TRP110.BAF~
COMPILE ~IATweaks\scripts\others\S!TRP111.BAF~

// Master Brain

COPY_EXISTING ~UDMASTER.cre~ ~override~
  WRITE_BYTE 0x234 30 // Level 1
  WRITE_BYTE 0x272 124 // Race
 
  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~S!MFPROT~
  END 
  ADD_CRE_ITEM ~MINDFLAY~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~WEAPON1~ EQUIP
  ADD_CRE_ITEM ~SUREHP1~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~LRING~

  COMPILE ~IATweaks\scripts\creatures\UDMASTER.BAF~

// Brain Golem

COPY_EXISTING ~UDGOLEM.cre~ ~override~
  WRITE_LONG 0x14 15000 // Exp for creature
  WRITE_BYTE 0x52 THIS - 4 // Thac0
  WRITE_BYTE 0x53 3  // APR
  WRITE_BYTE 0x5b 50  // Electricity Resistance
  WRITE_BYTE 0x5d 75 // Resist Magic
  WRITE_BYTE 0x60 75 // Resist Slashing
  WRITE_BYTE 0x61 75 // Resist Crushing
  WRITE_BYTE 0x62 75 // Resist Piercing
  WRITE_BYTE 0x63 75 // Resist Missile

// Brain Golem item

COPY_EXISTING ~S!GOLBRA.itm~ ~override~
  LPF ~ALTER_ITEM_HEADER~
    INT_VAR
      dicesize = 6
      dicenumber = 1
      damage_bonus = 15
  END
  LPF ~ADD_ITEM_EFFECT~
    INT_VAR
      type = 1
      opcode = 146
      insert_point = 0
      parameter2 = 1
      probability1 = 20
      probability2 = 1
      target = 2
    STR_VAR
      resource = "S!MFBLST"
  END

// Simbja, the Goblin from Underdark evil party

COPY_EXISTING ~GPSIMB.cre~ ~override~
  WRITE_SHORT 0x24 108 // HP
  WRITE_SHORT 0x26 108 // HP
  WRITE_BYTE 0x45 88 // Hide in Shadows
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC
  WRITE_BYTE 0x52 4 // Thac0
  WRITE_BYTE 0x53 1  // APR
  WRITE_BYTE 0x54 3  // Saves
  WRITE_BYTE 0x55 5  // Saves
  WRITE_BYTE 0x56 4  // Saves
  WRITE_BYTE 0x57 4  // Saves
  WRITE_BYTE 0x58 6  // Saves
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x68 20 // Stealth Strike
  WRITE_BYTE 0x234 16 // Level 1
  WRITE_BYTE 0x235 1 // Level 2
  WRITE_BYTE 0x23d 17 // Constitution
  WRITE_BYTE 0x241 1 // Racial Enemy = Human
  WRITE_LONG 0x244 0x40070000 // Kit = Archer
  WRITE_ASCII 0x248 ~~ #8
  WRITE_ASCII 0x250 ~S!SIMBJA~ #8
  WRITE_BYTE 0x273 12 // Class = Ranger
    
  LPF ~ADD_CRE_EFFECT~ // ***** in Short Bows
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 105
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // * in Daggers
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 96
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // * in Single Weapon
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 1
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END
  
  LPF ~ADD_CRE_EFFECT~ // Increase movement speed
    INT_VAR
      target = 1
      opcode = 126
      parameter1 = 4
      parameter2 = 0
      resist_dispel = 0
      timing = 9
  END

  // thac0 and damage bonuses to ranged
  FOR (i=0; i<5; ++i) BEGIN
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 167
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL122~
    END
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 286
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL122~
    END
  END
  
  PATCH_FOR_EACH item_to_remove IN ~LEAT10~ ~DAGG01~ ~BOW05~ ~AROW01~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~HELM02~ #0 #0 #0 ~UNSTEALABLE~ ~HELMET~
  ADD_CRE_ITEM ~OHLEAT52~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~
  ADD_CRE_ITEM ~DAGG01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~
  ADD_CRE_ITEM ~BOW18~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON2~ EQUIP
  ADD_CRE_ITEM ~AROW15~ #25 #0 #0 ~UNSTEALABLE~ ~QUIVER1~ // Arrow +3
  ADD_CRE_ITEM ~AROW11~ #35 #0 #0 ~UNSTEALABLE~ ~QUIVER2~ // Arrow +2
  ADD_CRE_ITEM ~AROW01~ #40 #0 #0 ~UNSTEALABLE~ ~QUIVER3~ // Arrow
  ADD_CRE_ITEM ~POTN14~ #1 #0 #0 ~UNSTEALABLE~ ~INV10~ // Oil of Speed
  ADD_CRE_ITEM ~POTN10~ #3 #0 #0 ~UNSTEALABLE~ ~INV11~ // Potion of Invisibility
  ADD_CRE_ITEM ~POTN41~ #0 #0 #0 ~UNSTEALABLE~ ~INV12~ // Potion of Power
  ADD_CRE_ITEM ~POTN35~ #0 #0 #0 ~UNSTEALABLE~ ~INV13~ // Potion of Magic Shielding
  ADD_CRE_ITEM ~POTN55~ #2 #0 #0 ~UNSTEALABLE~ ~INV14~ // Superior Healing Potion
  ADD_CRE_ITEM ~POTN37~ #0 #0 #0 ~UNSTEALABLE~ ~INV15~ // Oil of Resurgence

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 2 ) // Doom
  ADD_MEMORIZED_SPELL ~SPPR202~ #1 ~priest~ ( 1 ) // Barkskin
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 1 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR210~ #1 ~priest~ ( 1 ) // Resist Fire/Cold
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 1 ) // Protection from Fire
  ADD_MEMORIZED_SPELL ~SPPR312~ #2 ~priest~ ( 1 ) // Strength of One
  ADD_MEMORIZED_SPELL ~SPPR315~ #2 ~priest~ ( 1 ) // Cure Medium Wounds
  ADD_MEMORIZED_SPELL ~SPCL121~ #0 ~innate~ ( 4 ) // Called Shot

COMPILE ~IATweaks\scripts\creatures\S!SIMBJA.BAF~

// Boz the Ogre from Underdark evil party

COPY_EXISTING ~GPFIGHT1.cre~ ~override~
  WRITE_SHORT 0x24 138 // HP
  WRITE_SHORT 0x26 138 // HP
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x59 40 // Fire Resistance
  WRITE_BYTE 0x5c 40 // Acid Resistance
  WRITE_BYTE 0x5e 40 // Magic Fire Resistance
  WRITE_BYTE 0x60 40 // Resist Slashing
  WRITE_BYTE 0x61 40 // Resist Crushing
  WRITE_BYTE 0x62 40 // Resist Piercing
  WRITE_BYTE 0x63 40 // Resist Missile
  WRITE_BYTE 0x23d 19 // Constitution
  WRITE_LONG 0x244 0x40010000 // Kit = Berserker

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END
  
  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~DRAGRING~
  END

  LPF ~DELETE_CRE_EFFECT~
    STR_VAR
      opcode_to_delete = 16
  END

  LPF ~DELETE_CRE_EFFECT~
    STR_VAR
      opcode_to_delete = 0
  END

  LPF ~ALTER_EFFECT~
    STR_VAR
      match_opcode = 31
      parameter1 = 40
  END

  ADD_CRE_ITEM ~DWPLAT01~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~
  ADD_CRE_ITEM ~POTN14~ #1 #0 #0 ~UNSTEALABLE~ ~INV10~ // Oil of Speed
  ADD_CRE_ITEM ~POTN09~ #0 #0 #0 ~UNSTEALABLE~ ~INV12~ // Potion of Heroism

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL321~ #0 ~innate~ ( 4 ) // Enrage
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike

COMPILE ~IATweaks\scripts\creatures\S!BOZ.BAF~

// Jae'llat Guards

COPY_EXISTING ~JAEL04.cre~ ~override~
  WRITE_BYTE 0x2f 83 // Skin Color
  WRITE_BYTE 0x32 79 // Hair Color
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x23c 19 // Dexterity
  WRITE_LONG 0x244 0x40010000 // Kit = Berserker
  WRITE_ASCII 0x248 ~S!SHOUT~ #8
  WRITE_ASCII 0x268 ~S!JAEL04~ #8

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  LPF ~ADD_CRE_EFFECT~  // ***** in Long Swords
    INT_VAR
      opcode = 233
      timing = 9
      parameter1 = 5
      parameter2 = 90
  END

  LPF ~ADD_CRE_EFFECT~ // ** in Sword and Shield
    INT_VAR
      opcode = 233
      timing = 9
      parameter1 = 2
      parameter2 = 112
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~DWCHAN01~
  END

  ADD_CRE_ITEM ~DWPLAT01~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~
  ADD_CRE_ITEM ~SW1H04~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON3~
  ADD_CRE_ITEM ~POTN14~ #2 #0 #0 ~UNSTEALABLE~ ~INV10~ // Oil of Speed
  ADD_CRE_ITEM ~POTN02~ #1 #0 #0 ~UNSTEALABLE~ ~INV12~ // Potion of Fire Resistance

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL321~ #0 ~innate~ ( 4 ) // Enrage

COMPILE ~IATweaks\scripts\creatures\S!JAEL04.BAF~
COMPILE ~IATweaks\scripts\creatures\S!SHOUT.BAF~

// Ist'tar Jae'llat

COPY_EXISTING ~JAEL03.cre~ ~override~
  WRITE_SHORT 0x24 135 // HP
  WRITE_SHORT 0x26 135 // HP
  WRITE_BYTE 0x2f 83 // Skin Color
  WRITE_BYTE 0x32 79 // Hair Color
  WRITE_BYTE 0x60 15 // Resist Slashing
  WRITE_BYTE 0x61 15 // Resist Crushing
  WRITE_BYTE 0x62 15 // Resist Piercing
  WRITE_BYTE 0x63 15 // Resist Missile
  WRITE_BYTE 0x234 24 // Level 1
  WRITE_BYTE 0x238 18 // Strength
  WRITE_BYTE 0x239 100 // Exceptional Strength
  WRITE_BYTE 0x23c 19 // Dexterity
  WRITE_LONG 0x244 0x40030000 // Kit = Kensai

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ALTER_EFFECT~ // *** in Dual Wield
    INT_VAR
      match_opcode = 233
      match_parameter2 = 112
      parameter1 = 3
      parameter2 = 114
  END

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 16
  END

  // thac0 and damage bonuses to melee
  FOR (i=0; i<8; ++i) BEGIN
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 285
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL141~
    END
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 284
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL141~
    END
  END

  LPF ~ADD_CRE_EFFECT~ // AC
    INT_VAR
      opcode = 0
      target = 1
      parameter1 = 2
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL142~
  END

  LPF ~ADD_CRE_EFFECT~ // Weapon speed
    INT_VAR
      opcode = 190
      target = 1
      parameter1 = 7
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL143~
  END

  PATCH_FOR_EACH item_to_remove IN ~HELM10~ ~DWPLAT01~ ~DWSHLD01~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~DWSW1H02~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~
  ADD_CRE_ITEM ~SW1H04~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON3~
  ADD_CRE_ITEM ~HELM19~ #0 #0 #0 ~UNSTEALABLE~ ~HELMET~
  ADD_CRE_ITEM ~RING06~ #0 #0 #0 ~UNSTEALABLE~ ~LRING~
  ADD_CRE_ITEM ~POTN33~ #1 #0 #0 ~UNSTEALABLE~ ~INV10~ // Barbarian Essence
  ADD_CRE_ITEM ~POTN35~ #1 #0 #0 ~UNSTEALABLE~ ~INV11~ // Potion of Magic Shielding
  ADD_CRE_ITEM ~POTN07~ #1 #0 #0 ~UNSTEALABLE~ ~INV12~ // Potion of Storm Giant Strength
  ADD_CRE_ITEM ~POTN11~ #1 #0 #0 ~UNSTEALABLE~ ~INV13~ // Potion of Invulnerability
  ADD_CRE_ITEM ~POTN14~ #2 #0 #0 ~UNSTEALABLE~ ~INV14~ // Oil of Speed
  ADD_CRE_ITEM ~POTN14~ #1 #0 #0 ~UNSTEALABLE~ ~INV15~ // Oil of Resurgence

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL144~ #0 ~innate~ ( 6 ) // Kai
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike

COMPILE ~IATweaks\scripts\creatures\S!JAEL03.BAF~

// Move him next to the Priestess

COPY_EXISTING ~AR2209.are~ ~override~
  LPF ~ALTER_AREA_ACTOR~
    INT_VAR
      x_coord = 627
      y_coord = 838
    STR_VAR
     actor_name = ~Ist'tar Jae'llat~
  END

// Troll King

COPY ~IATweaks\resources\itm\s!torga2.itm~ ~override~

COPY_EXISTING ~S!TROLLK.cre~ ~override~
  WRITE_SHORT 0x24 407 // HP
  WRITE_SHORT 0x26 407 // HP
  WRITE_BYTE 0x53 2  // APR
  WRITE_BYTE 0x59 80 // Fire Resistance
  WRITE_BYTE 0x5c 80 // Acid Resistance
  WRITE_BYTE 0x5e 80 // Magic Fire Resistance
  WRITE_BYTE 0x60 55 // Resist Slashing
  WRITE_BYTE 0x61 55 // Resist Crushing
  WRITE_BYTE 0x62 55 // Resist Piercing
  WRITE_BYTE 0x63 55 // Resist Missile
  WRITE_SHORT 0x246 IDS_OF_SYMBOL(~kit~ ~RISKBREAKER~) // Kit
    
  LPF ~ADD_CRE_EFFECT~ // Color
    INT_VAR
      target = 1
      opcode = 51
      parameter1 = 5046016
      parameter2 = 2
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // RB base bonuses
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~SPCLI05~
      effsource = ~SPCLI05~
  END

  LPF ~ADD_CRE_EFFECT~ // RB on-hit bonuses
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~SPCLI09~
      effsource = ~SPCLI09~
  END

  LPF ~ADD_CRE_EFFECT~ // Regeneration
    INT_VAR
      opcode = 98
      target = 2
      parameter1 = 2
      parameter2 = 2
      timing = 9
      resist_dispel = 0
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!TORGAL~
  END

  ADD_CRE_ITEM ~S!TORGA2~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~WEAPON1~ EQUIP

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPINI34~ #0 ~innate~ ( 3 ) // Risk Decrement
  ADD_MEMORIZED_SPELL ~SPINI51~ #0 ~innate~ ( 2 ) // Chain Breaker Stance
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 3 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 4 ) // Critical Strike

COMPILE ~IATweaks\scripts\creatures\S!TROLLK.BAF~

// Troll Queen

COPY ~IATweaks\resources\spl\s!flee01.spl~ ~override~
COPY ~IATweaks\resources\spl\s!retrea.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6254

COPY ~IATweaks\resources\spl\s!lowres.spl~ ~override~
COPY ~IATweaks\resources\spl\s!linkup.spl~ ~override~

COPY_EXISTING ~S!TROLLQ.cre~ ~override~
  WRITE_SHORT 0x24 223 // HP
  WRITE_SHORT 0x26 223 // HP
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x53 2  // APR
  WRITE_BYTE 0x59 15 // Fire Resistance
  WRITE_BYTE 0x5e 15 // Magic Fire Resistance
  WRITE_BYTE 0x234 36 // Level 1
  WRITE_BYTE 0x235 1 // Level 2
  WRITE_BYTE 0x238 19 // Strength
  WRITE_BYTE 0x23d 16 // Constitution
  WRITE_SHORT 0x246 IDS_OF_SYMBOL(~kit~ ~AURAMASTER~) // Kit
  WRITE_BYTE 0x273 11 // Class = Druid
    
  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // Color
    INT_VAR
      target = 1
      opcode = 51
      parameter1 = 0xe0f59500
      parameter2 = 2
      timing = 9
  END

  LPF ~ALTER_EFFECT~
    STR_VAR
      match_opcode = 189 // Casting Speed
      parameter1 = 2
  END

  LPF ~DELETE_EFFECT~
    STR_VAR
      match_opcode = 66 // Translucency
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~HELMNOAN~
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~CLCK01~
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!TORGAL~
  END

  ADD_CRE_ITEM ~S!TORGA2~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~WEAPON1~ EQUIP
  ADD_CRE_ITEM ~CLCK02~ #0 #0 #0 ~NONE~ ~CLOAK~
  ADD_CRE_ITEM ~POTN10~ #0 #0 #0 ~NONE~ ~INV1~
  ADD_CRE_ITEM ~S!HELM04~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~HELMET~

COMPILE ~IATweaks\scripts\creatures\S!TROLLQ.BAF~
COMPILE ~IATweaks\scripts\creatures\S!ntrol2.BAF~

// Egg Prisons in Mind Flayers' Dungeon

COMPILE ~IATweaks\scripts\others\S!MFDOOR.BAF~

COPY_EXISTING ~AR2400.are~ ~override~

  LPF ALTER_AREA_ACTOR
    INT_VAR
      x_coord = 627
      y_coord = 838
    STR_VAR
     actor_name = ~Ist'tar Jae'llat~
  END

  GET_OFFSET_ARRAY doors ARE_V10_DOORS

  PHP_EACH doors AS int1 => door_off BEGIN
    READ_ASCII door_off + 0x20 door_id

    PATCH_IF NOT (~%door_id%~ STRING_CONTAINS_REGEXP ~EGG0~) BEGIN
      WRITE_SHORT  door_off + 0x70 1
      WRITE_ASCII  door_off + 0x80 ~S!MFDOOR~
    END
  END

// Insane Dwarf in the Underdark

COPY_EXISTING ~UDDWARF.cre~ ~override~
  WRITE_BYTE 0x52 THIS + 4 // Thac0
  WRITE_BYTE 0x5d 50 // Resist Magic
  WRITE_LONG 0x244 0x40010000 // Kit = Berserker
  WRITE_BYTE 0x27b 51 // Alignment

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~DRAGRING~
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!DRACON~
  END

  LPF ~ALTER_EFFECT~
    STR_VAR
      match_opcode = 31
      parameter1 = 60
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL321~ #0 ~innate~ ( 4 ) // Enrage
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 3 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 2 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 4 ) // Critical Strike

COMPILE ~IATweaks\scripts\creatures\S!UDDWAR.BAF~

// Archer from North Forest party

COPY_EXISTING ~AR18ARCH.cre~ ~override~
  WRITE_LONG 0x14 25000 // Exp
  WRITE_SHORT 0x24 126 // HP
  WRITE_SHORT 0x26 126 // HP
  WRITE_BYTE 0x45 100 // Hide in Shadows
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x53 1  // APR
  WRITE_BYTE 0x54 3  // Saves
  WRITE_BYTE 0x55 5  // Saves
  WRITE_BYTE 0x56 4  // Saves
  WRITE_BYTE 0x57 4  // Saves
  WRITE_BYTE 0x58 6  // Saves
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x68 20 // Stealth Strike
  WRITE_BYTE 0x234 21 // Level 1
  WRITE_BYTE 0x235 1 // Level 2
  WRITE_BYTE 0x23d 18 // Constitution
  WRITE_BYTE 0x241 1 // Racial Enemy = Human
  WRITE_LONG 0x244 0x40070000 // Kit = Archer
  WRITE_ASCII 0x248 ~~ #8
  WRITE_ASCII 0x250 ~S!ARCH21~ #8
  WRITE_ASCII 0x268 ~~ #8
  WRITE_BYTE 0x273 12 // Class = Ranger
    
  LPF ~ADD_CRE_EFFECT~ // ***** in Long Bows
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 104
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // * in Daggers
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 1
      parameter2 = 96
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // * in Single Weapon
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 1
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  // thac0 and damage bonuses to ranged
  FOR (i=0; i<7; ++i) BEGIN
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 167
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL122~
    END
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 286
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL122~
    END
  END
  
  PATCH_FOR_EACH item_to_remove IN ~LEAT10~ ~DAGG01~ ~BOW05~ ~AROW04~ ~AROW09~ ~AROW11~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_CRE_ITEM ~HELM02~ #0 #0 #0 ~UNSTEALABLE~ ~HELMET~
  ADD_CRE_ITEM ~OHLEAT52~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~
  ADD_CRE_ITEM ~DAGG01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~
  ADD_CRE_ITEM ~BOW16~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON2~ EQUIP
  ADD_CRE_ITEM ~AROW15~ #35 #0 #0 ~UNSTEALABLE~ ~QUIVER1~ // Arrow +3
  ADD_CRE_ITEM ~AROW15~ #35 #0 #0 ~UNSTEALABLE~ ~QUIVER2~ // Arrow +3
  ADD_CRE_ITEM ~AROW01~ #80 #0 #0 ~UNSTEALABLE~ ~QUIVER3~ // Arrow
  ADD_CRE_ITEM ~POTN14~ #1 #0 #0 ~UNSTEALABLE~ ~INV10~ // Oil of Speed
  ADD_CRE_ITEM ~POTN10~ #3 #0 #0 ~UNSTEALABLE~ ~INV11~ // Potion of Invisibility
  ADD_CRE_ITEM ~POTN55~ #2 #0 #0 ~UNSTEALABLE~ ~INV14~ // Superior Healing Potion
  ADD_CRE_ITEM ~POTN37~ #0 #0 #0 ~UNSTEALABLE~ ~INV15~ // Oil of Resurgence

  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 2 ) // Doom
  ADD_MEMORIZED_SPELL ~SPPR202~ #1 ~priest~ ( 1 ) // Barkskin
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 1 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR209~ #1 ~priest~ ( 1 ) // Know Alignment
  ADD_MEMORIZED_SPELL ~SPPR210~ #1 ~priest~ ( 1 ) // Resist Fire/Cold
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 1 ) // Protection from Fire
  ADD_MEMORIZED_SPELL ~SPPR312~ #2 ~priest~ ( 1 ) // Strength of One
  ADD_MEMORIZED_SPELL ~SPPR315~ #2 ~priest~ ( 1 ) // Cure Medium Wounds
  ADD_MEMORIZED_SPELL ~SPCL121~ #0 ~innate~ ( 5 ) // Called Shot
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL922~ #0 ~innate~ ( 1 ) // Contact with Nature

COMPILE ~IATweaks\scripts\creatures\S!ARCH21.BAF~

// Maferan, the Minotaur from Guarded Compound

COPY_EXISTING ~HLMAFER.cre~ ~override~
  WRITE_LONG 0x14 22000 // Exp
  WRITE_SHORT 0x24 126 // HP
  WRITE_SHORT 0x26 126 // HP
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x60 10 // Resist Slashing
  WRITE_BYTE 0x61 10 // Resist Crushing
  WRITE_BYTE 0x62 10 // Resist Piercing
  WRITE_BYTE 0x63 10 // Resist Missile
  WRITE_BYTE 0x234 22 // Level 1  
  WRITE_BYTE 0x23c 18 // Dexterity
  WRITE_LONG 0x244 0x40010000 // Kit = Berserker
  WRITE_BYTE 0x272 171 // Race = Minotaur
    
  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ***** in Axes
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 92
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ** in Sword and Shield
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 2
      parameter2 = 112
      resist_dispel = 0
      timing = 9
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END
  
  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = EVAL ~S!MISS6~
  END

  ADD_CRE_ITEM ~POTN41~ #1 #0 #0 ~NONE~ ~INV10~ // Potion of Power

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL321~ #0 ~innate~ ( 5 ) // Enrage
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!MAFER.BAF~

// Olaf, the Orc from Guarded Compound

COPY_EXISTING ~HLOLAF.cre~ ~override~
  WRITE_LONG 0x14 25000 // Exp
  WRITE_SHORT 0x24 150 // HP
  WRITE_SHORT 0x26 150 // HP
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x5d 40 // Resist Magic
  WRITE_BYTE 0x60 30 // Resist Slashing
  WRITE_BYTE 0x61 30 // Resist Crushing
  WRITE_BYTE 0x62 30 // Resist Piercing
  WRITE_BYTE 0x63 30 // Resist Missile
  WRITE_BYTE 0x234 24 // Level 1
  WRITE_BYTE 0x238 19 // Strength
  WRITE_BYTE 0x23d 19 // Constitution
  WRITE_LONG 0x244 0x00004000 // Kit = Barbarian
    
  LPF ~ADD_CRE_EFFECT~ // Movement speed set to 11
    INT_VAR
      target = 1
      opcode = 126
      parameter1 = 11
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ** in 2h Swords
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 2
      parameter2 = 93
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // *** in 2h Weapons
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 111
      resist_dispel = 0
      timing = 9
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END
  
  PATCH_FOR_EACH item_to_remove IN ~PLAT14~ ~S!MISS6~ ~SW2H11~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~CLCK01~ #0 #0 #0 ~NONE~ ~CLOAK~
  ADD_CRE_ITEM ~OHCHAN50~ #0 #0 #0 ~NONE~ ~ARMOR~
  ADD_CRE_ITEM ~SW2H20~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
  ADD_CRE_ITEM ~SW2H01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON2~
  ADD_CRE_ITEM ~POTN37~ #1 #0 #0 ~NONE~ ~INV10~ // Oil of Resurgence

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL152~ #0 ~innate~ ( 5 ) // Barbarian Rage
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 2 ) // Critical Strike

COMPILE ~IATweaks\scripts\creatures\S!OLAF.BAF~

// Koshi, the Kensai from Guarded Compound

COPY_EXISTING ~HLKOSHI.cre~ ~override~
  WRITE_LONG 0x14 36000 // Exp
  WRITE_SHORT 0x24 144 // HP
  WRITE_SHORT 0x26 144 // HP
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x60 10 // Resist Slashing
  WRITE_BYTE 0x61 10 // Resist Crushing
  WRITE_BYTE 0x62 10 // Resist Piercing
  WRITE_BYTE 0x63 10 // Resist Missile
  WRITE_BYTE 0x234 27 // Level 1
  WRITE_BYTE 0x238 18 // Strength
  WRITE_BYTE 0x239 100 // Exceptional Strength
  WRITE_BYTE 0x23d 18 // Constitution
  WRITE_LONG 0x244 0x40030000 // Kit = Kensai
    
  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END

  LPF ~ALTER_EFFECT~ // ***** in Katanas
    INT_VAR
      match_opcode = 233
      match_parameter2 = 94
      parameter1 = 5
  END

  LPF ~ALTER_EFFECT~ // *** in Dual Wield
    INT_VAR
      match_opcode = 233
      match_parameter2 = 114
      parameter1 = 3
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  // thac0 and damage bonuses to melee
  FOR (i=0; i<9; ++i) BEGIN
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 285
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL141~
    END
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 284
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL141~
    END
  END

  LPF ~ADD_CRE_EFFECT~ // AC
    INT_VAR
      opcode = 0
      target = 1
      parameter1 = 2
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL142~
  END

  LPF ~ADD_CRE_EFFECT~ // Weapon speed
    INT_VAR
      opcode = 190
      target = 1
      parameter1 = 7
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL143~
  END
  
  PATCH_FOR_EACH item_to_remove IN ~SW1H44~ ~S!MISS6~ ~S!KOSHI~ ~HELM01~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~CLCK02~ #0 #0 #0 ~NONE~ ~CLOAK~
  ADD_CRE_ITEM ~SW1H75~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~
  ADD_CRE_ITEM ~SW1H43~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON2~
  ADD_CRE_ITEM ~POTN37~ #1 #0 #0 ~NONE~ ~INV10~ // Oil of Resurgence
  ADD_CRE_ITEM ~POTN11~ #1 #0 #0 ~NONE~ ~INV11~ // Potion of Invulnerability
  ADD_CRE_ITEM ~POTN07~ #1 #0 #0 ~NONE~ ~INV12~ // Potion of Storm Giant Strength

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL144~ #0 ~innate~ ( 6 ) // Kai
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 2 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 2 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!KOSHI.BAF~

// Disable universal dispel on entering Guarded Compound level 2

COPY_EXISTING ~AR0907.BCS~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_EVALUATE
      ~SetGlobal("EnteredAR0907","GLOBAL",1)~
      BEGIN
          SPRINT val ~%MATCH0%
          SetGlobal("Iatrap","AR0907",1)
          ~ END
      ~%val%~
  END

// Akae from Samia's party

COPY_EXISTING ~AKAE.cre~ ~override~
  WRITE_LONG 0x14 21000 // Exp
  WRITE_SHORT 0x24 123 // HP
  WRITE_SHORT 0x26 123 // HP
  WRITE_BYTE 0x59 25  // Fire Resistance
  WRITE_BYTE 0x5e 25  // Magic Fire Resistance
  WRITE_BYTE 0x239 92 // Exceptional Strength
  WRITE_BYTE 0x23d 18 // Constitution
  WRITE_LONG 0x244 0x40030000 // Kit = Kensai
  WRITE_ASCII 0x248 ~S!SHOUT~ #8
  WRITE_ASCII 0x250 ~AKAE~ #8
  WRITE_BYTE 0x272 3 // Race
  
  PATCH_FOR_EACH opcode_to_remove IN 267 101 296 BEGIN
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = opcode_to_remove
    END
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  // thac0 and damage bonuses to melee
  FOR (i=0; i<6; ++i) BEGIN
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 285
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL141~
    END
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 284
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL141~
    END
  END

  LPF ~ADD_CRE_EFFECT~ // AC
    INT_VAR
      opcode = 0
      target = 1
      parameter1 = 2
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL142~
  END

  LPF ~ADD_CRE_EFFECT~ // Weapon speed
    INT_VAR
      opcode = 190
      target = 1
      parameter1 = 5
      parameter2 = 0
      resist_dispel = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL143~
  END

  LPF ~ALTER_EFFECT~
    STR_VAR
      match_opcode = 31
      parameter1 = 40
  END
  
  PATCH_FOR_EACH item_to_remove IN ~S!KOSHI~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~SW1H43~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON2~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL144~ #0 ~innate~ ( 4 ) // Kai
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness

COMPILE ~IATweaks\scripts\creatures\AKAE.BAF~

// Samia

COPY_EXISTING ~SAMIA.cre~ ~override~
  WRITE_LONG 0x14 28000 // Exp
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x59 50  // Fire Resistance
  WRITE_BYTE 0x5c 75  // Acid Resistance
  WRITE_BYTE 0x5e 50  // Magic Fire Resistance
  WRITE_BYTE 0x60 30 // Resist Slashing
  WRITE_BYTE 0x61 30 // Resist Crushing
  WRITE_BYTE 0x62 30 // Resist Piercing
  WRITE_BYTE 0x63 30 // Resist Missile
  WRITE_BYTE 0x239 100 // Exceptional Strength
  WRITE_BYTE 0x23d 18 // Constitution
  WRITE_ASCII 0x248 ~S!SHOUT~ #8
  WRITE_ASCII 0x250 ~SAMIA~ #8
  
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 0
  END

  LPF ~ADD_CRE_EFFECT~ // ** in Sword and Shield
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 2
      parameter2 = 112
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  LPF ~ALTER_EFFECT~
    STR_VAR
      match_opcode = 31
      parameter1 = 75
  END
  
  PATCH_FOR_EACH item_to_remove IN ~DRAGRING~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~SW1H04~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON2~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 2 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\SAMIA.BAF~

/////////////// Firkraag Fight

ADD_PROJECTILE ~IATweaks\resources\pro\s!firag0.PRO~

COPY ~IATweaks\resources\eff\s!firag0.eff~ ~override~
COPY ~IATweaks\resources\spl\s!firag0.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR
      projectile = ~%s!firag0%~
  END

COPY ~IATweaks\resources\vvc\s!firbal.vvc~ ~override~
COPY ~IATweaks\resources\spl\s!firaga.spl~ ~override~
COPY ~IATweaks\resources\spl\s!firagb.spl~ ~override~
COMPILE ~IATweaks\scripts\creatures\S!FIRAG1.BAF~
COPY ~IATweaks\resources\cre\s!firag1.CRE~ ~override~
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_INVISIBLE~))
COPY_EXISTING ~s!firag1.cre~ ~override\s!firag2.cre~
  WRITE_ASCII 0x248 ~~ #8
  WRITE_BYTE 0x272 255 // Race
  WRITE_ASCII 0x280 ~S!FIRAG2~ #20
COPY_EXISTING ~s!firag1.cre~ ~override~
  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 272
      target = 1
      parameter1 = 12
      parameter2 = 3
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~S!FIRAG0~
  END

// Improved Fireball

COPY_EXISTING ~spwii40.spl~ ~override~
  WRITE_BYTE 0x25 6
  WRITE_LONG 0x34 6
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 221
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 12
      savingthrow = 16777216 // bypass Mirror Images
  END

// Red Dragon Breath

COPY_EXISTING ~spin693.spl~ ~override~
  WRITE_BYTE 0x25 0
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 221
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 12
      match_savingthrow = 0
      parameter1 = 0
      dicenumber = 10
      savingthrow = 16777216 // bypass Mirror Images
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 12
      match_savingthrow = 2
      parameter1 = 0
      dicenumber = 10
      savingthrow = 16777218 // bypass Mirror Images
  END

// Red Dragon Claw

COPY_EXISTING ~DRAGRED1.itm~ ~override~
  LPF ~ALTER_ITEM_HEADER~
    INT_VAR
      range = 4
  END

// Firkraag

COPY_EXISTING ~FIRKRA02.cre~ ~override~
  WRITE_SHORT 0x24 THIS * 2 // HP
  WRITE_SHORT 0x26 THIS * 2 // HP
  WRITE_BYTE 0x52 THIS - 3 // Thac0
  WRITE_BYTE 0x234 28 // Level 1

  LPF ~ADD_CRE_EFFECT~ // Aura Cleansing
    INT_VAR
      target = 1
      opcode = 188
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL "SPWI302" #2 "wizard" ( 3 ) // Remove Magic
  ADD_MEMORIZED_SPELL "SPWI513" #4 "wizard" ( 5 ) // Breach
  ADD_MEMORIZED_SPELL "SPWI514" #4 "wizard" ( 3 ) // Lower Resistance
  ADD_MEMORIZED_SPELL "SPWI605" #5 "wizard" ( 2 ) // Death Spell
  ADD_MEMORIZED_SPELL "SPWI704" #6 "wizard" ( 5 ) // Ruby Ray of Reversal
  ADD_MEMORIZED_SPELL "SPWI812" #7 "wizard" ( 1 ) // Abi-Dalzim's Horrid Wilting
  ADD_MEMORIZED_SPELL "SPWII40" #0 "innate" ( 3 ) // Improved Fireball

COMPILE ~IATweaks\scripts\creatures\DRAGRED.BAF~

// Firrkraag's Lair, change deprecated string
COPY_EXISTING ~AR1203.BCS~ ~override~
  SET StrRef = RESOLVE_STR_REF (@5123)
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY
      ~DisplayStringNoName(Player1,16297)~
      ~DisplayStringNoName(Player1,%StrRef%)~
  END

// // Flamestrike creature

// COMPILE ~IATweaks\scripts\creatures\S!FLSTRK.BAF~
// COPY_EXISTING ~s!firag1.cre~ ~override\s!flstrk.cre~
//   WRITE_ASCII 0x248 ~S!FLSTRK~ #8
//   WRITE_ASCII 0x280 ~S!FLSTRK~ #20
// ADD_PROJECTILE ~IATweaks\resources\pro\s!flstrk.PRO~

// COPY ~IATweaks\resources\bam\s!sumcir.bam~ ~override~
// COPY ~IATweaks\resources\vvc\s!sumcir.vvc~ ~override~
// COPY ~IATweaks\resources\spl\s!flstr1.spl~ ~override~
// COPY ~IATweaks\resources\spl\s!flstrk.spl~ ~override~
//   LPF ~ALTER_SPELL_HEADER~ 
//     INT_VAR
//       projectile = ~%s!flstrk%~
//   END

// Archer from Illithid Hideout

COPY ~IATweaks\resources\cre\hlarch.cre~ ~override~
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile

  ADD_CRE_ITEM ~HELM06~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~HELMET~
  ADD_CRE_ITEM ~RING06~ #0 #0 #0 ~NONE~ ~RRING~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPPR111~ #0 ~priest~ ( 2 ) // Armor of Faith
  ADD_MEMORIZED_SPELL ~SPPR113~ #0 ~priest~ ( 2 ) // Doom
  ADD_MEMORIZED_SPELL ~SPPR202~ #1 ~priest~ ( 1 ) // Barkskin
  ADD_MEMORIZED_SPELL ~SPPR206~ #1 ~priest~ ( 1 ) // Flame Blade
  ADD_MEMORIZED_SPELL ~SPPR209~ #1 ~priest~ ( 1 ) // Know Alignment
  ADD_MEMORIZED_SPELL ~SPPR210~ #1 ~priest~ ( 1 ) // Resist Fire/Cold
  ADD_MEMORIZED_SPELL ~SPPR306~ #2 ~priest~ ( 1 ) // Protection from Fire
  ADD_MEMORIZED_SPELL ~SPPR312~ #2 ~priest~ ( 1 ) // Strength of One
  ADD_MEMORIZED_SPELL ~SPPR315~ #2 ~priest~ ( 1 ) // Cure Medium Wounds
  ADD_MEMORIZED_SPELL ~SPCL121~ #0 ~innate~ ( 5 ) // Called Shot
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL922~ #0 ~innate~ ( 1 ) // Contact with Nature
  
COMPILE ~IATweaks\scripts\creatures\S!ARCH19.BAF~

// Fighter from Illithid Compound turned into a Wizard Slayer

COPY_EXISTING ~HLFIGHT.cre~ ~override/S!WIZSL1.cre~
  WRITE_LONG 0x8 5753
  WRITE_LONG 0xc 5753
  WRITE_LONG 0x14 30000 // Exp
  WRITE_SHORT 0x24 135 // HP
  WRITE_SHORT 0x26 135 // HP
  WRITE_LONG 0x28 0x6102 // Dwarf
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x234 24 // Level 1
  WRITE_BYTE 0x238 18 // Strength
  WRITE_BYTE 0x239 100 // Exceptional Strength
  WRITE_BYTE 0x23c 17 // Dexterity
  WRITE_BYTE 0x23d 19 // Constitution
  WRITE_LONG 0x244 0x40020000 // Kit = Wizard Slayer
  WRITE_ASCII 0x250 ~S!WIZSL1~ #8
  WRITE_BYTE 0x272 4 // Dwarf
  WRITE_ASCII 0x280 ~S!WIZSL1~ #20
    
  LPF ~ADD_CRE_EFFECT~ // ***** in 2h Sword
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 93
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // *** in 2h Weapons
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 111
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  FOR (i = 1; i < 5; ++i) BEGIN // Magic Res
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 146
        target = 1
        parameter2 = 1
        timing = 9
        resist_dispel = 0
      STR_VAR
        resource = ~SPWSL01~
    END
  END

  FOR (i = 1; i < 3; ++i) BEGIN // Stats
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 146
        target = 1
        parameter2 = 1
        timing = 9
        resist_dispel = 0
      STR_VAR
        resource = ~SPWSL02~
    END
  END

  LPF ~ADD_CRE_EFFECT~ // Immunity to Haste/Slow
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~SPWSL03~
  END

  FOR (i = 1; i < 4; ++i) BEGIN // Fire Res
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 146
        target = 1
        parameter2 = 1
        timing = 9
        resist_dispel = 0
      STR_VAR
        resource = ~SPWSL07~
    END
  END

  PATCH_FOR_EACH item_to_remove IN ~BLUN13~ ~SW1H07~ ~PLAT04~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~SW2H06~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
  ADD_CRE_ITEM ~SW2H01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON2~
  ADD_CRE_ITEM ~PLAT05~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPWSL04~ #0 ~innate~ ( 2 ) // Purge Magic
  ADD_MEMORIZED_SPELL ~SPWSL08~ #0 ~innate~ ( 2 ) // Tower of Resilience
  ADD_MEMORIZED_SPELL ~SPWSL05~ #0 ~innate~ ( 1 ) // Continual Cure

COMPILE ~IATweaks\scripts\creatures\S!WIZSL1.BAF~

COPY_EXISTING ~AR0711.are~ ~override~
  LPF ~S!ALTER_AREA_ACTOR~
    INT_VAR
      creature_x = 1952
      creature_y = 1149
    STR_VAR
     actor_name = ~Fighter~
     cre_file = ~S!WIZSL1~
  END

// // Fighter from Illithid Compound

COPY_EXISTING ~HLFIGHT.cre~ ~override~
  WRITE_LONG 0x14 20000 // Exp
  WRITE_SHORT 0x24 123 // HP
  WRITE_SHORT 0x26 123 // HP
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x238 18 // Strength
  WRITE_BYTE 0x239 100 // Exceptional Strength
    
  LPF ~ADD_CRE_EFFECT~ // ***** in Flail
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 5
      parameter2 = 100
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // *** in Single Weapon
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  PATCH_FOR_EACH item_to_remove IN ~SW1H07~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~CLCK01~ #0 #0 #0 ~NONE~ ~CLOAK~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness

COMPILE ~IATweaks\scripts\creatures\HLFIGHT.BAF~

// Alhoon

COPY ~IATweaks\resources\bam\s!barrie.bam~ ~override~
COPY ~IATweaks\resources\vvc\s!barrie.vvc~ ~override~
COPY ~IATweaks\resources\spl\s!barrie.spl~ ~override~
  SAY NAME1 @6256

COPY ~IATweaks\resources\spl\s!mfpull.spl~ ~override~
  SAY NAME1 @6257

COPY ~IATweaks\resources\spl\s!mfsplt.spl~ ~override~
  SAY NAME1 @6258

COPY_EXISTING ~mindal01.cre~ ~override~
  WRITE_BYTE 0x53 3  // APR
  WRITE_BYTE 0x59 0  // Fire Resistance
  WRITE_BYTE 0x5e 0  // Magic Fire Resistance
  WRITE_BYTE 0x234 26 // Level 1

  // Cast S!MFPROT each time the damage is dealt
  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 232
      target = 1
      parameter1 = 0
      parameter2 = 11
      timing = 1
      resist_dispel = 0
    STR_VAR
      resource = ~S!MFPROT~
  END
  
  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~S!MFPROT~
  END

  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Casting Speed
    INT_VAR
      target = 1
      opcode = 189
      parameter1 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // See Invisible
    INT_VAR
      target = 1
      opcode = 193
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~S!BARRIE~
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL "SPWI112" #0 "wizard" ( 6 ) // Magic Missile

  ADD_MEMORIZED_SPELL "SPWI209" #1 "wizard" ( 1 ) // Luck
  ADD_MEMORIZED_SPELL "SPWI211" #1 "wizard" ( 3 ) // Melf's Acid Arrow
  ADD_MEMORIZED_SPELL "SPWI212" #1 "wizard" ( 2 ) // Mirror Image

  ADD_MEMORIZED_SPELL "SPWI302" #2 "wizard" ( 2 ) // Remove Magic
  ADD_MEMORIZED_SPELL "SPWI303" #2 "wizard" ( 3 ) // Flame Arrow
  ADD_MEMORIZED_SPELL "SPWI314" #2 "wizard" ( 1 ) // Vampiric Touch

  ADD_MEMORIZED_SPELL "SPWI403" #3 "wizard" ( 1 ) // Fire Shield (Blue)
  ADD_MEMORIZED_SPELL "SPWI405" #3 "wizard" ( 1 ) // Improved Invisibility
  ADD_MEMORIZED_SPELL "SPWI414" #3 "wizard" ( 1 ) // Spirit Armor
  ADD_MEMORIZED_SPELL "SPWI418" #3 "wizard" ( 1 ) // Fire Shield (Red)
  ADD_MEMORIZED_SPELL "SPWI419" #3 "wizard" ( 2 ) // Secret Word

  ADD_MEMORIZED_SPELL "SPWI510" #4 "wizard" ( 1 ) // Spell Immunity
  ADD_MEMORIZED_SPELL "SPWI513" #4 "wizard" ( 4 ) // Breach
  ADD_MEMORIZED_SPELL "SPWI514" #4 "wizard" ( 1 ) // Lower Resistance

  ADD_MEMORIZED_SPELL "SPWI602" #5 "wizard" ( 1 ) // Globe of Invulnerability
  ADD_MEMORIZED_SPELL "SPWI607" #5 "wizard" ( 1 ) // Giant Strength
  ADD_MEMORIZED_SPELL "SPWI613" #5 "wizard" ( 2 ) // PFMW
  ADD_MEMORIZED_SPELL "SPWI613" #5 "wizard" ( 1 ) // Improved Haste

  ADD_MEMORIZED_SPELL "SPWI701" #6 "wizard" ( 1 ) // Spell Turning
  ADD_MEMORIZED_SPELL "SPWI704" #6 "wizard" ( 3 ) // Ruby Ray of Reversal
  ADD_MEMORIZED_SPELL "SPWI714" #6 "wizard" ( 2 ) // Prismatic Spray

  ADD_MEMORIZED_SPELL "SPWI812" #7 "wizard" ( 6 ) // Abi-Dalzim's Horrid Wilting

  ADD_MEMORIZED_SPELL "SPWI915" #8 "wizard" ( 1 ) // Black Blade of Disaster
  ADD_MEMORIZED_SPELL "SPWI922" #8 "wizard" ( 4 ) // Dragon's Breath

COMPILE ~IATweaks\scripts\creatures\MINDAL01.BAF~

COPY_EXISTING ~MINDAL01.BCS~ ~override~
  SET StrRef = RESOLVE_STR_REF (@5125)
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY
      ~DisplayString(Myself,0)~
      ~DisplayString(Myself,%StrRef%)~
  END

// Kangaxx the Demilich fight

// Visual effects

COPY ~IATweaks\resources\bam\s!reddhm.bam~ ~override~
COPY ~IATweaks\resources\vvc\s!reddhm.vvc~ ~override~

// Spells for debuffing Kangaxx

COPY ~IATweaks\resources\spl\s!demipr.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      target = 2
      power = 0
      timing = 1
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 139
      parameter1 = RESOLVE_STR_REF (@6272)
  END

COPY ~IATweaks\resources\spl\s!demivs.spl~ ~override~
COPY ~IATweaks\resources\spl\s!demim0.spl~ ~override~
COPY ~IATweaks\resources\spl\s!demim1.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 139
      parameter1 = RESOLVE_STR_REF (@6271)
  END
COPY ~IATweaks\resources\spl\s!demim2.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 139
      parameter1 = RESOLVE_STR_REF (@6271)
  END

// Skulls

COPY ~IATweaks\resources\spl\s!gobinf.spl~ ~override~

COPY ~IATweaks\resources\cre\s!demimg.cre~ ~override~
  SAY NAME1 @5128
  SAY NAME2 @5128
    
  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~S!GOBINF~
  END

COMPILE ~IATweaks\scripts\creatures\S!DEMIMG.BAF~

COPY ~IATweaks\resources\cre\s!demipr.cre~ ~override~
  SAY NAME1 @5129
  SAY NAME2 @5129
    
  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~S!GOBINF~
  END

COMPILE ~IATweaks\scripts\creatures\S!DEMIPR.BAF~

// Black Dragon fom Sulda

COPY_EXISTING ~DRAGBLAC.cre~ ~override~
  WRITE_SHORT 0x24 THIS * 2 // HP
  WRITE_SHORT 0x26 THIS * 2 // HP
  WRITE_BYTE 0x52 THIS - 3 // Thac0
  WRITE_BYTE 0x54 1  // Saves
  WRITE_BYTE 0x55 3 // Saves
  WRITE_BYTE 0x56 2  // Saves
  WRITE_BYTE 0x57 2  // Saves
  WRITE_BYTE 0x58 4 // Saves
  WRITE_BYTE 0x5b 75  // Electricity Resistance

  LPF ~ADD_CRE_EFFECT~ // Aura Cleansing
    INT_VAR
      target = 1
      opcode = 188
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Casting Speed
    INT_VAR
      target = 1
      opcode = 189
      parameter1 = 2
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL "SPWI302" #2 "wizard" ( 3 ) // Remove Magic
  ADD_MEMORIZED_SPELL "SPWI513" #4 "wizard" ( 5 ) // Breach
  ADD_MEMORIZED_SPELL "SPWI514" #4 "wizard" ( 3 ) // Lower Resistance
  ADD_MEMORIZED_SPELL "SPWI605" #5 "wizard" ( 3 ) // Death Spell
  ADD_MEMORIZED_SPELL "SPWI704" #6 "wizard" ( 5 ) // Ruby Ray of Reversal

COMPILE ~IATweaks\scripts\creatures\DRAGBLAC.BAF~

// Raamilat, Drow from Sulda

COMPILE ~IATweaks\scripts\creatures\S!SURAAM.BAF~

// Revanek from Twisted Rune

COPY_EXISTING ~HLREVAN.cre~ ~override~
  WRITE_LONG 0x14 25000 // Exp
  WRITE_SHORT 0x24 138 // HP
  WRITE_SHORT 0x26 138 // HP
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x23d 18 // Constitution

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 0
  END

  LPF ~ALTER_EFFECT~ // *** in 2h Weapon
    INT_VAR
      match_opcode = 233
      match_parameter2 = 111
      parameter1 = 3
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  ADD_CRE_ITEM ~RING06~ #0 #0 #0 ~NONE~ ~RRING~
  ADD_CRE_ITEM ~SW2H01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON2~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!REVAN.BAF~

// Shyressa from Twisted Rune

COPY_EXISTING ~HLSHYR.cre~ ~override~
  WRITE_BYTE 0x52 THIS + 2 // Thac0
    WRITE_BYTE 0x59 75  // Fire Resistance
    WRITE_BYTE 0x5c 75  // Acid Resistance
    WRITE_BYTE 0x5e 75  // Magic Fire Resistance

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 0
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 31
      parameter1 = 25
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 3 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 2 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 3 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!HLSHYR.BAF~

// Valeria from Squirreled Away

COPY_EXISTING ~DEMFIG02.cre~ ~override~
  WRITE_SHORT 0x24 129 // HP
  WRITE_SHORT 0x26 129 // HP
  WRITE_BYTE  0x23d 18 // Constitution

  LPF ~ALTER_EFFECT~ // *** in 2h Weapon
    INT_VAR
      match_opcode = 233
      match_parameter2 = 111
      parameter1 = 3
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 2 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!DEMFI2.BAF~

// Exterminator

COPY_EXISTING ~DEMFIG02.cre~ ~override~
  WRITE_SHORT 0x24 135 // HP
  WRITE_SHORT 0x26 135 // HP
  WRITE_BYTE 0x5b 75  // Electricity Resistance
  WRITE_BYTE 0x5c 75  // Acid Resistance
  WRITE_BYTE  0x23d 18 // Constitution

  LPF ~ALTER_EFFECT~ // *** in 2h Weapon
    INT_VAR
      match_opcode = 233
      match_parameter2 = 111
      parameter1 = 3
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 2 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 2 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!DEMARC.BAF~

// Falahar from Squirreled Away

COPY_EXISTING ~DEMFIG02.cre~ ~override~
  WRITE_SHORT 0x24 129 // HP
  WRITE_SHORT 0x26 129 // HP
  WRITE_BYTE  0x23d 18 // Constitution

  LPF ~ALTER_EFFECT~ // *** in 2h Weapon
    INT_VAR
      match_opcode = 233
      match_parameter2 = 111
      parameter1 = 3
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  ADD_CRE_ITEM ~HALB01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON3~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 1 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 2 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!DEMFIG.BAF~

// Dracandros from Squirreled Away

COMPILE ~IATweaks\scripts\creatures\DEMMAG.BAF~

// Thax, Shadow Dragon

COPY_EXISTING ~SHADRA01.cre~ ~override~
  WRITE_SHORT 0x24 THIS + 50 // HP
  WRITE_SHORT 0x26 THIS + 50 // HP

// Pirate Captain

COPY_EXISTING ~PIRSEA01.cre~ ~override~
  WRITE_SHORT 0x24 138 // HP
  WRITE_SHORT 0x26 138 // HP
  WRITE_SHORT 0x46 6 // AC
  WRITE_SHORT 0x48 6 // AC
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x59 20 // Fire Resistance
  WRITE_BYTE 0x5c 20 // Acid Resistance
  WRITE_BYTE 0x5a 20  // Cold Resistance
  WRITE_BYTE 0x5b 20  // Electricity Resistance
  WRITE_BYTE 0x5e 20 // Magic Fire Resistance
  WRITE_BYTE 0x5f 200  // Magic Cold Resistance
  WRITE_BYTE 0x60 15 // Resist Slashing
  WRITE_BYTE 0x61 15 // Resist Crushing
  WRITE_BYTE 0x62 15 // Resist Piercing
  WRITE_BYTE 0x63 15 // Resist Missile
  WRITE_BYTE  0x23d 16 // Constitution
  WRITE_SHORT 0x246 IDS_OF_SYMBOL(~kit~ ~RISKBREAKER~) // Kit

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 31
  END

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 0
  END

  LPF ~ALTER_EFFECT~ // *** in Single Weapon
    INT_VAR
      match_opcode = 233
      match_parameter2 = 113
      parameter1 = 3
  END

  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  LPF ~ADD_CRE_EFFECT~ // RB base bonuses
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~SPCLI05~
      effsource = ~SPCLI05~
  END

  // RB AC bonus
  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 0
      target = 1
      parameter1 = 4
      parameter2 = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // RB on-hit bonuses
    INT_VAR
      opcode = 146
      target = 1
      parameter2 = 1
      timing = 9
      resist_dispel = 0
    STR_VAR
      resource = ~SPCLI09~
      effsource = ~SPCLI09~
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~DRAGRING~
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~CHAN11~
  END

  ADD_CRE_ITEM ~CHAN11~ #0 #0 #0 ~UNSTEALABLE~ ~INV15~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPINI34~ #0 ~innate~ ( 2 ) // Risk Decrement
  ADD_MEMORIZED_SPELL ~SPINI51~ #0 ~innate~ ( 2 ) // Chain Breaker Stance
  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 1 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 1 ) // Critical Strike

COMPILE ~IATweaks\scripts\creatures\S!PIRCAP.BAF~

// Harper's House in Sulda

COPY_EXISTING ~AR2811.are~ ~override~

  LPF fj_are_structure
    INT_VAR
      fj_loc_x       = 450
      fj_loc_y       = 294
      fj_dest_x      = 450
      fj_dest_y      = 294
      fj_animation   = 29458
      fj_orientation = 5
    STR_VAR
      fj_structure_type = actor
      fj_name           = ~Greater Elemental Golem~
      fj_cre_resref     = ~S!GELEGS~
  END

  LPF fj_are_structure
    INT_VAR
      fj_loc_x       = 319
      fj_loc_y       = 319
      fj_dest_x      = 319
      fj_dest_y      = 319
      fj_animation   = 32528
      fj_orientation = 7
    STR_VAR
      fj_structure_type = actor
      fj_name           = ~Noble Rakshasa~
      fj_cre_resref     = ~S!RAK1S~
  END

COMPILE ~IATweaks\scripts\areas\ar2811.BAF~

///////////////////// Beholders

COPY_EXISTING ~SPIN989.spl~ ~override~
  WRITE_SHORT 0x1c 4 // spell type = innate
  LPF ~ALTER_SPELL_HEADER~ INT_VAR speed = 0 END
  LPF ~ALTER_EFFECT~ INT_VAR power = 0 END

COMPILE ~IATweaks\scripts\creatures\behold01.BAF~

/////////////////////// Why is it so cold down there

// Turn Ele Golem to 4 Ice Elementals, remove freeze action of main character
COMPILE ~IATweaks\scripts\areas\ar0412.BAF~

// Make Ice Golem capable of shout/hear actions

<<<<<<<< .../inlined/shout_logic.baf
IF
	Allegiance(Myself,ENEMY)
	See([GOODCUTOFF])
	!GlobalTimerNotExpired("IaShoutTimer","LOCALS")
	ActionListEmpty()
THEN
	RESPONSE #100
		SetGlobalTimer("IaShoutTimer","LOCALS",THREE_ROUNDS)
		GlobalShout(99)
		Continue()
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	ActionListEmpty()
THEN
	RESPONSE #100
		GlobalShout(99)
		Continue()
END

IF
	HitBy([GOODCUTOFF],CRUSHING)
	ActionListEmpty()
THEN
	RESPONSE #100
		GlobalShout(99)
		Continue()
END

IF
	Heard([ANYONE],99)
	ActionListEmpty()
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

>>>>>>>>
EXTEND_TOP ~s!icegol.bcs~ ~.../inlined/shout_logic.baf~
  EVALUATE_BUFFER

///////// Green Wyrm

// Green Wyrm Claw

COPY_EXISTING ~S!DRAGGR.itm~ ~override~
  LPF ~ALTER_ITEM_HEADER~
    INT_VAR
      range = 3
      speed = 0
  END

// Dragon

COPY_EXISTING ~S!DRAGGR.cre~ ~override~
  WRITE_SHORT 0x24 437 // HP
  WRITE_SHORT 0x26 437 // HP

  LPF ~ADD_CRE_EFFECT~ // Aura Cleansing
    INT_VAR
      target = 1
      opcode = 188
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

