PRINT @5107

SILENT

// Improve Keldorn

ACTION_FOR_EACH keldorn_SoA_file IN ~KELDOR8~ ~KELDOR9~ ~KELDOR10~ ~KELDOR12~ BEGIN
  COPY_EXISTING ~%keldorn_SoA_file%.cre~ ~override~  
    WRITE_SHORT 0x24 79 // HP
    WRITE_SHORT 0x26 79 // HP
    WRITE_BYTE  0x23c 17 // dexterity
END

// Enable *** in Sword and Shield for Paladins

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~weapprof.2da~  ~override/weapprof.2da~
  COUNT_2DA_COLS ~colcount~
  SET sw_and_sh_row = $weapprof_rows("SWORDANDSHIELD")
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("PALADIN") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("CAVALIER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("INQUISITOR") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("UNDEAD_HUNTER") ~3~
  SET_2DA_ENTRIES_NOW ~_#_#_#weapprof~ ~colcount~
  PRETTY_PRINT_2DA

COPY_EXISTING ~spcl211.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6229
  // Extend duration by 50%
  GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
    GET_OFFSET_ARRAY2 fx_array ab_off SPL_V10_HEAD_EFFECTS
    PHP_EACH fx_array AS int => fx_off BEGIN
      READ_SHORT (fx_off + 0x00) opcode
      PATCH_IF opcode = 17 BEGIN
        WRITE_LONG (fx_off + 0x04) THIS * 5  / 2
      END
    END
  END
BUT_ONLY