PRINT @5107

SILENT

INCLUDE "%MOD_FOLDER%/lib/components/IA_rebalancing/helper_functions.tph"

// Improve Keldorn

ACTION_FOR_EACH keldorn_SoA_file IN ~KELDOR8~ ~KELDOR9~ ~KELDOR10~ ~KELDOR12~ BEGIN
  COPY_EXISTING ~%keldorn_SoA_file%.cre~ ~override~  
    WRITE_SHORT 0x24 79 // HP
    WRITE_SHORT 0x26 79 // HP
    WRITE_BYTE  0x23c 17 // dexterity
END

// Remove Smite, Deathblow and Greater Deathblow from Paladin HLAs

  COPY_EXISTING ~LUPA0.2da~ ~override~
    COUNT_2DA_COLS ~colcount~
    COUNT_2DA_ROWS ~colcount~ ~rowcount~
    SET smite_row = (0 - 1)
    SET deathblow_row = (0 - 1)
    SET greater_deathblow_row = (0 - 1)
    FOR (i = 0; i < ~rowcount~; ++i) BEGIN
      READ_2DA_ENTRY i 1 %colcount% current_val
      PATCH_IF (~%current_val%~ STR_EQ ~GA_SPCL903~) BEGIN
        SET greater_deathblow_row = i
      END
    END
    PATCH_IF (greater_deathblow_row != (0 - 1)) BEGIN
      REMOVE_2DA_ROW greater_deathblow_row ~colcount~
    END
    BUT_ONLY

  COPY_EXISTING ~LUPA0.2da~ ~override~
    COUNT_2DA_COLS ~colcount~
    COUNT_2DA_ROWS ~colcount~ ~rowcount~
    SET smite_row = (0 - 1)
    SET deathblow_row = (0 - 1)
    SET greater_deathblow_row = (0 - 1)
    FOR (i = 0; i < ~rowcount~; ++i) BEGIN
      READ_2DA_ENTRY i 1 %colcount% current_val
      PATCH_IF (~%current_val%~ STR_EQ ~GA_SPCL909~) BEGIN
        SET smite_row = i
      END
    END
    PATCH_IF (smite_row != (0 - 1)) BEGIN
      REMOVE_2DA_ROW smite_row ~colcount~
    END
    BUT_ONLY

  COPY_EXISTING ~LUPA0.2da~ ~override~
    COUNT_2DA_COLS ~colcount~
    COUNT_2DA_ROWS ~colcount~ ~rowcount~
    SET smite_row = (0 - 1)
    SET deathblow_row = (0 - 1)
    SET greater_deathblow_row = (0 - 1)
    FOR (i = 0; i < ~rowcount~; ++i) BEGIN
      READ_2DA_ENTRY i 1 %colcount% current_val
      PATCH_IF (~%current_val%~ STR_EQ ~GA_SPCL902~) BEGIN
        SET deathblow_row = i
      END
    END
    PATCH_IF (deathblow_row != (0 - 1)) BEGIN
      REMOVE_2DA_ROW deathblow_row ~colcount~
    END
    BUT_ONLY
  
// Remove Protection from Evil from all Paladins

ACTION_FOR_EACH paladin_kit_clab IN ~CLABPA01.2da~ ~CLABPA02.2da~ ~CLABPA03.2da~ ~CLABPA04.2da~ BEGIN
  COPY_EXISTING ~%paladin_kit_clab%~ ~override~
    REPLACE_EVALUATE
      ~GA_SPCL213~
      BEGIN
      END
      ~****~
    PRETTY_PRINT_2DA
END

// Rework current Protection from Evil to an AoE version

COPY_EXISTING ~SPPR408.spl~ ~override/SPCL213.spl~
  SAY UNIDENTIFIED_DESC @6283
  WRITE_SHORT 0x1c 4
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      speed = 2
      location = 4
  END

// Grant this new Prot from Evil for evey 10 levels

ACTION_FOR_EACH paladin_kit_clab IN ~CLABPA01.2da~ ~CLABPA02.2da~ ~CLABPA03.2da~ ~CLABPA04.2da~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%paladin_kit_clab%~
      row_desc = ~PROT_FROM_EVIL~
      level5 = ~GA_SPCL213~
      level15 = ~GA_SPCL213~
      level25 = ~GA_SPCL213~
      level35 = ~GA_SPCL213~
  END
END

// Remove all instantces of of Remove Fear from Cavalier

COPY_EXISTING ~CLABPA02.2da~ ~override~
  REPLACE_EVALUATE
    ~GA_SPCL222~
    BEGIN
    END
    ~****~
  PRETTY_PRINT_2DA

// Enable *** in Sword and Shield for Paladins

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~weapprof.2da~  ~override/weapprof.2da~
  COUNT_2DA_COLS ~colcount~
  SET sw_and_sh_row = $weapprof_rows("SWORDANDSHIELD")
  SET 2h_row = $weapprof_rows("2HANDED")
  SET single_weap_row = $weapprof_rows("SINGLEWEAPON")
  SET 2_weap_row = $weapprof_rows("2WEAPON")
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("PALADIN") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("CAVALIER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("INQUISITOR") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("UNDEAD_HUNTER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ sw_and_sh_row $weapprof_cols("BLACKGUARD") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2h_row $weapprof_cols("PALADIN") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2h_row $weapprof_cols("CAVALIER") ~1~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2h_row $weapprof_cols("INQUISITOR") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2h_row $weapprof_cols("UNDEAD_HUNTER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2h_row $weapprof_cols("BLACKGUARD") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weap_row $weapprof_cols("PALADIN") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weap_row $weapprof_cols("CAVALIER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weap_row $weapprof_cols("INQUISITOR") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weap_row $weapprof_cols("UNDEAD_HUNTER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weap_row $weapprof_cols("BLACKGUARD") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2_weap_row $weapprof_cols("PALADIN") ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2_weap_row $weapprof_cols("CAVALIER") ~1~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2_weap_row $weapprof_cols("INQUISITOR") ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2_weap_row $weapprof_cols("UNDEAD_HUNTER") ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2_weap_row $weapprof_cols("BLACKGUARD") ~2~
  SET_2DA_ENTRIES_NOW ~_#_#_#weapprof~ ~colcount~
  PRETTY_PRINT_2DA

// Improve Lay on Hands progression

COPY_EXISTING ~spcl211.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6229
  GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
    GET_OFFSET_ARRAY2 fx_array ab_off SPL_V10_HEAD_EFFECTS
    PHP_EACH fx_array AS int => fx_off BEGIN
      READ_SHORT (fx_off + 0x00) opcode
      PATCH_IF opcode = 17 BEGIN
        WRITE_LONG (fx_off + 0x04) THIS * 5  / 2
      END
    END
  END
BUT_ONLY

COPY ~IATweaks\resources\2da\layhands.2da~ ~override~

// Grant additional uses of Lay on Hands to Paladin

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABPA01.2da~
    row_desc = ~LAY_ON_HANDS~
    level15 = ~GA_SPCL211~
    level30 = ~GA_SPCL211~
END

// Grant +2 to critical hit chance when using large swords

COPY ~IATweaks\resources\eff\s!palcrt.eff~ ~override~
COPY ~IATweaks\resources\spl\s!palcrt.spl~ ~override~

ACTION_FOR_EACH paladin_kit_clab IN ~CLABPA01.2da~ ~CLABPA02.2da~ ~CLABPA03.2da~ ~CLABPA04.2da~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%paladin_kit_clab%~
      row_desc = ~BONUS_CRIT_SWORDS~
      level1 = ~AP_S!PALCRT~
  END
END

// Make an ability version of Heavenly Shield

COPY_EXISTING ~sppr617.spl~ ~override/s!heashl.spl~
  SAY UNIDENTIFIED_DESC @6274
  WRITE_SHORT 0x1c 4
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      location = 4
  END

// Grant that Heavenly Shield to Paladins

ACTION_FOR_EACH paladin_kit_clab IN ~CLABPA01.2da~ ~CLABPA02.2da~ ~CLABPA04.2da~ ~CLABPA06.2da~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%paladin_kit_clab%~
      row_desc = ~HEAVENLY_SHIELD~
      level12 = ~GA_S!HEASHL~
  END
END

// Grant Heavenly Shield as a HLA once

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LUPA0.2DA~
    row_desc = ~HEAVENLY_SHIELD~
    ability = ~GA_S!HEASHL~
    num_allowed = ~1~
END

// Grant Aura of Courage to Paladins and Cavaliers

ADD_PROJECTILE ~IATweaks\resources\pro\s!aocour.pro~
COPY ~IATweaks\resources\eff\s!courag.eff~ ~override~
COPY ~IATweaks\resources\spl\s!nofear.SPL~ ~override~
COPY ~IATweaks\resources\spl\s!courag.SPL~ ~override~
COPY ~IATweaks\resources\spl\s!aocour.SPL~ ~override~
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      projectile = %s!aocour%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 139
      parameter1 = RESOLVE_STR_REF (@6275)
  END

ACTION_FOR_EACH paladin_kit_clab IN ~CLABPA01.2da~ ~CLABPA02.2da~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%paladin_kit_clab%~
      row_desc = ~AURA_OF_COURAGE~
      level1 = ~AP_S!NOFEAR~
  END
END

// Plate Armor Mastery

COPY ~IATweaks\resources\eff\s!plate0.eff~ ~override~
COPY ~IATweaks\resources\eff\s!plate1.eff~ ~override~
COPY ~IATweaks\resources\eff\s!plate2.eff~ ~override~
COPY ~IATweaks\resources\eff\s!plate3.eff~ ~override~
COPY ~IATweaks\resources\eff\s!plate4.eff~ ~override~
COPY ~IATweaks\resources\bam\s!platem.bam~ ~override~
COPY ~IATweaks\resources\spl\s!platem.SPL~ ~override~
  SAY NAME1 @6281
  SAY UNIDENTIFIED_DESC @6282

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABPA01.2da~
    row_desc = ~PLATE_ARMOR_MASTERY~
    level14 = ~AP_S!PLATEM~
END

// Grant Plate Armor Mastery as a HLA once

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LUPA0.2DA~
    row_desc = ~PLATE_ARMOR_MASTERY~
    ability = ~AP_S!PLATEM~
    num_allowed = ~1~
END

// Remove bonuses to hit/damage from Cavaliers, grant them ability to prevent regeneration

COPY ~IATweaks\resources\spl\s!norege.spl~ ~override~
COPY ~IATweaks\resources\eff\s!norege.eff~ ~override~
COPY ~IATweaks\resources\eff\s!caval1.eff~ ~override~
COPY ~IATweaks\resources\eff\s!caval2.eff~ ~override~

COPY_EXISTING ~spcl221.spl~ ~override~
  PATCH_FOR_EACH bonus_vs_creature IN ~dragdam3~ ~draghit~ ~demhit3~ BEGIN
    LPF ~DELETE_EFFECT~
      STR_VAR
        match_resource = EVAL ~%bonus_vs_creature%~
    END
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 177
      multi_match = 1
      opcode = 248
      parameter1 = 0
      parameter2 = 0
    STR_VAR
      match_resource = ~DEMDAM3~
      resource = ~S!CAVAL1~
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 248
      multi_match = 1
      parameter1 = 0
      parameter2 = 0
    STR_VAR
      match_resource = ~S!CAVAL1~
      resource = ~S!CAVAL2~
  END

// Guardian's Stand

COPY ~IATweaks\resources\spl\s!caval3.spl~ ~override~
  SAY NAME1 @6277
  SAY UNIDENTIFIED_DESC @6279
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter1 = shield_equipped_state
  END
ADD_PROJECTILE ~IATweaks\resources\pro\s!aly4ft.pro~

COPY ~IATweaks\resources\bam\s!caval4.bam~ ~override~
OUTER_SET guardian_stand_desc_str_ref = RESOLVE_STR_REF (@6277)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %guardian_stand_desc_str_ref%
  STR_VAR
    bam_file = ~S!CAVAL4~
  RET
    guardian_stand_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\spl\s!caval4.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      header = 0
      projectile = %s!aly4ft%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %guardian_stand_icon_id%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      match_parameter1 = 0
      parameter1 = shield_equipped_state
  END

COPY ~IATweaks\resources\bam\s!caval5.bam~ ~override~
COPY ~IATweaks\resources\spl\s!caval5.spl~ ~override~
  SAY NAME1 @6278

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABPA02.2da~
    row_desc = ~GUARDIAN_STAND~
    level10 = ~GA_S!CAVAL3~
    level20 = ~GA_S!CAVAL3~
    level30 = ~GA_S!CAVAL3~
    level40 = ~GA_S!CAVAL3~
END

COPY ~IATweaks\resources\spl\s!caval6.spl~ ~override~

// Cleansing Light

COPY ~IATweaks\resources\bam\s!caval8.bam~ ~override~
COPY ~IATweaks\resources\spl\s!caval8.spl~ ~override~
  SAY NAME1 @6284
  SAY UNIDENTIFIED_DESC @6285

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABPA02.2da~
    row_desc = ~CLEANSING_LIGHT~
    level12 = ~GA_S!CAVAL8~
    level20 = ~GA_S!CAVAL8~
    level28 = ~GA_S!CAVAL8~
    level36 = ~GA_S!CAVAL8~
END

// Remove casting restrictions from Inquisitor

COPY_EXISTING ~SPCL234.spl~ ~override~
  LPF ~DELETE_EFFECT~ END

COPY_EXISTING ~SPCL234D.spl~ ~override~
  LPF ~DELETE_EFFECT~ END

// Remove 4th level spells from Inquisitor

COPY ~IATweaks\resources\spl\s!-pr4lv.spl~ ~override~

OUTER_FOR (k = 0; k <= 9; ++k) BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~CLABPA03.2da~
      row_desc = ~NO_4TH_LEVEL_SPELLS~
      level15 = ~AP_S!-PR4LV~
  END
END

// Move Inquisitor Usability Flags

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~kitlist.2da~ ~override/kitlist.2da~
  COUNT_2DA_COLS ~colcount~
  SET_2DA_ENTRY $kitlist_rows("INQUISITOR") $kitlist_cols("UNUSABLE") ~colcount~ ~0x00000020~ // Lack of spells is hardcoded to usability flags

// Ability version of Weaken Undead for Undead Hunters

COPY_EXISTING ~sppr515.spl~ ~override/s!undht1.spl~
  WRITE_SHORT 0x1c 4
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      location = 4
  END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABPA04.2da~
    row_desc = ~WEAKEN_UNDEAD~
    level12 = ~GA_S!UNDHT1~
    level20 = ~GA_S!UNDHT1~
    level28 = ~GA_S!UNDHT1~
    level36 = ~GA_S!UNDHT1~
END

// Additional Lay on Hands

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABPA04.2da~
    row_desc = ~LAY_ON_HANDS~
    level1 = ~GA_SPCL211~
END

// Class and Kit description

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_rows = 2da_rows_to_ids_mapping
END

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  INT_VAR
    col_with_names = 1
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_rows = 2da_rows_to_ids_mapping
END

// update class description for Paladins
COPY_EXISTING ~clastext.2da~ ~override/clastext.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $clastext_cols("DESCSTR")
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $clastext_rows("PALADIN") description_col RESOLVE_STR_REF (@5131)
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $clastext_rows("CAVALIER") description_col RESOLVE_STR_REF (@5133)
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $clastext_rows("INQUISITOR") description_col RESOLVE_STR_REF (@5132)
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $clastext_rows("UNDEAD_HUNTER") description_col RESOLVE_STR_REF (@5135)
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $clastext_rows("BLACKGUARD") description_col RESOLVE_STR_REF (@5136)
  SET_2DA_ENTRIES_NOW ~s!paladin_desc~ ~colcount~
  PRETTY_PRINT_2DA

COPY_EXISTING ~kitlist.2da~ ~override/kitlist.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $kitlist_cols("HELP")
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $kitlist_rows("CAVALIER") description_col RESOLVE_STR_REF (@5133)
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $kitlist_rows("INQUISITOR") description_col RESOLVE_STR_REF (@5132)
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $kitlist_rows("UNDEAD_HUNTER") description_col RESOLVE_STR_REF (@5135)
  SET_2DA_ENTRY_LATER ~s!paladin_desc~ $kitlist_rows("Blackguard") description_col RESOLVE_STR_REF (@5136)
  SET_2DA_ENTRIES_NOW ~s!paladin_desc~ ~colcount~
  PRETTY_PRINT_2DA
