// Change Kensai bonuses to only apply to melee weapons

COPY_EXISTING ~SPCL141.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 278
      opcode = 284
  END 
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 73
      opcode = 285
  END 

// Change Riskbreaker crit bonuses to only apply to melee weapons

COPY_EXISTING ~SPCLI05.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 301
      special = 1
  END 

// Add Wings to Swanmays

COPY ~IATweaks\resources\bam\WQMZWA1.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA2.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA3.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA4.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA5.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA6.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA7.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA8.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA9.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWCA.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWG1.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWSA.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWSS.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWSX.bam~ ~override~

COPY ~IATweaks\resources\itm\s!wings.itm~ ~override~
  SAY NAME2 @7004

ACTION_FOR_EACH swanmay_cre IN ~s!swansu~ ~s!gswan~ ~s!edeswa~ ~s!swanfa~ ~s!swanq~ ~s!swanme~ BEGIN
  COPY_EXISTING ~%swanmay_cre%.cre~ ~override~
    ADD_CRE_ITEM ~s!wings~ #0 #0 #0 ~IDENTIFIED~ ~HELMET~
    WRITE_BYTE 0x32 105 // Change hair color to white (the same color will be set for the wings)
  IF_EXISTS
END

// Remove immunity to "remove item" from s!immune.itm
COPY_EXISTING ~S!IMMUNE.ITM~ ~override~
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 101
      match_parameter2 = 112
  END

// Change Cavalier resistance bonus from "set" to "increment"
COPY_EXISTING ~SPCL221.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 27
      parameter2 = 0
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 30
      parameter2 = 0
  END

// Give Improved Alacrity to C/M

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LUCM0.2DA~
    row_desc = ~ALACRITY~
    ability = ~GA_SPWI921~
    num_allowed = ~1~
END

// Make Energy Blades ignore enemy Magic Resistance

COPY_EXISTING ~ENEBLADE.itm~ ~override~
  SAY IDENTIFIED_DESC @7012
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 12
      resist_dispel = 0
  END

// Rework spells for summoned Nymph

COPY_EXISTING ~SPPR410.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6146

COPY_EXISTING ~NYMPHSU.cre~ ~override~
  ADD_MEMORIZED_SPELL ~SPPR202~ #1 ~priest~ ( 1 )
  ADD_MEMORIZED_SPELL ~SPPR208~ #1 ~priest~ ( 1 )

// Remove immunity to Haste and IH from invincibility ring

COPY_EXISTING ~SUREHP1.itm~ ~override~
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 206
    STR_VAR
      match_resource = ~SPWI613~
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 206
    STR_VAR
      match_resource = ~SPWI305~
  END
  BUT_ONLY

// Make Improved Chain Lightning an Evocation spell and increase its casting time

COPY_EXISTING ~SPWII13.spl~ ~override~
  WRITE_SHORT 0x22 15 // casting animation
  WRITE_BYTE 0x25 6 // Spell School
  
  // Update casting speed
  LPF ~ALTER_SPELL_HEADER~ INT_VAR speed = 4 END

  
/////////////////// Asylum Tome //////////////////////

COMPILE ~IATweaks\scripts\others\PPBOOK.BAF~

// Add Rest effect to spell which triggers when PARTY_FLED is detected

COPY_EXISTING ~SPWII07.spl~ ~override~
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 81
      opcode = 316
  END