SILENT

// Change Kensai bonuses to only apply to melee weapons

COPY_EXISTING ~SPCL141.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 278
      opcode = 284
  END 
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 73
      opcode = 285
  END 

// Change Riskbreaker crit bonuses to only apply to melee weapons

COPY_EXISTING ~SPCLI05.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 301
      special = 1
  END 

// Add Wings to Swanmays

COPY ~IATweaks\resources\bam\WQMZWA1.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA2.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA3.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA4.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA5.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA6.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA7.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA8.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWA9.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWCA.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWG1.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWSA.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWSS.bam~ ~override~
COPY ~IATweaks\resources\bam\WQMZWSX.bam~ ~override~

COPY ~IATweaks\resources\itm\s!wings.itm~ ~override~
  SAY NAME2 @7004

ACTION_FOR_EACH swanmay_cre IN ~s!swansu~ ~s!gswan~ ~s!edeswa~ ~s!swanfa~ ~s!swanq~ ~s!swanme~ BEGIN
  COPY_EXISTING ~%swanmay_cre%.cre~ ~override~
    ADD_CRE_ITEM ~s!wings~ #0 #0 #0 ~IDENTIFIED~ ~HELMET~
    WRITE_BYTE 0x32 105 // Change hair color to white (the same color will be set for the wings)
  IF_EXISTS
END

// Remove immunity to "remove item" from s!immune.itm
COPY_EXISTING ~S!IMMUNE.ITM~ ~override~
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 101
      match_parameter2 = 112
  END

// Change Cavalier resistance bonus from "set" to "increment"
COPY_EXISTING ~SPCL221.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 27
      parameter2 = 0
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 30
      parameter2 = 0
  END

// Give Improved Alacrity to C/M

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LUCM0.2DA~
    row_desc = ~ALACRITY~
    ability = ~GA_SPWI921~
    num_allowed = ~1~
END

// Make Energy Blades ignore enemy Magic Resistance

COPY_EXISTING ~ENEBLADE.itm~ ~override~
  SAY IDENTIFIED_DESC @7012
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 12
      resist_dispel = 0
  END

// Rework spells for summoned Nymph

COPY_EXISTING ~SPPR410.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6146

COPY_EXISTING ~NYMPHSU.cre~ ~override~
  ADD_MEMORIZED_SPELL ~SPPR202~ #1 ~priest~ ( 1 )
  ADD_MEMORIZED_SPELL ~SPPR208~ #1 ~priest~ ( 1 )

// Remove immunity to Haste and IH from invincibility ring

COPY_EXISTING ~SUREHP1.itm~ ~override~
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 206
    STR_VAR
      match_resource = ~SPWI613~
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 206
    STR_VAR
      match_resource = ~SPWI305~
  END
  BUT_ONLY

// Make Improved Chain Lightning an Evocation spell and increase its casting time

COPY_EXISTING ~SPWII13.spl~ ~override~
  WRITE_SHORT 0x22 15 // casting animation
  WRITE_BYTE 0x25 6 // Spell School
  
  // Update casting speed
  LPF ~ALTER_SPELL_HEADER~ INT_VAR speed = 4 END

  
/////////////////// Asylum Tome //////////////////////

COMPILE ~IATweaks\scripts\others\PPBOOK.BAF~

// Add Rest effect to spell which triggers when PARTY_FLED is detected

COPY_EXISTING ~SPWII07.spl~ ~override~
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 81
      opcode = 316
  END

// Change thac0 bonus from Potion of Heroism and of Power to static bonus

COPY_EXISTING ~POTN41.itm~ ~override~
  SAY IDENTIFIED_DESC @7038
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 54
      parameter1 = 2
      parameter2 = 0
  END

COPY_EXISTING ~POTN09.itm~ ~override~
  SAY IDENTIFIED_DESC @7039
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 54
      parameter1 = 1
      parameter2 = 0
  END

// Add partial immunity to Greater Command for Elves and Half Elves

COPY_EXISTING ~sppr512.spl~ ~override~
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 39
      opcode = 324
      parameter1 = 0 
      parameter2 = 15
      duration = 0
      probability1 = 90
      multi_match = 1
    STR_VAR
      resource = ~SPPR512~
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      match_opcode = 39
      opcode = 324
      parameter1 = 0 
      parameter2 = 19
      duration = 0
      probability1 = 30
      multi_match = 1
    STR_VAR
      resource = ~SPPR512~
  END

// Contingency files

COPY ~IATweaks\resources\spl\s!cont01.spl~ ~override~ // Remove Magic if HP less than 75

// Make stores sell and buy items of new categories, like Bastard Sword (69) - used for backstab weapons

COPY_EXISTING_REGEXP GLOB ~.+\.sto~ ~override~
  SET deals_in_armors = 0
  SET deals_in_weapons = 0
  READ_LONG 0x2c item_categories_offset
  READ_LONG 0x30 item_category_number
  FOR (i = 0; i < item_category_number; ++i) BEGIN
    READ_LONG (item_categories_offset + (4 * i)) item_category
    PATCH_IF (item_category = 2) BEGIN
      SET deals_in_armors = 1
    END
    PATCH_IF (item_category = 16) BEGIN
      SET deals_in_weapons = 1
    END
  END
  PATCH_IF (deals_in_armors = 1) BEGIN
    PATCH_FOR_EACH IWD_armor_category IN 60 61 62 63 64 65 66 67 68 BEGIN
      LPF ~S!ADD_STORE_PURCHASE~
        INT_VAR
          category = IWD_armor_category
      END
    END
  END
  PATCH_IF (deals_in_weapons = 1) BEGIN
    PATCH_FOR_EACH IWD_weapon_category IN 57 69 BEGIN
      LPF ~S!ADD_STORE_PURCHASE~
        INT_VAR
          category = IWD_weapon_category
      END
    END
  END