SILENT

INCLUDE "%MOD_FOLDER%/lib/components/IA_rebalancing/helper_functions.tph"

// Add condition for checking specific kit in splprot.2da

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~KIT=n~
    stat                  = ~152~
    value                 = ~-1~
    relation              = ~1~
  RET
    kit_equals_row = new_line_number
END

// Add proper CLAB file if it does not exist

ACTION_FOR_EACH mage_kit_clab_file IN ~CLABMA01.2da~ ~CLABMA02.2da~ ~CLABMA03.2da~ ~CLABMA04.2da~ ~CLABMA05.2da~ ~CLABMA06.2da~ ~CLABMA07.2da~ ~CLABMA08.2da~ ~CLABMA09.2da~ BEGIN
  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%mage_kit_clab_file%~ THEN BEGIN
    COPY ~IATweaks\resources\2da\clabtemp.2da~ ~override/%mage_kit_clab_file%~
  END
END

// Luck

COPY_EXISTING ~spwi209.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6119
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 133
      opcode = 22
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      match_duration = 18
      duration = 120
  END

ACTION_FOR_EACH luck_scroll IN ~s!scrl18.itm~ ~scrl93.itm~ BEGIN
  COPY_EXISTING ~%luck_scroll%~ ~override~
    SAY IDENTIFIED_DESC @6119
END

// Mirror Image

COPY_EXISTING ~spwi212.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 119
      opcode = 159
  END

// Web

COPY_EXISTING ~spwi215.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6056
  READ_BYTE 0x1f spell_flags
  WRITE_BYTE 0x1f (%spell_flags% BAND 0b00000000) // enable the spell for Conjurers
  WRITE_BYTE 0x1f (%spell_flags% BOR 0b00000001) // disable the spell for Diviners
  WRITE_SHORT 0x22 14 // Casting animation
  WRITE_BYTE 0x25 2 // School

COPY_EXISTING ~SCRL99.itm~ ~override~
  SAY IDENTIFIED_DESC @6056

// Shield Mind and Body

COPY_EXISTING ~sppr112a.bam~ ~override\spwi725a.bam~
COPY_EXISTING ~sppr112b.bam~ ~override\spwi725b.bam~
COPY_EXISTING ~sppr112c.bam~ ~override\spwi725c.bam~
COPY ~IATweaks\resources\bam\spwi725d.bam~ ~override~
COPY ~IATweaks\resources\bam\spwi725e.bam~ ~override~

OUTER_SET shield_mind_desc_str_ref = RESOLVE_STR_REF (@6138)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %shield_mind_desc_str_ref%
  STR_VAR
    bam_file = ~SPWI725D~
  RET
    shield_mind_icon_id = portrait_icon_id
END

OUTER_SET shield_body_desc_str_ref = RESOLVE_STR_REF (@6139)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %shield_body_desc_str_ref%
  STR_VAR
    bam_file = ~SPWI725E~
  RET
    shield_body_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\spl\spwi725.spl~ ~override~
  SAY NAME1 @6137
  SAY UNIDENTIFIED_DESC @6140
COPY ~IATweaks\resources\spl\spwi725d.spl~ ~override~
  SAY NAME1 @6139
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %shield_body_icon_id%
  END
COPY ~IATweaks\resources\spl\spwi725e.spl~ ~override~
  SAY NAME1 @6138
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %shield_mind_icon_id%
  END

COPY ~IATweaks\resources\itm\spwi725.itm~ ~override~
  SAY NAME2 @6137
  SAY IDENTIFIED_DESC @6140

// RVE

COPY_EXISTING ~spwi905.spl~ ~override~
  // Remove removal of Illusion spells from party
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 47
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 221
  END

//////// CONJURER //////////

// More powerful versions of summons for Conjurer

COMPILE ~IATweaks\scripts\creatures\S!MONSUM.baf~

COPY ~IATweaks\resources\spl\s!smbuf1.spl~ ~override~
COPY ~IATweaks\resources\spl\s!smbuf2.spl~ ~override~

ACTION_FOR_EACH summoned_monster IN ~OGRELESU~ ~OGRESU~ ~ETTERCSU~ ~S!MINOSU~ ~S!SALASU~ ~S!TROLSU~ ~S!YUANSU~ BEGIN
  COPY_EXISTING ~%summoned_monster%.cre~ ~override~
    WRITE_ASCII 0x258 ~S!MONSUM~ #8
END

//////// TRANSMUTER //////////

// Stoneskin that can be cast at others

COPY_EXISTING ~spwi408.spl~ ~override/s!stonsk.spl~
  WRITE_SHORT 0x1c 4 // Innate
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      location = 4
      target = 1
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      target = 2
  END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA04.2da~
    row_desc = ~ALLY_STONESKIN~
    level5 = ~GA_S!STONSK~
    level15 = ~GA_S!STONSK~
    level25 = ~GA_S!STONSK~
    level35 = ~GA_S!STONSK~
END

// Tenser's Transformation

COPY ~IATweaks\resources\eff\s!1_2apr.eff~ ~override~
COPY ~IATweaks\resources\spl\spwi603d.spl~ ~override~
COPY_EXISTING ~spwi603.spl~ ~override~
  LPF ~CLONE_EFFECT~
    INT_VAR
      multi_match = 1
      match_opcode = 206
      opcode = 326
      parameter1 = 8192
      parameter2 = %kit_equals_row%
    STR_VAR
      resource = ~spwi603d~
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 145
      match_parameter2 = 2
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      multi_match = 1
      match_opcode = 206
      opcode = 318
      parameter1 = 8192
      parameter2 = %kit_equals_row%
    STR_VAR
      resource = ~spwi804~
  END  
  LPF ~CLONE_EFFECT~
    INT_VAR
      multi_match = 1
      match_opcode = 206
      opcode = 318
      parameter1 = 8192
      parameter2 = %kit_equals_row%
    STR_VAR
      resource = ~spwi603~
  END  
  LPF ~CLONE_EFFECT~
    INT_VAR
      multi_match = 1
      match_opcode = 206
      opcode = 145
      parameter2 = 2
  END  

// Tenser's Partial Transformation

COPY ~IATweaks\resources\spl\spwi804d.spl~ ~override~
COPY_EXISTING ~spwi804.spl~ ~override~
  LPF ~CLONE_EFFECT~
    INT_VAR
      multi_match = 1
      match_opcode = 206
      opcode = 326
      parameter1 = 8192
      parameter2 = %kit_equals_row%
    STR_VAR
      resource = ~spwi804d~
  END

// Dragon Strength

COPY ~IATweaks\resources\bam\s!dragsb.bam~ ~override~
COPY ~IATweaks\resources\bam\s!dragsd.bam~ ~override~

OUTER_SET dragon_str_desc_str_ref = RESOLVE_STR_REF (@6057)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %dragon_str_desc_str_ref%
  STR_VAR
    bam_file = ~S!DRAGSD~
  RET
    dragon_str_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\spl\s!drgstr.spl~ ~override~
  SAY NAME1 @6057
  SAY UNIDENTIFIED_DESC @6058
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %dragon_str_icon_id%
  END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA04.2da~
    row_desc = ~DRAGON_STRENGTH~
    level18 = ~GA_S!DRGSTR~
    level24 = ~GA_S!DRGSTR~
    level30 = ~GA_S!DRGSTR~
    level36 = ~GA_S!DRGSTR~
END

// Blinding Speed

COPY ~IATweaks\resources\bam\s!blspdb.bam~ ~override~
COPY ~IATweaks\resources\spl\s!bldspd.spl~ ~override~
  SAY NAME1 @6059
  SAY UNIDENTIFIED_DESC @6060

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA04.2da~
    row_desc = ~BLINDING_SPEED~
    level14 = ~GA_S!BLDSPD~
    level21 = ~GA_S!BLDSPD~
    level28 = ~GA_S!BLDSPD~
    level35 = ~GA_S!BLDSPD~
END

//////// INVOKER ////////

// Chain Sequencer

COPY_EXISTING ~inareanp.pro~ ~override/s!wij01.pro~
  READ_BYTE 0x2f ext_flags_4
  WRITE_BYTE 0x2f (%ext_flags_4% BOR 0b01000000) // Activate IWD style checks
  WRITE_SHORT 0x3e 142 // Do not affect invisible creatures
  WRITE_SHORT 0x214 0 // No secondary projectile
  WRITE_SHORT 0x21a 0 // No explosion projectile

ADD_PROJECTILE ~override\s!wij01.pro~

COPY ~IATweaks\resources\bam\spwij01b.bam~ ~override~
COPY ~IATweaks\resources\spl\spwij01.spl~ ~override~
  SAY NAME1 @6061
  SAY UNIDENTIFIED_DESC @6062
COPY ~IATweaks\resources\spl\spwij01d.spl~ ~override~
  SAY NAME1 @6063
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      projectile = %s!wij01%
  END

COPY ~IATweaks\resources\spl\spwij01e.spl~ ~override~
COPY ~IATweaks\resources\spl\spwij01p.spl~ ~override~
  SAY NAME1 @6063
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      projectile = %s!wij01%
  END

COPY_EXISTING ~bgee.lua~ ~override~
	REPLACE_TEXTUALLY EXACT_MATCH ~mageBookStrings = {~ ~mageBookStrings = {
	SPWIJ01 = {tip = 60420, title = 'MINOR_SEQUENCER_TITLE', action = "ADD_SPELLS_SEQUENCER_LABEL"},~

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA07.2da~
    row_desc = ~CHAIN_SEQUENCER~
    level15 = ~GA_SPWIJ01~
    level25 = ~GA_SPWIJ01~
END

// +5% elemental damage per 10 levels

COPY ~IATweaks\resources\spl\s!+5eled.spl~ ~override~

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA07.2da~
    row_desc = ~5%_ELEM_DAMAGE~
    level10 = ~GA_S!+5ELED~
    level20 = ~GA_S!+5ELED~
    level30 = ~GA_S!+5ELED~
    level40 = ~GA_S!+5ELED~
END

////// Illusionist ////////

// Non-detection

// Add spellstate shield_equipped

LAF resolve_state STR_VAR new_state_id = ~NON_DETECTION~ RET new_state_index END
OUTER_SET non_detection_state = %new_state_index%

// Add 7eyes.2da file if it does not exist

ACTION_IF NOT FILE_EXISTS_IN_GAME ~7EYES.2da~ THEN BEGIN
  COPY ~IATweaks\resources\2da\7eyestempl.2da~ ~override/7EYES.2da~
END

LAF ~S!ADD_7EYES_ROW~
  INT_VAR
    strref        = RESOLVE_STR_REF (@6065)
  STR_VAR
    row_desc      = ~NON_DETECTION~
    spellstate    = EVAL ~%non_detection_state%~
    eff1          = ~136~ // Force visible
    eff2          = ~116~ // Cure invisibility
    eff3          = ~47~ // Another cure invisibility
    eff4          = ~220*5~ // Remove spell school protection (ILLUSIONIST)
    eff5          = ~221*3~ // Remove spell type protection (ILLUSIONARYPROTECTIONS)
    eff6          = ~*~
    eff7          = ~*~
    eff8          = ~*~
    eff9          = ~*~
  RET non_detect_row_id = new_row_id 
END

COPY_EXISTING ~spwi310.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6064
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      range = 60 //Visual range of the caster
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 69
      opcode = 335
      parameter1 = %non_detection_state%
      parameter2 = %non_detect_row_id%
  END

// Create a list of all spells that grant Improved Invisibility
COPY_EXISTING_REGEXP GLOB ~.*\.SPL~ ~override~
  LPF ~S!SPELL_USES_OPCODE~
    INT_VAR
      match_opcode   = 20 // Invisibility
      match_param2   = 1  // Improved
    RET is_found opcode_resource
  END
  PATCH_IF ~%is_found%~ STR_EQ ~TRUE~ BEGIN
    SPRINT source_name ~%SOURCE_RES%~
    TO_UPPER source_name
    SPRINT $imp_inv_spells("%source_name%") "irrelevant"
  END
  BUT_ONLY

ACTION_PHP_EACH imp_inv_spells AS ii_spell=>irrelevant BEGIN
  OUTER_SET immune_to_ii_strref = RESOLVE_STR_REF (@6066)
  // Apply -4 penalty to Saving Throws, since Improved Invisibility grants a +4 bonus
  COPY_EXISTING ~%ii_spell%.spl~ ~override~
    LPF ~S!CLONE_EFFECT~
      INT_VAR
        match_opcode = 20
        match_parameter2 = 1
        opcode = 325
        parameter1 = ~-4~
        parameter2 = 0
    END
    // Remove all vanilla protections from II spells
    PATCH_PHP_EACH imp_inv_spells AS ii_spell_inner=>irrelevant BEGIN
      LPF ~DELETE_EFFECT~
        INT_VAR
          match_opcode = 206
        STR_VAR
          match_resource = EVAL ~%ii_spell_inner%~
      END
    // Make all II spells protect against all other such spells for their duration
      PATCH_IF ~%SOURCE_RES%~ STRING_COMPARE_CASE ~%ii_spell_inner%~ != 0 BEGIN
        LPF ~CLONE_EFFECT~
          INT_VAR
            match_opcode = 20
            opcode = 206
            multi_match = 1
            parameter1 = %immune_to_ii_strref%
            parameter2 = 0
          STR_VAR
            resource = EVAL ~%ii_spell_inner%~
            insert = ~last~
        END
      END
    END
    // Ensure that protection from self is applied as the last effect
    LPF ~CLONE_EFFECT~
      INT_VAR
        match_opcode = 20
        opcode = 206
        multi_match = 1
        parameter1 = %immune_to_ii_strref%
        parameter2 = 0
      STR_VAR
        resource = EVAL ~%SOURCE_RES%~
        insert = ~last~
    END
    BUT_ONLY
  // Make spells that remove Invisibility also dispel all such spells to ensure that -4 ST penalty is not duplicated
  ACTION_FOR_EACH spell_removing_invisibility IN ~spwi203.spl~ ~sppr309.spl~ BEGIN
    COPY_EXISTING ~%spell_removing_invisibility%~ ~override~
      LPF ~CLONE_EFFECT~
        INT_VAR
          match_opcode = 116
          opcode = 321
        STR_VAR
          resource = EVAL ~%SOURCE_RES%~
      END
    BUT_ONLY
  END
END

COPY_EXISTING ~SPWI405.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6123

COPY_EXISTING ~SCRL1Y.itm~ ~override~
  SAY IDENTIFIED_DESC @6123

// Add permanent sequencers for single and multi target Non-detection to Illusionist

COPY ~IATweaks\resources\eff\s!stillu.eff~ ~override~
COPY ~IATweaks\resources\eff\s!mtillu.eff~ ~override~
COPY ~IATweaks\resources\spl\s!mtillu.spl~ ~override~
COPY ~IATweaks\resources\spl\s!stillu.spl~ ~override~
COPY ~IATweaks\resources\spl\s!illu01.spl~ ~override~
COPY ~IATweaks\resources\spl\s!illu02.spl~ ~override~

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA08.2da~
    row_desc = ~CONTINGENCY_NONDETECTION_SINGLE~
    level15 = ~AP_S!ILLU01~
END
LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA08.2da~
    row_desc = ~CONTINGENCY_NONDETECTION_MULTI~
    level15 = ~AP_S!ILLU02~
END

// Add sequencer triggers to Improved and Mass Invisibility

COPY_EXISTING ~spwi405.spl~ ~override~
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 258
      target = 1
      parameter1 = 0
      parameter2 = 0
      resist_dispel = 0
      duration = 0
    STR_VAR
      resource = ~S!STILLU~
  END      

COPY_EXISTING ~spwi721.spl~ ~override~
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 260
      target = 1
      parameter1 = 0
      parameter2 = 0
      resist_dispel = 0
      duration = 0
    STR_VAR
      resource = ~S!MTILLU~
  END
      
// Simulacrum

COPY ~IATweaks\resources\bam\s!simulb.bam~ ~override~
COPY ~IATweaks\resources\bam\s!simulc.bam~ ~override~
COPY ~IATweaks\resources\spl\s!simorg.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6067
COPY ~IATweaks\resources\spl\s!simuli.spl~ ~override~

COPY_EXISTING ~simulacr.spl~ ~override~
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 146
      target = 1
      parameter1 = 0
      parameter2 = 0
      resist_dispel = 0
      duration = 0
    STR_VAR
      resource = ~S!SIMULI~
  END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA08.2da~
    row_desc = ~SIMULACRUM~
    level16 = ~GA_S!SIMORG~
END

// TODO:
// - set number of attacks to 0
// - address level properly
// - remove opcode 177 to prevent non-detection? maybe through a wizard spell that removes it if spell level < 14
//   as the 1st class can be Fighter, not Illusionist
// Add some bonuses to HiS and Detect Illusions

//////// Enchanter /////////

// Bonus Saving Throws against enchantment

COPY ~IATweaks\resources\spl\s!+1ench.spl~ ~override~

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA09.2da~
    row_desc = ~SAVE_VS_ENCHANTMENT~
    level6  = ~AP_S!+1ENCH~
    level12 = ~AP_S!+1ENCH~
    level18 = ~AP_S!+1ENCH~
    level24 = ~AP_S!+1ENCH~
    level30 = ~AP_S!+1ENCH~
    level36 = ~AP_S!+1ENCH~
END

// Focused Mind Blast

ADD_PROJECTILE ~IATweaks\resources\pro\s!mindbl.pro~
COPY ~IATweaks\resources\bam\s!mindbl.bam~ ~override~
COPY ~IATweaks\resources\bam\s!mblasb.bam~ ~override~
COPY ~IATweaks\resources\spl\s!mindbl.spl~ ~override~
  SAY NAME1 @6068
  SAY UNIDENTIFIED_DESC @6069

COPY ~IATweaks\resources\spl\s!mblast.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~ 
    INT_VAR 
      projectile = ~%s!mindbl%~
  END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA09.2da~
    row_desc = ~FOCUSED_MIND_BLAST~
    level10 = ~GA_S!MINDBL~
    level20 = ~GA_S!MINDBL~
    level30 = ~GA_S!MINDBL~
END

// TODO:
// - decide what to do with godslaying enchantment
// - probably rename it to High Enchantment or something
// - potentially grant some bonuses to thac0/damage

/////// Diviner /////////

// Automatically learn Foreknowledge at lvl 16

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA05.2da~
    row_desc = ~FOREKNOWLEDGE~
    level16 = ~GA_SPWI807~
END

// See Invisible

COPY ~IATweaks\resources\bam\s!seeinb.bam~ ~override~
COPY ~IATweaks\resources\bam\s!seeind.bam~ ~override~

OUTER_SET see_invisible_desc_str_ref = RESOLVE_STR_REF (@6070)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %see_invisible_desc_str_ref%
  STR_VAR
    bam_file = ~S!SEEIND~
  RET
    see_invisible_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\spl\s!seeinv.spl~ ~override~
  SAY NAME1 @6070
  SAY UNIDENTIFIED_DESC @6071
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %see_invisible_icon_id%
  END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA05.2da~
    row_desc = ~SEE_INVISIBLE~
    level18 = ~GA_S!SEEINV~
    level25 = ~GA_S!SEEINV~
    level32 = ~GA_S!SEEINV~
END

// Glimpse of the Future

COPY ~IATweaks\resources\2da\s!glimp1.2da~ ~override~
COPY ~IATweaks\resources\bam\s!glimpb.bam~ ~override~
COPY ~IATweaks\resources\bam\s!glimpd.bam~ ~override~

OUTER_SET glimpse_of_future_desc_str_ref = RESOLVE_STR_REF (@6072)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %glimpse_of_future_desc_str_ref%
  STR_VAR
    bam_file = ~S!GLIMPD~
  RET
    glimpse_of_future_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\spl\s!glimp1.spl~ ~override~
  SAY NAME1 @6072
  SAY UNIDENTIFIED_DESC @6073

COPY ~IATweaks\resources\spl\s!glimp2.spl~ ~override~
  SAY NAME1 @6072
  SAY UNIDENTIFIED_DESC @6073
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %glimpse_of_future_icon_id%
  END

COPY ~IATweaks\resources\spl\s!glimp3.spl~ ~override~

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA05.2da~
    row_desc = ~GLIMPSE_OF_FUTURE~
    level1  = ~GA_S!GLIMP1~
    level8  = ~GA_S!GLIMP1~
    level16 = ~GA_S!GLIMP1~
    level24 = ~GA_S!GLIMP1~
    level32 = ~GA_S!GLIMP1~
    level40 = ~GA_S!GLIMP1~
END

//////// Abjurer /////////

// Abjuration Mastery

// 2DA lists of Abjuration spells
COPY ~IATweaks\resources\2da\abjurmasttempl.2da~ ~override\s!abjur4.2da~
COPY_EXISTING_REGEXP GLOB ~SPWI[1-4][0-5][0-9].SPL~ ~override~
  READ_BYTE 0x25 spell_school
  INNER_ACTION BEGIN
    ACTION_IF %spell_school% = 1 AND NOT ~%SOURCE_RES%~ STR_EQ ~SPWI222~ THEN BEGIN // Abjurer, No Chaos Shield
      APPEND ~s!abjur4.2da~ ~%SOURCE_RES% %SOURCE_RES% 4~
    END
  END
  BUT_ONLY

ACTION_FOR_EACH spl_level IN 5 6 7 8 9 BEGIN
  OUTER_SET lower_level = %spl_level% - 1
  COPY_EXISTING ~s!abjur%lower_level%.2da~ ~override\s!abjur%spl_level%.2da~
  COPY_EXISTING_REGEXP GLOB ~SPWI%spl_level%[0-5][0-9].SPL~ ~override~
    READ_BYTE 0x25 spell_school
    INNER_ACTION BEGIN
      ACTION_IF %spell_school% = 1 AND NOT ~%SOURCE_RES%~ STR_EQ ~SPWI723~ THEN BEGIN // Abjurer, No Improved Chaos Shield
        APPEND ~s!abjur%spl_level%.2da~ ~%SOURCE_RES% %SOURCE_RES% 4~
      END
    END
    BUT_ONLY
END

COPY ~IATweaks\resources\bam\s!abjmab.bam~ ~override~
COPY ~IATweaks\resources\spl\s!abjmas.spl~ ~override~
  SAY NAME1 @6074
  SAY UNIDENTIFIED_DESC @6075

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABMA02.2da~
    row_desc = ~ABJUR_MASTERY~
    level12 = ~GA_S!ABJMAS~
    level18 = ~GA_S!ABJMAS~
    level24 = ~GA_S!ABJMAS~
    level30 = ~GA_S!ABJMAS~
    level36 = ~GA_S!ABJMAS~
END

///////////////// Creatures ////////////////////

// Sorcerous Amon
COPY_EXISTING ~SEVPAT02.cre~ ~override~
  WRITE_SHORT 0x24 47 // HP
  WRITE_SHORT 0x26 47 // HP
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC
  WRITE_BYTE 0x60 0 // Resist Slashing
  WRITE_BYTE 0x61 0 // Resist Crushing
  WRITE_BYTE 0x62 0 // Resist Piercing
  WRITE_BYTE 0x63 0 // Resist Missile
  WRITE_LONG 0x244 0x00000800 // Kit = Invoker

  LPF ~ADD_CRE_EFFECT~ // Sequencer with Flame Arrow
    INT_VAR
      opcode = 256
      target = 1
      resist_dispel = 0
      timing = 9
      parameter3 = 0
    STR_VAR
      effsource = ~SPWIJ01~
      resource = ~SPWI303~
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!IMMUNE~
  END
// Gaius

COPY_EXISTING ~GAIUS.cre~ ~override~
  WRITE_SHORT 0x24 84 // HP
  WRITE_SHORT 0x26 84 // HP
  WRITE_SHORT 0x46 10 // AC
  WRITE_SHORT 0x48 10 // AC
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5a 0 // Resist Cold
  WRITE_BYTE 0x5b 0 // Resist Electricity
  WRITE_BYTE 0x5c 0 // Resist Acid
  WRITE_BYTE 0x5d 0 // Resist Magic
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x5e 0 // Resist Magic Cold
  WRITE_BYTE 0x60 0 // Resist Slashing
  WRITE_BYTE 0x61 0 // Resist Crushing
  WRITE_BYTE 0x62 0 // Resist Piercing
  WRITE_BYTE 0x63 0 // Resist Missile

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 0
  END

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 31
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!IMMUNE~
  END

  ADD_CRE_ITEM ~POTN33~ #0 #0 #0 ~~ ~INV15~

COMPILE ~IATweaks\scripts\creatures\S!GAIUS.BAF~
  PATCH_IF(FILE_EXISTS_IN_GAME ~POTN33.spl~) BEGIN
    ADD_CRE_ITEM ~POTN33~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~INV14~
  END

// Random Encounter Bandit Mage
COPY_EXISTING ~REBAND04.cre~ ~override~
  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!IMMUNE~
  END
