PRINT @5088

SILENT

INCLUDE "%MOD_FOLDER%/lib/components/IA_rebalancing/helper_functions.tph"
INCLUDE "%MOD_FOLDER%/lib/components/IA_rebalancing/helper_functions_GUI.tph"

// Improve thac0 table for Thieves

COPY_EXISTING ~thac0.2da~ ~override~
  REPLACE_EVALUATE
    ~THIEF.*~
    BEGIN
    END
    ~THIEF 20 19 18 18 17 16 16 15 14 14 13 12 12 11 10 10 9 8 8 7 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5~
  REPLACE_EVALUATE
    ~FIGHTER_MAGE_THIEF.*~
    BEGIN
    END
    ~FIGHTER_MAGE_THIEF 20                  19                  18                  17                  16                  15                  14                  13                  12                  11                  10                  9                   8                   7                   6                   5                   4                   3                   2                   1                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0~
  REPLACE_EVALUATE
    ~FIGHTER_THIEF.*~
    BEGIN
    END
    ~FIGHTER_THIEF 20                  19                  18                  17                  16                  15                  14                  13                  12                  11                  10                  9                   8                   7                   6                   5                   4                   3                   2                   1                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0~
  PRETTY_PRINT_2DA

// Enable ** in Short Swords, Daggers and Single Weapon Style for Assassins

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~weapprof.2da~  ~override/weapprof.2da~
  COUNT_2DA_COLS ~colcount~
  SET Assassin_column = $weapprof_cols("ASSASIN")
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SINGLEWEAPON") %Assassin_column% ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("DAGGER") %Assassin_column% ~2~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ $weapprof_rows("SHORTSWORD") %Assassin_column% ~2~
  SET_2DA_ENTRIES_NOW ~_#_#_#weapprof~ ~colcount~
  PRETTY_PRINT_2DA

// HLA tables for Thieves

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~luabbr.2da~
  RET_ARRAY
    luabbr_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~luabbr.2da~  ~override~
  COUNT_2DA_COLS ~colcount~
  READ_2DA_ENTRY $luabbr_rows("ASSASIN") 1 ~colcount~ assassin_hlas_suffix
  PATCH_IF (~%assassin_hlas_suffix%~ STR_EQ ~Th0~) BEGIN
    SET_2DA_ENTRY $luabbr_rows("ASSASIN") 1 ~colcount~ ~S!ASSA~
    PRETTY_PRINT_2DA
  END
  BUT_ONLY

ACTION_IF (~%assassin_hlas_suffix%~ STR_EQ ~Th0~) BEGIN
  COPY_EXISTING ~LUTH0.2da~ ~override/LUS!ASSA.2da~
  SPRINT assassin_hlas_suffix ~S!ASSA~
END

COPY_EXISTING ~luabbr.2da~  ~override~
  COUNT_2DA_COLS ~colcount~
  READ_2DA_ENTRY $luabbr_rows("STALKER") 1 ~colcount~ stalker_hlas_suffix
  PATCH_IF (~%stalker_hlas_suffix%~ STR_EQ ~Ra0~) BEGIN
    SET_2DA_ENTRY $luabbr_rows("STALKER") 1 ~colcount~ ~S!STLK~
    PRETTY_PRINT_2DA
  END
  BUT_ONLY

ACTION_IF (~%stalker_hlas_suffix%~ STR_EQ ~Ra0~) BEGIN
  COPY_EXISTING ~LURA0.2da~ ~override/LUS!STLK.2da~
  SPRINT stalker_hlas_suffix ~S!STLK~
END

// Required checks for Thieving Ability values

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~PICKPOCKET<n~
    stat                  = ~29~
    value                 = ~-1~
    relation              = ~2~
  RET
    pickpocket_lower_than_row = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~SET_TRAPS<n~
    stat                  = ~137~
    value                 = ~-1~
    relation              = ~2~
  RET
    set_traps_lower_than_row = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~DETECT_ILLUSIONS<n~
    stat                  = ~136~
    value                 = ~-1~
    relation              = ~2~
  RET
    detect_illusions_lower_than_row = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~HIDE_IN_SHADOWS<n~
    stat                  = ~135~
    value                 = ~-1~
    relation              = ~2~
  RET
    hide_in_shadows_lower_than_row = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~FIND_TRAPS<n~
    stat                  = ~28~
    value                 = ~-1~
    relation              = ~2~
  RET
    find_traps_lower_than_row = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~STEALTH_STRIKE<n~
    stat                  = ~27~
    value                 = ~-1~
    relation              = ~2~
  RET
    stealth_strike_lower_than_row = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~HIDE_IN_SHADOWS>n~
    stat                  = ~135~
    value                 = ~-1~
    relation              = ~3~
  RET
    hide_in_shadows_higher_than_row = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~HIDE_IN_SHADOWS>=n~
    stat                  = ~135~
    value                 = ~-1~
    relation              = ~4~
  RET
    hide_in_shadows_higher_or_equal_to_row = new_line_number
END

// Disable backstab for Staves

COPY_EXISTING_REGEXP GLOB ~.+\.itm~ ~override~
  READ_SHORT 0x1c item_category
  PATCH_IF (item_category = 26) THEN BEGIN  
    READ_BYTE 0x18 item_flags_1
    PATCH_IF (%item_flags_1% BAND 0b01000000) > 0 BEGIN // If weapon is two-handed
      LPF ~ADD_ITEM_EQEFFECT~
        INT_VAR
          opcode = 263
          target = 1
          timing = 2
          parameter1 = ~-5~
          parameter2 = 0
      END
    END
  END
  BUT_ONLY

// Update Quarterstaff description to inform that they can't backstab

COPY_EXISTING ~weapprof.2da~ ~override~
  SET quarterstaff_weapontype_desc = RESOLVE_STR_REF (@5010)
  REPLACE_TEXTUALLY ~34161~ ~%quarterstaff_weapontype_desc%~
  PRETTY_PRINT_2DA

COPY ~IATweaks\resources\2da\skilldex.2da~ ~override~

// Race thieving bonuses

ACTION_DEFINE_ASSOCIATIVE_ARRAY race_to_thieving_bonuses_mapping BEGIN
  //                       PICK_POCKETS    OPEN_LOCKS      FIND_TRAPS      STEALTH_STRIKE  HIDE_IN_SHADOWS   DETECT_ILLUSION   SET_TRAPS
  ~HUMAN~   =>~HUMAN       15              10              5               5               5                 0                 5~
  ~DWARF~   =>~DWARF       10              10              20              0               0                 5                 10~
  ~ELF~     =>~ELF         20              15              5               5               15                10                0~
  ~GNOME~   =>~GNOME       15              15              15              5               10                20                5~
  ~HALF_ELF~=>~HALF_ELF    25              15              5               10              10                5                 0~
  ~HALFLING~=>~HALFLING    20              20              10              20              20                0                 0~
  ~HALFORC~ =>~HALFORC     10              5               5               5               0                 0                 0~
END

COPY_EXISTING ~skillrac.2da~ ~override~
  PHP_EACH race_to_thieving_bonuses_mapping AS race => race_thieving_bonuses BEGIN
    REPLACE_EVALUATE ~%race%.*~ BEGIN END ~%race_thieving_bonuses%~
  END
  PRETTY_PRINT_2DA

// Lower backstab modifiers to x2

COPY_EXISTING ~backstab.2da~ ~override~
  COUNT_2DA_COLS ~colcount~
  COUNT_2DA_ROWS ~colcount~ ~rowcount~
  FOR (current_column = 2; current_column < %colcount%; ++current_column) BEGIN
    FOR (current_row = 0; current_row < %rowcount%; ++current_row) BEGIN
      READ_2DA_ENTRY %current_row% %current_column% %colcount% current_val
      PATCH_IF %current_val% > 2 BEGIN
        SET_2DA_ENTRY %current_row% %current_column% %colcount% 2
      END
    END
  END
  BUT_ONLY

// Remove additional backstab bonuses to Assassins

COPY_EXISTING ~CLABTH02.2da~ ~override~
  REPLACE_EVALUATE
    ~AP_SPCL332~
    BEGIN
    END
    ~****~
  PRETTY_PRINT_2DA

// Remove starting bonuses from all Thieves, the bonuses will be granted in another form

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clasiskl.2da~
  RET_ARRAY
    clasiskl_columns = 2da_columns_to_ids_mapping
END

COPY_EXISTING ~clasiskl.2da~ ~override~
  COUNT_2DA_COLS ~colcount~
  COUNT_2DA_ROWS ~colcount~ ~rowcount~
  PATCH_FOR_EACH class_kit_name IN ~THIEF~ ~FIGHTER_THIEF~ ~FIGHTER_MAGE_THIEF~ ~MAGE_THIEF~ ~CLERIC_THIEF~ ~ASSASIN~ ~BOUNTY_HUNTER~ ~SWASHBUCKLER~ ~SHADOWDANCER~ BEGIN
    FOR (current_row = 0; current_row < %rowcount%; ++current_row) BEGIN
      SPRINT class_kit_id $clasiskl_columns("%class_kit_name%")
      SET_2DA_ENTRY %current_row% ~%class_kit_id%~ %colcount% 0
    END
  END
  // Increase Dark Moon's Detect Illusions
  SET_2DA_ENTRY 5 $clasiskl_columns("DARK_MOON") %colcount% 20
  PRETTY_PRINT_2DA
  BUT_ONLY

// Rework thieving ability scaling to be either 100 or 0 for all

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~thiefscl.2da~
  RET_ARRAY
    thiefscl_columns = 2da_columns_to_ids_mapping
END

COPY_EXISTING ~thiefscl.2da~ ~override~
  COUNT_2DA_COLS ~colcount~
  COUNT_2DA_ROWS ~colcount~ ~rowcount~
  SET pickpocket_row = 0
  SET stealth_strike_row = 3
  SET detect_illusions_row = 5
  SET set_traps_row = 6
  PATCH_FOR_EACH class_kit_name IN ~RANGER~ ~CLERIC_RANGER~ ~FERALAN~ ~BEASTMASTER~ ~SWASHBUCKLER~ ~MONK~ ~DARK_MOON~ ~SUN_SOUL~ ~VAGRANT~ ~PROTECTOR~ BEGIN
    SET_2DA_ENTRY %stealth_strike_row% $thiefscl_columns("%class_kit_name%") %colcount% 0
  END
  PATCH_FOR_EACH class_kit_name IN ~BARD~ ~BLADE~ ~JESTER~ ~SKALD~ BEGIN
    SET_2DA_ENTRY %pickpocket_row% $thiefscl_columns("%class_kit_name%") %colcount% 100
  END
  SET_2DA_ENTRY %set_traps_row% $thiefscl_columns("SWASHBUCKLER") %colcount% 0
  PRETTY_PRINT_2DA
  BUT_ONLY

// Rework starting and per-level thieving ability points

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~thiefskl.2da~
  RET_ARRAY
    thiefskl_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~thiefskl.2da~ ~override~
  COUNT_2DA_COLS ~colcount~
  COUNT_2DA_ROWS ~colcount~ ~rowcount~
  SET starting_points_column = 1
  SET per_level_points_column = 2
  PATCH_FOR_EACH class_kit_name IN ~THIEF~ ~FIGHTER_THIEF~ ~MAGE_THIEF~ ~CLERIC_THIEF~ ~FIGHTER_MAGE_THIEF~ BEGIN
    SET_2DA_ENTRY $thiefskl_rows("%class_kit_name%") %starting_points_column% %colcount% 40
    SET_2DA_ENTRY $thiefskl_rows("%class_kit_name%") %per_level_points_column% %colcount% 10
  END
  PATCH_FOR_EACH class_kit_name IN ~SHADOWDANCER~ ~ASSASIN~ ~BOUNTY_HUNTER~ BEGIN
    SET_2DA_ENTRY $thiefskl_rows("%class_kit_name%") %starting_points_column% %colcount% 10
    SET_2DA_ENTRY $thiefskl_rows("%class_kit_name%") %per_level_points_column% %colcount% 10
  END
  PATCH_FOR_EACH class_kit_name IN ~MONK~ ~DARK_MOON~ ~SUN_SOUL~ BEGIN
    SET_2DA_ENTRY $thiefskl_rows("%class_kit_name%") %starting_points_column% %colcount% 0
    SET_2DA_ENTRY $thiefskl_rows("%class_kit_name%") %per_level_points_column% %colcount% 5
  END
  SET_2DA_ENTRY $thiefskl_rows("SWASHBUCKLER") %starting_points_column% %colcount% 20
  SET_2DA_ENTRY $thiefskl_rows("SWASHBUCKLER") %per_level_points_column% %colcount% 10
  BUT_ONLY

// Per level bonuses for Rangers, Shamans and Bards

COPY ~IATweaks\resources\spl\s!0ss.spl~ ~override~

ACTION_FOR_EACH kit_that_can_hide_but_not_backstab IN ~CLABRN01~ ~CLABRN02~ ~CLABRN04~ ~VAGRAN~ ~PROTEC~ ~CLABMO01~ ~CLABMO02~ ~CLABMO03~ ~CLABTH04~ BEGIN
  // All kits/classes that can't backstab will get -250 to Stealth Strike at lvl1 to prevent them from gaining bonuses from it
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%kit_that_can_hide_but_not_backstab%.2da~
      row_desc = ~NO_STEALTH_STRIKE~
      level1 = ~AP_S!0SS~
  END
END

COPY ~IATweaks\resources\2da\skillbrd.2da~ ~override~
COPY ~IATweaks\resources\2da\skillrng.2da~ ~override~

// Block real Stealth for every character, so that they can't access vanilla Stealth through some quick button

COPY ~IATweaks\resources\spl\s!disste.spl~ ~override~

ACTION_FOR_EACH kit_that_can_hide IN ~CLABRN01~ ~CLABRN02~ ~CLABRN03~ ~CLABRN04~ ~VAGRAN~ ~PROTEC~ ~CLABMO01~ ~CLABMO02~ ~CLABMO03~ ~CLABTH01~ ~CLABTH02~ ~CLABTH03~ ~CLABTH04~ ~CLABTH05~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%kit_that_can_hide%.2da~
      row_desc = ~NO_REAL_STEALTH_BUTTON~
      level1 = ~AP_S!DISSTE~
  END
END

// Remove bonus detect illusion from Dark Moon Monks

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clasiskl.2da~
  RET_ARRAY
    clasiskl_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clasiskl.2da~
  RET_ARRAY
    clasiskl_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~clasiskl.2da~  ~override~
  COUNT_2DA_COLS ~colcount~
  SET_2DA_ENTRY $clasiskl_rows("DETECT_ILLUSION") $clasiskl_cols("DARK_MOON") ~colcount~ ~0~
  PRETTY_PRINT_2DA

// Stalker

COPY ~IATweaks\resources\bam\s!mfkild.bam~ ~override~

OUTER_SET marked_for_kill_icon_desc_str_ref = RESOLVE_STR_REF (@6194)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %marked_for_kill_icon_desc_str_ref%
  STR_VAR
    bam_file = ~S!MFKILD~
  RET
    marked_for_kill_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\spl\s!mfkill.spl~ ~override~
  SAY NAME1 @6192
  SAY UNIDENTIFIED_DESC @6193
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %marked_for_kill_icon_id%
  END

COPY ~IATweaks\resources\2da\s!mfkill.2da~ ~override~
COPY ~IATweaks\resources\spl\s!mfkild.spl~ ~override~
COPY ~IATweaks\resources\spl\s!mfkile.spl~ ~override~
COPY ~IATweaks\resources\spl\s!mfkilf.spl~ ~override~
  SAY NAME1 @6192
COPY ~IATweaks\resources\spl\s!mfkbas.spl~ ~override~
COPY ~IATweaks\resources\eff\s!mfkill.eff~ ~override~

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABRN03.2da~
    row_desc = ~MARKED_FOR_KILL~
    level1 = ~AP_S!MFKBAS~
END

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LU%stalker_hlas_suffix%.2DA~
    row_desc = ~ASSASSINATION~
    ability = ~GA_SPCL916~
    num_allowed = ~1~
END

// Base thieving stat increasing spells for thief kits

COPY ~IATweaks\resources\spl\s!40his.spl~ ~override~
COPY ~IATweaks\resources\spl\s!40di.spl~ ~override~
COPY ~IATweaks\resources\spl\s!40ss.spl~ ~override~
COPY ~IATweaks\resources\spl\s!40st.spl~ ~override~
COPY ~IATweaks\resources\spl\s!40ft.spl~ ~override~
COPY ~IATweaks\resources\spl\s!40pp.spl~ ~override~
COPY ~IATweaks\resources\spl\s!40ol.spl~ ~override~

////// Thief ///////

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH01.2da~
    row_desc = ~PICK_POCKETS_BONUS~
    level1 = ~AP_S!40PP~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH01.2da~
    row_desc = ~OPEN_LOCKS_BONUS~
    level1 = ~AP_S!40OL~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH03.2da~
    row_desc = ~FIND_TRAPS_BONUS~
    level1 = ~AP_S!40FT~
END

////// Swashbuckler ///////

// Remove traps

COPY_EXISTING ~CLABTH04.2da~ ~override~
  REPLACE_EVALUATE
    ~GA_SPCL412~
    BEGIN
    END
    ~****~
  PRETTY_PRINT_2DA

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH04.2da~
    row_desc = ~PICK_POCKETS_BONUS~
    level1 = ~AP_S!40PP~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH04.2da~
    row_desc = ~OPEN_LOCKS_BONUS~
    level1 = ~AP_S!40OL~
END
// Lower thac0 bonus from 2 to 1

COPY_EXISTING ~SPCLI14.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 278
      parameter1 = 1
  END

////// Assassin ///////

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH02.2da~
    row_desc = ~STEALTH_STRIKE_BONUS~
    level1 = ~AP_S!40SS~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH02.2da~
    row_desc = ~HIDE_IN_SHADOWS_BONUS~
    level1 = ~AP_S!40HIS~
END

////// Bounty Hunter ///////

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH03.2da~
    row_desc = ~SET_TRAPS_BONUS~
    level1 = ~AP_S!40ST~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH03.2da~
    row_desc = ~FIND_TRAPS_BONUS~
    level1 = ~AP_S!40FT~
END

////// Shadowdancer ///////

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH05.2da~
    row_desc = ~DETECT_ILLUSIONS_BONUS~
    level1 = ~AP_S!40DI~
END

LAF ~S!ADD_CLAB_ROW~
  STR_VAR
    filename = ~CLABTH05.2da~
    row_desc = ~HIDE_IN_SHADOWS_BONUS~
    level1 = ~AP_S!40HIS~
END

////// Pick Pockets ///////

COPY ~IATweaks\resources\spl\s!ppbase.spl~ ~override~
COPY ~IATweaks\resources\spl\s!ppthac.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %pickpocket_lower_than_row%
      duration = 5
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 54
      opcode = 284
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      duration_high = 12
  END
COPY ~IATweaks\resources\spl\s!ppacli.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %pickpocket_lower_than_row%
      duration = 1
  END
COPY ~IATweaks\resources\spl\s!ppache.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %pickpocket_lower_than_row%
      duration = 1
  END
COPY ~IATweaks\resources\spl\s!ppcrit.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %pickpocket_lower_than_row%
      duration = 5
  END
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      duration_high = 12
  END
COPY ~IATweaks\resources\spl\s!ppremv.spl~ ~override~
COPY ~IATweaks\resources\eff\s!ppremv.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ppthac.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ppacli.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ppache.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ppcrit.eff~ ~override~

// Add this ability to every class and kit that can use pickpocket at lvl 1

ACTION_FOR_EACH class_kit_which_can_pickpocket IN ~CLABTH01.2da~ ~CLABTH02.2da~ ~CLABTH03.2da~ ~CLABTH04.2da~ ~CLABTH05.2da~ ~CLABBA01.2da~ ~CLABBA02.2da~ ~CLABBA03.2da~ ~CLABBA04.2da~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%class_kit_which_can_pickpocket%~
      row_desc = ~PICKPOCKET_FIGHTING~
      level1 = ~AP_S!PPBASE~
  END
END

//////// HIDE IN SHADOWS ///////

COPY ~IATweaks\resources\bam\s!hisact.bam~ ~override~
COPY ~IATweaks\resources\bam\s!hisdea.bam~ ~override~

OUTER_SET stealth_active_icon_desc_str_ref = RESOLVE_STR_REF (@6077)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %stealth_active_icon_desc_str_ref%
  STR_VAR
    bam_file = ~S!HISACT~
  RET
    stealth_active_icon_id = portrait_icon_id
END

OUTER_SET stealth_disabled_icon_desc_str_ref = RESOLVE_STR_REF (@6078)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %stealth_disabled_icon_desc_str_ref%
  STR_VAR
    bam_file = ~S!HISDEA~
  RET
    stealth_disabled_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\eff\s!hisvis.eff~ ~override~
COPY ~IATweaks\resources\spl\s!hisbas.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %stealth_active_icon_id%
  END
COPY ~IATweaks\resources\spl\s!histry.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %hide_in_shadows_higher_than_row%
      duration = 1
  END
COPY ~IATweaks\resources\spl\s!his100.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %hide_in_shadows_higher_than_row%
      duration = 1
  END

COPY ~IATweaks\resources\spl\s!his101.spl~ ~override/s!his101.spl~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %hide_in_shadows_higher_than_row%
      duration = 1
  END

ADD_PROJECTILE ~IATweaks\resources\pro\s!hisfoe.pro~
COPY ~IATweaks\resources\spl\s!hisfoe.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      projectile = %s!hisfoe%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 326
      parameter1 = %hide_in_shadows_success_state%
      parameter2 = 76 // SPLSTATE = n
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 328
      parameter2 = %hide_in_shadows_success_state%
  END

COPY ~IATweaks\resources\spl\s!hisen1.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 326
      parameter2 = %hide_in_shadows_lower_than_row%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %hide_in_shadows_lower_than_row%
      probability1 = 100
  END

COPY ~IATweaks\resources\spl\s!hisen2.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 326
      parameter2 = %hide_in_shadows_lower_than_row%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %hide_in_shadows_lower_than_row%
      probability1 = 100
      probability2 = 0
  END

COPY ~IATweaks\resources\spl\s!hissnd.spl~ ~override~

ADD_PROJECTILE ~IATweaks\resources\pro\s!hisinv.pro~
COPY ~IATweaks\resources\spl\s!hisin1.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      projectile = %s!hisinv%
  END
COPY ~IATweaks\resources\spl\s!hisin2.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      projectile = %s!hisinv%
  END
COPY ~IATweaks\resources\spl\s!hisin3.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      projectile = %s!hisinv%
  END

// Main spell with Stealth bonuses

COPY ~IATweaks\resources\spl\s!hisinv.spl~ ~override~
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      projectile = %s!hisinv%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 328
      parameter2 = %hide_in_shadows_success_state%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %stealth_active_icon_id%
  END

COPY ~IATweaks\resources\spl\s!hisdmg.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter1 = 13
      parameter2 = %stealth_strike_lower_than_row%
  END
  PATCH_FOR_EACH stealth_strike_value IN 25 38 50 63 75 88 100 110 120 130 140 150 160 170 180 190 200 208 216 224 232 240 248 256 264 272 280 288 296 304 312 320 328 336 344 352 360 BEGIN
    LPF ~CLONE_EFFECT~
      INT_VAR
        multi_match = 1
        match_opcode = 318
        parameter1 = stealth_strike_value
      STR_VAR
        insert = ~last~
    END
    LPF ~CLONE_EFFECT~
      INT_VAR
        multi_match = 1
        match_opcode = 285
      STR_VAR
        insert = ~last~
    END
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      multi_match = 1
      match_opcode = 318
      parameter1 = 0
      parameter2 = 143
    STR_VAR
      insert = ~first~
  END

ACTION_DEFINE_ASSOCIATIVE_ARRAY hide_in_shadows_value_to_cooldown_mapping BEGIN
  110 => 88
  120 => 87
  130 => 85
  140 => 84
  150 => 82
  160 => 81
  170 => 79
  180 => 78
  190 => 76
  200 => 75
  205 => 73
  210 => 72
  215 => 70
  220 => 69
  225 => 67
  230 => 66
  235 => 64
  240 => 63
  245 => 61
  250 => 60
  255 => 58
  260 => 57
  265 => 55
  270 => 54
  275 => 52
  280 => 51
  285 => 49
  290 => 48
  295 => 46
  300 => 45
  305 => 43
  310 => 42
  315 => 40
  320 => 39
  325 => 37
  330 => 36
  335 => 34
  340 => 33
  345 => 31
  350 => 30
  355 => 28
  360 => 27
  365 => 25
  370 => 24
END

COPY ~IATweaks\resources\eff\s!hisrem.eff~ ~override~
COPY ~IATweaks\resources\spl\s!hisrem.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %stealth_disabled_icon_id%
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 328
      parameter2 = %hide_in_shadows_fail_state%
  END
  PHP_EACH hide_in_shadows_value_to_cooldown_mapping AS his_value=>cooldown_in_ticks BEGIN
    LPF ~ADD_SPELL_EFFECT~
      INT_VAR
        opcode = 318
        target = 1
        parameter1 = %his_value%
        parameter2 = %hide_in_shadows_higher_or_equal_to_row%
        duration = 1
        insert_point = 0
      STR_VAR
        resource = ~S!HISREM~
    END
    LPF ~CLONE_EFFECT~
      INT_VAR
        match_opcode = 328
        duration = %cooldown_in_ticks%
        multi_match = 1
      STR_VAR
        insert = ~first~
    END
    LPF ~CLONE_EFFECT~
      INT_VAR
        match_opcode = 142
        duration = %cooldown_in_ticks%
        multi_match = 1
      STR_VAR
        insert = ~first~
    END
  END
  PATCH_FOR_EACH spell_to_remove IN ~S!HISINV~ ~S!HIS101~ ~S!HIS100~ ~S!HISFOE~ ~S!HISTRY~ ~S!HISBAS~ ~S!HISDMG~ BEGIN
    LPF ~ADD_SPELL_EFFECT~
      INT_VAR
        opcode = 321
        target = 1
        insert_point = 0
      STR_VAR
        resource = EVAL ~%spell_to_remove%~
    END
  END
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 206
      target = 1
      duration = 1
      insert_point = 0
    STR_VAR
      resource = ~S!HISINV~
  END
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 267
      target = 1
      duration = 1
      parameter1 = 17120 // HiS Failed
      insert_point = 0
  END
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 139
      target = 1
      parameter1 = 17120 // HiS Failed
      insert_point = 0
  END
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      opcode = 174
      target = 1
      insert_point = 0
    STR_VAR
      resource = ~ACT_07~
  END

COPY_EXISTING ~s!hisrem.spl~ ~override/s!hisre2.spl~
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 174
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 139
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 206
    STR_VAR
      match_resource = ~S!HISINV~
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
    STR_VAR
      match_resource = ~S!HISREM~
      resource = ~S!HISRE2~
  END

COPY_EXISTING ~s!hisre2.spl~ ~override/s!hisre3.spl~
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      target = 1
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      target = 2
  END

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~
  LPF ~CLONE_EFFECT~
    INT_VAR
      silent = 1
      multi_match = 1
      match_opcode = 220
      match_parameter2 = 5 // Illusionist
      opcode = 326
      parameter1 = %hide_in_shadows_success_state%
      parameter2 = 76 // SPLSTATE = n
    STR_VAR
      insert = ~below~
      resource = ~S!HISRE3~
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      silent = 1
      multi_match = 1
      match_opcode = 221
      match_parameter2 = 3 // Illusionary Protections
      opcode = 326
      parameter1 = %hide_in_shadows_success_state%
      parameter2 = 76 // SPLSTATE = n
    STR_VAR
      insert = ~below~
      resource = ~S!HISRE3~
  END
  BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~
  LPF ~CLONE_EFFECT~
    INT_VAR
      silent = 1
      multi_match = 1
      match_opcode = 220
      match_parameter2 = 5 // Illusionist
      opcode = 326
      parameter1 = %hide_in_shadows_success_state%
      parameter2 = 76 // SPLSTATE = n
    STR_VAR
      insert = ~below~
      resource = ~S!HISRE3~
  END
  LPF ~CLONE_EFFECT~
    INT_VAR
      silent = 1
      multi_match = 1
      match_opcode = 221
      match_parameter2 = 3 // Illusionary Protections
      opcode = 326
      parameter1 = %hide_in_shadows_success_state%
      parameter2 = 76 // SPLSTATE = n
    STR_VAR
      insert = ~below~
      resource = ~S!HISRE3~
  END
  BUT_ONLY

// Ensure that Hide in Shadows sound ID is present in .IDS file

OUTER_PATCH 0 BEGIN
  LOOKUP_IDS_SYMBOL_OF_INT his_sound_id ~SOUNDOFF~ 70
END

ACTION_IF ~%his_sound_id%~ STR_EQ ~70~ BEGIN
  APPEND ~SOUNDOFF.ids~ ~70 HIDDEN_IN_SHADOWS~
END

// Ensure that Hide in Shadows character sound is said only once

<<<<<<<<.../IATweaks-inlined/hide_in_shadows_sound.baf
IF
    NextTriggerObject(Player1)
	Global("S!HISSND","LOCALS",1)
THEN
	RESPONSE #100
		VerbalConstant(Player1,HIDDEN_IN_SHADOWS)
		ReallyForceSpellRES("S!HISSND",Player1)
END

IF
    NextTriggerObject(Player2)
	Global("S!HISSND","LOCALS",1)
THEN
	RESPONSE #100
		VerbalConstant(Player2,HIDDEN_IN_SHADOWS)
		ReallyForceSpellRES("S!HISSND",Player2)
END

IF
    NextTriggerObject(Player3)
	Global("S!HISSND","LOCALS",1)
THEN
	RESPONSE #100
		VerbalConstant(Player3,HIDDEN_IN_SHADOWS)
		ReallyForceSpellRES("S!HISSND",Player3)
END

IF
    NextTriggerObject(Player4)
	Global("S!HISSND","LOCALS",1)
THEN
	RESPONSE #100
		VerbalConstant(Player4,HIDDEN_IN_SHADOWS)
		ReallyForceSpellRES("S!HISSND",Player4)
END

IF
    NextTriggerObject(Player5)
	Global("S!HISSND","LOCALS",1)
THEN
	RESPONSE #100
		VerbalConstant(Player5,HIDDEN_IN_SHADOWS)
		ReallyForceSpellRES("S!HISSND",Player5)
END

IF
    NextTriggerObject(Player6)
	Global("S!HISSND","LOCALS",1)
THEN
	RESPONSE #100
		VerbalConstant(Player6,HIDDEN_IN_SHADOWS)
		ReallyForceSpellRES("S!HISSND",Player6)
END
>>>>>>>>

EXTEND_TOP "baldur.bcs" ".../IATweaks-inlined/hide_in_shadows_sound.baf"
EXTEND_TOP "baldur25.bcs" ".../IATweaks-inlined/hide_in_shadows_sound.baf"

///////// DETECT ILLUSIONS ///////////

COPY ~IATweaks\resources\spl\s!dibase.spl~ ~override~
COPY ~IATweaks\resources\spl\s!diillu.spl~ ~override~
COPY ~IATweaks\resources\eff\s!dinorm.eff~ ~override~
COPY ~IATweaks\resources\spl\s!dinorm.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %detect_illusions_lower_than_row%
  END
COPY ~IATweaks\resources\eff\s!disavt.eff~ ~override~
COPY ~IATweaks\resources\spl\s!disavt.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %detect_illusions_lower_than_row%
  END
COPY ~IATweaks\resources\eff\s!dimres.eff~ ~override~
COPY ~IATweaks\resources\spl\s!dimres.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = %detect_illusions_lower_than_row%
  END

// Add this ability to every class and kit that can use detect illusions at lvl 1

ACTION_FOR_EACH class_kit_which_can_detect_illusions IN ~CLABTH01.2da~ ~CLABTH02.2da~ ~CLABTH03.2da~ ~CLABTH04.2da~ ~CLABTH05.2da~ ~CLABMO02~ ~CLABSH01~ BEGIN
  LAF ~S!ADD_CLAB_ROW~
    STR_VAR
      filename = ~%class_kit_which_can_detect_illusions%~
      row_desc = ~PASSIVE_DETECT_ILLUSIONS~
      level1 = ~AP_S!DIBASE~
  END
END

//////// Thieving for various creatures /////////

// Add repeating effects for Pickpocket and Detect Illusions to all creatures that have proper class/kit

COPY_EXISTING_REGEXP GLOB ~.+\.cre~ ~override~
  READ_LONG 0x244 cre_kit
  READ_BYTE 0x273 cre_class
  // Pickpocket
  PATCH_IF %cre_class% == 4 OR %cre_class% == 5 OR %cre_class% == 9 OR %cre_class% == 10 OR %cre_class% == 13 OR %cre_class% == 15 BEGIN
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 146
        target = 1
        parameter2 = 1
        timing = 9
        resist_dispel = 0
      STR_VAR
        resource = ~S!PPBASE~
        effsource = ~S!PPBASE~
    END
  END
  // Detect Illusionsx
  PATCH_IF %cre_class% == 4 OR %cre_class% == 9 OR %cre_class% == 10 OR %cre_class% == 13 OR %cre_class% == 15 OR %cre_class% == 21 OR %cre_kit% == 1076101120 BEGIN
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 146
        target = 1
        parameter2 = 1
        timing = 9
        resist_dispel = 0
      STR_VAR
        resource = ~S!DIBASE~
        effsource = ~S!DIBASE~
    END
  END
  BUT_ONLY

// Rework Thieving Skills for companions

COPY_EXISTING ~jan8.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 13 BEGIN // If Mage-Thief
    // 110 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 30 // Detect Illusions
    WRITE_BYTE 0x65 15 // Set Traps
    WRITE_BYTE 0x67 20 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 45 // Find Traps
    WRITE_BYTE 0x6a 0 // Pick Pockets
  END

COPY_EXISTING ~jan8.cre~ ~override/jan10.cre~
COPY_EXISTING ~jan8.cre~ ~override/jan11.cre~
COPY_EXISTING ~jan8.cre~ ~override/jan12.cre~

COPY_EXISTING ~jan15.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 13 BEGIN // If Mage-Thief
    // 150 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 55 // Detect Illusions
    WRITE_BYTE 0x65 25 // Set Traps
    WRITE_BYTE 0x67 20 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 50 // Find Traps
    WRITE_BYTE 0x6a 0 // Pick Pockets
  END

COPY_EXISTING ~nalia8.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 13 BEGIN // If Mage-Thief
    // 70 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 0 // Set Traps
    WRITE_BYTE 0x67 30 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 40 // Find Traps
    WRITE_BYTE 0x6a 0 // Pick Pockets
  END

COPY_EXISTING ~nalia8.cre~ ~override/nalia10.cre~
COPY_EXISTING ~nalia8.cre~ ~override/nalia11.cre~
COPY_EXISTING ~nalia8.cre~ ~override/nalia13.cre~
COPY_EXISTING ~nalia8.cre~ ~override/nalia15.cre~

COPY_EXISTING ~nalia18.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 13 BEGIN // If Mage-Thief
    // 70 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 0 // Set Traps
    WRITE_BYTE 0x67 30 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 40 // Find Traps
    WRITE_BYTE 0x6a 0 // Pick Pockets
  END

COPY_EXISTING ~yoshi7.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 4 BEGIN // If Thief
    // 100 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 50 // Set Traps
    WRITE_BYTE 0x67 0 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 50 // Find Traps
    WRITE_BYTE 0x6a 0 // Pick Pockets
  END

COPY_EXISTING ~yoshi7.cre~ ~override/yoshi8.cre~
COPY_EXISTING ~yoshi7.cre~ ~override/yoshi10.cre~
COPY_EXISTING ~yoshi7.cre~ ~override/yoshi11.cre~
COPY_EXISTING ~yoshi7.cre~ ~override/yoshi12.cre~

COPY_EXISTING ~ohhex8.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 4 BEGIN // If Thief
    // 90 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 0 // Set Traps
    WRITE_BYTE 0x67 30 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 60 // Find Traps
    WRITE_BYTE 0x6a 0 // Pick Pockets
  END

COPY_EXISTING ~ohhex8.cre~ ~override/ohhex9.cre~
COPY_EXISTING ~ohhex8.cre~ ~override/ohhex10.cre~
COPY_EXISTING ~ohhex8.cre~ ~override/ohhex11.cre~
COPY_EXISTING ~ohhex8.cre~ ~override/ohhex13.cre~
COPY_EXISTING ~ohhex8.cre~ ~override/ohhex15.cre~

COPY_EXISTING ~ohhex25.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 4 BEGIN // If Thief
    // 160 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 0 // Set Traps
    WRITE_BYTE 0x67 40 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 40 // Find Traps
    WRITE_BYTE 0x6a 80 // Pick Pockets
  END

COPY_EXISTING ~ohhfak8.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 4 BEGIN // If Thief
    // 110 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 0 // Set Traps
    WRITE_BYTE 0x67 50 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 60 // Find Traps
    WRITE_BYTE 0x6a 0 // Pick Pockets
  END

COPY_EXISTING ~ohhfak8.cre~ ~override/ohhfak9.cre~
COPY_EXISTING ~ohhfak8.cre~ ~override/ohhfak10.cre~
COPY_EXISTING ~ohhfak8.cre~ ~override/ohhfak11.cre~
COPY_EXISTING ~ohhfak8.cre~ ~override/ohhfak13.cre~
COPY_EXISTING ~ohhfak8.cre~ ~override/ohhfak15.cre~

COPY_EXISTING ~s!sibel.cre~ ~override~
  READ_BYTE 0x273 current_class
  PATCH_IF %current_class% == 4 BEGIN // If Thief
    // 100 points to distribute
    WRITE_BYTE 0x45 0 // Hide in Shadows
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 0 // Set Traps
    WRITE_BYTE 0x67 45 // Open Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 45 // Find Traps
    WRITE_BYTE 0x6a 10 // Pick Pockets
  END
  IF_EXISTS

COPY_EXISTING ~s!sibe25.cre~ ~override~
  READ_BYTE 0x273 current_class
  // 100 points to distribute
  WRITE_BYTE 0x45 0 // Hide in Shadows
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 45 // Open Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 45 // Find Traps
  WRITE_BYTE 0x6a 10 // Pick Pockets
  IF_EXISTS

COPY_EXISTING ~rasaad8.cre~ ~override~
  // 40 points to distribute
  WRITE_BYTE 0x45 40 // Hide in Shadows
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Open Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 0 // Pick Pockets

COPY_EXISTING ~rasaad8.cre~ ~override/rasaad9.cre~
COPY_EXISTING ~rasaad8.cre~ ~override/rasaad10.cre~
COPY_EXISTING ~rasaad8.cre~ ~override/rasaad11.cre~
COPY_EXISTING ~rasaad8.cre~ ~override/rasaad13.cre~

COPY_EXISTING ~rasaad12.cre~ ~override~
  // 65 points to distribute
  WRITE_BYTE 0x45 65 // Hide in Shadows
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Open Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 0 // Pick Pockets

//////// GUI part of the mod /////////

COPY ~IATweaks\resources\lua\M_thief.lua~ ~override~

// New name for Move Silently

COPY_EXISTING ~enginest.2da~ ~override~
  SET silent_strike_gui_strref = RESOLVE_STR_REF (@5011)
  REPLACE_TEXTUALLY ~STRREF_GUI_MIXED_MOVE_SILENTLY[ %TAB%]*[0-9]+~ ~STRREF_GUI_MIXED_MOVE_SILENTLY %silent_strike_gui_strref%~
  PRETTY_PRINT_2DA

// New descriptions for Thieving Abilities

COPY_EXISTING ~enginest.2da~ ~override~
  SET pick_pocket_desc_gui_strref = RESOLVE_STR_REF (@5012)
  SET hide_in_shadows_desc_gui_strref = RESOLVE_STR_REF (@5013)
  SET silent_strike_desc_gui_strref = RESOLVE_STR_REF (@5014)
  SET detect_illusions_desc_gui_strref = RESOLVE_STR_REF (@5015)
  // SET find_traps_desc_gui_strref = RESOLVE_STR_REF (@5016)
  // SET set_traps_desc_gui_strref = RESOLVE_STR_REF (@5017)
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_PICK_POCKETS[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_PICK_POCKETS %pick_pocket_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_HIDE_IN_SHADOWS[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_HIDE_IN_SHADOWS %hide_in_shadows_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_MOVE_SILENTLY[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_MOVE_SILENTLY %silent_strike_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_DETECT_ILLUSION[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_DETECT_ILLUSION %detect_illusions_desc_gui_strref%~
  // REPLACE_TEXTUALLY ~STRREF_GUI_HELP_DETECT_TRAPS[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_DETECT_TRAPS %find_traps_desc_gui_strref%~
  // REPLACE_TEXTUALLY ~STRREF_GUI_HELP_SET_TRAPS[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_SET_TRAPS %set_traps_desc_gui_strref%~
  PRETTY_PRINT_2DA

// Update race description

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~racetext.2da~
  RET_ARRAY
    racetext_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~racetext.2da~
  RET_ARRAY
    racetext_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~racetext.2da~ ~override~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $racetext_cols("DESCSTR")
  SET_2DA_ENTRY_LATER ~s!race_desc~ $racetext_rows("HUMAN") description_col RESOLVE_STR_REF (@5032)
  SET_2DA_ENTRY_LATER ~s!race_desc~ $racetext_rows("DWARF") description_col RESOLVE_STR_REF (@5033)
  SET_2DA_ENTRY_LATER ~s!race_desc~ $racetext_rows("ELF") description_col RESOLVE_STR_REF (@5034)
  SET_2DA_ENTRY_LATER ~s!race_desc~ $racetext_rows("GNOME") description_col RESOLVE_STR_REF (@5035)
  SET_2DA_ENTRY_LATER ~s!race_desc~ $racetext_rows("HALFLING") description_col RESOLVE_STR_REF (@5036)
  SET_2DA_ENTRY_LATER ~s!race_desc~ $racetext_rows("HALF_ELF") description_col RESOLVE_STR_REF (@5037)
  SET_2DA_ENTRY_LATER ~s!race_desc~ $racetext_rows("HALF_ORC") description_col RESOLVE_STR_REF (@5038)
  SET_2DA_ENTRIES_NOW ~s!race_desc~ ~colcount~
  PRETTY_PRINT_2DA

COPY_EXISTING ~enginest.2da~ ~override~
  SET human_race_desc_gui_strref = RESOLVE_STR_REF (@5032)
  SET dwarf_race_desc_gui_strref = RESOLVE_STR_REF (@5033)
  SET elf_race_desc_gui_strref = RESOLVE_STR_REF (@5034)
  SET gnome_race_desc_gui_strref = RESOLVE_STR_REF (@5035)
  SET halfling_race_desc_gui_strref = RESOLVE_STR_REF (@5036)
  SET half_elf_race_desc_gui_strref = RESOLVE_STR_REF (@5037)
  SET half_orc_race_desc_gui_strref = RESOLVE_STR_REF (@5038)
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_HUMAN[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_HUMAN %human_race_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_DWARF[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_DWARF %dwarf_race_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_ELF[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_ELF %elf_race_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_GNOME[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_GNOME %gnome_race_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_HALFLING[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_HALFLING %halfling_race_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_HALF_ELF[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_HALF_ELF %half_elf_race_desc_gui_strref%~
  REPLACE_TEXTUALLY ~STRREF_GUI_HELP_HALFORC[ %TAB%]*[0-9]+~ ~STRREF_GUI_HELP_HALFORC %half_orc_race_desc_gui_strref%~
  PRETTY_PRINT_2DA

// New UI functionalities

COPY_EXISTING ~UI.MENU~ ~override~
  LPF ~S!GENERATE_AND_INSERT_THIEVING_BUTTON_FUNCTIONS~
  END
  LPF ~S!APPLY_IA_LOGIC_TO_THIEVING_ABILITIES~
  END
  LPF ~S!5POINTS_PER_CLICK_THIEVING_ABILITIES~
  END
  LPF ~S!GENERATE_AND_INSERT_STEALTH_BUTTON_FUNCTIONS~
    INT_VAR
      stealth_active_icon_id = %stealth_active_icon_id%
      stealth_disabled_icon_id = %stealth_disabled_icon_id%
  END
  LPF ~S!CREATE_NEW_STEALTH_BUTTONS~
  END
  LPF ~S!READ_AND_PUT_NEEDED_VARIABLES_IN_M_THIEF_LUA~
  END
  LPF ~S!SHOW_BASE_THIEVING_ABILITIES_ON_CHARGEN_SCREEN~
  END


// Make all armors that disable Thieving abilities protect from new stuff

COPY ~IATweaks\resources\eff\s!icsdis.eff~ ~override~
  WRITE_LONG 0x20 %stealth_disabled_icon_id%

COPY_EXISTING_REGEXP GLOB ~.+\.itm~ ~override~
  READ_SHORT 0x1c item_category
  PATCH_IF (item_category = 2) OR (item_category = 60) OR (item_category = 61) OR (item_category = 62) OR (item_category = 63) OR (item_category = 64) OR (item_category = 65) OR (item_category = 66)
    THEN BEGIN
      LPF ~S!ITEM_USES_OPCODE~
        INT_VAR
          check_globals  = 1
          check_headers  = 0
          match_opcode   = 144
          match_param2   = 0
        RET
          is_found
      END
      PATCH_IF ~%is_found%~ STR_EQ ~TRUE~ BEGIN
        LPF ~ADD_ITEM_EQEFFECT~
          INT_VAR
            opcode = 206
            target = 1
            timing = 2
          STR_VAR
            resource = ~S!PPACHE~
        END
        LPF ~ADD_ITEM_EQEFFECT~
          INT_VAR
            opcode = 206
            target = 1
            timing = 2
          STR_VAR
            resource = ~S!HISBAS~
        END
        PATCH_FOR_EACH thief_class IN 4 9 10 12 13 15 18 BEGIN
          LPF ~ADD_ITEM_EQEFFECT~
            INT_VAR
              opcode = 177 
              target = 1
              timing = 2
              parameter1 = thief_class
              parameter2 = 5
            STR_VAR
              resource = ~S!ICSDIS~
          END
        END
        LPF ~ADD_ITEM_EQEFFECT~
          INT_VAR
            opcode = 328
            target = 1
            timing = 2
            parameter2 = %hide_in_shadows_fail_state%
            special = 1
        END
      END
  END
  BUT_ONLY

/////// AREAS ////////

// Lower lock and trap difficulty in Chateau Irenicus

COPY_EXISTING_REGEXP GLOB ~AR060[1-3]\.are$~ ~override~

  // process triggers //

  GET_OFFSET_ARRAY regions ARE_V10_REGIONS

  PHP_EACH regions AS int1 => region_off BEGIN
    READ_SHORT region_off + 0x68 trap_det_diff // trap detection difficulty
    READ_SHORT region_off + 0x6a trap_rem_diff // trap removal difficulty

    PATCH_IF ((trap_rem_diff > 25) AND (trap_det_diff < 100)) BEGIN
      WRITE_SHORT  region_off + 0x68 20 // trap detection difficulty
      WRITE_SHORT  region_off + 0x6a 25 // trap detection difficulty
    END
  END

  // process containers //

  GET_OFFSET_ARRAY containers ARE_V10_CONTAINERS

  PHP_EACH containers AS int2 => cont_off BEGIN
    READ_ASCII cont_off + 0x78 key // key item
    READ_SHORT cont_off + 0x26 lock_diff // lock difficulty
    READ_SHORT cont_off + 0x2c trap_det_diff // trap detection difficulty
    READ_SHORT cont_off + 0x2e trap_rem_diff // trap removal difficulty

    PATCH_IF (("%key%" STRING_COMPARE_CASE "" = 0) OR ("%key%" STRING_COMPARE_CASE "None" = 0)) BEGIN
      PATCH_IF (lock_diff > 25 AND lock_diff < 100) BEGIN
        WRITE_SHORT cont_off + 0x26 25 // lock difficulty
      END
    END

    PATCH_IF ((trap_det_diff < 100) AND (trap_rem_diff > 25)) BEGIN
      WRITE_SHORT  cont_off + 0x2c 20 // trap detection difficulty
      WRITE_SHORT  cont_off + 0x2e 25 // trap detection difficulty
    END
  END

////// HLAs ///////

// Make Avoid Death undispellable and last for 1 turn

COPY_EXISTING ~spcl917.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6079
  WRITE_BYTE 0x25 0 // No primary type
  WRITE_BYTE 0x27 0 // No secondary type
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      resist_dispel = 2
      duration_high = 60
  END

// Make Evasion undispellable and last for 6 rounds

COPY_EXISTING ~spcl913.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6080
  WRITE_BYTE 0x25 0 // No primary type
  WRITE_BYTE 0x27 0 // No secondary type
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      resist_dispel = 2
      duration_high = 36
  END

// Make Greater Evasion undispellable and last for 1 turn

COPY_EXISTING ~spcl914.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6081
  WRITE_BYTE 0x25 0 // No primary type
  WRITE_BYTE 0x27 0 // No secondary type
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      match_opcode = ~-1~
      resist_dispel = 2
      duration_high = 60
  END

// Make Extend Lifespan add 10HP and allow it to be picked only 3 times

COPY_EXISTING ~SPCLI27.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6184
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 18
      parameter1 = 10
  END

COPY_EXISTING_REGEXP GLOB ~LU.*\.2da~ ~override~
  COUNT_2DA_COLS ~colcount~
  COUNT_2DA_ROWS ~colcount~ ~rowcount~
  FOR (i = 0; i < ~rowcount~; ++i) BEGIN
    READ_2DA_ENTRY i 1 %colcount% current_val
    PATCH_IF (~%current_val%~ STR_EQ ~AP_SPCLI27~) BEGIN
      SET_2DA_ENTRY i 6 ~colcount~ 3
    END
  END
  BUT_ONLY

// Rework Assassination

COPY_EXISTING ~SPCL916.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6185
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      duration_high = 30
  END
  FOR (i = 1; i <= 15; ++i) BEGIN
    LPF ~ADD_SPELL_EFFECT~
      INT_VAR
        insert_point = ~-1~
        opcode = 321
        target = 1
        duration = 30
        timing = 3
      STR_VAR
        resource = EVAL ~S!ASSA%i%~
    END
  END
  FOR (i = 15; i >= 1; --i) BEGIN
    LPF ~ADD_SPELL_EFFECT~
      INT_VAR
        insert_point = 0
        opcode = 321
        target = 1
        timing = 0
      STR_VAR
        resource = EVAL ~S!ASSA%i%~
    END
  END
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      insert_point = ~-1~
      opcode = 326
      parameter1 = 16394 // Assassin
      parameter2 = kit_equals_row
      target = 1
      resist_dispel = 0
      duration = 30
      timing = 0
    STR_VAR
      resource = ~S!ASSA15~
  END
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      insert_point = ~-1~
      opcode = 318
      parameter1 = 16394 // Assassin
      parameter2 = kit_equals_row
      target = 1
      resist_dispel = 0
      timing = 0
    STR_VAR
      resource = ~SPCL916~
  END
  LPF ~ADD_SPELL_EFFECT~
    INT_VAR
      insert_point = ~-1~
      opcode = 146
      parameter2 = 1
      target = 1
      resist_dispel = 0
      duration = 30
      timing = 0
    STR_VAR
      resource = ~S!ASSA10~
  END

COPY ~IATweaks\resources\spl\s!assa1.spl~ ~override~
COPY ~IATweaks\resources\spl\s!assa15.spl~ ~override~
COPY ~IATweaks\resources\eff\s!assa15.eff~ ~override~

OUTER_FOR (i=14;i>=2;--i) BEGIN
  OUTER_SET j = i + 1
  OUTER_SET k = i - 1
  COPY_EXISTING ~s!assa15.spl~ ~override/s!assa%i%.spl~
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 321
      STR_VAR
        resource = EVAL ~S!ASSA%j%~
    END
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 248
      STR_VAR
        resource = EVAL ~S!ASSA%i%~
    END

COPY_EXISTING ~s!assa15.eff~ ~override/s!assa%i%.eff~
    WRITE_ASCIIE 0x30 ~S!ASSA%k%~ #8
END

// Rework Scribe Scrolls to grant 3 scrolls at the same time

COPY ~IATweaks\resources\itm\s!sscrl2.itm~ ~override~
COPY ~IATweaks\resources\itm\s!sscrl3.itm~ ~override~
COPY ~IATweaks\resources\itm\s!sscrl4.itm~ ~override~

COPY_EXISTING ~spcl919.spl~ ~override~
  SAY UNIDENTIFIED_DESC @6086
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 122
      timing = 0
      duration = 1200
      probability1 = 100
      probability2 = 0
    STR_VAR
      match_resource = ~S!SCRL20~
      resource = ~S!SSCRL2~
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 122
      timing = 0
      duration = 1200
      probability1 = 100
      probability2 = 0
    STR_VAR
      match_resource = ~S!SCRL15~
      resource = ~S!SSCRL3~
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 122
      timing = 0
      duration = 1200
      probability1 = 100
      probability2 = 0
    STR_VAR
      match_resource = ~S!SCRL19~
      resource = ~S!SSCRL4~
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 122
    STR_VAR
      match_resource = ~S!SCRL18~
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 122
    STR_VAR
      match_resource = ~S!SCRL14~
  END

// Analyze Opponent

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~CAN_BE_BACKSTABBED~
    stat                  = ~175~
    value                 = 0
    relation              = ~1~
  RET
    can_be_backstabbed = new_line_number
END

COPY ~IATweaks\resources\bam\s!analyb.bam~ ~override~
COPY ~IATweaks\resources\spl\s!analyz.spl~ ~override~
  SAY NAME1 @6182
  SAY UNIDENTIFIED_DESC @6183
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      parameter2 = can_be_backstabbed
  END

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LU%assassin_hlas_suffix%.2DA~
    row_desc = ~ANALYZE_OPPONENT~
    ability = ~GA_S!ANALYZ~
    prerequisite = ~GA_SPCL916~ // Assassination
    num_allowed = ~3~
END

// Ghost's Grace

OUTER_SET ghost_grace_icon_desc_str_ref = RESOLVE_STR_REF (@6180)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %ghost_grace_icon_desc_str_ref%
  STR_VAR
    bam_file = ~S!GGRACD~
  RET
    ghost_grace_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\bam\s!ggracb.bam~ ~override~
COPY ~IATweaks\resources\bam\s!ggracd.bam~ ~override~
COPY ~IATweaks\resources\spl\s!ggracd.spl~ ~override~
COPY ~IATweaks\resources\spl\s!ggrace.spl~ ~override~
  SAY NAME1 @6180
  SAY UNIDENTIFIED_DESC @6181
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %ghost_grace_icon_id%
  END

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LU%assassin_hlas_suffix%.2DA~
    row_desc = ~GHOST_GRACE~
    ability = ~GA_S!GGRACE~
    num_allowed = ~3~
END

// Straight Through the Heart

OUTER_SET straight_through_the_heart_icon_desc_str_ref = RESOLVE_STR_REF (@6190)
LAF ~S!ADD_PORTRAIT_ICON~
  INT_VAR
    description_str_ref = %straight_through_the_heart_icon_desc_str_ref%
  STR_VAR
    bam_file = ~S!HEARTD~
  RET
    straight_through_the_heartt_icon_id = portrait_icon_id
END

COPY ~IATweaks\resources\bam\s!heartb.bam~ ~override~
COPY ~IATweaks\resources\bam\s!heartd.bam~ ~override~
COPY ~IATweaks\resources\spl\s!heart.spl~ ~override~
  SAY NAME1 @6190
  SAY UNIDENTIFIED_DESC @6191
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 142
      parameter2 = %straight_through_the_heartt_icon_id%
  END

COPY ~IATweaks\resources\spl\s!heart1.spl~ ~override~
COPY ~IATweaks\resources\eff\s!heart1.eff~ ~override~

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LU%assassin_hlas_suffix%.2DA~
    row_desc = ~STRAIGHT_THROUGH_HEART~
    ability = ~GA_S!HEART~
    prerequisite = ~GA_SPCL916~ // Assassination
    num_allowed = ~1~
END

LAF ~S!ADD_HLA_ROW~
  STR_VAR
    filename = ~LUTH0.2DA~
    row_desc = ~STRAIGHT_THROUGH_HEART~
    ability = ~GA_S!HEART~
    prerequisite = ~GA_SPCL916~ // Assassination
    num_allowed = ~1~
END

// Class and Kit description

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~clastext.2da~
  RET_ARRAY
    clastext_rows = 2da_rows_to_ids_mapping
END

// update class description for Thieves
COPY_EXISTING ~clastext.2da~ ~override/clastext.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $clastext_cols("DESCSTR")
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $clastext_rows("THIEF") description_col RESOLVE_STR_REF (@5024)
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $clastext_rows("ASSASSIN") description_col RESOLVE_STR_REF (@5025)
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $clastext_rows("BOUNTY_HUNTER") description_col RESOLVE_STR_REF (@5026)
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $clastext_rows("SWASHBUCKLER") description_col RESOLVE_STR_REF (@5027)
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $clastext_rows("SHADOWDANCER") description_col RESOLVE_STR_REF (@5028)
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $clastext_rows("STALKER") description_col RESOLVE_STR_REF (@5039)
  SET_2DA_ENTRIES_NOW ~s!thief_desc~ ~colcount~
  PRETTY_PRINT_2DA

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  INT_VAR
    col_with_names = 1
  STR_VAR
    2da_table_name = ~kitlist.2da~
  RET_ARRAY
    kitlist_rows = 2da_rows_to_ids_mapping
END

COPY_EXISTING ~kitlist.2da~ ~override/kitlist.2da~
  COUNT_2DA_COLS ~colcount~
  SET description_col = $kitlist_cols("HELP")
  PATCH_IF VARIABLE_IS_SET $kitlist_rows("ASSASSIN") BEGIN
    SET_2DA_ENTRY_LATER ~s!thief_desc~ $kitlist_rows("ASSASSIN") description_col RESOLVE_STR_REF (@5025)
  END
  PATCH_IF VARIABLE_IS_SET $kitlist_rows("ASSASIN") BEGIN
    SET_2DA_ENTRY_LATER ~s!thief_desc~ $kitlist_rows("ASSASIN") description_col RESOLVE_STR_REF (@5025)
  END
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $kitlist_rows("BOUNTY_HUNTER") description_col RESOLVE_STR_REF (@5026)
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $kitlist_rows("SWASHBUCKLER") description_col RESOLVE_STR_REF (@5027)
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $kitlist_rows("SHADOWDANCER") description_col RESOLVE_STR_REF (@5028)
  SET_2DA_ENTRY_LATER ~s!thief_desc~ $kitlist_rows("STALKER") description_col RESOLVE_STR_REF (@5039)
  SET_2DA_ENTRIES_NOW ~s!thief_desc~ ~colcount~
  PRETTY_PRINT_2DA

///////// Enemies /////////

// Rune Assassin
COPY_EXISTING ~TANTHF01.cre~ ~override~
  WRITE_BYTE 0x10 64 // Original class = Thief
  WRITE_SHORT 0x24 73 // HP
  WRITE_SHORT 0x26 73 // HP
  WRITE_BYTE 0x45 150 // Hide in Shadows
  WRITE_BYTE 0x52 5 // Thac0
  WRITE_BYTE 0x54 4 // Saves
  WRITE_BYTE 0x55 6 // Saves
  WRITE_BYTE 0x56 5 // Saves
  WRITE_BYTE 0x57 4 // Saves
  WRITE_BYTE 0x58 7 // Saves
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 0 // Pick Pockets
  WRITE_BYTE 0x234 15 // 1st Class Level
  WRITE_BYTE 0x235 16 // 2nd Class Level
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 233
      match_parameter2 = 91
      parameter1 = 5
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

COMPILE ~IATweaks\scripts\creatures\S!RUNEAS.baf~

// Thieves right before the exit from Chateau Irenicus
ACTION_FOR_EACH low_level_thief_cre IN ~ISHADTH1.cre~ ~ISHADMT1.cre~ ~ISHADFT1.cre~ BEGIN 
  COPY_EXISTING ~%low_level_thief_cre%~ ~override~
    WRITE_BYTE 0x52 17 // Thac0
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 0 // Set Traps
    WRITE_BYTE 0x67 0 // Pick Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 0 // Find Traps
    WRITE_BYTE 0x6a 80 // Pick Pockets
    WRITE_BYTE 0x23c 17 // Dexterity
    WRITE_BYTE 0x272 3 // Half Elf because they're multi-class
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 90
        target = 1
        parameter1 = 40
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~S!40OL~
    END

    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 91
        target = 1
        parameter1 = 40
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~S!40FT~
    END

    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 92
        target = 1
        parameter1 = 40
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~S!40PP~
    END

    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 144
        target = 1
        timing = 9
      STR_VAR
        effsource = ~S!DISSTE~
    END
END

COPY_EXISTING ~ISHADFT1.cre~ ~override~
  WRITE_BYTE 0x52 16 // Thac0
  WRITE_BYTE 0x238 17 // Strength

// Suna Seni Assassin
ACTION_FOR_EACH thief_thug_cre IN ~RETHIE01.cre~ ~RETHUG04.cre~ BEGIN
  COPY_EXISTING ~%thief_thug_cre%~ ~override~
    WRITE_SHORT 0x24 66 // HP
    WRITE_SHORT 0x26 66 // HP
    WRITE_BYTE 0x45 130 // Hide in Shadows
    WRITE_BYTE 0x52 12 // Thac0
    WRITE_BYTE 0x64 0 // Detect Illusions
    WRITE_BYTE 0x65 0 // Set Traps
    WRITE_BYTE 0x67 0 // Pick Locks
    WRITE_BYTE 0x68 0 // Stealth Strike
    WRITE_BYTE 0x69 0 // Find Traps
    WRITE_BYTE 0x6a 0 // Pick Pockets
    WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 233
        match_parameter2 = 91
        parameter1 = 2
    END

    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = 233
        match_parameter2 = 113
        parameter1 = 2
    END

    LPF ~ADD_CRE_EFFECT~ // For some reason damage bonus is already applied
      INT_VAR
        opcode = 278
        target = 1
        parameter1 = 1
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~SPCL421~
    END

    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 59
        target = 1
        parameter1 = 40
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~S!40SS~
    END

    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 275
        target = 1
        parameter1 = 40
        parameter2 = 0
        timing = 9
      STR_VAR
        effsource = ~S!40HIS~
    END

    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        opcode = 144
        target = 1
        timing = 9
      STR_VAR
        effsource = ~S!DISSTE~
    END
END

COMPILE ~IATweaks\scripts\creatures\s!rethie.baf~

// Iko from Galvarey's party
COPY_EXISTING ~JAGA4.cre~ ~override~
  WRITE_BYTE 0x45 0 // Hide in Shadows
  WRITE_BYTE 0x52 14 // Thac0
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 20 // Pick Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 110 // Pick Pockets
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 90
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40OL~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 91
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40FT~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 92
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40PP~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

// Mae'Var
COPY_EXISTING ~MAEVAR.cre~ ~override~
  WRITE_BYTE 0x10 64 // Original class = Thief
  WRITE_SHORT 0x24 73 // HP
  WRITE_SHORT 0x26 73 // HP
  WRITE_BYTE 0x45 150 // Hide in Shadows
  WRITE_BYTE 0x52 5 // Thac0
  WRITE_BYTE 0x54 4 // Saves
  WRITE_BYTE 0x55 6 // Saves
  WRITE_BYTE 0x56 5 // Saves
  WRITE_BYTE 0x57 4 // Saves
  WRITE_BYTE 0x58 7 // Saves
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 0 // Pick Pockets
  WRITE_BYTE 0x234 15 // 1st Class Level
  WRITE_BYTE 0x235 16 // 2nd Class Level
  WRITE_BYTE 0x23d 16 // Strength
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 233
      match_parameter2 = 91
      parameter1 = 5
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

// Smuggler from Fallen Paladins quest

COPY_EXISTING ~KAYSMG01.cre~ ~override~ // Rindus
  WRITE_SHORT 0x24 64 // HP
  WRITE_SHORT 0x26 64 // HP
  WRITE_BYTE 0x45 0 // Hide in Shadows
  WRITE_BYTE 0x52 12 // Thac0
  WRITE_BYTE 0x53 1  // APR
  WRITE_BYTE 0x64 40 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 110 // Pick Pockets
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 90
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40OL~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 91
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40FT~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 92
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40PP~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

// Assassins from Slaver Ship
COPY_EXISTING ~s!slassa.cre~ ~override~
  WRITE_SHORT 0x24 80 // HP
  WRITE_SHORT 0x26 80 // HP
  WRITE_BYTE 0x45 120 // Hide in Shadows
  WRITE_BYTE 0x52 10 // Thac0
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 30 // Pick Pockets
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 233
      match_parameter2 = 91
      parameter1 = 2
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 233
      match_parameter2 = 113
      parameter1 = 2
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 193
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~RING95~
  END

COMPILE ~IATweaks\scripts\creatures\S!SLASSA.baf~

// Thief from Mencar's party
COPY_EXISTING ~SEVPAT05.cre~ ~override~
  WRITE_BYTE 0x45 0 // Hide in Shadows
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 45 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 45 // Find Traps
  WRITE_BYTE 0x6a 110 // Pick Pockets
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ALTER_EFFECT~ // ***** in Short Sword
    INT_VAR
      match_opcode = 233
      match_parameter2 = 91
      parameter1 = 5
  END
    
  LPF ~ALTER_EFFECT~ // ** in Sword & Shield
    INT_VAR
      match_opcode = 233
      match_parameter2 = 113
      parameter2 = 112
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 90
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40OL~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 91
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40FT~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 92
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40PP~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

// Borinall

COPY ~IATweaks\resources\spl\s!talbls.spl~ ~override~
  SAY NAME1 @6144

COPY_EXISTING ~BORINALL.cre~ ~override~
  WRITE_SHORT 0x24 100 // HP
  WRITE_SHORT 0x26 100 // HP
  WRITE_BYTE 0x45 100 // Hide in Shadows
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 60 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 110 // Pick Pockets
  WRITE_BYTE 0x23d 18 // constitution
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 90
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40OL~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 91
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40FT~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 92
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40PP~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 0
      parameter1 = 3
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~RING06~
  END

  ADD_CRE_ITEM ~CLCK01~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~CLOAK~
  ADD_CRE_ITEM ~RING06~ #0 #0 #0 ~NONE~ ~INV12~

COMPILE ~IATweaks\scripts\creatures\S!BORINA.baf~

// Turmish Thief

COPY_EXISTING ~BDTURM02.cre~ ~override~
  WRITE_SHORT 0x24 93 // HP
  WRITE_SHORT 0x26 93 // HP
  WRITE_BYTE 0x45 0 // Hide in Shadows
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x64 100 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 20 // Pick Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 110 // Pick Pockets
  WRITE_BYTE 0x23d 17 // Constitution

  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 101
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 90
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40OL~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 91
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40FT~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 92
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40PP~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~S!IMMUNE~
  END

  ADD_CRE_ITEM ~POTN36~ #0 #0 #0 ~NONE~ ~INV15~

COMPILE ~IATweaks\scripts\creatures\S!TURM02.BAF~

// Damien from evil Underdark party

COPY_EXISTING ~GPTHIEF1.cre~ ~override~
  WRITE_SHORT 0x24 94 // HP
  WRITE_SHORT 0x26 94 // HP
  WRITE_LONG 0x28 0x6301 // Animation Thief Male Elf
  WRITE_BYTE 0x45 160 // Hide in Shadows
  WRITE_BYTE 0x52 5 // Thac0
  WRITE_BYTE 0x54 8 // Saves
  WRITE_BYTE 0x55 4 // Saves
  WRITE_BYTE 0x56 7 // Saves
  WRITE_BYTE 0x57 11 // Saves
  WRITE_BYTE 0x58 5 // Saves
  WRITE_BYTE 0x59 0 // Resist Fire
  WRITE_BYTE 0x5b 0 // Resist Electricity
  WRITE_BYTE 0x5e 0 // Resist Magic Fire
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 110 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 0 // Pick Pockets
  WRITE_BYTE 0x234 27 // 1st Class Level
  WRITE_BYTE 0x235 1 // 2nd Class Level
  WRITE_BYTE 0x238 18 // Strength
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  WRITE_BYTE 0x270 255 // Allegiance = Enemy
  WRITE_BYTE 0x273 4 // Class = Thief
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  PATCH_FOR_EACH opcode_to_remove IN 101 267 16 0 BEGIN
    LPF ~DELETE_EFFECT~
      INT_VAR
        match_opcode = opcode_to_remove
    END
  END

  PATCH_FOR_EACH item_to_remove IN ~MAGE01~ ~RING05~ ~LEAT02~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~LEAT05~ #0 #0 #0 ~NONE~ ~ARMOR~
  ADD_CRE_ITEM ~RING06~ #0 #0 #0 ~NONE~ ~RRING~
  ADD_CRE_ITEM ~AMUL14~ #0 #0 #0 ~NONE~ ~AMULET~
  ADD_CRE_ITEM ~SW1H07~ #0 #0 #0 ~NONE~ ~WEAPON3~
  ADD_CRE_ITEM ~POTN14~ #2 #0 #0 ~UNSTEALABLE~ ~INV10~ // Oil of Speed
  ADD_CRE_ITEM ~POTN33~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~INV11~ // Barbarian Essence
  ADD_CRE_ITEM ~POTN41~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~INV12~ // Potion of Power
  ADD_CRE_ITEM ~POTN39~ #0 #0 #0 ~UNSTEALABLE~ ~INV13~ // Potion of Perception

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL423~ #0 ~innate~ ( 5 ) // Poison Weapon
  ADD_MEMORIZED_SPELL ~S!GGRACE~ #0 ~innate~ ( 1 ) // Ghost's Grace
  ADD_MEMORIZED_SPELL ~SPCL913~ #0 ~innate~ ( 1 ) // Evasion
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 1 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 1 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 1 ) // Avoid Death

COMPILE ~IATweaks\scripts\creatures\S!GPTHIE.baf~

// Ketta from Guarded Compound

COPY_EXISTING ~HLKETTA.cre~ ~override~
  WRITE_SHORT 0x24 130 // HP
  WRITE_SHORT 0x26 130 // HP
  WRITE_BYTE 0x45 160 // Hide in Shadows
  WRITE_BYTE 0x52 5 // Thac0
  WRITE_BYTE 0x54 8 // Saves
  WRITE_BYTE 0x55 4 // Saves
  WRITE_BYTE 0x56 7 // Saves
  WRITE_BYTE 0x57 11 // Saves
  WRITE_BYTE 0x58 5 // Saves
  WRITE_BYTE 0x59 50 // Resist Fire
  WRITE_BYTE 0x5e 50 // Resist Magic Fire
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 140 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 0 // Pick Pockets
  WRITE_BYTE 0x234 30 // 1st Class Level
  WRITE_BYTE 0x235 1 // 2nd Class Level
  WRITE_BYTE 0x238 18 // Strength
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  WRITE_BYTE 0x270 255 // Allegiance = Enemy
  WRITE_BYTE 0x273 4 // Class = Thief

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  PATCH_FOR_EACH item_to_remove IN ~DRAGRING~ ~LEAT12~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~OHLEAT53~ #0 #0 #0 ~NONE~ ~ARMOR~
  ADD_CRE_ITEM ~SW1H07~ #0 #0 #0 ~NONE~ ~WEAPON3~
  ADD_CRE_ITEM ~POTN14~ #2 #0 #0 ~UNSTEALABLE~ ~INV10~ // Oil of Speed
  ADD_CRE_ITEM ~POTN39~ #0 #0 #0 ~UNSTEALABLE~ ~INV13~ // Potion of Perception

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL423~ #0 ~innate~ ( 6 ) // Poison Weapon
  ADD_MEMORIZED_SPELL ~S!GGRACE~ #0 ~innate~ ( 1 ) // Ghost's Grace
  ADD_MEMORIZED_SPELL ~SPCL913~ #0 ~innate~ ( 1 ) // Evasion
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 1 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 1 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 1 ) // Avoid Death

COMPILE ~IATweaks\scripts\creatures\HLKETTA.baf~

COPY_EXISTING ~AR0907.are~ ~override~
  LPF ~ALTER_AREA_ACTOR~
    INT_VAR
      x_coord  = 965
      y_coord  = 738
    STR_VAR
      actor_name = ~Ketta~
  END

// Ferric from Samia's party

COPY_EXISTING ~DESHAR.cre~ ~override~
  WRITE_SHORT 0x24 99 // HP
  WRITE_SHORT 0x26 99 // HP
  WRITE_BYTE 0x45 0 // Hide in Shadows
  WRITE_BYTE 0x59 25 // Resist Fire
  WRITE_BYTE 0x5e 25 // Resist Magic Fire
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 75 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 0 // Stealth Strike
  WRITE_BYTE 0x69 45 // Find Traps
  WRITE_BYTE 0x6a 110 // Pick Pockets
  WRITE_BYTE 0x238 18 // Strength
  WRITE_BYTE 0x239 76 // Exceptional Strength
  WRITE_BYTE 0x23d 18 // constitution
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 90
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40OL~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 91
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40FT~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 92
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40PP~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  ADD_CRE_ITEM ~SW1H43~ #0 #0 #0 ~NONE~ ~WEAPON3~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL913~ #0 ~innate~ ( 1 ) // Evasion
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 1 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 1 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 1 ) // Avoid Death

COMPILE ~IATweaks\scripts\creatures\S!DESHAR.baf~

COPY_EXISTING ~S!DESHAR.itm~ ~override~
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 206
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 101
      parameter2 = 45
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 101
      parameter2 = 175
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 0
      parameter1 = 2
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 31
      parameter1 = 50
  END

/////////// Items ////////////

// Randomize Ring of Duplication between Shadow Dragon, Borinall and Damien

COPY_EXISTING ~OHRDALTN.cre~ ~override~
  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~ohrring1~
  END

COPY_EXISTING ~AR0602.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    SET ofs = INDEX_BUFFER(~\(.*\)"Iarandomizer","AR0602",0~)
    PATCH_IF %ofs% >= 0 BEGIN
      // PATCH_PRINT ~%ofs%~
      REPLACE_EVALUATE
      ~\(.*\)"Iarandomizer","AR0602",0~
      BEGIN
        SPRINT val ~	Global("Iadupliringplace","GLOBAL",0)
THEN
	RESPONSE #50
		SetGlobal("Iadupliringplace","GLOBAL",1)
	RESPONSE #50
		SetGlobal("Iadupliringplace","GLOBAL",2)
	RESPONSE #50
		SetGlobal("Iadupliringplace","GLOBAL",3)
END

IF
%MATCH1%"Iarandomizer","AR0602",0~
      END
      ~%val%~
    END
  END
  BUT_ONLY

COPY_EXISTING ~SHADRA01.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    SET ofs = INDEX_BUFFER(~\(.*\)"sw1h40",Myself,0,0,0\(.*\)~)
    PATCH_IF %ofs% >= 0 BEGIN
      REPLACE_EVALUATE
      ~\(.*\)"sw1h40",Myself,0,0,0\(.*\)~
      BEGIN
        SPRINT val ~%MATCH1%"sw1h40",Myself,0,0,0%MATCH2%
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iadupliringplace","GLOBAL",3)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iadupliringplace","GLOBAL",4)
		GiveItemCreate("ohrring1",Myself,0,0,0)~
      END
      ~%val%~
    END
  END
  BUT_ONLY

// Move Grave Binder to Founder of Trademeet

COPY_EXISTING ~ohngduke.sto~ ~override~
  LPF ~REMOVE_STORE_ITEM_EX~
    STR_VAR item_name = ~dagg04~
  END

COPY_EXISTING ~CESKEL01.cre~ ~override~
  ADD_CRE_ITEM ~DAGG04~ #0 #0 #0 ~NONE~ ~INV16~

// No stacking for potions that grant Thieving Abilities

COPY_EXISTING ~potn36.itm~ ~override~
  WRITE_LONG 0x34 THIS * 4
  LPF ~ADD_ITEM_EFFECT~
    INT_VAR
      opcode = 321
      insert_point = 0
      target = 1
      power = 4
    STR_VAR
      resource = "POTN36"
  END

ACTION_FOR_EACH perception_potion_item IN ~POTN39.itm~ ~s!potn09.itm~ BEGIN
  COPY_EXISTING ~%perception_potion_item%~ ~override~
    WRITE_LONG 0x34 THIS * 4
    SAY IDENTIFIED_DESC @7001
    LPF ~ADD_ITEM_EFFECT~
      INT_VAR
        opcode = 321
        insert_point = 0
        target = 1
        power = 4
      STR_VAR
        resource = "POTN39"
    END
    LPF ~ADD_ITEM_EFFECT~
      INT_VAR
        opcode = 321
        insert_point = 0
        target = 1
        power = 4
      STR_VAR
        resource = "S!POTN09"
    END
    LPF ~CLONE_EFFECT~
      INT_VAR
        match_opcode = 92
        opcode = 276
    END
END

COPY_EXISTING ~potn41.itm~ ~override~
  LPF ~ADD_ITEM_EFFECT~
    INT_VAR
      opcode = 321
      insert_point = 0
      target = 1
      power = 4
    STR_VAR
      resource = "POTN41"
  END
  PATCH_FOR_EACH thieving_abilities_opcode IN 90 91 92 275 BEGIN
    LPF ~ALTER_EFFECT~
      INT_VAR
        match_opcode = thieving_abilities_opcode
        parameter1 = 20
        parameter2 = 0
    END
  END

// Worn Whispers

COPY_EXISTING ~boot02.itm~ ~override~
  SAY IDENTIFIED_DESC @7005
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 59
      parameter1 = 5
  END

// Boots of Elvenkind

COPY_EXISTING ~boot07.itm~ ~override~
  SAY IDENTIFIED_DESC @7082
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 59
      opcode = 275
      parameter1 = 15
  END

// Assassin's Dream +4

COPY ~IATweaks\resources\bam\s!dag01d.bam~ ~override~
COPY ~IATweaks\resources\bam\s!dagg01.bam~ ~override~
COPY ~IATweaks\resources\itm\s!dagg01.itm~ ~override~
  SAY NAME2 @7023
  SAY IDENTIFIED_DESC @7024

// Assassin's Dream +5

COPY ~IATweaks\resources\eff\s!-1apr.eff~ ~override~
COPY ~IATweaks\resources\bam\s!dagg02.bam~ ~override~
COPY ~IATweaks\resources\itm\s!dagg02.itm~ ~override~
  SAY NAME2 @7064
  SAY IDENTIFIED_DESC @7065
  PATCH_FOR_EACH weapon_type IN 0x10 0x11 0x13 0x14 0x15 0x16 0x17 0x19 0x1a BEGIN
    LPF ~ADD_ITEM_EQEFFECT~
      INT_VAR
        insert_point = ~-1~
        opcode = 183
        target = 1
        parameter2 = weapon_type
        timing = 2
      STR_VAR
        resource = EVAL ~S!-1APR~
    END  
  END
  
// Piwafwi Cloaks

COPY_EXISTING ~misc9w.itm~ ~override~
  SAY IDENTIFIED_DESC @7043
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 59
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 275
      parameter1 = 25
  END

COPY_EXISTING ~dwclck01.itm~ ~override~
  SAY IDENTIFIED_DESC @7042
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 59
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 275
      parameter1 = 25
  END

// Cloak of Elvenkind

COPY_EXISTING ~clck23.itm~ ~override~
  SAY IDENTIFIED_DESC @7044
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 275
      parameter1 = 10
  END

// Make Armors of Stamina protect from Stealth spell

ACTION_FOR_EACH stamina_armor_itm IN ~LEAT09~ ~S!LEAT06~ BEGIN
  COPY_EXISTING ~%stamina_armor_itm%.itm~ ~override~
    LPF ~CLONE_EFFECT~
      INT_VAR
        multi_match = 1
        match_opcode = 144
        match_parameter2 = 0
        opcode = 206
      STR_VAR
        resource = ~S!HISBAS~
    END
END

//////////////// Weapons for backstabs ///////////////

COPY ~IATweaks\resources\eff\s!ss-20.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ss-30.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ss-40.eff~ ~override~
COPY ~IATweaks\resources\eff\s!ss-50.eff~ ~override~

ACTION_DEFINE_ASSOCIATIVE_ARRAY weapon_to_stealth_strike_bonus_mapping BEGIN
  "sw1h10"=>20 // Short sword of backstabbing
  "s!dagg01"=>40 // Assassin's Dream +4
  "s!dagg02"=>50 // Assassin's Dream +5
END

ACTION_PHP_EACH weapon_to_stealth_strike_bonus_mapping AS weapon => bonus BEGIN
  COPY_EXISTING ~%weapon%.itm~ ~override~
    WRITE_SHORT 0x1c 0x45	// item_type = bastard sword to prevent using in offhand
    LPF ~ADD_ITEM_EQEFFECT~
      INT_VAR
        insert_point = 0
        opcode = 59
        target = 1
        parameter1 = bonus
        timing = 2
    END  
    PATCH_FOR_EACH weapon_type IN 0x10 0x11 0x13 0x14 0x15 0x16 0x17 0x19 0x1a BEGIN
      LPF ~ADD_ITEM_EQEFFECT~
        INT_VAR
          insert_point = ~-1~
          opcode = 183
          target = 1
          parameter2 = weapon_type
          timing = 2
        STR_VAR
          resource = EVAL ~S!SS-%bonus%~
      END  
    END
END

// Short Sword of Backstabbing

COPY_EXISTING ~sw1h10.itm~ ~override~
  SAY IDENTIFIED_DESC @7008

// Mercykiller Ring

COPY_EXISTING ~wa2ring.itm~ ~override~
  SAY IDENTIFIED_DESC @7011
  WRITE_LONG 0x34 25000
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 275
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 277
  END

// Spirit of the Night

COPY ~IATweaks\resources\itm\s!leat02.itm~ ~override~
  SAY IDENTIFIED_DESC @7052

// //////// Spells /////////

// Detect Traps //

COPY ~IATweaks\resources\2da\sppr205.2da~ ~override~
COPY ~IATweaks\resources\spl\sppr205f.spl~ ~override~
  SAY NAME1 @6131
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 139
      parameter1 = RESOLVE_STR_REF (@6132)
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 328
      parameter2 = %trap_immunity_state%
  END

COPY_EXISTING ~spwi313.spl~ ~override/sppr205e.spl~

COPY_EXISTING ~spwi313.spl~ ~override~
  SAY NAME1 @6127
  SAY UNIDENTIFIED_DESC @6129
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      target = 7
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = ~-1~
  END
  LPF ~ADD_SPELL_EFFECT~ 
    INT_VAR
      opcode = 214
      target = 1
      resist_dispel = 2
      timing = 1
      power = 3
    STR_VAR
      resource = ~SPPR205~
  END

COPY_EXISTING ~sppr205.spl~ ~override~
  SAY NAME1 @6127
  SAY UNIDENTIFIED_DESC @6128
  LPF ~ALTER_SPELL_HEADER~
    INT_VAR
      target = 7
  END
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = ~-1~
  END
  LPF ~ADD_SPELL_EFFECT~ 
    INT_VAR
      opcode = 214
      target = 1
      resist_dispel = 2
      timing = 1
      power = 3
    STR_VAR
      resource = ~SPPR205~
  END

COPY_EXISTING ~scrl1p.itm~ ~override~
  SAY NAME2 @6127
  SAY IDENTIFIED_DESC @6129

OUTER_SET trap_script_id = 0

COPY_EXISTING_REGEXP GLOB ~.*\.are$~ ~override~
  // process triggers //

  GET_OFFSET_ARRAY regions ARE_V10_REGIONS

  PHP_EACH regions AS int1 => region_off BEGIN
    READ_SHORT region_off + 0x68 trap_det_diff // trap detection difficulty
    READ_SHORT region_off + 0x6a trap_dis_diff
    READ_SHORT region_off + 0x6c is_trapped
    READ_ASCII region_off + 0x7c script_file
    TO_UPPER script_file

    PATCH_IF ((is_trapped == 1) AND (trap_det_diff < 100) AND (trap_dis_diff > 0)) BEGIN
      SPRINT $trigger_area_trap_scripts("%script_file%") "OK"
    END
    PATCH_IF ((is_trapped == 1) AND (trap_det_diff >= 100)) BEGIN
      INNER_ACTION BEGIN
        COPY_EXISTING ~%script_file%.bcs~ ~override/S!TRP%trap_script_id%.bcs~
      END
      WRITE_ASCIIE region_off + 0x7c ~S!TRP%trap_script_id%~ #8
      trap_script_id = trap_script_id + 1
    END
  END

  // process containers //

  GET_OFFSET_ARRAY containers ARE_V10_CONTAINERS

  PHP_EACH containers AS int2 => cont_off BEGIN
    READ_SHORT cont_off + 0x2c trap_det_diff // trap detection difficulty
    READ_SHORT cont_off + 0x2e trap_dis_diff // trap disarm difficulty
    READ_SHORT cont_off + 0x30 is_trapped
    READ_ASCII cont_off + 0x48 script_file
    TO_UPPER script_file

    PATCH_IF ((is_trapped == 1) AND (trap_det_diff < 100) AND (trap_dis_diff > 0)) BEGIN
      SPRINT $container_trap_scripts("%script_file%") "OK"
    END
    PATCH_IF ((is_trapped == 1) AND (trap_det_diff >= 100)) BEGIN
      INNER_ACTION BEGIN
        COPY_EXISTING ~%script_file%.bcs~ ~override/S!TRP%trap_script_id%.bcs~
      END
      WRITE_ASCIIE cont_off + 0x48  ~S!TRP%trap_script_id%~ #8
      trap_script_id = trap_script_id + 1
    END
  END
  IF_EXISTS

<<<<<<<<.../IATweaks-inlined/trap_immunity_and_removal.baf
IF
  OR(2)
	  Opened([ANYONE])
	  Entered([ANYONE])
  CheckSpellState(LastTrigger,%state%)
THEN
	RESPONSE #100
		DisplayString(LastTrigger,%strref%)
    TriggerActivation(Myself,FALSE)
    RemoveTraps(Myself)
END

>>>>>>>>

ACTION_PHP_EACH container_trap_scripts AS trap_script => _ BEGIN
  EXTEND_TOP "%trap_script%.bcs" ".../IATweaks-inlined/trap_immunity_and_removal.baf"
    SET strref = RESOLVE_STR_REF (@5031)
    SET state = trap_immunity_state
    EVALUATE_BUFFER
END

ACTION_PHP_EACH trigger_area_trap_scripts AS trap_script => _ BEGIN
  EXTEND_TOP "%trap_script%.bcs" ".../IATweaks-inlined/trap_immunity_and_removal.baf"
    SET strref = RESOLVE_STR_REF (@5031)
    SET state = trap_immunity_state
    EVALUATE_BUFFER
END

// Assassin from Illithid Compound

COPY_EXISTING ~HLASSA.cre~ ~override~
  WRITE_SHORT 0x24 130 // HP
  WRITE_SHORT 0x26 130 // HP
  WRITE_SHORT 0x28  0x6303 // animation
  WRITE_BYTE 0x45 160 // Hide in Shadows
  WRITE_BYTE 0x52 5 // Thac0
  WRITE_BYTE 0x54 8 // Saves
  WRITE_BYTE 0x55 4 // Saves
  WRITE_BYTE 0x56 7 // Saves
  WRITE_BYTE 0x57 11 // Saves
  WRITE_BYTE 0x58 5 // Saves
  WRITE_BYTE 0x5d 25 // Resist Magic
  WRITE_BYTE 0x60 20 // Resist Slashing
  WRITE_BYTE 0x61 20 // Resist Crushing
  WRITE_BYTE 0x62 20 // Resist Piercing
  WRITE_BYTE 0x63 20 // Resist Missile
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 140 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 0 // Pick Pockets
  WRITE_BYTE 0x234 30 // 1st Class Level
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  WRITE_BYTE 0x272 5 // Race
    
  LPF ~ADD_CRE_EFFECT~ // normal Haste
    INT_VAR
      target = 1
      opcode = 16
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ** in Daggers
    INT_VAR
      target = 1
      opcode = 233
      parameter2 = 96
      parameter1 = 2
      resist_dispel = 0
      timing = 9
  END
    
  LPF ~ADD_CRE_EFFECT~ // ** in Single Weapon Style
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 2
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  PATCH_FOR_EACH item_to_remove IN ~S!HLASSA~ ~SHLD17~ BEGIN
    LPF ~DELETE_CRE_ITEM~
      STR_VAR
        item_to_delete = EVAL ~%item_to_remove%~
    END
  END

  ADD_CRE_ITEM ~OHLEAT53~ #0 #0 #0 ~NONE~ ~ARMOR~
  ADD_CRE_ITEM ~SW1H07~ #0 #0 #0 ~NONE~ ~WEAPON3~
  ADD_CRE_ITEM ~SHLD17~ #2 #0 #0 ~UNSTEALABLE~ ~INV11~ // Buckler +1
  ADD_CRE_ITEM ~POTN41~ #0 #0 #0 ~UNSTEALABLE~ ~INV12~ // Potion of Power
  ADD_CRE_ITEM ~POTN55~ #2 #0 #0 ~UNSTEALABLE~ ~INV13~ // Potion of Superior Healing

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL423~ #0 ~innate~ ( 6 ) // Poison Weapon
  ADD_MEMORIZED_SPELL ~S!GGRACE~ #0 ~innate~ ( 1 ) // Ghost's Grace
  ADD_MEMORIZED_SPELL ~SPCL913~ #0 ~innate~ ( 1 ) // Evasion
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 1 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 1 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 1 ) // Avoid Death

COMPILE ~IATweaks\scripts\creatures\S!HLASSA.baf~

// Elite Rune Assassin

COPY_EXISTING ~S!TANTHF.cre~ ~override~
  WRITE_BYTE 0x10 64 // Original class = Thief
  WRITE_SHORT 0x24 73 // HP
  WRITE_SHORT 0x26 73 // HP
  WRITE_BYTE 0x45 150 // Hide in Shadows
  WRITE_BYTE 0x52 4 // Thac0
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 10 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 0 // Pick Pockets
  WRITE_BYTE 0x234 16 // 1st Class Level
  WRITE_BYTE 0x235 17 // 2nd Class Level
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  WRITE_ASCII 0x248 ~S!RUNEAS~ #8
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 233
      match_parameter2 = 91
      parameter1 = 5
  END

  LPF ~ALTER_EFFECT~ // *** in Single Weapon
    INT_VAR
      match_opcode = 233
      match_parameter2 = 113
      parameter1 = 3
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

// Master Assassin (that is actually a F-T multiclass)

COPY_EXISTING ~S!RUNE2.cre~ ~override~
  WRITE_SHORT 0x24 105 // HP
  WRITE_SHORT 0x26 105 // HP
  WRITE_BYTE 0x45 140 // Hide in Shadows
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 100 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 30 // Pick Pockets
  WRITE_BYTE 0x23c 21 // Dexterity
  WRITE_BYTE 0x23d 18 // constitution
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 90
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40OL~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 91
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40FT~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 92
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40PP~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  ADD_CRE_ITEM ~SW1H07~ #0 #0 #0 ~NONE~ ~WEAPON3~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL423~ #0 ~innate~ ( 5 ) // Poison Weapon
  ADD_MEMORIZED_SPELL ~SPCL913~ #0 ~innate~ ( 1 ) // Evasion
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 1 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 1 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 1 ) // Avoid Death

  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 2 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 2 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!RUNE2.baf~
COMPILE ~IATweaks\scripts\creatures\S!RUNEF2.baf~

// Guildmaster

COPY_EXISTING ~S!RUNE1.cre~ ~override~
  WRITE_BYTE 0x10 64 // Original class = Thief
  WRITE_SHORT 0x24 143 // HP
  WRITE_SHORT 0x26 143 // HP
  WRITE_BYTE 0x45 190 // Hide in Shadows
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 100 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 50 // Pick Pockets
  WRITE_BYTE 0x23c 21 // Dexterity
  WRITE_BYTE 0x23d 18 // constitution
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ALTER_EFFECT~ // Backstab multiplier
    INT_VAR
      match_opcode = 263
      parameter1 = 1
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL423~ #0 ~innate~ ( 5 ) // Poison Weapon
  ADD_MEMORIZED_SPELL ~SPCL913~ #0 ~innate~ ( 1 ) // Evasion
  ADD_MEMORIZED_SPELL ~S!GGRACE~ #0 ~innate~ ( 1 ) // Ghost's Grace
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 2 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 2 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 1 ) // Avoid Death

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 2 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 2 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!RUNE1.baf~

// Grandfather of Assassins

COPY_EXISTING ~S!RUNEF.cre~ ~override~
  WRITE_BYTE 0x10 64 // Original class = Thief
  WRITE_SHORT 0x24 153 // HP
  WRITE_SHORT 0x26 153 // HP
  WRITE_BYTE 0x45 210 // Hide in Shadows
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 150 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 100 // Pick Pockets
  WRITE_BYTE 0x23c 23 // Dexterity
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
    
  LPF ~ALTER_EFFECT~ // ***** in Short Sword
    INT_VAR
      match_opcode = 233
      match_parameter2 = 91
      parameter1 = 5
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ALTER_EFFECT~ // Backstab multiplier
    INT_VAR
      match_opcode = 263
      parameter1 = 1
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL423~ #0 ~innate~ ( 5 ) // Poison Weapon
  ADD_MEMORIZED_SPELL ~SPCL913~ #0 ~innate~ ( 1 ) // Evasion
  ADD_MEMORIZED_SPELL ~S!GGRACE~ #0 ~innate~ ( 1 ) // Ghost's Grace
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 2 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 2 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 1 ) // Avoid Death

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 3 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 2 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 3 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\S!RUNEF.baf~

// Illasera

COPY ~IATweaks\resources\itm\s!illase.itm~ ~override~

COPY_EXISTING ~ILLASERA.cre~ ~override~
  WRITE_LONG 0x14 55000 // Exp
  WRITE_SHORT 0x24 192 // HP
  WRITE_SHORT 0x26 192 // HP
  WRITE_BYTE 0x45 200 // Hide in Shadows
  WRITE_BYTE 0x53 4  // APR
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 150 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 100 // Pick Pockets
  WRITE_BYTE 0x23c 22 // Dexterity
  WRITE_BYTE 0x23d 17 // Constitution
  WRITE_BYTE 0x234 28 // 1st Class Level
  WRITE_BYTE 0x235 29 // 2nd Class Level
    
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 263
  END
    
  LPF ~DELETE_EFFECT~
    INT_VAR
      match_opcode = 193
  END

  LPF ~ADD_CRE_EFFECT~ // Permanent Alacrity
    INT_VAR
      target = 1
      opcode = 188
      parameter1 = 0
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // *** in Single Weapon Style
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // +15 movement speed
    INT_VAR
      opcode = 126
      target = 1
      parameter1 = 15
      parameter2 = 0
      timing = 9
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // All saving throws
    INT_VAR
      opcode = 325
      target = 1
      parameter1 = 5
      parameter2 = 0
      timing = 9
  END

  PATCH_FOR_EACH poison_weapon_eff IN ~SPCL422~ ~SPCL422A~ ~SPCL422B~ BEGIN
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        target = 1
        opcode = 248
        parameter2 = 1
        resist_dispel = 0
        timing = 9
      STR_VAR
        resource = EVAL ~%poison_weapon_eff%~
    END
    LPF ~ADD_CRE_EFFECT~
      INT_VAR
        target = 1
        opcode = 249
        parameter2 = 1
        resist_dispel = 0
        timing = 9
      STR_VAR
        resource = EVAL ~%poison_weapon_eff%~
    END
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 16
      parameter2 = 1
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~SW1H75~
  END

  ADD_CRE_ITEM ~S!ILLASE~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~WEAPON1~ EQUIP
  ADD_CRE_ITEM ~SW1H43~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON3~
  ADD_CRE_ITEM ~SW1H75~ #0 #0 #0 ~UNSTEALABLE~ ~INV10~
  ADD_CRE_ITEM ~SCRL7M~ #2 #0 #0 ~UNSTEALABLE~ ~INV11~

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~S!GGRACE~ #0 ~innate~ ( 2 ) // Ghost's Grace
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 3 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 2 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 3 ) // Avoid Death

  ADD_MEMORIZED_SPELL ~SPCL907~ #0 ~innate~ ( 2 ) // Hardiness
  ADD_MEMORIZED_SPELL ~SPCL906~ #0 ~innate~ ( 2 ) // Power Attack
  ADD_MEMORIZED_SPELL ~SPCL905~ #0 ~innate~ ( 3 ) // Critical Strike
  ADD_MEMORIZED_SPELL ~SPCL900~ #0 ~innate~ ( 1 ) // Whirlwind Attack
  ADD_MEMORIZED_SPELL ~SPCL901~ #0 ~innate~ ( 1 ) // Greater Whirlwind Attack

COMPILE ~IATweaks\scripts\creatures\ILLASERA.baf~

// Eler Had from Gromnir Fight

COPY_EXISTING ~GROMG09.cre~ ~override~
  WRITE_LONG 0x14 30000 // Exp
  WRITE_SHORT 0x24 134 // HP
  WRITE_SHORT 0x26 134 // HP
  WRITE_BYTE 0x45 160 // Hide in Shadows
  WRITE_BYTE 0x52 0 // Thac0
  WRITE_BYTE 0x53 7  // 1,5 APR
  WRITE_BYTE 0x54 8 // Saves
  WRITE_BYTE 0x55 4 // Saves
  WRITE_BYTE 0x56 7 // Saves
  WRITE_BYTE 0x57 11 // Saves
  WRITE_BYTE 0x58 5 // Saves
  WRITE_BYTE 0x64 0 // Detect Illusions
  WRITE_BYTE 0x65 0 // Set Traps
  WRITE_BYTE 0x67 0 // Pick Locks
  WRITE_BYTE 0x68 160 // Stealth Strike
  WRITE_BYTE 0x69 0 // Find Traps
  WRITE_BYTE 0x6a 15 // Pick Pockets
  WRITE_BYTE 0x234 32 // 1st Class Level
  WRITE_BYTE 0x235 1 // 2nd Class Level
  WRITE_BYTE 0x23c 21 // Dexterity
  WRITE_LONG 0x244 0x400a0000 // Kit = Assassin
  WRITE_BYTE 0x270 255 // Allegiance = Enemy
  WRITE_BYTE 0x273 4 // Class = Thief

  LPF ~ADD_CRE_EFFECT~ // *** in Single Weapon Style
    INT_VAR
      target = 1
      opcode = 233
      parameter1 = 3
      parameter2 = 113
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~ // Add ENEMY_GROUP spellstate
    INT_VAR
      target = 1
      opcode = 328
      parameter1 = 0
      parameter2 = enemy_group_state
      resist_dispel = 0
      timing = 9
      special = 1
  END

  LPF ~ADD_CRE_EFFECT~ // All saving throws
    INT_VAR
      opcode = 325
      target = 1
      parameter1 = 5
      parameter2 = 0
      timing = 9
  END
  
  LPF ~ADD_CRE_EFFECT~ // Set persistent AI
    INT_VAR
      target = 1
      opcode = 293
      parameter2 = 1
      resist_dispel = 0
      timing = 9
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 73
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 278
      target = 1
      parameter1 = 1
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~SPCL421~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 59
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40SS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 275
      target = 1
      parameter1 = 40
      parameter2 = 0
      timing = 9
    STR_VAR
      effsource = ~S!40HIS~
  END

  LPF ~ADD_CRE_EFFECT~
    INT_VAR
      opcode = 144
      target = 1
      timing = 9
    STR_VAR
      effsource = ~S!DISSTE~
  END

  LPF ~DELETE_CRE_ITEM~
    STR_VAR
      item_to_delete = ~SW1H74~
  END

  ADD_CRE_ITEM ~SW1H10~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
  ADD_CRE_ITEM ~SW1H07~ #0 #0 #0 ~NONE~ ~WEAPON3~
  ADD_CRE_ITEM ~POTN39~ #0 #0 #0 ~UNSTEALABLE~ ~INV13~ // Potion of Perception

  REMOVE_MEMORIZED_SPELLS

  ADD_MEMORIZED_SPELL ~SPCL423~ #0 ~innate~ ( 6 ) // Poison Weapon
  ADD_MEMORIZED_SPELL ~S!GGRACE~ #0 ~innate~ ( 2 ) // Ghost's Grace
  ADD_MEMORIZED_SPELL ~SPCL913~ #0 ~innate~ ( 1 ) // Evasion
  ADD_MEMORIZED_SPELL ~SPCL914~ #0 ~innate~ ( 2 ) // Greater Evasion
  ADD_MEMORIZED_SPELL ~SPCL916~ #0 ~innate~ ( 1 ) // Assassination
  ADD_MEMORIZED_SPELL ~SPCL917~ #0 ~innate~ ( 2 ) // Avoid Death

COMPILE ~IATweaks\scripts\creatures\S!GROASA.baf~