PRINT @5082

SILENT

INCLUDE "%MOD_FOLDER%/lib/components/IA_rebalancing/helper_functions.tph"

// change weapon style bonus descriptions
COPY_EXISTING ~weapprof.2da~  ~override/weapprof.2da~
  COUNT_2DA_COLS ~colcount~
  // change Two-handed Weapon description
  SET_2DA_ENTRY 28 3 ~colcount~ RESOLVE_STR_REF (@5005)
  // change Sword and Shield description
  SET_2DA_ENTRY 29 3 ~colcount~ RESOLVE_STR_REF (@5003)
  // change Single Weapon description
  SET_2DA_ENTRY 30 3 ~colcount~ RESOLVE_STR_REF (@5004)
  // change Two Weapons description
  SET_2DA_ENTRY 31 3 ~colcount~ RESOLVE_STR_REF (@5137)
  PRETTY_PRINT_2DA


COPY_EXISTING ~stylbonu.2da~  ~override/stylbonu.2da~
  COUNT_2DA_COLS ~colcount~
  // give all bonuses to Single Weapon Style
  SET_2DA_ENTRY 5 1 ~colcount~ ~1~
  SET_2DA_ENTRY 5 3 ~colcount~ ~-1~
  SET_2DA_ENTRY 5 7 ~colcount~ ~-1~
  SET_2DA_ENTRY 5 8 ~colcount~ ~1~
  SET_2DA_ENTRY 9 1 ~colcount~ ~2~
  SET_2DA_ENTRY 9 3 ~colcount~ ~-2~
  SET_2DA_ENTRY 9 7 ~colcount~ ~-2~
  SET_2DA_ENTRY 9 8 ~colcount~ ~2~
  // give additional AC to Sword and Shield
  SET_2DA_ENTRY 6 5 ~colcount~ ~-1~
  SET_2DA_ENTRY 6 6 ~colcount~ ~-1~
  SET_2DA_ENTRY 10 5 ~colcount~ ~-2~
  SET_2DA_ENTRY 10 6 ~colcount~ ~-2~
  // give additional AC to *** in Two Weapon Style
  SET_2DA_ENTRY 12 5 ~colcount~ ~-1~
  // give additional damage to ** in Two-handed Weapon
  SET_2DA_ENTRY 8 1 ~colcount~ ~3~
  PRETTY_PRINT_2DA

// add bonuses for *** in different styles
COPY_EXISTING ~stylbonu.2da~  ~override/stylbonu.2da~
  COUNT_2DA_COLS ~colcount~
  COUNT_2DA_ROWS ~colcount~ ~rowcount~
  INSERT_2DA_ROW ~rowcount~ ~colcount~ ~SWORDANDSHIELD-3    0                0                0                0                -3               -3               0                0~
  INSERT_2DA_ROW ~rowcount~ + 1 ~colcount~ ~TWOHANDED-3     3                0                0                0                0                0                -4               1~
  INSERT_2DA_ROW ~rowcount~ + 2 ~colcount~ ~SINGLEWEAPON-3  2                0                -2               0                -2               0                -2               2~
  PRETTY_PRINT_2DA

// Add needed splprot entries

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~SHIELD_EQUIPPED~
    stat                  = ~0x112~
    value                 = ~%shield_equipped_state%~
    relation              = ~1~
  RET
    is_shield_equipped = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~SWORD_SHIELD_STYLE=n~
    stat                  = ~112~
    value                 = ~-1~
    relation              = ~1~
  RET
    sw_sh_style = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~2H_WEAPON_STYLE<n~
    stat                  = ~111~
    value                 = ~-1~
    relation              = ~2~
  RET
    two_handed_style = new_line_number
END
LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~SINGLE_WEAPON_STYLE<n~
    stat                  = ~113~
    value                 = ~-1~
    relation              = ~2~
  RET
    single_weapon_style = new_line_number
END

LAF ~S!ADD_SPLPROT_2DA_ENTRY~
  STR_VAR
    condition_description = ~TRACKING_NUM_WEAPONS>=n~
    stat                  = ~33~
    value                 = ~-1~
    relation              = ~4~
  RET
    tracking_num_weapons = new_line_number
END

COPY ~IATweaks\resources\eff\s!+05apr.eff~ ~override~
COPY ~IATweaks\resources\eff\s!swpapr.eff~ ~override~
COPY ~IATweaks\resources\eff\s!countw.eff~ ~override~
COPY ~IATweaks\resources\spl\s!+05apr.spl~ ~override~
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      match_parameter1 = 1
      parameter1 = 0
      parameter2 = is_shield_equipped
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      match_parameter1 = 2
      parameter1 = 2
      parameter2 = tracking_num_weapons
  END
  LPF ~ALTER_EFFECT~
    INT_VAR
      match_opcode = 318
      match_parameter1 = 3
      parameter2 = single_weapon_style
  END

LAF ~S!MAP_COLUMN_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_cols = 2da_columns_to_ids_mapping
END

LAF ~S!MAP_ROW_NAMES_TO_IDS_IN_2DA_FILE~
  STR_VAR
    2da_table_name = ~weapprof.2da~
  RET_ARRAY
    weapprof_rows = 2da_rows_to_ids_mapping
END

// Allow almost all Fighters to put *** in all weapon styles but S&S

COPY_EXISTING ~weapprof.2da~  ~override/weapprof.2da~
  COUNT_2DA_COLS ~colcount~
  SET 2handed_row = $weapprof_rows("2HANDED")
  SET single_weapon_row = $weapprof_rows("SINGLEWEAPON")
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("FIGHTER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("FIGHTER_CLERIC") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("FIGHTER_MAGE") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("FIGHTER_THIEF") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("FIGHTER_MAGE_CLERIC") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("FIGHTER_MAGE_THIEF") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("FIGHTER_DRUID") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("BERSERKER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("WIZARD_SLAYER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ single_weapon_row $weapprof_cols("KENSAI") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("FIGHTER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("FIGHTER_CLERIC") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("FIGHTER_MAGE") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("FIGHTER_THIEF") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("FIGHTER_MAGE_CLERIC") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("FIGHTER_MAGE_THIEF") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("FIGHTER_DRUID") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("BERSERKER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("WIZARD_SLAYER") ~3~
  SET_2DA_ENTRY_LATER ~_#_#_#weapprof~ 2handed_row $weapprof_cols("KENSAI") ~3~
  SET_2DA_ENTRIES_NOW ~_#_#_#weapprof~ ~colcount~
  PRETTY_PRINT_2DA