IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		MoveViewObject("BAZDRA01",-1)  // Draconis
		ScreenShake([5.5],10)
		FadeToColor([30.0],0)
		Wait(2)
		ActionOverride("BAZDRA01",ReallyForceSpellRES("abzaway",Myself))
		Wait(1)
		ActionOverride("BAZDRA01",ChangeAnimation("BazDra02"))  // Draconis
		ActionOverride("BAZDRA01",ReallyForceSpellRES("SPCTMD02",Myself))  // Death Field
		Wait(1)
		CreateCreatureObjectEffect("S!ABISHG","SPPORTAL","BAZDRA02")
		CreateCreatureObjectEffect("S!ABISHG","SPPORTAL","BAZDRA02")
		ActionOverride("BAZDRA02",ReallyForceSpell(Myself,HEAL_NO_VISUAL))  // SPIN679.SPL (Heal)
		FadeFromColor([30.0],0)
		Wait(2)
		EndCutSceneMode()
END

