IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		CreateCreatureDoor("uddrow27",[4099.1668],S)  // Drow
		CreateCreatureDoor("uddrow27",[3945.1915],N)  // Drow
		CreateCreatureDoor("uddrow27",[4094.1632],S)  // Drow
		CreateCreatureDoor("drow06",[3893.1944],N)  // Drow
		CreateCreatureDoor("s!gspid1",[4152.1642],N)
		CreateCreatureDoor("drow07",[3914.1875],N)  // Drow Priestess
		Wait(4)
		ReallyForceSpellRES("SPINI22",Myself)  // No such index
		SetGlobal("Iap1nr","GLOBAL",0)
		SetGlobal("Iap2nr","GLOBAL",0)
		SetGlobal("Iap3nr","GLOBAL",0)
		SetGlobal("Iap4nr","GLOBAL",0)
		SetGlobal("Iap5nr","GLOBAL",0)
		SetGlobal("Iap6nr","GLOBAL",0)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobal("Iap6nb","GLOBAL",0)
		EndCutSceneMode()
END

