
IF
	OR(2)
		Allegiance(Myself,ENEMY)
		Range([GOODCUTOFF],75)
	Global("Prepare","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prepare","LOCALS",1)
		SetGlobalTimer("Iadraconisrest","GLOBAL",SEVEN_HOURS)
		SetGlobalTimer("absolute","LOCALS",FOUR_ROUNDS)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
		ReallyForceSpellRES("jwglobe",Myself)  // Globe of Invulnerability
		ReallyForceSpellRES("spwii10",Myself)  // Black Blade of Disaster
		ReallyForceSpellRES("spwii03",Myself)  // Spell Turning
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	GlobalTimerExpired("Iadraconisrest","GLOBAL")
	GlobalGT("Prepare","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iadraconisrest","GLOBAL",SEVEN_HOURS)
		SetGlobal("Prepare","LOCALS",0)
		SetGlobal("Prepare2","LOCALS",0)
		SetGlobal("Summon","LOCALS",0)
		SetGlobal("Iadra03","LOCALS",0)
		SetGlobal("Iadra04","LOCALS",0)
		SetGlobal("Irefreshsi","LOCALS",0)
		SetGlobal("Iadra07","LOCALS",0)
		SetGlobal("Iadra08","LOCALS",0)
		SetGlobal("Iadra09","LOCALS",0)
		SetGlobal("Iadra10","LOCALS",0)
		SetGlobal("Iadra11","LOCALS",0)
		SetGlobal("Iadra12","LOCALS",0)
		SetGlobal("Iacastbreach","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("Iabbd","LOCALS",0)
		SetGlobal("Iaabs","LOCALS",0)
		SetGlobal("Iawilting","LOCALS",0)
		SetGlobal("Ianoward","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
	!HPLT(Myself,2)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(2)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",2)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(FourthNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(FifthNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SixthNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	HPPercentLT(Myself,75)
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Prepare2","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prepare2","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	HPPercentLT(Myself,90)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalLT("Iahardiness","LOCALS",9)
	CheckStatLT(Myself,90,RESISTSLASHING)
THEN
	RESPONSE #100
		IncrementGlobal("Iahardiness","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	GlobalLT("Iadra08","LOCALS",4)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iadra08","LOCALS",1)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	OR(2)
		Range(LastSeenBy(Myself),4)
		AttackedBy(LastSeenBy(Myself),MELEE)
	OR(2)
		!GlobalTimerNotExpired("absolute","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iaabs","LOCALS",5)
THEN
	RESPONSE #100
		SetGlobalTimer("absolute","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iaabs","LOCALS",1)
		SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatGT(Myself,0,SCRIPTINGSTATE6)
	CheckStat(Myself,0,SCRIPTINGSTATE7)
	Global("Irefreshsi","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobal("Irefreshsi","LOCALS",1)
		SpellNoDec(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	GlobalLT("Iabbd","LOCALS",3)
	!HasItem("BLAKBLAD",Myself)  // Black Blade of Disaster
THEN
	RESPONSE #100
		IncrementGlobal("Iabbd","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWII10",Myself)  // Black Blade of Disaster
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Detect([PC])
	OR(2)
		!See([PC])
		!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // Spellstrike
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	Global("Iaspellstrike","AR6000",0)  // Abazigal's Entrance
	GlobalGT("Iap1nr","GLOBAL",1)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","AR6000",1)  // Abazigal's Entrance
		SetGlobal("Iap1nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9m",Player1)  // Spellstrike
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	OR(2)
		CheckStatGT(Player1,2,SCRIPTINGSTATE6)
		CheckSpellState(Player1,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // Spellstrike
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	Global("Iaspellstrike","AR6000",0)  // Abazigal's Entrance
	GlobalGT("Iap2nr","GLOBAL",1)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","AR6000",1)  // Abazigal's Entrance
		SetGlobal("Iap2nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9m",Player2)  // Spellstrike
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	OR(2)
		CheckStatGT(Player2,2,SCRIPTINGSTATE6)
		CheckSpellState(Player2,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // Spellstrike
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	Global("Iaspellstrike","AR6000",0)  // Abazigal's Entrance
	GlobalGT("Iap3nr","GLOBAL",1)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","AR6000",1)  // Abazigal's Entrance
		SetGlobal("Iap3nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9m",Player3)  // Spellstrike
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	OR(2)
		CheckStatGT(Player3,2,SCRIPTINGSTATE6)
		CheckSpellState(Player3,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // Spellstrike
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	Global("Iaspellstrike","AR6000",0)  // Abazigal's Entrance
	GlobalGT("Iap4nr","GLOBAL",1)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","AR6000",1)  // Abazigal's Entrance
		SetGlobal("Iap4nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9m",Player4)  // Spellstrike
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	OR(2)
		CheckStatGT(Player4,2,SCRIPTINGSTATE6)
		CheckSpellState(Player4,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // Spellstrike
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	Global("Iaspellstrike","AR6000",0)  // Abazigal's Entrance
	GlobalGT("Iap5nr","GLOBAL",1)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","AR6000",1)  // Abazigal's Entrance
		SetGlobal("Iap5nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9m",Player5)  // Spellstrike
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	OR(2)
		CheckStatGT(Player5,2,SCRIPTINGSTATE6)
		CheckSpellState(Player5,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // Spellstrike
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	Global("Iaspellstrike","AR6000",0)  // Abazigal's Entrance
	GlobalGT("Iap6nr","GLOBAL",1)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","AR6000",1)  // Abazigal's Entrance
		SetGlobal("Iap6nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9m",Player6)  // Spellstrike
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	OR(2)
		CheckStatGT(Player6,2,SCRIPTINGSTATE6)
		CheckSpellState(Player6,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	OR(2)
		CheckStat(Player1,2,SCRIPTINGSTATE3)
		CheckSpellState(Player1,DISPELLABLE_INCREASED_FIRE_RESISTANCE)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	Global("Iadispelpotp1","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpotp1","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	Global("Iadra12","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See([PC])
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(SecondNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(ThirdNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(FourthNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(FifthNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(SixthNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iadra09","LOCALS",0)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(3)
		CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	GlobalLT("Summon","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Summon","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iahlas","LOCALS")
	!GlobalTimerNotExpired("Iacshlas","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,8,CRITICALHITBONUS)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	HasItem("blakblad",Myself)  // Black Blade of Disaster
	GlobalLT("Iacshla","LOCALS",9)
THEN
	RESPONSE #100
		IncrementGlobal("Iacshla","LOCALS",1)
		SetGlobalTimer("Iacshlas","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iahlas","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iahlas","LOCALS")
	!GlobalTimerNotExpired("Iagwhlas","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	HasItem("blakblad",Myself)  // Black Blade of Disaster
	GlobalLT("Iagwhla","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iagwhla","LOCALS",1)
		SetGlobalTimer("Iagwhlas","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iahlas","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iahlas","LOCALS")
	!GlobalTimerNotExpired("Iagwhlas","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	HasItem("blakblad",Myself)  // Black Blade of Disaster
	GlobalLT("Iagwhla","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iagwhla","LOCALS",1)
		SetGlobalTimer("Iagwhlas","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iahlas","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	OR(3)
		CheckStatGT(LastSeenBy(Myself),99,MAGICDAMAGERESISTANCE)
		CheckSpellState(LastSeenBy(Myself),DISPELLABLE_INCREASED_FIRE_RESISTANCE)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!HPLT(Myself,2)
	See([PC])
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iadra04","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	!HPLT(Myself,2)
	Global("Iadra09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra09","LOCALS",1)
		SetGlobalTimer("Iawishcombo","LOCALS",SIX_ROUNDS)
		ForceSpellRES("SPWII26",Myself)  // Wish
		ForceSpellRES("spwish17",Myself)  // Time Stop
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	!HPLT(Myself,2)
	Global("Iadra09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra09","LOCALS",1)
		SetGlobalTimer("Iawishcombo","LOCALS",SIX_ROUNDS)
		ForceSpellRES("SPWII26",Myself)  // Wish
		ForceSpellRES("spwish17",Myself)  // Time Stop
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	!HPLT(Myself,2)
	Global("Iadra09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra09","LOCALS",1)
		SetGlobalTimer("Iawishcombo","LOCALS",SIX_ROUNDS)
		ForceSpellRES("SPWII26",Myself)  // Wish
		ForceSpellRES("spwish17",Myself)  // Time Stop
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	!HPLT(Myself,2)
	Global("Iadra09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra09","LOCALS",1)
		SetGlobalTimer("Iawishcombo","LOCALS",SIX_ROUNDS)
		ForceSpellRES("SPWII26",Myself)  // Wish
		ForceSpellRES("spwish17",Myself)  // Time Stop
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	!HPLT(Myself,2)
	Global("Iadra09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra09","LOCALS",1)
		SetGlobalTimer("Iawishcombo","LOCALS",SIX_ROUNDS)
		ForceSpellRES("SPWII26",Myself)  // Wish
		ForceSpellRES("spwish17",Myself)  // Time Stop
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	!HPLT(Myself,2)
	Global("Iadra09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra09","LOCALS",1)
		SetGlobalTimer("Iawishcombo","LOCALS",SIX_ROUNDS)
		ForceSpellRES("SPWII26",Myself)  // Wish
		ForceSpellRES("spwish17",Myself)  // Time Stop
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	!HPLT(Myself,2)
	Global("Iadra09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra09","LOCALS",1)
		SetGlobalTimer("Iawishcombo","LOCALS",SIX_ROUNDS)
		ForceSpellRES("SPWII26",Myself)  // Wish
		ForceSpellRES("spwish17",Myself)  // Time Stop
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iadra09","LOCALS",1)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	OR(3)
		CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	GlobalLT("Summon","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Summon","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iaadhwtime","LOCALS")
	Global("Iadra09","LOCALS",1)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iawilting","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iawilting","LOCALS",1)
		SetGlobalTimer("Iaadhwtime","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iaadhwtime","LOCALS")
	Global("Iadra09","LOCALS",1)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iawilting","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iawilting","LOCALS",1)
		SetGlobalTimer("Iaadhwtime","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iaadhwtime","LOCALS")
	Global("Iadra09","LOCALS",1)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iawilting","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iawilting","LOCALS",1)
		SetGlobalTimer("Iaadhwtime","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iaadhwtime","LOCALS")
	Global("Iadra09","LOCALS",1)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iawilting","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iawilting","LOCALS",1)
		SetGlobalTimer("Iaadhwtime","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iadra07","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iadra07","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iadra07","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	GlobalGT("Prepare","LOCALS",0)
	!HPLT(Myself,2)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	GlobalGT("Prepare","LOCALS",0)
	!HPLT(Myself,2)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	!HPLT(Myself,2)
	GlobalGT("Prepare","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prepare","LOCALS",0)
		SetGlobal("Prepare2","LOCALS",0)
		SetGlobal("Summon","LOCALS",0)
		SetGlobal("Iadra03","LOCALS",0)
		SetGlobal("Iadra04","LOCALS",0)
		SetGlobal("Irefreshsi","LOCALS",0)
		SetGlobal("Iadra07","LOCALS",0)
		SetGlobal("Iadra08","LOCALS",0)
		SetGlobal("Iadra09","LOCALS",0)
		SetGlobal("Iadra10","LOCALS",0)
		SetGlobal("Iadra11","LOCALS",0)
		SetGlobal("Iadra12","LOCALS",0)
		SetGlobal("Iacastbreach","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("Iabbd","LOCALS",0)
		SetGlobal("Iaabs","LOCALS",0)
		SetGlobal("Iawilting","LOCALS",0)
		SetGlobal("Ianoward","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	ActionListEmpty()
	!HPLT(Myself,2)
	HasItem("blakblad",Myself)  // Black Blade of Disaster
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
	HasItem("blakblad",Myself)  // Black Blade of Disaster
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
	HasItem("blakblad",Myself)  // Black Blade of Disaster
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
	HasItem("blakblad",Myself)  // Black Blade of Disaster
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
	HasItem("blakblad",Myself)  // Black Blade of Disaster
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HPLT(Myself,2)
	!HasItem("blakblad",Myself)  // Black Blade of Disaster
	GlobalLT("Iamissile","LOCALS",5)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HPLT(Myself,2)
	!HasItem("blakblad",Myself)  // Black Blade of Disaster
	GlobalLT("Iamissile","LOCALS",5)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HPLT(Myself,2)
	!HasItem("blakblad",Myself)  // Black Blade of Disaster
	GlobalLT("Iamissile","LOCALS",5)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),99,MAGICDAMAGERESISTANCE)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
		CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
		Global("Iamissile","LOCALS",5)
	!HPLT(Myself,2)
	!HasItem("blakblad",Myself)  // Black Blade of Disaster
THEN
	RESPONSE #100
		RunAwayFrom(NearestEnemyOf(Myself),45)
END
