IF
	Allegiance(Myself,ENEMY)
	HPLT(Myself,10)
	Global("Iagrestore","AR0530",0)  // Storehouse
THEN
	RESPONSE #100
		SetGlobal("Iagrestore","AR0530",1)  // Storehouse
		Continue()
END

IF
	Global("Iagrestore","AR0530",2)  // Storehouse
	Global("Iapcastts","GLOBAL",0)
	HasItem("bhaalhp1",Myself)  // No such index
THEN
	RESPONSE #100
		DestroyItem("bhaalhp1")  // No such index
		Continue()
END


IF
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("IaRestTimer","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("IaPrep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("IaPrep","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
		Continue()
END

IF
	!See([PC])
	!See([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("IaPrep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("IaRestTimer","LOCALS",SEVEN_HOURS)
		SetGlobal("partyfled","LOCALS",1)
END



IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
		Continue()
END

IF
	Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		NoAction()
END



IF
    ActionListEmpty()
	See(Player1)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar1SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar1Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player2)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar2SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar2Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player3)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar3SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar3Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player4)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar4SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar4Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player5)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar5SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar5Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player6)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar6SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar6Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar1SeenTimer","LOCALS")
	Global("IaChar1Seen","LOCALS",1)
	!See(Player1)
THEN
	RESPONSE #100
		SetGlobal("IaChar1Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar2SeenTimer","LOCALS")
	Global("IaChar2Seen","LOCALS",1)
	!See(Player2)
THEN
	RESPONSE #100
		SetGlobal("IaChar2Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar3SeenTimer","LOCALS")
	Global("IaChar3Seen","LOCALS",1)
	!See(Player3)
THEN
	RESPONSE #100
		SetGlobal("IaChar3Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar4SeenTimer","LOCALS")
	Global("IaChar4Seen","LOCALS",1)
	!See(Player4)
THEN
	RESPONSE #100
		SetGlobal("IaChar4Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar5SeenTimer","LOCALS")
	Global("IaChar5Seen","LOCALS",1)
	!See(Player5)
THEN
	RESPONSE #100
		SetGlobal("IaChar5Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar6SeenTimer","LOCALS")
	Global("IaChar6Seen","LOCALS",1)
	!See(Player6)
THEN
	RESPONSE #100
		SetGlobal("IaChar6Seen","LOCALS",0)
		Continue()
END


IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStat(Myself,2,SCRIPTINGSTATE3)
	HasItem("potn35",Myself)  // Potion of Magic Shielding
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn35",Myself)  // Potion of Magic Shielding
END
IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_HARDINESS)
	!CheckSpellState(Myself,HARDINESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	OR(3)
	    See(ThirdNearestEnemyOf(Myself))
	    See(SecondNearestEnemyOf(Myself))
	    See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
		RemoveSpell(WARRIOR_HARDINESS)
END

IF
	HaveSpell(WARRIOR_GREATER_WHIRLWIND)
	Detect(NearestEnemyOf(Myself))
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaWhirlwindTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaWhirlwindTimer","LOCALS",THREE_ROUNDS)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)
		RemoveSpell(WARRIOR_GREATER_WHIRLWIND)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,50)
	HasItem("potn55",Myself)  // Potion of Superior Healing
	!GlobalTimerNotExpired("IaAction","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn55",Myself)  // Potion of Superior Healing
END

IF
	HaveSpell(WARRIOR_WHIRLWIND)
	Detect(NearestEnemyOf(Myself))
	CheckStat(Myself,0,IMPROVEDHASTE)
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaWhirlwindTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaWhirlwindTimer","LOCALS",THREE_ROUNDS)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)
		RemoveSpell(WARRIOR_WHIRLWIND)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaSmite","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(NearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaSmite","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SecondNearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaSmite","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	HaveSpell(WARRIOR_WHIRLWIND)
	!HaveSpell(WARRIOR_GREATER_WHIRLWIND)
	Detect(NearestEnemyOf(Myself))
	CheckStat(Myself,0,IMPROVEDHASTE)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!GlobalTimerNotExpired("IaAction","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)
		RemoveSpell(WARRIOR_WHIRLWIND)
	RESPONSE #0
	    Continue()
END



IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState([PC],STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FourthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FifthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SixthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC.0.0.MAGE_ALL],3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC],3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC]),3)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC.0.0.MAGE_ALL],6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC],6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC]),6)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC.0.0.MAGE_ALL],10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC],10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC]),10)
    HasItem("HALB01",Myself)
THEN
	RESPONSE #100
		XEquipItem("HALB01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
        CheckStatGT([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	    !CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
        CheckStatGT([PC.0.0.DRUID_ALL],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	    !CheckSpellState([PC.0.0.DRUID_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([PC.0.0.DRUID_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
        CheckStatGT([PC.0.0.THIEF_ALL],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	    !CheckSpellState([PC.0.0.THIEF_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([PC.0.0.THIEF_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([PC],1,SCRIPTINGSTATE6)
        CheckStatGT([PC],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	    !CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
        CheckStatGT([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	    !CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
        CheckStatGT([PC.0.0.DRUID_ALL],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	    !CheckSpellState([PC.0.0.DRUID_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([PC.0.0.DRUID_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
        CheckStatGT([PC.0.0.THIEF_ALL],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	    !CheckSpellState([PC.0.0.THIEF_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([PC.0.0.THIEF_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([PC],1,SCRIPTINGSTATE6)
        CheckStatGT([PC],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	    !CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
        CheckStatGT(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([GOODCUTOFF])
	CheckStatLT([GOODCUTOFF],100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT([GOODCUTOFF],1,SCRIPTINGSTATE6)
        CheckStatGT([GOODCUTOFF],3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT([GOODCUTOFF],1,SCRIPTINGSTATE6)
	    !CheckSpellState([GOODCUTOFF],PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(SecondNearest([GOODCUTOFF]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SecondNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
        CheckStatGT(SecondNearest([GOODCUTOFF]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SecondNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SecondNearest([GOODCUTOFF]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(ThirdNearest([GOODCUTOFF]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(ThirdNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
        CheckStatGT(ThirdNearest([GOODCUTOFF]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(ThirdNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(ThirdNearest([GOODCUTOFF]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(FourthNearest([GOODCUTOFF]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(FourthNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
        CheckStatGT(FourthNearest([GOODCUTOFF]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(FourthNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(FourthNearest([GOODCUTOFF]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(FifthNearest([GOODCUTOFF]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(FifthNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
        CheckStatGT(FifthNearest([GOODCUTOFF]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(FifthNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(FifthNearest([GOODCUTOFF]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(SixthNearest([GOODCUTOFF]),100,RESISTPIERCING) // PIERCING/CRUSHING/SLASHING
	OR(2)
        !CheckStatGT(SixthNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
        CheckStatGT(SixthNearest([GOODCUTOFF]),3,SCRIPTINGSTATE6)
	OR(2)
        !CheckStatGT(SixthNearest([GOODCUTOFF]),1,SCRIPTINGSTATE6)
	    !CheckSpellState(SixthNearest([GOODCUTOFF]),PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END



IF
	!GlobalTimerNotExpired("IaWeaponUnusable","LOCALS")
	OR(2)
        !WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
        !WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
	    SetGlobalTimer("IaWeaponUnusable","LOCALS",ONE_ROUND)
		ClearActions(Myself)
END



IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar1Seen","LOCALS",1)
	!See(Player1)
	!HPLT(Player1,0)
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar2Seen","LOCALS",1)
	!See(Player2)
	!HPLT(Player2,0)
	InMyArea(Player2)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar3Seen","LOCALS",1)
	!See(Player3)
	!HPLT(Player3,0)
	InMyArea(Player3)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar4Seen","LOCALS",1)
	!See(Player4)
	!HPLT(Player4,0)
	InMyArea(Player4)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar5Seen","LOCALS",1)
	!See(Player5)
	!HPLT(Player5,0)
	InMyArea(Player5)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar6Seen","LOCALS",1)
	!See(Player6)
	!HPLT(Player6,0)
	InMyArea(Player6)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END


IF
	See(NearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FifthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SixthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

