
IF
	!See([PC])
	InMyArea(Player1)
	NumberOfTimesTalkedTo(0)
	Global("Iapcastts","GLOBAL",0)
	Global("IaInitialWait","LOCALS",0)
THEN
	RESPONSE #100
	    SetInterrupt(FALSE)
	    SetGlobal("IaInitialWait","LOCALS",1)
	    Wait(5)
	    SetInterrupt(TRUE)
END

IF
	!See([PC])
	InMyArea(Player1)
	NumberOfTimesTalkedTo(0)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	See([PC])
	NumberOfTimesTalkedTo(0)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
	    AddAreaFlag(NOREST)
		StartDialogueNoSet([PC])
END

IF
	Die()
THEN
	RESPONSE #100
	    RemoveAreaFlag(NOREST)
END

IF
	GlobalGT("IaUndeadWaves","GLOBAL",0)
	GlobalLT("IaUndeadWaves","GLOBAL",4)
THEN
	RESPONSE #100
		NoAction()
END

IF
	Global("IaUndeadWaves","GLOBAL",4)
	Global("IaTeleportBack","LOCALS",0)
THEN
	RESPONSE #100
	    SetGlobal("IaTeleportBack","LOCALS",1)
		JumpToPoint([1885.1736])
		SetGlobal("IaPrep","LOCALS",0)
		SetGlobal("Iaonewing","LOCALS",0)
		Rest()
END

IF
	InMyArea(Player1)
	XPLT(Player1,3000000)
	Global("IaToneDown","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaToneDown","LOCALS",2)
		SetGlobal("Iamywail","LOCALS",5)
		RemoveSpellRES("SPIN692")
		RemoveSpellRES("SPIN692")
END

IF
	InMyArea(Player1)
	XPLT(Player1,3400000)
	Global("IaToneDown","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaToneDown","LOCALS",1)
		SetGlobal("Iamywail","LOCALS",4)
		RemoveSpellRES("SPIN692")
END

IF
	InMyArea(Player1)
	OR(2)
		NumberOfTimesTalkedTo(0)
		Global("IaPrep","LOCALS",0)
	Global("Iareaction","ARia14",0)
	OR(5)
		AttackedBy([GOODCUTOFF],DEFAULT)
		AttackedBy([PC],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([PC],0)
		TookDamage()
THEN
	RESPONSE #100
		SetGlobal("Iareaction","ARia14",1)
END

IF
	Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	OR(2)
		See(NearestEnemyOf(Myself))
		Global("Iareaction","ARia14",1)
	Global("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaPrep","LOCALS",1)
		ReallyForceSpellRES("SPWII03",Myself)  // Spell Turning
		ReallyForceSpell(Myself,DRAGON_STONE_SKIN)  // SPIN694.SPL (Stoneskin)
		SetGlobal("Iaattack","LOCALS",2)
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iaaxeplace","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("Iaaxeplace","GLOBAL",4)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("ax1h10",Myself,0,0,0)  // Azuredge +3
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure2","LOCALS",0)
	Global("Iamanaplace","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("Iamanaplace","GLOBAL",3)
		SetGlobal("Iatreasure2","LOCALS",1)
		GiveItemCreate("bow13",Myself,0,0,0)  // Mana Bow +4
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure3","LOCALS",0)
	Global("Iakundaneplace","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("Iakundaneplace","GLOBAL",4)
		SetGlobal("Iatreasure3","LOCALS",1)
		GiveItemCreate("sw1h25",Myself,0,0,0)  // Kundane +2
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure4","LOCALS",0)
	Global("Iaperiaptplace","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("Iaperiaptplace","GLOBAL",4)
		SetGlobal("Iatreasure4","LOCALS",1)
		GiveItemCreate("amul22",Myself,0,0,0)  // Periapt of Proof Against Poison
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure5","LOCALS",0)
	Global("Iamalakplace","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("Iamalakplace","GLOBAL",5)
		SetGlobal("Iatreasure5","LOCALS",1)
		GiveItemCreate("sw1h45",Myself,0,0,0)  // Malakar +2
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure6","LOCALS",0)
	Global("Iafotnplace","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("Iafotnplace","GLOBAL",3)
		SetGlobal("Iatreasure6","LOCALS",1)
		GiveItemCreate("sw2h12",Myself,0,0,0)  // Flame of the North +2
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure7","LOCALS",0)
	Global("Iarynnplace","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("Iarynnplace","GLOBAL",5)
		SetGlobal("Iatreasure7","LOCALS",1)
		GiveItemCreate("staf20",Myself,0,0,0)  // Staff of Rhynn +4
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	See(NearestEnemyOf(Myself))
	!Global("Chapter","GLOBAL",5)
	Global("IAchaptercheck","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IAchaptercheck","LOCALS",1)
		DestroyGold(5000)
		DestroyItem("S!scrl02")
		DestroyItem("S!scrl03")
		DestroyItem("potn33")  // Barbarian Essence
		DestroyItem("S!scrl09")
		DestroyItem("scrla4")  // Limited Wish
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	CheckStat(Myself,0,SCRIPTINGSTATE6)
	HPPercentLT(Myself,100)
	Global("IaSpellTrigger","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellTrigger","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FIVE_MINUTES)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		DisplayString(Myself,@6267)
		CreateCreatureObjectEffect("s!skelre","SPRAISED","S!DRACOL") 
		ReallyForceSpell(Myself,DRAGON_STONE_SKIN)  // SPIN694.SPL (Stoneskin)
		ReallyForceSpellRES("SPWII01",Myself)  // Spell Shield
END


IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer1","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player1)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer1","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer2","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player2)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer2","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer3","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player3)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer3","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer4","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player4)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer4","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer5","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player5)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer5","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer6","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player6)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer6","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END


IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaCharmUndead","LOCALS")
	See([GOODCUTOFF.UNDEAD])
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@5126)
		SetGlobalTimer("IaCharmUndead","LOCALS",TWO_ROUNDS)
		ForceSpellRES("S!CHRUND",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END


IF
	Allegiance(Myself,ENEMY)
	HPPercentLT(Myself,90)
    !GlobalTimerNotExpired("IaDrainUndead","LOCALS")
	See([EVILCUTOFF.UNDEAD])
THEN
	RESPONSE #100
		SetGlobalTimer("IaDrainUndead","LOCALS",5)
		ForceSpellRES("S!DRAINL",LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END


IF
	Allegiance(Myself,ENEMY)
	CheckStatLT(Myself,1,STONESKINS)
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,50)
	Global("IaContingency","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaContingency","LOCALS",1)
		DisplayString(Myself,29736)  // Contingency—Stoneskin
		ReallyForceSpell(Myself,DRAGON_STONE_SKIN)  // SPIN694.SPL (Stoneskin)
END
IF
    HaveSpell(DRAGON_STONE_SKIN)
	Allegiance(Myself,ENEMY)
	HPPercentLT(Myself,50)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		RemoveSpell(DRAGON_STONE_SKIN)
		ForceSpell(Myself,DRAGON_STONE_SKIN)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,51,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE3)
	CheckStatGT(Player1,7,SAVEVSDEATH)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,51,RESISTMAGIC)
	!CheckStat(Player2,2,SCRIPTINGSTATE3)
	CheckStatGT(Player2,7,SAVEVSDEATH)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,51,RESISTMAGIC)
	!CheckStat(Player3,2,SCRIPTINGSTATE3)
	CheckStatGT(Player3,7,SAVEVSDEATH)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,51,RESISTMAGIC)
	!CheckStat(Player4,2,SCRIPTINGSTATE3)
	CheckStatGT(Player4,7,SAVEVSDEATH)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,51,RESISTMAGIC)
	!CheckStat(Player5,2,SCRIPTINGSTATE3)
	CheckStatGT(Player5,7,SAVEVSDEATH)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,51,RESISTMAGIC)
	!CheckStat(Player6,2,SCRIPTINGSTATE3)
	CheckStatGT(Player6,7,SAVEVSDEATH)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,51,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE3)
	CheckStatGT(Player1,7,SAVEVSDEATH)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,51,RESISTMAGIC)
	!CheckStat(Player2,2,SCRIPTINGSTATE3)
	CheckStatGT(Player2,7,SAVEVSDEATH)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,51,RESISTMAGIC)
	!CheckStat(Player3,2,SCRIPTINGSTATE3)
	CheckStatGT(Player3,7,SAVEVSDEATH)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,51,RESISTMAGIC)
	!CheckStat(Player4,2,SCRIPTINGSTATE3)
	CheckStatGT(Player4,7,SAVEVSDEATH)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,51,RESISTMAGIC)
	!CheckStat(Player5,2,SCRIPTINGSTATE3)
	CheckStatGT(Player5,7,SAVEVSDEATH)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,51,RESISTMAGIC)
	!CheckStat(Player6,2,SCRIPTINGSTATE3)
	CheckStatGT(Player6,7,SAVEVSDEATH)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,51,RESISTMAGIC)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	!CheckStat(Player1,2,SCRIPTINGSTATE3)
	CheckStatGT(Player1,7,SAVEVSDEATH)
	!HasBounceEffects(Player1)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,51,RESISTMAGIC)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
	!CheckStat(Player2,2,SCRIPTINGSTATE3)
	CheckStatGT(Player2,7,SAVEVSDEATH)
	!HasBounceEffects(Player2)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,51,RESISTMAGIC)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
	!CheckStat(Player3,2,SCRIPTINGSTATE3)
	CheckStatGT(Player3,7,SAVEVSDEATH)
	!HasBounceEffects(Player3)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,51,RESISTMAGIC)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
	!CheckStat(Player4,2,SCRIPTINGSTATE3)
	CheckStatGT(Player4,7,SAVEVSDEATH)
	!HasBounceEffects(Player4)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,51,RESISTMAGIC)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
	!CheckStat(Player5,2,SCRIPTINGSTATE3)
	CheckStatGT(Player5,7,SAVEVSDEATH)
	!HasBounceEffects(Player5)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,51,RESISTMAGIC)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
	!CheckStat(Player6,2,SCRIPTINGSTATE3)
	CheckStatGT(Player6,7,SAVEVSDEATH)
	!HasBounceEffects(Player6)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END


IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	OR(3)
		CheckStatLT(LastSeenBy(Myself),8,SAVEVSBREATH)
		CheckStatLT(LastSeenBy(Myself),8,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),-8,THAC0)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!GlobalTimerNotExpired("Iagdoom","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iagdoom","LOCALS",15)
		ForceSpellRES("SPINI68",LastSeenBy(Myself))  // Greater Doom
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	OR(3)
		CheckStatLT(LastSeenBy(Myself),8,SAVEVSBREATH)
		CheckStatLT(LastSeenBy(Myself),8,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),-8,THAC0)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!GlobalTimerNotExpired("Iagdoom","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iagdoom","LOCALS",15)
		ForceSpellRES("SPINI68",LastSeenBy(Myself))  // Greater Doom
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(ThirdNearest([PC]))
	OR(3)
		CheckStatLT(LastSeenBy(Myself),8,SAVEVSBREATH)
		CheckStatLT(LastSeenBy(Myself),8,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),-8,THAC0)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!GlobalTimerNotExpired("Iagdoom","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iagdoom","LOCALS",15)
		ForceSpellRES("SPINI68",LastSeenBy(Myself))  // Greater Doom
END


IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaonewing","LOCALS",0)
	Global("Iafog","ARia14",0)
	!GlobalTimerNotExpired("MyTimer","LOCALS")
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("Iafog","ARia14",1)
		SetGlobalTimer("FogTimer","ARia14",FIVE_ROUNDS)
		SetGlobalTimer("MyTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		Wait(1)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		Wait(1)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		Wait(1)
		SetInterrupt(TRUE)
END



IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
    CheckStatGT([PC],10,DISPELLABLEBUFFSPOWER)
	TriggerOverride([PC], Range([PC], 15))
	TriggerOverride([PC], CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride([PC], CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
    CheckStatGT([PC],10,DISPELLABLEBUFFSPOWER)
	TriggerOverride([PC], Range(SecondNearest([PC]), 15))
	TriggerOverride([PC], CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride([PC], CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
    CheckStatGT([PC],10,DISPELLABLEBUFFSPOWER)
	TriggerOverride([PC], Range(ThirdNearest([PC]), 15))
	TriggerOverride([PC], CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride([PC], CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
    CheckStatGT(SecondNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SecondNearest([PC]), Range([PC], 15))
	TriggerOverride(SecondNearest([PC]), CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SecondNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
    CheckStatGT(SecondNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SecondNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(SecondNearest([PC]), CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SecondNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
    CheckStatGT(SecondNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(SecondNearest([PC]), CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SecondNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
    CheckStatGT(ThirdNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(ThirdNearest([PC]), Range([PC], 15))
	TriggerOverride(ThirdNearest([PC]), CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(ThirdNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
    CheckStatGT(ThirdNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(ThirdNearest([PC]), CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(ThirdNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
    CheckStatGT(ThirdNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(ThirdNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(ThirdNearest([PC]), CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(ThirdNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
    CheckStatGT(FourthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FourthNearest([PC]), Range([PC], 15))
	TriggerOverride(FourthNearest([PC]), CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FourthNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
    CheckStatGT(FourthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(FourthNearest([PC]), CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FourthNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
    CheckStatGT(FourthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(FourthNearest([PC]), CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FourthNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
    CheckStatGT(FifthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FifthNearest([PC]), Range([PC], 15))
	TriggerOverride(FifthNearest([PC]), CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FifthNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
    CheckStatGT(FifthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(FifthNearest([PC]), CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FifthNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
    CheckStatGT(FifthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(FifthNearest([PC]), CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FifthNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
    CheckStatGT(SixthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SixthNearest([PC]), Range([PC], 15))
	TriggerOverride(SixthNearest([PC]), CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SixthNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
    CheckStatGT(SixthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(SixthNearest([PC]), CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SixthNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
    CheckStatGT(SixthNearest([PC]),10,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(SixthNearest([PC]), CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SixthNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END


IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
    CheckStatGT([PC],12,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
    CheckStatGT(SecondNearest([PC]),12,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
    CheckStatGT(ThirdNearest([PC]),12,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
    CheckStatGT(FourthNearest([PC]),12,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
    CheckStatGT(FifthNearest([PC]),12,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
    CheckStatGT(SixthNearest([PC]),12,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",18)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END



IF
    HaveSpell(WIZARD_DEATH_SPELL)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaDeathSpellWait","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	OR(3)
		CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStat(LastSeenBy(Myself),89,RESISTMAGIC)
	TriggerOverride(LastSeenBy(Myself), Range([GOODCUTOFF.0.0.0.0.SUMMONED], 15))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		SetGlobalTimer("IaDeathSpellWait","LOCALS",1)
		RemoveSpell(WIZARD_DEATH_SPELL)
		ForceSpell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #25
	    Continue()
END


IF
	Allegiance(Myself,ENEMY)
	See([PC])
	Range(LastSeenBy(Myself),11)
	Global("Iaonewing","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaonewing","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
		SetGlobalTimer("Iaattacking","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iaattack","LOCALS",1)
	GlobalTimerExpired("Iaattacking","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",2)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Iaattacking","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Global("Iaattack","LOCALS",1)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Iaattacking","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Global("Iaattack","LOCALS",1)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END



IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See([PC])
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SecondNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(ThirdNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FourthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FifthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SixthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END


IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See([PC])
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SecondNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(ThirdNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FourthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FifthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SixthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckSpellState(LastSeenBy(Myself),HARDINESS)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END


IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See([PC])
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SecondNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(ThirdNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FourthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FifthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SixthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),10,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),6,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #50
	    Continue()
END


IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See([PC])
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SecondNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(ThirdNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FourthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FifthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SixthNearest([PC]))
	!CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE2)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        CheckStatGT(LastSeenBy(Myself),5,BREACHABLESPECIFICBUFFSPOWER)
	OR(2)
        CheckStatGT(LastSeenBy(Myself),4,BREACHABLECOMBATBUFFSPOWER)
        !CheckSpellState(LastSeenBy(Myself),REMOVE_SPECIFIC_PROTS_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",2)
		RemoveSpell(WIZARD_BREACH)
		ForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
	RESPONSE #250
	    Continue()
END



IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	OR(2)
	    HaveSpell(WIZARD_REMOVE_MAGIC)
	    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See([PC])
	CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	OR(2)
	    HaveSpell(WIZARD_REMOVE_MAGIC)
	    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SecondNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	OR(2)
	    HaveSpell(WIZARD_REMOVE_MAGIC)
	    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(ThirdNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	OR(2)
	    HaveSpell(WIZARD_REMOVE_MAGIC)
	    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FourthNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	OR(2)
	    HaveSpell(WIZARD_REMOVE_MAGIC)
	    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FifthNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	OR(2)
	    HaveSpell(WIZARD_REMOVE_MAGIC)
	    HaveSpell(WIZARD_BREACH)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SixthNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END



IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
    CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER)
	TriggerOverride([PC], Range([PC], 15))
	TriggerOverride([PC], CheckStatGT([PC],5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride([PC], CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
    CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER)
	TriggerOverride([PC], Range(SecondNearest([PC]), 15))
	TriggerOverride([PC], CheckStatGT(SecondNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride([PC], CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
    CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER)
	TriggerOverride([PC], Range(ThirdNearest([PC]), 15))
	TriggerOverride([PC], CheckStatGT(ThirdNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride([PC], CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
    CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SecondNearest([PC]), Range([PC], 15))
	TriggerOverride(SecondNearest([PC]), CheckStatGT([PC],5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SecondNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
    CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SecondNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(SecondNearest([PC]), CheckStatGT(SecondNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SecondNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
    CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(SecondNearest([PC]), CheckStatGT(ThirdNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SecondNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
    CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(ThirdNearest([PC]), Range([PC], 15))
	TriggerOverride(ThirdNearest([PC]), CheckStatGT([PC],5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(ThirdNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
    CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(ThirdNearest([PC]), CheckStatGT(SecondNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(ThirdNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
    CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(ThirdNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(ThirdNearest([PC]), CheckStatGT(ThirdNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(ThirdNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
    CheckStatGT(FourthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FourthNearest([PC]), Range([PC], 15))
	TriggerOverride(FourthNearest([PC]), CheckStatGT([PC],5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FourthNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
    CheckStatGT(FourthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(FourthNearest([PC]), CheckStatGT(SecondNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FourthNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
    CheckStatGT(FourthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(FourthNearest([PC]), CheckStatGT(ThirdNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FourthNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
    CheckStatGT(FifthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FifthNearest([PC]), Range([PC], 15))
	TriggerOverride(FifthNearest([PC]), CheckStatGT([PC],5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FifthNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
    CheckStatGT(FifthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(FifthNearest([PC]), CheckStatGT(SecondNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FifthNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
    CheckStatGT(FifthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(FifthNearest([PC]), CheckStatGT(ThirdNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(FifthNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
    CheckStatGT(SixthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SixthNearest([PC]), Range([PC], 15))
	TriggerOverride(SixthNearest([PC]), CheckStatGT([PC],5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SixthNearest([PC]), CheckStat([PC],1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
    CheckStatGT(SixthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 15))
	TriggerOverride(SixthNearest([PC]), CheckStatGT(SecondNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SixthNearest([PC]), CheckStat(SecondNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
    CheckStatGT(SixthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 15))
	TriggerOverride(SixthNearest([PC]), CheckStatGT(ThirdNearest([PC]),5,DISPELLABLEBUFFSPOWER))
	!TriggerOverride(SixthNearest([PC]), CheckStat(ThirdNearest([PC]),1,SCRIPTINGSTATE7))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #150
	    Continue()
END


IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
    CheckStatGT([PC],8,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
    CheckStatGT(SecondNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
    CheckStatGT(ThirdNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
    CheckStatGT(FourthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
    CheckStatGT(FifthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #250
	    Continue()
END

IF
    HaveSpell(WIZARD_REMOVE_MAGIC)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaRemoveMagicWait","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
    CheckStatGT(SixthNearest([PC]),8,DISPELLABLEBUFFSPOWER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaRemoveMagicWait","LOCALS",24)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_REMOVE_MAGIC)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #250
	    Continue()
END


IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		Wait(1)
		SetInterrupt(TRUE)
END


IF
    HaveSpell(WIZARD_LOWER_RESISTANCE)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),110,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),30,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		RemoveSpell(WIZARD_LOWER_RESISTANCE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_LOWER_RESISTANCE)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),110,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),30,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		RemoveSpell(WIZARD_LOWER_RESISTANCE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_LOWER_RESISTANCE)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),110,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),30,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		RemoveSpell(WIZARD_LOWER_RESISTANCE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_LOWER_RESISTANCE)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(FourthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),110,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),30,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		RemoveSpell(WIZARD_LOWER_RESISTANCE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_LOWER_RESISTANCE)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(FifthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),110,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),30,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		RemoveSpell(WIZARD_LOWER_RESISTANCE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_LOWER_RESISTANCE)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(SixthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),110,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),30,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		RemoveSpell(WIZARD_LOWER_RESISTANCE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
	RESPONSE #50
	    Continue()
END



IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SixthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(SixthNearest([PC]), Range([PC], 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SixthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SixthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FifthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(FifthNearest([PC]), Range([PC], 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FifthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FifthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FourthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(FourthNearest([PC]), Range([PC], 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FourthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FourthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(ThirdNearest([PC]), Range([PC], 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(ThirdNearest([PC]), Range(ThirdNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(SecondNearest([PC]), Range([PC], 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(SecondNearest([PC]), Range(SecondNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride([PC], Range([PC], 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride([PC], Range(SecondNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	TriggerOverride([PC], Range(ThirdNearest([PC]), 15))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #25
	    Continue()
END


IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SixthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FifthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FourthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Global("IaSpellSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaSpellSequencer","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
	RESPONSE #100
	    Continue()
END



IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See([PC])
	CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SecondNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(ThirdNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FourthNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(FifthNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END

IF
	HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaProtRemovalWait","LOCALS")
	See(SixthNearest([PC]))
	CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaProtRemovalWait","LOCALS",1)
		RemoveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
		ForceSpell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
	RESPONSE #200
	    Continue()
END


IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawail","LOCALS")
	GlobalLT("Iamywail","LOCALS",5)
	See([PC])
	Range(LastSeenBy(Myself),13)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSDEATH)
THEN
	RESPONSE #100
		IncrementGlobal("Iamywail","LOCALS",1)
		SetGlobalTimer("Iawail","LOCALS",THREE_ROUNDS)
		ForceSpellRES("SPINI31",Myself)  // Wail of Dracolich
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawail","LOCALS")
	GlobalLT("Iamywail","LOCALS",5)
	See(SecondNearest([PC]))
	Range(LastSeenBy(Myself),13)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSDEATH)
THEN
	RESPONSE #100
		IncrementGlobal("Iamywail","LOCALS",1)
		SetGlobalTimer("Iawail","LOCALS",THREE_ROUNDS)
		ForceSpellRES("SPINI31",Myself)  // Wail of Dracolich
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawail","LOCALS")
	GlobalLT("Iamywail","LOCALS",5)
	See(ThirdNearest([PC]))
	Range(LastSeenBy(Myself),13)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSDEATH)
THEN
	RESPONSE #100
		IncrementGlobal("Iamywail","LOCALS",1)
		SetGlobalTimer("Iawail","LOCALS",THREE_ROUNDS)
		ForceSpellRES("SPINI31",Myself)  // Wail of Dracolich
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawail","LOCALS")
	GlobalLT("Iamywail","LOCALS",5)
	See([GOODCUTOFF])
	!Gender(LastSeenBy(Myself),SUMMONED)
	Range(LastSeenBy(Myself),13)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!HasItemEquiped("S!skelsu",LastSeenBy(Myself))
	!HasItemEquiped("S!spidsu",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		IncrementGlobal("Iamywail","LOCALS",1)
		SetGlobalTimer("Iawail","LOCALS",THREE_ROUNDS)
		ForceSpellRES("SPINI31",Myself)  // Wail of Dracolich
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	Range(LastSeenBy(Myself),11)
	Global("Iaonewing","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaonewing","LOCALS",2)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
		SetGlobal("Iafog","ARia14",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",0)
	See([PC])
	Range(LastSeenBy(Myself),15)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",0)
	See(SecondNearest([PC]))
	Range(LastSeenBy(Myself),15)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",0)
	See(ThirdNearest([PC]))
	Range(LastSeenBy(Myself),15)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END


IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END


IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #100
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #100
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #100
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #100
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #100
	    Continue()
END

IF
    HaveSpell(WIZARD_CHAOS)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!SEEAOE",Myself)
		RemoveSpell(WIZARD_CHAOS)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		ReallyForceSpellRES("S!SEEREM",Myself)
		SetInterrupt(TRUE)
	RESPONSE #100
	    Continue()
END


IF
	See(NearestEnemyOf(Myself))
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
	Global("DRAGONFEAR","LOCALS",0)
THEN
	RESPONSE #100
		ReallyForceSpell(LastSeenBy(Myself),DRAGON_FEAR)  // SPIN895.SPL (Dragon Fear)
		SetGlobal("DRAGONFEAR","LOCALS",1)
		SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",1)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
END

IF
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
	Global("WingBuffet","LOCALS",0)
THEN
	RESPONSE #70
		SetGlobal("WingBuffet","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
		SetGlobal("Iafog","ARia14",0)
	RESPONSE #30
		SetGlobal("WingBuffet","LOCALS",1)
END

IF
	!GlobalTimerNotExpired("IaWingBuffetUnlimited","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
THEN
	RESPONSE #70
		SetGlobalTimer("IaWingBuffetUnlimited","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
		SetGlobal("Iafog","ARia14",0)
	RESPONSE #30
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!HasItemEquiped("S!skelsu",LastSeenBy(Myself))
	!HasItemEquiped("S!swansu",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gswan",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!swanq",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gscim",LastSeenBy(Myself))  // Skull
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
THEN
	RESPONSE #100
		SetGlobal("WingBuffet","LOCALS",0)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",THREE_ROUNDS)
END

IF
	See(SecondNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!HasItemEquiped("S!skelsu",LastSeenBy(Myself))
	!HasItemEquiped("S!swansu",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gswan",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!swanq",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gscim",LastSeenBy(Myself))  // Skull
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
THEN
	RESPONSE #100
		SetGlobal("WingBuffet","LOCALS",0)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",THREE_ROUNDS)
END

IF
	!GlobalTimerNotExpired("Iarefreshwing","GLOBAL")
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
	See(NearestEnemyOf(Myself))
	Global("WingBuffet","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iarefreshwing","GLOBAL",FOUR_ROUNDS)
		SetGlobal("WingBuffet","LOCALS",0)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("partyfled","LOCALS",0)
	Global("IaPrep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("partyfled","LOCALS",0)
	HPPercentLT(Myself,100)
	Global("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	InMyArea(Player1)
	NumberOfTimesTalkedTo(0)
	Global("Iareaction","ARia14",1)
	Global("IaPrep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iareaction","ARia14",2)
		SetGlobal("partyfled","LOCALS",1)
		MoveToObject(Player1)
END
