IF
	See(NearestEnemyOf(Myself))
	Global("IaPrep","LOCALS",0)
	HasItem("POTN35",Myself)  // Potion of Magic Shielding
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN35X",Myself)  // No such index
		DestroyItem("POTN35")  // Potion of Magic Shielding
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	Global("IaPrep","LOCALS",0)
	HasItem("POTN33",Myself)
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN33X",Myself)
		DestroyItem("POTN33")
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	Global("IaPrep","LOCALS",0)
	HasItem("POTN07",Myself)
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN07X",Myself)  // No such index
		DestroyItem("POTN07")
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	Global("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaPrep","LOCALS",1)
		Continue()
END

IF
	HasItem("POTN11",Myself)
	Detect(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN11",Myself)
END

IF
	HaveSpell(WARRIOR_GREATER_WHIRLWIND)
	Detect(NearestEnemyOf(Myself))
	CheckStat(Myself,0,IMPROVEDHASTE)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),15)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)
		RemoveSpell(WARRIOR_GREATER_WHIRLWIND)
END

IF
	HaveSpell(WARRIOR_WHIRLWIND)
	Detect(NearestEnemyOf(Myself))
	CheckStat(Myself,0,IMPROVEDHASTE)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),15)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)
		RemoveSpell(WARRIOR_WHIRLWIND)
END

IF
	HaveSpell(WARRIOR_WAR_CRY)
	Detect(NearestEnemyOf(Myself))
	CheckStat(Myself,0,IMPROVEDHASTE)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_WAR_CRY)
		RemoveSpell(WARRIOR_WAR_CRY)
END

IF
	HasItem("POTN14",Myself)
	Detect(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_HASTED)
	CheckStat(Myself,0,IMPROVEDHASTE)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN14",Myself)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_HARDINESS)
	!CheckSpellState(Myself,HARDINESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
		RemoveSpell(WARRIOR_HARDINESS)
END

IF
	Range(NearestEnemyOf(Myself),10)
	HPPercent(Myself,100)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("POTN37",Myself)  // Oil of Resurgence
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN37",Myself)  // Oil of Resurgence
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,60)
	HasItem("potn55",Myself)  // Potion of Superior Healing
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn55",Myself)  // Potion of Superior Healing
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END
IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_CRITICAL_STRIKE)
	!CheckStatGT(Myself,5,CRITICALHITBONUS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
		RemoveSpell(WARRIOR_CRITICAL_STRIKE)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(NearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SecondNearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FourthNearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FifthNearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(WARRIOR_POWER_ATTACK)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SixthNearestEnemyOf(Myself),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("PowerAttackActiveTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)
		RemoveSpell(WARRIOR_POWER_ATTACK)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaist01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaist01","LOCALS",0)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	GlobalGT("Iaist01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaist01","LOCALS",0)
		SetGlobal("Iaist02","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],50)
	OR(2)
	    CheckStatGT([PC],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],50)
	OR(2)
	    CheckStatGT([PC],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],50)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],100)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],100)
	OR(2)
	    CheckStatGT([PC],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	OR(2)
	    CheckStatGT([PC],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState([PC],STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FourthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FifthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SixthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC.0.0.MAGE_ALL],5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],100)
	OR(2)
	    CheckStatGT([PC],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],100)
	OR(2)
	    CheckStatGT([PC],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	HPLT(NearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(NearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(NearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	HPLT(SecondNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(SecondNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearestEnemyOf(Myself))
	HPLT(ThirdNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(ThirdNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearestEnemyOf(Myself))
	HPLT(FourthNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(FourthNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearestEnemyOf(Myself))
	HPLT(FifthNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(FifthNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearestEnemyOf(Myself))
	HPLT(SixthNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(SixthNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],500)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],500)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],500)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-25,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],500)
	OR(2)
	    CheckStatGT([PC],-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	HPLT([PC],500)
	OR(2)
	    CheckStatGT([PC],-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC],10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	HPLT(NearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(NearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(NearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	HPLT(SecondNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(SecondNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearestEnemyOf(Myself))
	HPLT(ThirdNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(ThirdNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearestEnemyOf(Myself))
	HPLT(FourthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(FourthNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearestEnemyOf(Myself))
	HPLT(FifthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(FifthNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearestEnemyOf(Myself))
	HPLT(SixthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(SixthNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	HPLT(NearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(NearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(NearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(NearestEnemyOf(Myself),3,SCRIPTINGSTATE6)
	!CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(NearestEnemyOf(Myself),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	HPLT(SecondNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(SecondNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearestEnemyOf(Myself),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearestEnemyOf(Myself),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearestEnemyOf(Myself))
	HPLT(ThirdNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(ThirdNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearestEnemyOf(Myself),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearestEnemyOf(Myself),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearestEnemyOf(Myself))
	HPLT(FourthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(FourthNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearestEnemyOf(Myself),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearestEnemyOf(Myself),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearestEnemyOf(Myself))
	HPLT(FifthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(FifthNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearestEnemyOf(Myself),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearestEnemyOf(Myself),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearestEnemyOf(Myself))
	HPLT(SixthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(SixthNearestEnemyOf(Myself),-30,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearestEnemyOf(Myself),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearestEnemyOf(Myself),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

