
IF
	!StateCheck(Myself,STATE_HELPLESS)
	Global("Iapcastts","GLOBAL",0)
	HPPercentLT(Myself,60)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN55",Myself)  // Potion of Superior Healing
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN55",Myself)  // Potion of Superior Healing
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("gww","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Player1))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	OR(2)
		Global("Iathethree","AR4500",2)  // Pocket Plane
		!HasItem("S!rakp",LastSeenBy(Myself))  // Skull
	GlobalLT("Iapasha01","LOCALS",8)
THEN
	RESPONSE #100
		IncrementGlobal("Iapasha01","LOCALS",1)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("gww","LOCALS",THREE_ROUNDS)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("cstrike","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Player1))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	OR(2)
		Global("Iathethree","AR4500",2)  // Pocket Plane
		!HasItem("S!rakp",LastSeenBy(Myself))  // Skull
    CheckStatLT(Myself,8,CRITICALHITBONUS)
	GlobalLT("Iapasha02","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iapasha02","LOCALS",1)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("cstrike","LOCALS",THREE_ROUNDS)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("gww","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Player1))
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	OR(2)
		Global("Iathethree","AR4500",2)  // Pocket Plane
		!HasItem("S!rakp",LastSeenBy(Myself))  // Skull
	Global("Iapasha03","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapasha03","LOCALS",1)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("gww","LOCALS",THREE_ROUNDS)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)  // SPCL900.SPL (Whirlwind Attack)
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",1)  // Pocket Plane
	Dead("S!supgol")  // Supreme Golem
	Dead("S!ultgg1")  // Ultra Golem
	Dead("S!ultgg2")  // Ultra Golem
THEN
	RESPONSE #100
		SetGlobal("Iathethree","AR4500",2)  // Pocket Plane
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",1)  // Pocket Plane
	See(NearestEnemyOf(Player1))
	!HasItem("S!rakp",LastSeenBy(Myself))  // Skull
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",1)  // Pocket Plane
	See(SecondNearestEnemyOf(Player1))
	!HasItem("S!rakp",LastSeenBy(Myself))  // Skull
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",1)  // Pocket Plane
	See(ThirdNearestEnemyOf(Player1))
	!HasItem("S!rakp",LastSeenBy(Myself))  // Skull
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",1)  // Pocket Plane
	See(NearestEnemyOf(Player1))
	HasItem("S!rakp",LastSeenBy(Myself))  // Skull
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",0)  // Pocket Plane
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",2)  // Pocket Plane
	See(NearestEnemyOf(Player1))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",2)  // Pocket Plane
	See(SecondNearestEnemyOf(Player1))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",2)  // Pocket Plane
	See(ThirdNearestEnemyOf(Player1))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iathethree","AR4500",2)  // Pocket Plane
	See(NearestEnemyOf(Player1))
	OR(2)
		!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
		!HasItem("S!rakp",LastSeenBy(Myself))  // Skull
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Player1))
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	Global("Iaepicbattle","AR4500",4)  // Pocket Plane
	Global("Farewell","LOCALS",0)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("Farewell","LOCALS",1)
		MoveToObjectNoInterrupt(Player1)
		StartDialogueNoSet(Player1)
END

IF
	Allegiance(Myself,GOODBUTBLUE)
	!See(NearestEnemyOf(Player1))
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,GOODBUTBLUE)
THEN
	RESPONSE #100
		ChangeEnemyAlly(Myself,GOODBUTBLUE)
END
