
IF
	See(NearestEnemyOf(Myself))
	Global("Prep","LOCALS",0)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Prep","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Global("Iarestwish","AR1008",1)  // Twisted Rune
	Global("Iarest","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iarest","LOCALS",1)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iadeath","LOCALS",0)
		SetGlobal("Iaprotection","LOCALS",0)
		SetGlobal("Ialower","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("SpellTrigger","LOCALS",0)
		SetGlobal("Iahorrid","LOCALS",0)
		SetGlobal("Iabreath","LOCALS",0)
		SetGlobal("Iafinger","LOCALS",0)
		SetGlobal("Iafball","LOCALS",0)
		SetGlobal("Iaacid","LOCALS",0)
		SetGlobal("Iamissile","LOCALS",0)
		SetGlobal("Iaemotion","LOCALS",0)
		SetGlobal("Iabcrush","LOCALS",0)
		SetGlobal("Iacomet","LOCALS",0)
		SetGlobal("Iaspray","LOCALS",0)
		SetGlobal("Iapword","LOCALS",0)
		SetGlobal("Iabclenched","LOCALS",0)
		SetGlobal("Iadispel","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	HPPercentLT(Myself,50)
	!HPLT(Myself,1)
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iacontingency","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iacontingency","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	OR(2)
		!GlobalTimerNotExpired("pfmw","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iaprotection","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaprotection","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Ialichcontin","LOCALS",0)
	Global("Iaprotection","LOCALS",4)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	CheckStat(Myself,0,SCRIPTINGSTATE6)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Ialichcontin","LOCALS",1)
		DisplayString(Myself,40252)  // Contingency—Protection From Magical Weapons
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(2)
		GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		GlobalGT("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,IMMUNITY_TO_BACKSTAB)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // Larloch's Interrupter
END


IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilence[PC]","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilence[PC]","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceSecondNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceSecondNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceThirdNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceThirdNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceFourthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceFourthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceFifthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceFifthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceSixthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceSixthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END


IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilence[PC]","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilence[PC]","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceSecondNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceSecondNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceThirdNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceThirdNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceFourthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceFourthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceFifthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceFifthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceSixthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceSixthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END


IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilence[PC]","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-5,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilence[PC]","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceSecondNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-5,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceSecondNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceThirdNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-5,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceThirdNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceFourthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-5,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceFourthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceFifthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-5,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceFifthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END

IF
	HaveSpellRES("SPINI39")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGraveSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilenceSixthNearest([PC])","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	CheckStatGT(LastSeenBy(Myself),-5,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGraveSilence","LOCALS", 18)
		SetGlobalTimer("IaSilenceSixthNearest([PC])","LOCALS", ONE_TURN)
		RemoveSpellRES("SPINI39")
		ForceSpellRES("SPINI39", LastSeenBy(Myself))
	RESPONSE #25
	    Continue()
END


IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,90)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player2)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player3)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player4)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player6)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,90)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player2)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player3)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player4)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player6)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,90)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player2)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player3)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player4)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iapword","LOCALS",4)
	Global("Iaremove","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasBounceEffects(Player6)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player1)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player1)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player1)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player2)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player2)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player2)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player3)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player3)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player3)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player4)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player4)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player4)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player5)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player5)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player5)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player6)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player6)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player6)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player1)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player2)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player3)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player4)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player5)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player6)  // Ruby Ray of Reversal
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	GlobalLT("Iadispel","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispel","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(2)
		CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iacomet","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iacomet","LOCALS",1)
		SpellNoDecRES("SPWII51",LastSeenBy(Myself))  // Stellar Gravestone
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(2)
		CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iacomet","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iacomet","LOCALS",1)
		SpellNoDecRES("SPWII51",LastSeenBy(Myself))  // Stellar Gravestone
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(2)
		CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iacomet","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iacomet","LOCALS",1)
		SpellNoDecRES("SPWII51",LastSeenBy(Myself))  // Stellar Gravestone
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(2)
		CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iacomet","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iacomet","LOCALS",1)
		SpellNoDecRES("SPWII51",LastSeenBy(Myself))  // Stellar Gravestone
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(2)
		CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iacomet","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iacomet","LOCALS",1)
		SpellNoDecRES("SPWII51",LastSeenBy(Myself))  // Stellar Gravestone
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(2)
		CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iacomet","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iacomet","LOCALS",1)
		SpellNoDecRES("SPWII51",LastSeenBy(Myself))  // Stellar Gravestone
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Iabreath","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iabreath","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Iabreath","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iabreath","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Iabreath","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iabreath","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END


IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See([PC])
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(FourthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(FifthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(SixthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See([PC])
	CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Ialower","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Ialower","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Ialower","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Ialower","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Ialower","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Ialower","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iagmalison","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagmalison","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	Global("Iapcastts","GLOBAL",0)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iagmalison","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagmalison","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iascrl","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	HasItem("scrl8o",Myself)  // Finger of Death
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	!Class(LastSeenBy(Myself),FIGHTER_ALL)
	!Class(LastSeenBy(Myself),CLERIC_ALL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iafinger","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iascrl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8o",LastSeenBy(Myself))  // Finger of Death
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iascrl","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	HasItem("scrl8o",Myself)  // Finger of Death
	See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
	!Class(LastSeenBy(Myself),FIGHTER_ALL)
	!Class(LastSeenBy(Myself),CLERIC_ALL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iafinger","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iascrl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8o",LastSeenBy(Myself))  // Finger of Death
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iascrl","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	HasItem("scrl8o",Myself)  // Finger of Death
	See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
	!Class(LastSeenBy(Myself),FIGHTER_ALL)
	!Class(LastSeenBy(Myself),CLERIC_ALL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iafinger","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iascrl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8o",LastSeenBy(Myself))  // Finger of Death
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iascrl","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	HasItem("scrl8o",Myself)  // Finger of Death
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iafinger","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iascrl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8o",LastSeenBy(Myself))  // Finger of Death
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iascrl","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	HasItem("scrl8o",Myself)  // Finger of Death
	See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iafinger","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iascrl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8o",LastSeenBy(Myself))  // Finger of Death
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iascrl","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	HasItem("scrl8o",Myself)  // Finger of Death
	See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iafinger","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iascrl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8o",LastSeenBy(Myself))  // Finger of Death
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	OR(3)
		CheckStatGT(LastSeenBy(Myself),94,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
		CheckStat(LastSeenBy(Myself),70,RESISTMISSILE)
	Global("Iadeath","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadeath","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iabigby","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iabcrush","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabcrush","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iabigby","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iabigby","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iabcrush","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabcrush","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iabigby","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iabigby","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iabcrush","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabcrush","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iabigby","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iabigby","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iabclenched","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabclenched","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iabigby","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iabigby","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iabclenched","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabclenched","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iabigby","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iabigby","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	GlobalLT("Iabclenched","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabclenched","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iabigby","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	Global("SpellTrigger","LOCALS",0)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("SpellTrigger","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	Global("Iaspray","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaspray","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	Global("Iaspray","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaspray","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaemotimer","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iaemotion","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iaemotion","LOCALS",1)
		SetGlobalTimer("Iaemotimer","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaemotimer","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iaemotion","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iaemotion","LOCALS",1)
		SetGlobalTimer("Iaemotimer","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaemotimer","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iaemotion","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iaemotion","LOCALS",1)
		SetGlobalTimer("Iaemotimer","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	Global("Iaspray","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaspray","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	Global("Iaspray","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaspray","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iahorrid","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iahorrid","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iahorrid","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iahorrid","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iahorrid","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iahorrid","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),4)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iafball","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafball","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),2)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iafball","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafball","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iafball","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafball","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iafball","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafball","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iafball","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafball","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaacid","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaacid","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaacid","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	GlobalLT("Iamissile","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iamissile","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	GlobalLT("Iamissile","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iamissile","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	GlobalLT("Iamissile","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iamissile","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("prep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TWO_TURNS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	Global("prep","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("prep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Prep","LOCALS",0)
		SetGlobal("Iaskins","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iadeath","LOCALS",0)
		SetGlobal("Iaprotection","LOCALS",0)
		SetGlobal("Iacontingency","LOCALS",0)
		SetGlobal("Ialower","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("SpellTrigger","LOCALS",0)
		SetGlobal("Iagmalison","LOCALS",0)
		SetGlobal("SpellTrigger","LOCALS",0)
		SetGlobal("Iahorrid","LOCALS",0)
		SetGlobal("Iabreath","LOCALS",0)
		SetGlobal("Iafinger","LOCALS",0)
		SetGlobal("Iafball","LOCALS",0)
		SetGlobal("Iaacid","LOCALS",0)
		SetGlobal("Iamissile","LOCALS",0)
		SetGlobal("Iaemotion","LOCALS",0)
		SetGlobal("Iabcrush","LOCALS",0)
		SetGlobal("Iacomet","LOCALS",0)
		SetGlobal("Iaspray","LOCALS",0)
		SetGlobal("Iapword","LOCALS",0)
		SetGlobal("Iabclenched","LOCALS",0)
		SetGlobal("Iadispel","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),95,RESISTPIERCING)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	GlobalGT("ShangalarMove","AR1008",0)  // Twisted Rune
THEN
	RESPONSE #100
		MoveToObject(Player1)
END
