
IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Global("TurnHostile","AR6106",0)  // Sendai's Lair -- Captain Egeissag
THEN
	RESPONSE #100
		SetGlobal("TurnHostile","AR6106",1)  // Sendai's Lair -- Captain Egeissag
END

IF
	Global("KillDrow","AR6106",1)  // Sendai's Lair -- Captain Egeissag
	Global("KillSelf","LOCALS",0)
THEN
	RESPONSE #100
		CreateVisualEffectObject("spdeath3",Myself)
		Kill(Myself)
		SetGlobal("KillSelf","LOCALS",1)
END

IF
	Global("TurnHostile","AR6106",1)  // Sendai's Lair -- Captain Egeissag
	Global("Enemy","LOCALS",0)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("Enemy","LOCALS",1)
END

IF
	HPPercentLT(Myself,50)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN55",Myself)  // Potion of Superior Healing
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN55",Myself)  // Potion of Superior Healing
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	OR(2)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iagww","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	GlobalLT("FighterAbility","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("FighterAbility","LOCALS",1)
		SetGlobalTimer("Iagww","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iagww","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	GlobalLT("FighterAbility","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("FighterAbility","LOCALS",1)
		SetGlobalTimer("Iagww","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iagww","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	See(ThirdNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	GlobalLT("FighterAbility","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("FighterAbility","LOCALS",1)
		SetGlobalTimer("Iagww","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iagww","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	Global("FighterAbility","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("FighterAbility","LOCALS",1)
		SetGlobalTimer("Iagww","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)  // SPCL900.SPL (Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iagww","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	Global("FighterAbility","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("FighterAbility","LOCALS",1)
		SetGlobalTimer("Iagww","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)  // SPCL900.SPL (Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iagww","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	See(ThirdNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	Global("FighterAbility","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("FighterAbility","LOCALS",1)
		SetGlobalTimer("Iagww","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)  // SPCL900.SPL (Whirlwind Attack)
END

IF
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iacshot","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	HaveSpell(ARCHER_CALL_SHOT)  // SPCL121.SPL (Called Shot)
THEN
	RESPONSE #100
		SetGlobalTimer("Iacshot","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		Spell(Myself,ARCHER_CALL_SHOT)  // SPCL121.SPL (Called Shot)
END

IF
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iacshot","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	HaveSpell(ARCHER_CALL_SHOT)  // SPCL121.SPL (Called Shot)
THEN
	RESPONSE #100
		SetGlobalTimer("Iacshot","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		Spell(Myself,ARCHER_CALL_SHOT)  // SPCL121.SPL (Called Shot)
END

IF
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("Iacshot","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	HaveSpell(ARCHER_CALL_SHOT)  // SPCL121.SPL (Called Shot)
THEN
	RESPONSE #100
		SetGlobalTimer("Iacshot","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		Spell(Myself,ARCHER_CALL_SHOT)  // SPCL121.SPL (Called Shot)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FourthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(FifthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SixthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END
