
IF
	Detect([PC])
	Global("Ianotalk","AR1402",0)  // Shadow Dragon Hideout
	Global("Iapcastts","GLOBAL",0)
	Allegiance(Myself,NEUTRAL)
	OR(6)
		!PartyHasItem("MISC6P")  // Shadow Dragon Wardstone
		AttackedBy([GOODCUTOFF],DEFAULT)
		AttackedBy([PC],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([PC],0)
		TookDamage()
	NumberOfTimesTalkedTo(0)
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
END

IF
	Allegiance(Myself,NEUTRAL)
	Global("Ianotalk","AR1402",0)  // Shadow Dragon Hideout
	InMyArea(Player1)
	OR(7)
		AttackedBy([GOODCUTOFF],DEFAULT)
		AttackedBy([PC],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([PC],0)
		HPPercentLT(Myself,100)
		TookDamage()
		GlobalGT("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Ianotalk","AR1402",1)  // Shadow Dragon Hideout
		Enemy()
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	!Allegiance(Myself,ENEMY)
	!Detect([PC])
	InMyArea(Player1)
	NumberOfTimesTalkedTo(0)
	!PartyHasItem("MISC6P")  // Shadow Dragon Wardstone
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iashadra01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra01","LOCALS",1)
		SetGlobal("Iaattack","LOCALS",2)
		ReallyForceSpellRES("SPWII03",Myself)  // Spell Turning
		ReallyForceSpell(Myself,DRAGON_STONE_SKIN)  // SPIN694.SPL (Stoneskin)
		ReallyForceSpellRES("SPWII01",Myself)  // Spell Shield
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaexit","AR1402",0)  // Shadow Dragon Hideout
	Global("Iaexitthing","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaexit","AR1402",1)  // Shadow Dragon Hideout
		SetGlobal("Iaexitthing","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iadoonce","LOCALS",0)
	HPPercentLT(Myself,100)
THEN
	RESPONSE #100
		SetGlobal("Iadoonce","LOCALS",1)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iadoonce","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadoonce","LOCALS",1)
END

IF
	Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		NoAction()
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,51,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,51,RESISTMAGIC)
	!CheckStat(Player2,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,51,RESISTMAGIC)
	!CheckStat(Player3,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,51,RESISTMAGIC)
	!CheckStat(Player4,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,51,RESISTMAGIC)
	!CheckStat(Player5,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,51,RESISTMAGIC)
	!CheckStat(Player6,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",0)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,51,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,51,RESISTMAGIC)
	!CheckStat(Player2,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,51,RESISTMAGIC)
	!CheckStat(Player3,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,51,RESISTMAGIC)
	!CheckStat(Player4,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,51,RESISTMAGIC)
	!CheckStat(Player5,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,51,RESISTMAGIC)
	!CheckStat(Player6,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,51,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,51,RESISTMAGIC)
	!CheckStat(Player2,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,51,RESISTMAGIC)
	!CheckStat(Player3,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,51,RESISTMAGIC)
	!CheckStat(Player4,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,51,RESISTMAGIC)
	!CheckStat(Player5,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,51,RESISTMAGIC)
	!CheckStat(Player6,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
	Global("Iashadra08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra08","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	CheckStat(Myself,0,SCRIPTINGSTATE6)
	HPPercentLT(Myself,100)
	Global("Iashadra10","LOCALS",0)
	!GlobalTimerNotExpired("pfmw","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Iashadra10","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(Myself,PROTECTION_MAGIC_WEAPON_NOEFF)  // SPIN686.SPL (Protection From Magical Weapons)
		ReallyForceSpell(Myself,DRAGON_STONE_SKIN)  // SPIN694.SPL (Stoneskin)
		ReallyForceSpellRES("SPWII02",Myself)  // Protection From Magic Energy
END

IF
	Allegiance(Myself,ENEMY)
	CheckStatLT(Myself,1,STONESKINS)
	See(NearestEnemyOf(Myself))
	Global("Iashadra10","LOCALS",1)
	OR(2)
		!GlobalTimerNotExpired("pfmw","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iashadra09","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iashadra09","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FIVE_MINUTES)
		ForceSpell(Myself,PROTECTION_MAGIC_WEAPON_NOEFF)  // SPIN686.SPL (Protection From Magical Weapons)
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iarosesplace","GLOBAL",1)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iarosesplace","GLOBAL",3)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("sw1h40",Myself,0,0,0)  // Blade of Roses +3
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iadupliringplace","GLOBAL",3)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iadupliringplace","GLOBAL",4)
		GiveItemCreate("ohrring1",Myself,0,0,0)  // Ring of Duplication
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure2","LOCALS",0)
	Global("Iaaxeplace","GLOBAL",1)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iaaxeplace","GLOBAL",4)
		SetGlobal("Iatreasure2","LOCALS",1)
		GiveItemCreate("ax1h10",Myself,0,0,0)  // Azuredge +3
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure3","LOCALS",0)
	Class(Player1,MAGE_ALL)
	!Class(Player1,FIGHTER_ALL)
	!Class(Player1,THIEF_ALL)
	!Class(Player1,CLERIC_ALL)
	Kit(Player1,MAGESCHOOL_NECROMANCER)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iatreasure3","LOCALS",1)
		GiveItemCreate("S!scrl21",Myself,0,0,0)  // Vocalize
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure4","LOCALS",0)
	XPLT(Player1,2350000)
	GlobalLT("Chapter","GLOBAL",4)
THEN
	RESPONSE #100
		SetGlobal("Iatreasure4","LOCALS",1)
		GiveItemCreate("S!misc41",Myself,0,0,0)  // Diamond Necklace
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure5","LOCALS",0)
	Global("Iadragonbladeplace","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("Iadragonbladeplace","GLOBAL",5)
		SetGlobal("Iatreasure5","LOCALS",1)
		GiveItemCreate("bdsw2h01",Myself,0,0,0)  // Dragon Blade +3
		Continue()
END


IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer1","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player1)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer1","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer2","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player2)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer2","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer3","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player3)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer3","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer4","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player4)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer4","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer5","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player5)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer5","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPIN692")
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaGreaterSilence","LOCALS")
    !GlobalTimerNotExpired("IaSilencePlayer6","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player6)
	OR(6)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),SORCERER)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),SHAMAN)
		Class(LastSeenBy(Myself),MAGE_ALL)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!Kit(LastSeenBy(Myself),AURAMASTER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE4)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaGreaterSilence","LOCALS", TWO_ROUNDS)
		SetGlobalTimer("IaSilencePlayer6","LOCALS", ONE_TURN)
		RemoveSpellRES("SPIN692")
		ForceSpellRES("SPIN692", LastSeenBy(Myself))
	RESPONSE #50
	    Continue()
END


IF
	Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,50)
	Global("Iaheal","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaheal","LOCALS",1)
		DisplayString(Myself,29736)  // Contingency—Stoneskin
		ReallyForceSpell(Myself,DRAGON_STONE_SKIN)  // SPIN694.SPL (Stoneskin)
		ForceSpellRES("SPPRI10",Myself)  // Heal
END

IF
	Allegiance(Myself,ENEMY)
	HPPercentLT(Myself,50)
	InMyArea(Player1)
	Global("Iacure","LOCALS",0)
	Global("Iaheal","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iacure","LOCALS",1)
		ForceSpellRES("SPPRI10",Myself)  // Heal
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iafog","AR1402",0)  // Shadow Dragon Hideout
	GlobalLT("Myfog","LOCALS",6)
	GlobalGT("Iaonewing","LOCALS",0)
	!GlobalTimerNotExpired("MyTimer","LOCALS")
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("Iafog","AR1402",1)  // Shadow Dragon Hideout
		IncrementGlobal("Myfog","LOCALS",1)
		SetGlobalTimer("FogTimer","AR1402",FIVE_ROUNDS)  // Shadow Dragon Hideout
		SetGlobalTimer("MyTimer","LOCALS",TWO_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		ForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		ForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	Global("Iapccloud","AR1402",1)  // Shadow Dragon Hideout
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("Iapccloud","AR1402",0)  // Shadow Dragon Hideout
		ForceSpell(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	OR(3)
		LevelGT(LastSeenBy(Myself),8)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	Global("Iashadra06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra06","LOCALS",1)
		DisplayString(Myself,45920)  // Your lackeys will not save you!
		ForceSpell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	Range(LastSeenBy(Myself),11)
	Global("Iaonewing","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaonewing","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",0)
	See([PC])
	Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",0)
	See(SecondNearest([PC]))
	Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",0)
	See(ThirdNearest([PC]))
	Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra11","LOCALS",0)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,40,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobal("Iashadra11","LOCALS",1)
		ForceSpellRES("SPPRI01",Myself)  // Magic Resistance
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
		SetGlobalTimer("Iaattacking","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iaattack","LOCALS",1)
	GlobalTimerExpired("Iaattacking","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",2)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Iaattacking","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Global("Iaattack","LOCALS",1)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Iaattacking","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Global("Iaattack","LOCALS",1)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		ForceSpell(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player1)
	Range(Player1,15)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player1)
	Class(Player1,MAGE_ALL)
	Global("Iashadra08","LOCALS",0)
	CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	CheckStatLT(Player1,51,RESISTMAGIC)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	!CheckStat(Player1,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player1)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		ForceSpell(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player2)
	Range(Player2,15)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player2)
	Class(Player2,MAGE_ALL)
	Global("Iashadra08","LOCALS",0)
	CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	CheckStatLT(Player2,51,RESISTMAGIC)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	!CheckStat(Player2,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player2)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		ForceSpell(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player3)
	Range(Player3,15)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player3)
	Class(Player3,MAGE_ALL)
	Global("Iashadra08","LOCALS",0)
	CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	CheckStatLT(Player3,51,RESISTMAGIC)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	!CheckStat(Player3,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player3)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		ForceSpell(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player4)
	Range(Player4,15)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player4)
	Class(Player4,MAGE_ALL)
	Global("Iashadra08","LOCALS",0)
	CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	CheckStatLT(Player4,51,RESISTMAGIC)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	!CheckStat(Player4,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player4)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		ForceSpell(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player5)
	Range(Player5,15)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player5)
	Class(Player5,MAGE_ALL)
	Global("Iashadra08","LOCALS",0)
	CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	CheckStatLT(Player5,51,RESISTMAGIC)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	!CheckStat(Player5,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player5)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		ForceSpell(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player6)
	Range(Player6,15)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player6)
	Class(Player6,MAGE_ALL)
	Global("Iashadra08","LOCALS",0)
	CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	CheckStatLT(Player6,51,RESISTMAGIC)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	!CheckStat(Player6,2,SCRIPTINGSTATE3)
	!HasBounceEffects(Player6)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobal("Iaattack","LOCALS",0)
		ForceSpell(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iashadra12","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra12","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iashadra12","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra12","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("RemoveMagic","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("RemoveMagic","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("RemoveMagic","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("RemoveMagic","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		ForceSpell(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		ForceSpell(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		ForceSpell(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		ForceSpell(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		ForceSpell(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		ForceSpell(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		ForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalLT("Ialowermr","LOCALS",2)
	See([PC])
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Ialowermr","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		Wait(2)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalLT("Ialowermr","LOCALS",2)
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Ialowermr","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		Wait(2)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalLT("Ialowermr","LOCALS",2)
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Ialowermr","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		Wait(2)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalLT("Ialowermr","LOCALS",2)
	See(FourthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Ialowermr","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		Wait(2)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalLT("Ialowermr","LOCALS",2)
	See(FifthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Ialowermr","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		Wait(2)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalLT("Ialowermr","LOCALS",2)
	See(SixthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Ialowermr","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		Wait(2)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	OR(3)
		LevelGT(LastSeenBy(Myself),8)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	Global("Iashadra06","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iashadra06","LOCALS",2)
		DisplayString(Myself,45920)  // Your lackeys will not save you!
		ForceSpell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra02","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
THEN
	RESPONSE #100
		SetGlobal("Iashadra02","LOCALS",1)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra02","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
THEN
	RESPONSE #100
		SetGlobal("Iashadra02","LOCALS",1)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	See(NearestEnemyOf(Myself))
	Global("Iashadra04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra04","LOCALS",1)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Global("Iashadra14","LOCALS",0)
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!HasItemEquiped("S!skelsu",LastSeenBy(Myself))
	!HasItemEquiped("S!swansu",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gswan",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!swanq",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gscim",LastSeenBy(Myself))  // Skull
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
THEN
	RESPONSE #100
		SetGlobal("Iashadra14","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Global("Iashadra15","LOCALS",0)
	See(NearestEnemyOfType([0.0.0.RANGER_ALL]))
	Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
THEN
	RESPONSE #100
		SetGlobal("Iashadra15","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",1)
	See([PC])
	Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",2)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",1)
	See(SecondNearest([PC]))
	Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",2)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iashadra13","LOCALS",1)
	See(ThirdNearest([PC]))
	Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
THEN
	RESPONSE #100
		SetGlobal("Iashadra13","LOCALS",2)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("RemoveMagic2","LOCALS",0)
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
THEN
	RESPONSE #100
		SetGlobal("RemoveMagic2","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	Global("RemoveMagic2","LOCALS",0)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
THEN
	RESPONSE #100
		SetGlobal("RemoveMagic2","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	Global("RemoveMagic2","LOCALS",0)
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
THEN
	RESPONSE #100
		SetGlobal("RemoveMagic2","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Offensive","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Offensive","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Offensive","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Offensive","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Offensive","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Offensive","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	Range(LastSeenBy(Myself),11)
	Global("Iaonewing","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaonewing","LOCALS",2)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
		SetGlobal("Iafog","AR1402",0)  // Shadow Dragon Hideout
		SetGlobalTimer("MyTimer","LOCALS",3)
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iashadra03","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra03","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iashadra03","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra03","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iashadra03","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashadra03","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		SetGlobal("Iaattack","LOCALS",0)
END

IF
	See(NearestEnemyOf(Myself))
	Global("DRAGONFEAR","LOCALS",0)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!HasItemEquiped("S!skelsu",LastSeenBy(Myself))
	!HasItemEquiped("S!swansu",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gswan",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!swanq",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gscim",LastSeenBy(Myself))  // Skull
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		ReallyForceSpell(LastSeenBy(Myself),DRAGON_FEAR)  // SPIN895.SPL (Dragon Fear)
		SetGlobal("DRAGONFEAR","LOCALS",1)
		SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",1)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
END

IF
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
	Global("WingBuffet","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("WingBuffet","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Wing Buffet)
		SetGlobal("Iafog","AR1402",0)  // Shadow Dragon Hideout
		SetGlobalTimer("MyTimer","LOCALS",3)
	RESPONSE #60
		SetGlobal("WingBuffet","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!HasItemEquiped("S!skelsu",LastSeenBy(Myself))
	!HasItemEquiped("S!swansu",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gswan",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!swanq",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gscim",LastSeenBy(Myself))  // Skull
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
THEN
	RESPONSE #100
		SetGlobal("WingBuffet","LOCALS",0)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",THREE_ROUNDS)
END

IF
	See(SecondNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!HasItemEquiped("S!skelsu",LastSeenBy(Myself))
	!HasItemEquiped("S!swansu",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gswan",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!swanq",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gscim",LastSeenBy(Myself))  // Skull
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
THEN
	RESPONSE #100
		SetGlobal("WingBuffet","LOCALS",0)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",THREE_ROUNDS)
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckSpellState(LastSeenBy(Myself),UNDISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!CheckSpellState(LastSeenBy(Myself),DISPELLABLE_PROT_FROM_LEVEL_DRAIN)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!HasItemEquiped("S!sw06",LastSeenBy(Myself))  // Hesperus +5
	!HasItemEquiped("S!amul08",LastSeenBy(Myself))  // Pendant of Recovered Light
	!HasItemEquiped("S!amul10",LastSeenBy(Myself))  // Black Onyx Amulet
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!HasItemEquiped("S!skelsu",LastSeenBy(Myself))
	!HasItemEquiped("S!swansu",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gswan",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!swanq",LastSeenBy(Myself))  // No such index
	!HasItemEquiped("S!gscim",LastSeenBy(Myself))  // Skull
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
THEN
	RESPONSE #100
		SetGlobal("WingBuffet","LOCALS",0)
		ForceSpell(LastSeenBy(Myself),SHADOW_DRAGON_BREATH)  // SPIN893.SPL (Shadow Dragon Breath)
		SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",THREE_ROUNDS)
END

IF
	!GlobalTimerNotExpired("Iarefreshwing","GLOBAL")
	GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
	See(NearestEnemyOf(Myself))
	Global("WingBuffet","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iarefreshwing","GLOBAL",FOUR_ROUNDS)
		SetGlobal("WingBuffet","LOCALS",0)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END
