
IF
	Die()
THEN
	RESPONSE #100
		ReallyForceSpellDead(Myself,ILLUSION_DEATH)  // SPIN835.SPL (No such index)
		Wait(1)
		DestroySelf()
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("IaPrep","LOCALS",1)
		SetGlobalTimer("IaContinThreeRRRTimer","LOCALS",12)
		ReallyForceSpell(Myself,WIZARD_NON_DETECTION)
		ReallyForceSpell(Myself,WIZARD_LUCK)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
		SetInterrupt(TRUE)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",5)
		SetGlobalTimer("IaPrismaticWait","LOCALS",7)
		SetGlobalTimer("IaConeOfColdWait","LOCALS",8)
		Continue()
END


IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaPrep","LOCALS",1)
END



IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
		Continue()
END

IF
	Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		NoAction()
END



IF
    ActionListEmpty()
	See(Player1)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar1SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar1Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player2)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar2SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar2Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player3)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar3SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar3Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player4)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar4SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar4Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player5)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar5SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar5Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player6)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar6SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar6Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar1SeenTimer","LOCALS")
	Global("IaChar1Seen","LOCALS",1)
	!See(Player1)
THEN
	RESPONSE #100
		SetGlobal("IaChar1Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar2SeenTimer","LOCALS")
	Global("IaChar2Seen","LOCALS",1)
	!See(Player2)
THEN
	RESPONSE #100
		SetGlobal("IaChar2Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar3SeenTimer","LOCALS")
	Global("IaChar3Seen","LOCALS",1)
	!See(Player3)
THEN
	RESPONSE #100
		SetGlobal("IaChar3Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar4SeenTimer","LOCALS")
	Global("IaChar4Seen","LOCALS",1)
	!See(Player4)
THEN
	RESPONSE #100
		SetGlobal("IaChar4Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar5SeenTimer","LOCALS")
	Global("IaChar5Seen","LOCALS",1)
	!See(Player5)
THEN
	RESPONSE #100
		SetGlobal("IaChar5Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar6SeenTimer","LOCALS")
	Global("IaChar6Seen","LOCALS",1)
	!See(Player6)
THEN
	RESPONSE #100
		SetGlobal("IaChar6Seen","LOCALS",0)
		Continue()
END


IF
	HPPercentLT(Myself,35)
	!GlobalTimerNotExpired("AuruHealTimer","LOCALS")
	!GlobalLT("AuruHeal","LOCALS",3)
THEN
	RESPONSE #100
		SetGlobalTimer("AuruHealTimer","LOCALS",THREE_ROUNDS)
		IncrementGlobal("AuruHeal","LOCALS",1)
		ForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (Heal)
END

IF
	!StateCheck(Myself,STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("AuruMirror","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("AuruMirror","LOCALS",24)
		ForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
END


IF
	HaveSpellRES("SPCL321")
	!CheckSpellState(Myself,BERSERKER_RAGE_FATIGUE) 
	!CheckSpellState(Myself,BERSERKER_RAGE) 
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SpellRES("SPCL321",Myself)  // Enrage
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaDeathSpellWait","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	OR(3)
		CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStat(LastSeenBy(Myself),89,RESISTMAGIC)
	TriggerOverride(LastSeenBy(Myself), Range([GOODCUTOFF.0.0.0.0.SUMMONED], 15))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaDeathSpellWait","LOCALS",10)
		ForceSpell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
		SetInterrupt(TRUE)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaPrismaticWait","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),14)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaPrismaticWait","LOCALS",15)
		ForceSpell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaPrismaticWait","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),14)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaPrismaticWait","LOCALS",15)
		ForceSpell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaPrismaticWait","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),14)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaPrismaticWait","LOCALS",15)
		ForceSpell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaPrismaticWait","LOCALS")
	See(FourthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),14)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaPrismaticWait","LOCALS",15)
		ForceSpell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaPrismaticWait","LOCALS")
	See(FifthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),14)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaPrismaticWait","LOCALS",15)
		ForceSpell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaPrismaticWait","LOCALS")
	See(SixthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),14)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaPrismaticWait","LOCALS",15)
		ForceSpell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)  // SPWI714.SPL (Prismatic Spray)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!Range(NearestAllyOf(Myself),17)
	See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("IaConeOfColdWait","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,RESISTCOLD)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),17)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaConeOfColdWait","LOCALS",12)
		ForceSpell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!Range(NearestAllyOf(Myself),17)
	See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("IaConeOfColdWait","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,RESISTCOLD)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),17)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaConeOfColdWait","LOCALS",12)
		ForceSpell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!Range(NearestAllyOf(Myself),17)
	See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("IaConeOfColdWait","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,RESISTCOLD)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),17)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaConeOfColdWait","LOCALS",12)
		ForceSpell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!Range(NearestAllyOf(Myself),17)
	See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("IaConeOfColdWait","LOCALS")
	See(FourthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,RESISTCOLD)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),17)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaConeOfColdWait","LOCALS",12)
		ForceSpell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!Range(NearestAllyOf(Myself),17)
	See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("IaConeOfColdWait","LOCALS")
	See(FifthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,RESISTCOLD)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),17)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaConeOfColdWait","LOCALS",12)
		ForceSpell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!Range(NearestAllyOf(Myself),17)
	See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("IaConeOfColdWait","LOCALS")
	See(SixthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),80,RESISTCOLD)
	CheckStatLT(LastSeenBy(Myself),60,RESISTMAGIC)
	Range(LastSeenBy(Myself),17)
	!Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("IaConeOfColdWait","LOCALS",12)
		ForceSpell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
		SetInterrupt(TRUE)
	RESPONSE #0
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(SixthNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),80,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(FifthNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),80,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(FourthNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),80,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(ThirdNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),80,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),80,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See([PC])
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),80,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(SixthNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),90,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(FifthNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),90,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(FourthNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),90,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(ThirdNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),90,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),90,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaFlameArrowWait","LOCALS")
	See([PC])
	OR(2)
	    CheckStatLT(LastSeenBy(Myself),90,RESISTFIRE)
	    CheckStatLT(LastSeenBy(Myself),25,RESISTPIERCING)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaFlameArrowWait","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
	RESPONSE #50
	    Continue()
END


IF
	!StateCheck(Myself,STATE_BLUR)
	!GlobalTimerNotExpired("FerruBlur","LOCALS")
	RandomNum(3,1)
THEN
	RESPONSE #100
		SetGlobalTimer("FerruBlur","LOCALS",THREE_MINUTES)
		ForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState([PC],STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FourthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FifthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SixthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),85,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END


IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	!See([PC])
	!See([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("IaPrep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END


IF
	!GlobalTimerNotExpired("IaWeaponUnusable","LOCALS")
	OR(2)
        !WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
        !WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
	    SetGlobalTimer("IaWeaponUnusable","LOCALS",ONE_ROUND)
		ClearActions(Myself)
END


IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar1Seen","LOCALS",1)
	!See(Player1)
	!HPLT(Player1,0)
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar2Seen","LOCALS",1)
	!See(Player2)
	!HPLT(Player2,0)
	InMyArea(Player2)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar3Seen","LOCALS",1)
	!See(Player3)
	!HPLT(Player3,0)
	InMyArea(Player3)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar4Seen","LOCALS",1)
	!See(Player4)
	!HPLT(Player4,0)
	InMyArea(Player4)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar5Seen","LOCALS",1)
	!See(Player5)
	!HPLT(Player5,0)
	InMyArea(Player5)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar6Seen","LOCALS",1)
	!See(Player6)
	!HPLT(Player6,0)
	InMyArea(Player6)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END


IF
	See(NearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FifthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SixthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

