
IF
	Allegiance(Myself,ENEMY)
	OR(4)
		Detect([PC])
		Detect([GOODCUTOFF])
		HPPercentLT(Myself,100)
		AttackedBy([GOODCUTOFF],DEFAULT)
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prep","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
		ReallyForceSpellRES("SPWII41",Myself)  // Improved Invisibility
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
END

IF
	See(NearestEnemyOf(Myself))
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prep","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
		ReallyForceSpellRES("SPWII41",Myself)  // Improved Invisibility
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
END

IF
	Allegiance(Myself,ENEMY)
	AreaCheck("AR0801")  // Bodhi's Hideout (sided with Aran)
	Global("Iadooncev","LOCALS",0)
	Global("Prep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iadooncev","LOCALS",1)
		CreateCreatureObject("nevm4",Myself,0,0,0)  // Vampire Bride
		CreateCreatureObject("nevm4",Myself,0,0,0)  // Vampire Bride
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(5)
		StateCheck(Myself,STATE_CONFUSED)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_PANIC)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		NoAction()
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		See(NearestEnemyOf(Myself))
		Detect([GOODCUTOFF])
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	Global("Prep1","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Prep1","LOCALS",2)
		SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Prep","LOCALS",0)
	Global("Iainvis","LOCALS",0)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobal("Iainvis","LOCALS",1)
		SpellNoDec(Myself,WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Prep","LOCALS",0)
	Global("Iasturning","LOCALS",0)
	Global("Iainvis","LOCALS",1)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobal("Iasturning","LOCALS",1)
		SpellNoDec(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
END

IF
	Detect([PC])
	!See([PC])
	HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
	CheckStatLT(Myself,1,STONESKINS)
	Global("Prep1","LOCALS",0)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Prep1","LOCALS",1)
		DisplayString(Myself,29736)  // Contingency—Stoneskin
		ForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	OR(3)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iadispelpot","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	OR(3)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iadispelpot","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iagmalison","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagmalison","LOCALS",1)
		SetGlobalTimer("Iasequencer","LOCALS",9)
		SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iagmalison","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagmalison","LOCALS",1)
		SetGlobalTimer("Iasequencer","LOCALS",9)
		SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	Global("Iagmalison","LOCALS",1)
	GlobalTimerExpired("Iasequencer","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Prep","LOCALS",1)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Prep","LOCALS",2)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	Global("Iagmalison","LOCALS",1)
	GlobalTimerExpired("Iasequencer","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Prep","LOCALS",1)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Prep","LOCALS",2)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iaeightcast","LOCALS",0)
	OR(2)
		Global("Iaeightcast2","LOCALS",0)
		LevelGT(Myself,16)
	RandomNumGT(4,2)
THEN
	RESPONSE #100
		SetGlobal("Iaeightcast","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_STUN)  // SPWI898.SPL (Symbol, Stun)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iaeightcast","LOCALS",0)
	OR(2)
		Global("Iaeightcast2","LOCALS",0)
		LevelGT(Myself,16)
THEN
	RESPONSE #100
		SetGlobal("Iaeightcast","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iaeightcast2","LOCALS",0)
	OR(2)
		Global("Iaeightcast","LOCALS",0)
		LevelGT(Myself,16)
THEN
	RESPONSE #100
		SetGlobal("Iaeightcast2","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iaeightcast2","LOCALS",0)
	OR(2)
		Global("Iaeightcast","LOCALS",0)
		LevelGT(Myself,16)
THEN
	RESPONSE #100
		SetGlobal("Iaeightcast2","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iaeightcast2","LOCALS",0)
	OR(2)
		Global("Iaeightcast","LOCALS",0)
		LevelGT(Myself,16)
THEN
	RESPONSE #100
		SetGlobal("Iaeightcast2","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(3)
		LevelGT(LastSeenBy(Myself),8)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	Global("Iadeath","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadeath","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iasword","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iamordy","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iamordy","LOCALS",1)
		SetGlobalTimer("Iasword","LOCALS",THREE_ROUNDS)
		SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iasword","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iamordy","LOCALS",1)
	LevelGT(Myself,16)
THEN
	RESPONSE #100
		SetGlobal("Iamordy","LOCALS",2)
		SetGlobalTimer("Iasword","LOCALS",THREE_ROUNDS)
		SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	Global("chain","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("chain","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaskelet","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalLT("Iaskel","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iaskel","LOCALS",1)
		SetGlobalTimer("Iaskelet","LOCALS",THREE_ROUNDS)
		SpellNoDec(Myself,WIZARD_ANIMATE_DEAD)  // SPWI501.SPL (Animate Dead)
END

IF
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),4)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iafarrow","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafarrow","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),2)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iafarrow","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafarrow","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iafarrow","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafarrow","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iafarrow","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafarrow","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iafarrow","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iafarrow","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaacid","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaacid","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaacid","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iamissile","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iamissile","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iamissile","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	GlobalGT("Prep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	GlobalGT("Prep","LOCALS",0)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	GlobalGT("Prep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("prep","LOCALS",0)
		SetGlobal("Iainvis","LOCALS",0)
		SetGlobal("Iasturning","LOCALS",0)
		SetGlobal("Prep1","LOCALS",0)
		SetGlobal("Iadeath","LOCALS",0)
		SetGlobal("Iagmalison","LOCALS",0)
		SetGlobal("Iaeightcast","LOCALS",0)
		SetGlobal("Iaeightcast2","LOCALS",0)
		SetGlobal("Iamordy","LOCALS",0)
		SetGlobal("chain","LOCALS",0)
		SetGlobal("Iaskel","LOCALS",0)
		SetGlobal("Iafarrow","LOCALS",0)
		SetGlobal("Iaacid","LOCALS",0)
		SetGlobal("Iamissile","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END


IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState([PC],STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FourthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FifthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SixthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],100)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],100)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],100)
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],100)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],100)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],100)
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],100)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],100)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),100)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],100)
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC],3)
    HasItem("SW2H01",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW2H01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC]),3)
    HasItem("SW2H01",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW2H01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC]),3)
    HasItem("SW2H01",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW2H01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC]),3)
    HasItem("SW2H01",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW2H01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC]),3)
    HasItem("SW2H01",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW2H01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC]),3)
    HasItem("SW2H01",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW2H01",Myself,SLOT_WEAPON3,EQUIP)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([GOODCUTOFF])
	CheckStatLT([GOODCUTOFF],100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([GOODCUTOFF],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(SecondNearest([GOODCUTOFF]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(ThirdNearest([GOODCUTOFF]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(FourthNearest([GOODCUTOFF]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(FifthNearest([GOODCUTOFF]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(SixthNearest([GOODCUTOFF]),100,RESISTCRUSHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END


IF
	!Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	!Detect([PC])
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		Enemy()
		MoveToObject(Player1)
END

IF
	AreaCheck("AR0801")  // Bodhi's Hideout (sided with Aran)
	Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	!Detect([PC])
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HPPercentLT(Myself,100)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	!See([PC])
	!See([GOODCUTOFF])
	Global("Prep","LOCALS",0)
	Global("anticheese","LOCALS",0)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HPPercentLT(Myself,100)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",1)
		SetGlobalTimer("chase2","LOCALS",TWO_ROUNDS)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	Global("Prep","LOCALS",0)
	!See([PC])
	!See([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

