IF
	NumberOfTimesTalkedTo(0)
	Global("Iapcastts","GLOBAL",0)
	Detect([PC])
	!Dead("pirmur07")  // Vadek
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
END

IF
	Dead("pirmur07")  // Vadek
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iagalvprep","LOCALS",0)
	Allegiance(Myself,ENEMY)
	HasItem("POTN34",Myself)
THEN
	RESPONSE #100
		ReallyForceSpellRES("POTN34",Myself)
		DestroyItem("POTN34")
		Continue()
END

IF
	Global("Iagalvprep","LOCALS",0)
	Allegiance(Myself,ENEMY)
	HasItem("POTN33",Myself)  // Barbarian Essence
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN33X",Myself)  // No such index
		DestroyItem("POTN33")  // Barbarian Essence
		Continue()
END

IF
	Global("Iagalvprep","LOCALS",0)
	Allegiance(Myself,ENEMY)
	HasItem("POTN33",Myself)  // Barbarian Essence
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN33X",Myself)  // No such index
		DestroyItem("POTN33")  // Barbarian Essence
		SetGlobal("Iagalvprep","LOCALS",1)
		Continue()
END


IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	!Allegiance(Myself,ENEMY)
	!HPLT(Myself,1)
	InMyArea(Player1)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		AttackedBy([PC],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([PC],0)
THEN
	RESPONSE #100
		Enemy()
		MoveToObject(Player1)
END

IF
	See(NearestEnemyOf(Myself))
	Global("EnemySeen","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iagal01","LOCALS",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("POTN35",Myself)  // Potion of Magic Shielding
	See([PC])
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobal("Iagal01","LOCALS",1)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN35",Myself)  // Potion of Magic Shielding
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	Global("Iagal01","LOCALS",1)
	HasItem("S!minhp1",Myself)  // No such index
THEN
	RESPONSE #100
		DestroyItem("S!minhp1")  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	Global("Iaitem","LOCALS",0)
	!HasItem("S!minhp1",Myself)  // No such index
	AreaCheck("AR1610")  // Brothel Prison
THEN
	RESPONSE #100
		SetGlobal("Iaitem","LOCALS",1)
		GiveItemCreate("leat09",Myself,0,0,0)  // Armor of Stamina +5
END

IF
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("POTN55",Myself)  // Potion of Superior Healing
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN55",Myself)  // Potion of Superior Healing
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	Range(LastSeenBy(Myself),3)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iagal02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagal02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)  // SPCL906.SPL (Power Attack)
END

IF
	!See([PC])
	!See([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("EnemySeen","LOCALS",1)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!See([PC])
	!See([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!See([PC])
	!See([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iagal02","LOCALS",0)
		SetGlobal("EnemySeen","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!See([PC])
	!See([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

