

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
		Continue()
END

IF
	Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		NoAction()
END



IF
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("IaRestTimer","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("IaPrep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iacontin","LOCALS",0)
		SetGlobal("IaSpellTrigger","LOCALS",0)
		SetGlobal("IaSpellSequencer","LOCALS",0)
		SetGlobal("IaMinorSequencer","LOCALS",0)
		SetGlobal("IaPrep","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
		Continue()
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	GlobalGT("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iacontin","LOCALS",0)
		SetGlobal("IaSpellTrigger","LOCALS",0)
		SetGlobal("IaSpellSequencer","LOCALS",0)
		SetGlobal("IaMinorSequencer","LOCALS",0)
		SetGlobal("IaPrep","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END


IF
    ActionListEmpty()
	See(Player1)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar1SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar1Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player2)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar2SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar2Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player3)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar3SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar3Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player4)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar4SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar4Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player5)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar5SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar5Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	See(Player6)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar6SeenTimer","LOCALS",TWO_TURNS)
		SetGlobal("IaChar6Seen","LOCALS",1)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar1SeenTimer","LOCALS")
	Global("IaChar1Seen","LOCALS",1)
	!See(Player1)
THEN
	RESPONSE #100
		SetGlobal("IaChar1Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar2SeenTimer","LOCALS")
	Global("IaChar2Seen","LOCALS",1)
	!See(Player2)
THEN
	RESPONSE #100
		SetGlobal("IaChar2Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar3SeenTimer","LOCALS")
	Global("IaChar3Seen","LOCALS",1)
	!See(Player3)
THEN
	RESPONSE #100
		SetGlobal("IaChar3Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar4SeenTimer","LOCALS")
	Global("IaChar4Seen","LOCALS",1)
	!See(Player4)
THEN
	RESPONSE #100
		SetGlobal("IaChar4Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar5SeenTimer","LOCALS")
	Global("IaChar5Seen","LOCALS",1)
	!See(Player5)
THEN
	RESPONSE #100
		SetGlobal("IaChar5Seen","LOCALS",0)
		Continue()
END

IF
    ActionListEmpty()
	GlobalTimerExpired("IaChar6SeenTimer","LOCALS")
	Global("IaChar6Seen","LOCALS",1)
	!See(Player6)
THEN
	RESPONSE #100
		SetGlobal("IaChar6Seen","LOCALS",0)
		Continue()
END


IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	Range(LastSeenBy(Myself),5)
	CheckStatGT(LastSeenBy(Myself),0,RESISTACID)
	GlobalLT("IaLowerAcid","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("IaLowerAcid","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!DRU12",LastSeenBy(Myself))  // Lower Acid Resistance
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	Range(LastSeenBy(Myself),5)
	CheckStatGT(LastSeenBy(Myself),0,RESISTACID)
	GlobalLT("IaLowerAcid","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("IaLowerAcid","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!DRU12",LastSeenBy(Myself))  // Lower Acid Resistance
END

IF
	Allegiance(Myself,ENEMY)
	HPPercentLT(Myself,90)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	CheckStatLT(Myself,71,RESISTCRUSHING)
	See(NearestEnemyOf(Myself))
	GlobalLT("Iahard","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iahard","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	GlobalLT("IaMelf","LOCALS",1)
	Global("IaLowerAcid","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("IaMelf","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	GlobalLT("IaMelf","LOCALS",1)
	Global("IaLowerAcid","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("IaMelf","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaDominTimer","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckSpellState(LastSeenBy(Myself),CHARM_DOMINATION_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!Class(LastSeenBy(Myself),MONK)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL)
	GlobalLT("IaDomination","LOCALS",3)
THEN
	RESPONSE #100
		SetGlobalTimer("IaDominTimer","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		IncrementGlobal("IaDomination","LOCALS",1)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_DOMINATION)  // SPWI506.SPL (Domination)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaDominTimer","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckSpellState(LastSeenBy(Myself),CHARM_DOMINATION_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!Class(LastSeenBy(Myself),MONK)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL)
	GlobalLT("IaDomination","LOCALS",3)
THEN
	RESPONSE #100
		SetGlobalTimer("IaDominTimer","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		IncrementGlobal("IaDomination","LOCALS",1)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_DOMINATION)  // SPWI506.SPL (Domination)
END


IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState([PC],STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FourthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(FifthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckSpellState(SixthNearest([PC]),STUN_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSDEATH)
	OR(2)
	    CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	    !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalTimerNotExpired("PowerAttackActiveTimer","LOCALS")
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	Range([PC],6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),75,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	CheckStatLT([PC.0.0.DRUID_ALL],100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT([PC],100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	CheckStatLT(SecondNearest([PC]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	CheckStatLT(ThirdNearest([PC]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	CheckStatLT(FourthNearest([PC]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	CheckStatLT(FifthNearest([PC]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	CheckStatLT(SixthNearest([PC]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([GOODCUTOFF])
	CheckStatLT([GOODCUTOFF],100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([GOODCUTOFF],2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(SecondNearest([GOODCUTOFF]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(ThirdNearest([GOODCUTOFF]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(FourthNearest([GOODCUTOFF]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(FifthNearest([GOODCUTOFF]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(SixthNearest([GOODCUTOFF]),100,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([GOODCUTOFF]),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END


IF
	!GlobalTimerNotExpired("IaWeaponUnusable","LOCALS")
	OR(2)
        !WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
        !WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
	    SetGlobalTimer("IaWeaponUnusable","LOCALS",ONE_ROUND)
		ClearActions(Myself)
END


IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar1Seen","LOCALS",1)
	!See(Player1)
	!HPLT(Player1,0)
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar2Seen","LOCALS",1)
	!See(Player2)
	!HPLT(Player2,0)
	InMyArea(Player2)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar3Seen","LOCALS",1)
	!See(Player3)
	!HPLT(Player3,0)
	InMyArea(Player3)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar4Seen","LOCALS",1)
	!See(Player4)
	!HPLT(Player4,0)
	InMyArea(Player4)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar5Seen","LOCALS",1)
	!See(Player5)
	!HPLT(Player5,0)
	InMyArea(Player5)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	Allegiance(Myself,ENEMY)
    ActionListEmpty()
	Global("IaChar6Seen","LOCALS",1)
	!See(Player6)
	!HPLT(Player6,0)
	InMyArea(Player6)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END


IF
	See(NearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FifthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SixthNearestEnemyOf(Myself))
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

