IF
	Allegiance("pbhunt01",ENEMY)  // Aawill
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
		Shout(89)
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iahound","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iahound","LOCALS",1)
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iamorehound","LOCALS")
	See([PC])
	!Range(LastSeenBy(Myself),4)
	Global("Iahound","LOCALS",1)
	Global("Prep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iamorehound","LOCALS",FOUR_ROUNDS)
		SetGlobal("Iahound","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iadoonce","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadoonce","LOCALS",1)
		SetGlobalTimer("Iamorehound","LOCALS",FOUR_ROUNDS)
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Heard([EVILCUTOFF],89)
	Allegiance(Myself,NEUTRAL)
	See(LastHeardBy(Myself))
THEN
	RESPONSE #100
		Enemy()
		MoveToObject(LastHeardBy(Myself))
END

IF
	Heard([EVILCUTOFF],89)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Heard([EVILCUTOFF],89)
	!See(NearestEnemyOf(Myself))
	See(LastHeardBy(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prep","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_RESIST_FEAR)
		ReallyForceSpell(Myself,WIZARD_GHOST_ARMOR)  // SPWI317.SPL (Ghost Armor)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
		ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
		ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
		ReallyForceSpell(Myself,CLERIC_AID)  // SPPR201.SPL (Aid)
		ReallyForceSpell(Myself,CLERIC_CHANT)
		ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
		ReallyForceSpell(Myself,CLERIC_FREE_ACTIONS)
		ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
		ReallyForceSpell(Myself,CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
		ReallyForceSpell(Myself,CLERIC_CHAOTIC_COMMANDS)
		ReallyForceSpell(Myself,CLERIC_RIGHTEOUS_MAGIC)
		ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Protection From Missiles)
		ReallyForceSpellRES("SPPR617", Myself)
		ReallyForceSpell(Myself,NPC_BLADE_BARRIER)  // SPPR698.SPL (Blade Barrier)
END

IF
	Global("Ianobook","LOCALS",0)
	Global("Iafmc","AR0516",1)  // Planar Prison
	Global("Ialegacybook","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("Ianobook","LOCALS",1)
		DestroyItem("S!misc16")  // Elven Ancestors' Legacy
END

IF
	Global("Ianobook","LOCALS",0)
	Global("Iafmc","AR0516",1)  // Planar Prison
THEN
	RESPONSE #100
		SetGlobal("Ianobook","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	XPLT(Player1,2350000)
	Global("IaToneDown","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaToneDown","LOCALS",1)
		SetGlobal("Iahard","LOCALS",5)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([GOODCUTOFF])
		Detect([PC])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(4)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	!HPLT(Myself,1)
	Global("Iabounty01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iabounty01","LOCALS",1)
		DisplayString(Myself,29736)  // Contingency—Stoneskin
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	Global("Iabounty01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iabounty01","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	HPPercentLT(Myself,90)
	CheckStatLT(Myself,70,RESISTSLASHING)
	GlobalLT("Iahard","LOCALS",1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("Iahard","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	InMyArea(Player1)
	GlobalLT("Iasweet","LOCALS",2)
	Global("Iapccloud","AR0516",1)  // Planar Prison
THEN
	RESPONSE #100
		SetGlobal("Iapccloud","AR0516",0)  // Planar Prison
		IncrementGlobal("Iasweet","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,NEUTRAL)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	InMyArea(Player1)
	Global("Iapccloud","AR0516",1)  // Planar Prison
	GlobalLT("Iasweet","LOCALS",2)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("Iapccloud","AR0516",0)  // Planar Prison
		IncrementGlobal("Iasweet","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),4)
	OR(2)
		!GlobalTimerNotExpired("pfmw","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iabounty02","LOCALS",4)
	HasItem("scrl7o",Myself)  // Protection From Magical Weapons
THEN
	RESPONSE #100
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		IncrementGlobal("Iabounty02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl7o",Myself)  // Protection From Magical Weapons
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,40)
	Global("Iaheal","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaheal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Detect([PC])
	OR(2)
		!See([PC])
		!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iadispel","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispel","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatGT(LastSeenBy(Myself),29,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Ialower","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialower","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatGT(LastSeenBy(Myself),29,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Ialower","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialower","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatGT(LastSeenBy(Myself),29,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Ialower","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialower","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iabounty04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iabounty04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iabounty04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iabounty04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iafinger","LOCALS",0)
	!HasBounceEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iafinger","LOCALS",0)
	!HasBounceEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iabounty09","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabounty09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iabounty09","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabounty09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iabounty09","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iabounty09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("scrl7i",Myself)  // Death Spell
	GlobalLT("Iabounty03","LOCALS",4)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(3)
		LevelGT(LastSeenBy(Myself),8)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
THEN
	RESPONSE #100
		IncrementGlobal("Iabounty03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl7i",LastSeenBy(Myself))  // Death Spell
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,75)
	GlobalLT("Iacure","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iacure","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Cure Serious Wounds)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	GlobalLT("Iahold","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iahold","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	GlobalLT("Iahold","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iahold","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	GlobalLT("Iahold","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iahold","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iabounty08","LOCALS",4)
	HasItem("scrl7s",Myself)  // Chain Lightning
THEN
	RESPONSE #100
		IncrementGlobal("Iabounty08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl7s",LastSeenBy(Myself))  // Chain Lightning
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iabounty08","LOCALS",4)
	HasItem("scrl7s",Myself)  // Chain Lightning
THEN
	RESPONSE #100
		IncrementGlobal("Iabounty08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl7s",LastSeenBy(Myself))  // Chain Lightning
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaflame","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaflame","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaflame","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaflame","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iacommand","LOCALS",8)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iacommand","LOCALS",8)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iacommand","LOCALS",8)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaacid","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaacid","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaacid","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaacid","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("partyfled","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

