IF
	Detect([PC])
	Global("Iatimer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("golemcall","LOCALS",THREE_ROUNDS)
		SetGlobal("Iatimer","LOCALS",1)
END

IF
	Global("IaSpawnElementals1","LOCALS",0)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Global("IaSpawnElementals2","LOCALS",0)
	HPPercentLT(Myself,50)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Global("IaSpawnElementals3","LOCALS",0)
	HPPercentLT(Myself,25)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOEL3",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	See([PC])
	Exists("S!aurie3")  // Chief Inspector Auriel
	!Dead("S!aurie3")  // Chief Inspector Auriel
	See("S!aurie3")  // Chief Inspector Auriel
	RandomNumLT(6,2)
THEN
	RESPONSE #100
		AttackOneRound("S!aurie3")  // Chief Inspector Auriel
		AttackOneRound("S!aurie3")  // Chief Inspector Auriel
END

IF
	!See([PC])
	Exists("S!aurie3")  // Chief Inspector Auriel
	!Dead("S!aurie3")  // Chief Inspector Auriel
	See("S!aurie3")  // Chief Inspector Auriel
THEN
	RESPONSE #100
		AttackOneRound("S!aurie3")  // Chief Inspector Auriel
		AttackOneRound("S!aurie3")  // Chief Inspector Auriel
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	InMyArea(Player1)
	Exists("S!aurie3")  // Chief Inspector Auriel
	!Dead("S!aurie3")  // Chief Inspector Auriel
	See(NearestEnemyOf(Myself))
	CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject("S!aurie3")  // Chief Inspector Auriel
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Exists("S!aurie3")  // Chief Inspector Auriel
	!Dead("S!aurie3")  // Chief Inspector Auriel
	!See("S!aurie3")  // Chief Inspector Auriel
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

