IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iaepicbattle","AR4500",2)  // Pocket Plane
	Global("Iasuicide","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iasuicide","LOCALS",1)
		DestroySelf()
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	Exists("S!pasha2")  // Pasha Mahmoud
	!Dead("S!pasha2")  // Pasha Mahmoud
	OR(2)
		See("S!pasha2")  // Pasha Mahmoud
		See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Detect([PC])
	Global("EnemySeen","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",1)
END

IF
	Detect([PC])
	Global("Iatimer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("golemcall","LOCALS",THREE_ROUNDS)
		SetGlobal("Iatimer","LOCALS",1)
END

IF
	Global("IaSpawnElementals1","LOCALS",0)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Global("IaSpawnElementals2","LOCALS",0)
	HPPercentLT(Myself,50)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Global("IaSpawnElementals3","LOCALS",0)
	HPPercentLT(Myself,25)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOELG",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	See([PC])
	Exists("S!pasha2")  // Pasha Mahmoud
	!Dead("S!pasha2")  // Pasha Mahmoud
	See("S!pasha2")  // Pasha Mahmoud
	Range("S!pasha2",2)  // Pasha Mahmoud
	RandomNumLT(6,2)
THEN
	RESPONSE #100
		AttackOneRound("S!pasha2")  // Pasha Mahmoud
		AttackOneRound("S!pasha2")  // Pasha Mahmoud
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	!See([PC])
	Exists("S!pasha2")  // Pasha Mahmoud
	!Dead("S!pasha2")  // Pasha Mahmoud
	See("S!pasha2")  // Pasha Mahmoud
	RandomNumGT(6,5)
THEN
	RESPONSE #100
		AttackOneRound("S!pasha2")  // Pasha Mahmoud
		AttackOneRound("S!pasha2")  // Pasha Mahmoud
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Exists("S!pasha2")  // Pasha Mahmoud
	!Dead("S!pasha2")  // Pasha Mahmoud
	!See("S!pasha2")  // Pasha Mahmoud
	Global("partyfled","LOCALS",0)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Exists("S!pasha2")  // Pasha Mahmoud
	!Dead("S!pasha2")  // Pasha Mahmoud
	!See("S!pasha2")  // Pasha Mahmoud
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Exists("S!pasha2")  // Pasha Mahmoud
	!Dead("S!pasha2")  // Pasha Mahmoud
	!See("S!pasha2")  // Pasha Mahmoud
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Dead("S!pasha2")  // Pasha Mahmoud
	Global("partyfled","LOCALS",0)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Dead("S!pasha2")  // Pasha Mahmoud
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Dead("S!pasha2")  // Pasha Mahmoud
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Global("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	Global("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	AreaCheck("AR4500")  // Pocket Plane
	GlobalGT("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Exists("S!pasha2")  // Pasha Mahmoud
	!Dead("S!pasha2")  // Pasha Mahmoud
	!See("S!pasha2")  // Pasha Mahmoud
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("Iapasha","AR4500",0)  // Pocket Plane
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

