IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	See(NearestEnemyOf(Myself))
	Global("Iaexit","AR0907",0)  // Guarded Compound 2nd Floor
THEN
	RESPONSE #100
		SetGlobal("Iaexit","AR0907",1)  // Guarded Compound 2nd Floor
END

IF
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	!GlobalTimerNotExpired("Iapurge","LOCALS")
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iapurge","LOCALS",FOUR_ROUNDS)
		ReallyForceSpellRES("SPINI29",LastSeenBy(Myself))  // Purge Magic
END

IF
	!GlobalTimerNotExpired("Iareconstruct","LOCALS")
	Global("Iapcastts","GLOBAL",1)
	!HPLT(Myself,1)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		SetGlobalTimer("Iareconstruct","LOCALS",THREE_ROUNDS)
		ReallyForceSpellRES("SPWII45",Myself)  // No such index
END

IF
	!GlobalTimerNotExpired("Iareconstruct","LOCALS")
	!Detect([PC])
	!Detect([GOODCUTOFF])
	!HPLT(Myself,1)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		SetGlobalTimer("Iareconstruct","LOCALS",TEN_ROUNDS)
		ReallyForceSpellRES("SPWII45",Myself)  // No such index
END

IF
	Detect([PC])
	Global("Iatimer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("golemcall","LOCALS",ONE_ROUND)
		SetGlobal("Iatimer","LOCALS",1)
END

IF
	Detect([PC])
	Global("IaAmbers","LOCALS",0)
THEN
	RESPONSE #100
		CreateCreatureObject("S!ambere",Myself,0,0,0)  // Amber Golem
		CreateCreatureObject("S!ambere",Myself,0,0,0)  // Amber Golem
		SetGlobal("IaAmbers","LOCALS",1)
END

IF
	Global("IaSpawnElementals1","LOCALS",0)
	HPPercentLT(Myself,83)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals1","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Global("IaSpawnElementals2","LOCALS",0)
	HPPercentLT(Myself,66)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals2","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Global("IaSpawnElementals3","LOCALS",0)
	HPPercentLT(Myself,50)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals3","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Global("IaSpawnElementals4","LOCALS",0)
	HPPercentLT(Myself,33)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals4","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals4","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals4","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals4","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Global("IaSpawnElementals5","LOCALS",0)
	HPPercentLT(Myself,17)
THEN
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!ICEEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals5","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ELEC-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!MAGEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals5","LOCALS",1)
		ReallyForceSpellRES("S!FIRE-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!OOZEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals5","LOCALS",1)
		ReallyForceSpellRES("S!COLD-5",Myself)
		ReallyForceSpellRES("S!ACID-5",Myself)
	RESPONSE #25
		ReallyForceSpellRES("S!ELEINF",Myself)
		CreateCreatureObject("S!SMOEL1",Myself,0,0,0)
		SetGlobal("IaSpawnElementals5","LOCALS",1)
		ReallyForceSpellRES("S!ELEC-5",Myself)
		ReallyForceSpellRES("S!FIRE-5",Myself)
END

IF
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iarynnplace","GLOBAL",4)
	GlobalGT("golems","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iarynnplace","GLOBAL",5)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("staf20",Myself,0,0,0)  // Staff of Rhynn +4
END

IF
	Detect([PC])
	Global("Iatreasure2","LOCALS",0)
	Global("Iaavoidplace","GLOBAL",1)
	GlobalGT("golems","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iaavoidplace","GLOBAL",5)
		SetGlobal("Iatreasure2","LOCALS",1)
		GiveItemCreate("boot04",Myself,0,0,0)  // Senses of the Cat
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure3","LOCALS",0)
	Global("Iaring35place","GLOBAL",4)
	GlobalGT("golems","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iaring35place","GLOBAL",5)
		SetGlobal("Iatreasure3","LOCALS",1)
		GiveItemCreate("ring35",Myself,0,0,0)  // Ring of Lock Picks
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure4","LOCALS",0)
	Global("Iaaegerplace","GLOBAL",1)
	GlobalGT("golems","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iaaegerplace","GLOBAL",3)
		SetGlobal("Iatreasure4","LOCALS",1)
		GiveItemCreate("leat20",Myself,0,0,0)  // Aeger's Hide +3
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Global("Iatimer","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Global("Iatimer","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Iatimer","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatimer","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!See([PC])
	!See([GOODCUTOFF])
	Global("Iatimer","LOCALS",0)
	Global("anticheese","LOCALS",0)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HPPercentLT(Myself,100)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",1)
		SetGlobalTimer("chase2","LOCALS",TWO_ROUNDS)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	Global("Iatimer","LOCALS",0)
	!See([PC])
	!See([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	Global("Iatimer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

