IF
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		TookDamage()
	Allegiance(Myself,NEUTRAL)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Enemy()
		Shout(99)
		MoveToObject(Player1)
END

IF
	Exists("tarnor")  // Tarnor the Hatchetman
	!Dead("tarnor")  // Tarnor the Hatchetman
	Allegiance("tarnor",ENEMY)  // Tarnor the Hatchetman
	Allegiance(Myself,NEUTRAL)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Enemy()
		Shout(99)
		MoveToObject(Player1)
END

IF
	Exists("tarnor")  // Tarnor the Hatchetman
	!Dead("tarnor")  // Tarnor the Hatchetman
	Allegiance("tarnor",NEUTRAL)  // Tarnor the Hatchetman
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Shout(99)
		ActionOverride("tarnor",Enemy())
END

IF
	Exists("gall")  // Gallchobhair
	!Dead("gall")  // Gallchobhair
	Allegiance("gall",ENEMY)  // Gallchobhair
	Allegiance(Myself,NEUTRAL)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Enemy()
		Shout(99)
		MoveToObject(Player1)
END

IF
	Heard([EVILCUTOFF],99)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
		Shout(57)
END

IF
	Heard([EVILCUTOFF],99)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Heard([EVILCUTOFF],57)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iagaius01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iagaiusrest","GLOBAL",SEVEN_HOURS)
		ReallyForceSpell(Myself,WIZARD_ARMOR)
		ReallyForceSpell(Myself,WIZARD_SHIELD)
		ReallyForceSpell(Myself,WIZARD_BLUR)
		ReallyForceSpell(Myself,WIZARD_LUCK)
		ReallyForceSpell(Myself,WIZARD_RESIST_FEAR)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_HASTE)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpellRES("SPWI522",Myself)
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
		ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
		ReallyForceSpellRES("SPWI725",Myself)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
		ForceSpell(Myself,WARRIOR_HARDINESS)
		SetGlobalTimer("Iamsword","LOCALS",SIX_ROUNDS)
		Shout(99)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iagaius01","LOCALS",0)
	Exists("tarnor")  // Tarnor the Hatchetman
	!Dead("tarnor")  // Tarnor the Hatchetman
THEN
	RESPONSE #100
		ReallyForceSpell("TARNOR",WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iagaius01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagaius01","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	GlobalTimerExpired("Iagaiusrest","GLOBAL")
	Global("Iagaius01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iagaiusrest","GLOBAL",SEVEN_HOURS)
		SetGlobal("Iagaius01","LOCALS",0)
		SetGlobal("Iagaius02","LOCALS",0)
		SetGlobal("Iagaius03","LOCALS",0)
		SetGlobal("Iagaius04","LOCALS",0)
		SetGlobal("Iagaius05","LOCALS",0)
		SetGlobal("Iagaius06","LOCALS",0)
		SetGlobal("Iagaius07","LOCALS",0)
		SetGlobal("Iagaius08","LOCALS",0)
		SetGlobal("Iagaius09","LOCALS",0)
		SetGlobal("Iagaius10","LOCALS",0)
		SetGlobal("Iagaius11","LOCALS",0)
		SetGlobal("Iagaius15","LOCALS",0)
		SetGlobal("Iagaius16","LOCALS",0)
		SetGlobal("Iagaius17","LOCALS",0)
		SetGlobal("Iagaius18","LOCALS",0)
		SetGlobal("Iagaius19","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("Iacastbreach","LOCALS",0)
		SetGlobal("Iapword","LOCALS",0)
		SetGlobal("Iahla","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([GOODCUTOFF])
		Detect([PC])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	See([PC])
	HasItem("potn35",Myself)  // Potion of Magic Shielding
	Global("Iashielding","LOCALS",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Iashielding","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn35",Myself)  // Potion of Magic Shielding
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaexit","AR0701",0)  // The Sewers
THEN
	RESPONSE #100
		SetGlobal("Iaexit","AR0701",1)  // The Sewers
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	Global("Iashielding","LOCALS",1)
	HasItem("surehp1",Myself)  // Ring
	!HPPercentLT(Myself,100)
THEN
	RESPONSE #100
		DestroyItem("surehp1")  // Ring
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	Global("Iashielding","LOCALS",1)
	HasItem("surehp1",Myself)  // Ring
	HPPercentLT(Myself,100)
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	!HasItem("surehp1",Myself)  // Ring
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_HELPLESS)
	HPPercentLT(Myself,75)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iagaius10","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Iagaius10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	Global("Iapcastts","GLOBAL",0)
	StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Myself))
	Global("Iagaius07","LOCALS",0)
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		SetGlobal("Iagaius07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iagaius07","LOCALS",1)
	CheckStatLT(Myself,1,STONESKINS)
	HPPercentLT(Myself,100)
	Global("Iagaius05","LOCALS",0)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Iagaius05","LOCALS",1)
		DisplayString(Myself,29736)  // Contingency—Stoneskin
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("scrl9c",Myself)  // Improved Mantle
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	OR(2)
		!GlobalTimerNotExpired("pfmw","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iagaius06","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius06","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9c",Myself)  // Improved Mantle
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	CheckStatLT(Myself,40,RESISTCRUSHING)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	HPPercentLT(Myself,90)
	CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iahla","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iahla","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,60)
	HasItem("potn52",Myself)  // Potion of Extra Healing
	!GlobalTimerNotExpired("Iaspell","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(4)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		!Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,50,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,50,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,50,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,50,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,50,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,50,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,50,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,50,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,50,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,50,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,50,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,50,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,50,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,50,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,50,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,50,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,50,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,50,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapword","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	XPLT(Player1,2350000)
	GlobalLT("Chapter","GLOBAL",4)
THEN
	RESPONSE #100
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("S!misc41",Myself,0,0,0)  // Diamond Necklace
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iagaius11","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iagaius11","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Detect([PC])
	OR(2)
		!See([PC])
		!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalTimerExpired("Iamsword","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	Global("Iagaius03","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagaius03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",2)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",2)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",2)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",2)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",2)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",2)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	See([PC])
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	See(FourthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	See(FifthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapword","LOCALS",0)
	See(SixthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",2)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	GlobalLT("Iagaius19","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius19","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iagaius04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagaius04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iagaius09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagaius09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iagaius09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagaius09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iagaius09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iagaius09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iagaius02","LOCALS",2)
	Dead("BERKREF")  // Zorl
	Dead("RENGAA")  // Rengaard
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(3)
		LevelGT(LastSeenBy(Myself),8)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iagaius02","LOCALS",2)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!Class(LastSeenBy(Myself),SKELETON)
	!Class(LastSeenBy(Myself),SKELETON_WARRIOR)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(3)
		LevelGT(LastSeenBy(Myself),8)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	GlobalLT("Iagaius08","LOCALS",2)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	GlobalLT("Iagaius08","LOCALS",2)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	GlobalLT("Iagaius08","LOCALS",2)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See([PC])
	GlobalLT("Iagaius16","LOCALS",4)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius16","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearest([PC]))
	GlobalLT("Iagaius16","LOCALS",4)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius16","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearest([PC]))
	GlobalLT("Iagaius16","LOCALS",4)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius16","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearest([PC]))
	GlobalLT("Iagaius17","LOCALS",3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius17","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearest([PC]))
	GlobalLT("Iagaius17","LOCALS",3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius17","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See([PC])
	GlobalLT("Iagaius17","LOCALS",3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius17","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	GlobalLT("Iagaius18","LOCALS",5)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	GlobalLT("Iagaius18","LOCALS",5)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	GlobalLT("Iagaius18","LOCALS",5)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iagaius18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("partyfled","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	HasItem("bull03",Myself)  // Bullet +2
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	ActionListEmpty()
	OR(2)
		!HasItem("bull03",Myself)  // Bullet +2
		Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	HasItem("bull03",Myself)  // Bullet +2
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	ActionListEmpty()
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	HasItem("bull03",Myself)  // Bullet +2
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	ActionListEmpty()
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	HasItem("bull03",Myself)  // Bullet +2
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	HasItem("bull03",Myself)  // Bullet +2
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	HasItem("bull03",Myself)  // Bullet +2
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

