IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	!See(NearestEnemyOf(Myself))
	Heard([EVILCUTOFF],151)
	!Class(Myself,INNOCENT)
	See(LastHeardBy(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

IF
	!See(NearestEnemyOf(Myself))
	Heard([EVILCUTOFF],152)
	See(LastHeardBy(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Global("EnemySeen","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([GOODCUTOFF])
		Detect([PC])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	HasItem("potn02",Myself)
	Global("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		ReallyForceSpellRES("POTN02",Myself)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	HasItem("potn14",Myself)
	Global("IaPrep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaPrep","LOCALS",1)
		ReallyForceSpellRES("POTN14",Myself)
		Continue()
END

IF
	HaveSpellRES("SPCL321")  // Enrage
	!CheckSpellState(Myself,BERSERKER_RAGE_FATIGUE)
	!CheckSpellState(Myself,BERSERKER_RAGE)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SpellRES("SPCL321",Myself)  // Enrage
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("IaPrep","LOCALS",0)
		SetGlobal("EnemySeen","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	HasItem("POTN14",Myself)
	Detect(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_HASTED)
	CheckStat(Myself,0,IMPROVEDHASTE)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		UseItem("POTN14",Myself)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-10,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-10,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-10,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-10,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-10,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-10,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),3)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],50)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],50)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),50)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),50)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),50)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),50)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.MAGE_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.MAGE_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.DRUID_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.DRUID_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.DRUID_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	Range([PC.0.0.THIEF_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SecondNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FourthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(FifthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),0,STONESKINS)
	!StateCheck(SixthNearest([PC.0.0.THIEF_ALL]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],100)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],100)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),50,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC.0.0.MAGE_ALL],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC.0.0.MAGE_ALL],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC.0.0.MAGE_ALL],5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC.0.0.MAGE_ALL]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],100)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],100)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],100)
	OR(2)
	    CheckStatGT([PC],-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT([PC],0,STONESKINS)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	Range([PC],5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),100)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	Range(SecondNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),100)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	Range(ThirdNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FourthNearest([PC]),0,STONESKINS)
	!StateCheck(FourthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FourthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),100)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(FifthNearest([PC]),0,STONESKINS)
	!StateCheck(FifthNearest([PC]),STATE_MIRRORIMAGE)
	Range(FifthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),100)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	!CheckStatGT(SixthNearest([PC]),0,STONESKINS)
	!StateCheck(SixthNearest([PC]),STATE_MIRRORIMAGE)
	Range(SixthNearest([PC]),5)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
	    
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	HPLT(NearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(NearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(NearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	HPLT(SecondNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(SecondNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	HPLT(ThirdNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(ThirdNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	HPLT(FourthNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(FourthNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	HPLT(FifthNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(FifthNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	HPLT(SixthNearestEnemyOf(Myself),100)
	OR(2)
	    CheckStatGT(SixthNearestEnemyOf(Myself),-15,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	HPLT([PC.0.0.MAGE_ALL],500)
	OR(2)
	    CheckStatGT([PC.0.0.MAGE_ALL],-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.MAGE_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.MAGE_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.MAGE_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	HPLT(SecondNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	HPLT(ThirdNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FourthNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	HPLT(FifthNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	HPLT(SixthNearest([PC.0.0.MAGE_ALL]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.MAGE_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.MAGE_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.MAGE_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.DRUID_ALL])
	HPLT([PC.0.0.DRUID_ALL],500)
	OR(2)
	    CheckStatGT([PC.0.0.DRUID_ALL],-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.DRUID_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.DRUID_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.DRUID_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	HPLT(SecondNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	HPLT(ThirdNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FourthNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.DRUID_ALL]))
	HPLT(FifthNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.DRUID_ALL]))
	HPLT(SixthNearest([PC.0.0.DRUID_ALL]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.DRUID_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.DRUID_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.DRUID_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	HPLT([PC.0.0.THIEF_ALL],500)
	OR(2)
	    CheckStatGT([PC.0.0.THIEF_ALL],-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC.0.0.THIEF_ALL],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC.0.0.THIEF_ALL],1,SCRIPTINGSTATE6)
	Range([PC.0.0.THIEF_ALL],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC.0.0.THIEF_ALL]))
	HPLT(SecondNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC.0.0.THIEF_ALL]))
	HPLT(ThirdNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FourthNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC.0.0.THIEF_ALL]))
	HPLT(FifthNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC.0.0.THIEF_ALL]))
	HPLT(SixthNearest([PC.0.0.THIEF_ALL]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC.0.0.THIEF_ALL]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC.0.0.THIEF_ALL]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC.0.0.THIEF_ALL]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],500)
	OR(2)
	    CheckStatGT([PC],-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT([PC],1,SCRIPTINGSTATE6)
	Range([PC],10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearest([PC]),1,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearest([PC]),1,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	HPLT([PC],500)
	OR(2)
	    CheckStatGT([PC],-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT([PC],80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat([PC],3,SCRIPTINGSTATE6)
	!CheckSpellState([PC],PROTECTION_FROM_NORMAL_WEAPONS)
	Range([PC],10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearest([PC]))
	HPLT(SecondNearest([PC]),500)
	OR(2)
	    CheckStatGT(SecondNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SecondNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SecondNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearest([PC]))
	HPLT(ThirdNearest([PC]),500)
	OR(2)
	    CheckStatGT(ThirdNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(ThirdNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(ThirdNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearest([PC]))
	HPLT(FourthNearest([PC]),500)
	OR(2)
	    CheckStatGT(FourthNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FourthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FourthNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearest([PC]))
	HPLT(FifthNearest([PC]),500)
	OR(2)
	    CheckStatGT(FifthNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(FifthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(FifthNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearest([PC]))
	HPLT(SixthNearest([PC]),500)
	OR(2)
	    CheckStatGT(SixthNearest([PC]),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	HPLT(NearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(NearestEnemyOf(Myself),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(NearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	HPLT(SecondNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(SecondNearestEnemyOf(Myself),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	HPLT(ThirdNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(ThirdNearestEnemyOf(Myself),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	HPLT(FourthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(FourthNearestEnemyOf(Myself),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	HPLT(FifthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(FifthNearestEnemyOf(Myself),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	HPLT(SixthNearestEnemyOf(Myself),500)
	OR(2)
	    CheckStatGT(SixthNearestEnemyOf(Myself),-20,ARMORCLASS)
	    CheckStatGT(Myself,5,CRITICALHITBONUS)
	CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See([PC])
	CheckStatLT(SixthNearest([PC]),80,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    CheckStat(SixthNearest([PC]),3,SCRIPTINGSTATE6)
	!CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_WEAPONS)
	Range(SixthNearest([PC]),10)
    HasItem("SW1H04",Myself)
THEN
	RESPONSE #100
		XEquipItem("SW1H04",Myself,SLOT_WEAPON3,EQUIP)
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	CheckStatLT(NearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(NearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(SecondNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(ThirdNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(FourthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(FifthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(SixthNearestEnemyOf(Myself),90,RESISTSLASHING) // PIERCING/CRUSHING/SLASHING
    !CheckStatGT(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END


