
IF
	Allegiance(Myself,ENEMY)
	Global("SamiaBattle","AR1202",0)  // Firkraag's Maze
THEN
	RESPONSE #100
		SetGlobal("SamiaBattle","AR1202",1)  // Firkraag's Maze
		Continue()
END

IF
	!Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	Global("SamiaBattle","AR1202",1)  // Firkraag's Maze
THEN
	RESPONSE #100
		Enemy()
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([GOODCUTOFF])
		Detect([PC])
	Global("Iakaol01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol01","LOCALS",1)
	    ReallyForceSpellRES("S!CNT03A",Myself)
	    ReallyForceSpellRES("S!CNT06A",Myself)
		ReallyForceSpellRES("PTN33X",Myself)  // No such index
		ReallyForceSpellRES("PTN33X",Myself)  // No such index
		SetGlobalTimer("Iatpt","LOCALS",66)
		SetGlobalTimer("absolute","LOCALS",FOUR_ROUNDS)
		ReallyForceSpellRES("SPWI305",Myself)
		ReallyForceSpellRES("SPWII41",Myself)  // Improved Invisibility
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpellRES("SPWI725",Myself)
		ReallyForceSpellRES("SPWI804",Myself)  // Tenser's Partial Transformation
		ReallyForceSpellRES("SPWI807",Myself)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_ABSOLUTE_IMMUNITY)  // SPWI907.SPL (Absolute Immunity)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	HasItem("surehp1",Myself)  // Ring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		DestroyItem("surehp1")  // Ring
		SetInterrupt(TRUE)
		Continue()
END

IF
	!HasItem("surehp1",Myself)  // Ring
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	AreaCheck("AR1202")  // Firkraag's Maze
	Detect([PC])
	Global("Iaskelw","AR1202",0)  // Firkraag's Maze
THEN
	RESPONSE #100
		SetGlobal("Iaskelw","AR1202",1)  // Firkraag's Maze
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iavecnaplace","GLOBAL",4)
	GlobalLT("Chapter","GLOBAL",6)
THEN
	RESPONSE #100
		SetGlobal("Iavecnaplace","GLOBAL",3)
END

IF
	Allegiance(Myself,ENEMY)
	AreaCheck("AR1202")  // Firkraag's Maze
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iavecnaplace","GLOBAL",4)
	Global("Iapcastts","GLOBAL",0)
	Global("SpawnSamiaFriends","AR1202",1)  // Firkraag's Maze
THEN
	RESPONSE #100
		SetGlobal("Iavecnaplace","GLOBAL",5)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("wa2robe",Myself,0,0,0)  // Robe of Vecna
		XEquipItem("wa2robe",Myself,SLOT_ARMOR,EQUIP)
END

IF
	Allegiance(Myself,ENEMY)
	AreaCheck("AR1202")  // Firkraag's Maze
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iavecnaplace","GLOBAL",4)
	Global("Iapcastts","GLOBAL",0)
	!Global("SpawnSamiaFriends","AR1202",1)  // Firkraag's Maze
THEN
	RESPONSE #100
		SetGlobal("Iavecnaplace","GLOBAL",2)
		SetGlobal("Iatreasure","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(4)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	!Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	Global("Iasamiadamaged","AR1202",0)  // Firkraag's Maze
	OR(5)
		AttackedBy([GOODCUTOFF],DEFAULT)
		AttackedBy([PC],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([PC],0)
		TookDamage()
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("Iasamiadamaged","AR1202",1)  // Firkraag's Maze
		Shout(151)
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	OR(2)
		!GlobalTimerNotExpired("absolute","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iakaol03","LOCALS",4)
	HasItem("scrl9p",Myself)  // Absolute Immunity
THEN
	RESPONSE #100
		SetGlobalTimer("absolute","LOCALS",FOUR_ROUNDS)
		IncrementGlobal("Iakaol03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9p",Myself)  // Absolute Immunity
END

IF
	!Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	Global("Iasamiadamaged","AR1202",1)  // Firkraag's Maze
	Global("Iahostile","LOCALS",0)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("Iahostile","LOCALS",1)
		Shout(151)
		MoveToObject(Player1)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,50,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,50,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,50,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,50,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,50,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,50,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,50,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,50,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,50,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,50,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,50,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,50,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,50,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,50,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,50,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,50,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,50,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,50,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iakaol12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	See(NearestEnemyOf(Myself))
	Global("Iakaol10","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalTimerExpired("Iatpt","LOCALS")
	Global("Iakaol16","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iakaol16","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI804",Myself)  // Tenser's Partial Transformation
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iaskin","LOCALS",0)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		SetGlobal("Iaskin","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Detect([PC])
	OR(2)
		!See([PC])
		!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",4)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",3)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE6)
		CheckSpellState(Player1,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",4)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",3)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE6)
		CheckSpellState(Player2,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",4)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",3)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE6)
		CheckSpellState(Player3,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",4)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",3)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE6)
		CheckSpellState(Player4,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",4)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",3)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE6)
		CheckSpellState(Player5,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",4)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",3)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",3)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE6)
		CheckSpellState(Player6,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	Global("Iakaol06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	Global("Iakaol06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iapotdispel","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
		CheckSpellState(LastSeenBy(Myself),DISPELLABLE_INCREASED_FIRE_RESISTANCE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	GlobalLT("Iadispelpot","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iapotdispel","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iapotdispel","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
		CheckSpellState(LastSeenBy(Myself),DISPELLABLE_INCREASED_FIRE_RESISTANCE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	GlobalLT("Iadispelpot","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iapotdispel","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iapotdispel","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
		CheckSpellState(LastSeenBy(Myself),DISPELLABLE_INCREASED_FIRE_RESISTANCE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	GlobalLT("Iadispelpot","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iapotdispel","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	See([PC])
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	See(FourthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	See(FifthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iakaol12","LOCALS",0)
	See(SixthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",4)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iakaol27","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol27","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END


IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See([PC])
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(FourthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(FifthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(SixthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Range(LastSeenBy(Myself),6)
	GlobalLT("Iakaol17","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Range(LastSeenBy(Myself),6)
	GlobalLT("Iakaol17","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	GlobalLT("Iakaol17","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	GlobalLT("Iakaol17","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	GlobalLT("Iakaol17","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iakaol04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iakaol04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iakaol08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iakaol08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iakaol08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
	Global("Iakaol09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
	Global("Iakaol09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Dead("LEGDOR")  // Legdoril
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(3)
		CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	GlobalLT("Iakaol05","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol05","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!Class(LastSeenBy(Myself),SKELETON)
	!Class(LastSeenBy(Myself),SKELETON_WARRIOR)
	OR(3)
		CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	GlobalLT("Iakaol05","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol05","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!HPLT(Myself,1)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),49,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iakaol26","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol26","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!HPLT(Myself,1)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),49,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iakaol26","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol26","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iakaol07","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iakaol07","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Ianoward2","LOCALS",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Ianoward2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Ianoward2","LOCALS",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Ianoward2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iakaol14","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol14","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iakaol14","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol14","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([PC.0.0.CLERIC_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	Global("Iakaol13","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol13","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(2)
		See(NearestEnemyOfType([PC.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([PC.0.0.SHAMAN]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!Kit(LastSeenBy(Myself),AURAMASTER)
	Global("Iakaol13","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol13","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!HasItemEquiped("amul21",LastSeenBy(Myself))  // Amulet of Power
	!HasItemEquiped("S!amul05",LastSeenBy(Myself))  // Amulet of Hades
	!HasItemEquiped("S!amul06",LastSeenBy(Myself))  // Lord of the Underworld
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	Global("Iakaol13","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol13","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaclight","LOCALS")
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),49,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iascroll","LOCALS",4)
	HasItem("scrl7s",Myself)  // Chain Lightning
THEN
	RESPONSE #100
		IncrementGlobal("Iascroll","LOCALS",1)
		SetGlobalTimer("Iaclight","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl7s",LastSeenBy(Myself))  // Chain Lightning
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iakaol22","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol22","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iakaol22","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol22","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iakaol23","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol23","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iakaol23","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol23","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iakaol24","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol24","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iakaol24","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol24","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iakaol24","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iakaol24","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Iakaol01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("Iakaol01","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	Global("Iakaol01","LOCALS",1)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iakaol01","LOCALS",0)
		SetGlobal("Iakaol02","LOCALS",0)
		SetGlobal("Iakaol03","LOCALS",0)
		SetGlobal("Iakaol04","LOCALS",0)
		SetGlobal("Iakaol05","LOCALS",0)
		SetGlobal("Iakaol06","LOCALS",0)
		SetGlobal("Iakaol07","LOCALS",0)
		SetGlobal("Iakaol08","LOCALS",0)
		SetGlobal("Iakaol09","LOCALS",0)
		SetGlobal("Iakaol10","LOCALS",0)
		SetGlobal("Iakaol11","LOCALS",0)
		SetGlobal("Iakaol12","LOCALS",0)
		SetGlobal("Iakaol13","LOCALS",0)
		SetGlobal("Iakaol14","LOCALS",0)
		SetGlobal("Iakaol16","LOCALS",0)
		SetGlobal("Iakaol17","LOCALS",0)
		SetGlobal("Iakaol22","LOCALS",0)
		SetGlobal("Iakaol23","LOCALS",0)
		SetGlobal("Iakaol24","LOCALS",0)
		SetGlobal("Iakaol26","LOCALS",0)
		SetGlobal("Iakaol27","LOCALS",0)
		SetGlobal("Iacastbreach","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("Iadispelpot","LOCALS",0)
		SetGlobal("Iaskin","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Myself))
	Global("Iakaol16","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iakaol16","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	HasItem("bull06",Myself)  // Bullet +4
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	HasItem("bull06",Myself)  // Bullet +4
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	HasItem("bull06",Myself)  // Bullet +4
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	HasItem("bull06",Myself)  // Bullet +4
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	HasItem("bull06",Myself)  // Bullet +4
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	HasItem("bull06",Myself)  // Bullet +4
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),MISSILE_IMMUNITY)
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	GlobalGT("Iakaol16","LOCALS",0)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	GlobalGT("Iakaol16","LOCALS",0)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	GlobalGT("Iakaol16","LOCALS",0)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END


