IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	OR(2)
		Detect([PC])
		See(NearestEnemyOf(Myself))
	Global("EnemySeen","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",1)
END

IF
	OR(2)
		Name("ppguard1",Myself)  // Guardian Spirit
		Name("ppguard3",Myself)  // Guardian Spirit
	Global("Iacreature","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iacreature","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	Global("Iacreature","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iacreature","LOCALS",1)
		CreateCreatureObjectDoor("S!ambers",Myself,0,0,0)  // Amber Golem
		CreateCreatureObjectDoor("S!ambers",Myself,0,0,0)  // Amber Golem
END

IF
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOf(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!GlobalTimerNotExpired("Iachain","LOCALS")
THEN
	RESPONSE #100
    	SetInterrupt(FALSE)
		SetGlobalTimer("Iachain","LOCALS",THREE_ROUNDS)
		ForceSpellRES("SPWII13",LastSeenBy(Myself))  // Improved Chain Lightning
    	SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	Global("Iapcastts","GLOBAL",0)
	See(SecondNearestEnemyOf(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!GlobalTimerNotExpired("Iachain","LOCALS")
THEN
	RESPONSE #100
    	SetInterrupt(FALSE)
		SetGlobalTimer("Iachain","LOCALS",THREE_ROUNDS)
		ForceSpellRES("SPWII13",LastSeenBy(Myself))  // Improved Chain Lightning
    	SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	Global("Iapcastts","GLOBAL",0)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!GlobalTimerNotExpired("Iachain","LOCALS")
THEN
	RESPONSE #100
    	SetInterrupt(FALSE)
		SetGlobalTimer("Iachain","LOCALS",THREE_ROUNDS)
		ForceSpellRES("SPWII13",LastSeenBy(Myself))  // Improved Chain Lightning
    	SetInterrupt(TRUE)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

