
IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,30,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	HPLT(Player1,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,30,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	HPLT(Player1,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,30,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	HPLT(Player1,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(Player1)
	!CheckStatGT(Player1,2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(Player1)
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(SecondNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(ThirdNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(FourthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(FifthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(SixthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Ialayene07","LOCALS",1)
	HasItem("eneblade",Myself)  // Energy Blade
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	GlobalGT("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("Ialayene01","LOCALS",0)
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		See(NearestEnemyOf(Myself))
		Detect([GOODCUTOFF])
	Global("Ialayene01","LOCALS",0)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Ialayene01","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_ARMOR)  // SPWI102.SPL (Armor)
		ReallyForceSpell(Myself,WIZARD_SHIELD)  // SPWI114.SPL (Shield)
		ReallyForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_LUCK)  // SPWI209.SPL (Luck)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,30,RESISTMAGIC)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	HPLT(Player2,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,30,RESISTMAGIC)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	HPLT(Player2,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,30,RESISTMAGIC)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	HPLT(Player2,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,30,RESISTMAGIC)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	HPLT(Player3,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,30,RESISTMAGIC)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	HPLT(Player3,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,30,RESISTMAGIC)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	HPLT(Player3,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,30,RESISTMAGIC)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	HPLT(Player4,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,30,RESISTMAGIC)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	HPLT(Player4,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,30,RESISTMAGIC)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	HPLT(Player4,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,30,RESISTMAGIC)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	HPLT(Player5,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,30,RESISTMAGIC)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	HPLT(Player5,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,30,RESISTMAGIC)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	HPLT(Player5,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,30,RESISTMAGIC)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	HPLT(Player6,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,30,RESISTMAGIC)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	HPLT(Player6,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,30,RESISTMAGIC)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	HPLT(Player6,60)
	Global("Iapwkill","LOCALS",0)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobal("Iapwkill","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("Ialayene01","LOCALS",0)
	Global("Iawishtimer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iawishtimer","LOCALS",1)
		SetGlobalTimer("Iaresttimer","LOCALS",TWO_TURNS)
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	Global("Ialayene07","LOCALS",0)
	Global("Iarestwish","AR1008",0)  // Twisted Rune
	OR(2)
		GlobalTimerExpired("Iaresttimer","LOCALS")
		HPLT(Myself,5)
THEN
	RESPONSE #100
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		ForceSpellRES("SPWII38",Myself)  // Wish
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		SetGlobal("Iarestwish","AR1008",1)  // Twisted Rune
		SetGlobal("Ialayene09","LOCALS",0)
		SetGlobal("Ialayene11","LOCALS",0)
		SetGlobal("Ialayene15","LOCALS",0)
		SetGlobal("Ialayene16","LOCALS",0)
		SetGlobal("Ialayene18","LOCALS",0)
		SetGlobal("Ialayene21","LOCALS",0)
		SetGlobal("Ialayene25","LOCALS",0)
		SetGlobal("Ialayene26","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iaskins","LOCALS",0)
		SetGlobal("Iahorrid","LOCALS",0)
		SetGlobal("Ialightning","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("Iacastbreach","LOCALS",0)
		SetGlobal("Ianoward","LOCALS",0)
		SetGlobal("Iabhand","LOCALS",0)
		SetGlobal("Iapwkill","LOCALS",0)
		SetGlobal("Iadispelpot","LOCALS",0)
		SetGlobal("Iadispelpot1","LOCALS",0)
		SetGlobal("Iarefreshsi","LOCALS",0)
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("absolute","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(NearestEnemyOf(Myself))
	GlobalLT("Ialayene27","LOCALS",9)
	HasItem("scrl9p",Myself)  // Absolute Immunity
THEN
	RESPONSE #100
		SetGlobalTimer("absolute","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		IncrementGlobal("Ialayene27","LOCALS",1)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9p",Myself)  // Absolute Immunity
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	GlobalGT("Ialayene01","LOCALS",0)
	CheckStatGT(Myself,0,SCRIPTINGSTATE6)
	CheckStat(Myself,0,SCRIPTINGSTATE7)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(NearestEnemyOf(Myself))
	Global("Iarefreshsi","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SetGlobal("Iarefreshsi","LOCALS",1)
		SpellNoDec(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalLT("Iaskins","LOCALS",4)
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		IncrementGlobal("Iaskins","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		EquipMostDamagingMelee()
END

IF
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iavecnaplace","GLOBAL",2)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iavecnaplace","GLOBAL",5)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("wa2robe",Myself,0,0,0)  // Robe of Vecna
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player1)
	OR(2)
		StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
		StateCheck(Player1,STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player1)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END


IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See([PC])
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(FourthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(FifthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END
IF
	HasItem("SCRL9M",Myself)
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaLowerResWait","LOCALS")
	See(SixthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),70,RESISTMAGIC)
	OR(2)
        CheckStatGT(Myself,0,SEEINVISIBLE)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaLowerResWait","LOCALS",2)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("SCRL9M",LastSeenBy(Myself))
	RESPONSE #150
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player1)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	StateCheck(Player1,STATE_MIRRORIMAGE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",6)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist1",Player1,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	GlobalLT("Iacastbreach","LOCALS",5)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player1,2,SCRIPTINGSTATE6)
		CheckSpellState(Player1,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist1",Player1,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Ialayene25","LOCALS",0)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Ialayene25","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iadispelpot1","LOCALS",0)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	CheckStat(Player1,2,SCRIPTINGSTATE3)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot1","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	GlobalLT("Ialayene18","LOCALS",1)
	CheckStatGT(Player1,30,RESISTMAGIC)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene18","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	Global("Iamoregolem","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iamoregolem","LOCALS",1)
		CreateCreatureObjectDoor("S!twist1",Player1,0,0,0)  // Twisted Golem
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!StateCheck(Myself,STATE_HELPLESS)
	Detect(Player1)
	!See(Player1)
	Global("Iamoregolem","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iamoregolem","LOCALS",1)
		CreateCreatureObjectDoor("S!twist1",Player1,0,0,0)  // Twisted Golem
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	ActionListEmpty()
	!Detect(Player1)
	InMyArea(Player1)
	Global("Iap1hidden","AR1008",0)  // Twisted Rune
THEN
	RESPONSE #100
		SetGlobal("Iap1hidden","AR1008",1)  // Twisted Rune
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStat(Player1,4,SCRIPTINGSTATE7)
	Range(Player1,30)
	Global("Ialayene07","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene07","LOCALS",1)
		SetGlobal("Iarestwish","AR1008",1)  // Twisted Rune
		SetGlobalTimer("Iawishcombo","LOCALS",SIX_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		ForceSpellRES("SPWII26",Myself)  // Wish
		ForceSpellRES("spwish17",Myself)  // Time Stop
		SetGlobalTimer("Ialayenets","AR1008",SIX_ROUNDS)  // Twisted Rune
END

IF
	Global("Ialayene24","LOCALS",0)
	Global("Ialayene07","LOCALS",1)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobal("Ialayene24","LOCALS",1)
		SetGlobal("Iap1hidden","AR1008",2)  // Twisted Rune
		SpellNoDec(Player1,WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(Player1,WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(Player1,WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(Player1,WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(Player1,WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(Player1,WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(Player1,WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellNoDec(Player1,WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(Player1,WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(Player1,WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(Player1,WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
		SpellNoDec(Player1,WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(Player1,WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(Player1,WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(Player1,WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
		SpellNoDec(Player1,WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		SpellNoDec(Player1,WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		SpellNoDec(Player1,WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		SpellNoDec(Player1,WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		SpellNoDec(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		SpellNoDec(Player1,WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(Player1,WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(Player1,WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(Player1,WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		SpellNoDec(Myself,WIZARD_ENERGY_BLADES)  // SPWI920.SPL (Energy Blades)
END

IF
	Global("Ialayene24","LOCALS",0)
	Global("Ialayene07","LOCALS",1)
	Global("Iap1invis","LOCALS",0)
	Detect(Player1)
	OR(3)
		!See(Player1)
		StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
		StateCheck(Player1,STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobal("Iap1invis","LOCALS",1)
		ApplySpellRES("SPWII50",Player1)  // No such index
END

IF
	Global("Ialayene24","LOCALS",0)
	Global("Ialayene07","LOCALS",1)
	GlobalLT("Iap1hidden","AR1008",2)  // Twisted Rune
	GlobalTimerNotExpired("Iawishcombo","LOCALS")
	ActionListEmpty()
	!Detect(Player1)
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("Ialayene07","LOCALS",1)
	Global("Iacontin","LOCALS",0)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	ActionListEmpty()
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStat(Player1,4,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobal("Iacontin","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		ReallyForceSpell(Player1,WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Detect([PC])
	OR(2)
		!See([PC])
		!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",6)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist2",Player2,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	GlobalLT("Iacastbreach","LOCALS",5)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player2,2,SCRIPTINGSTATE6)
		CheckSpellState(Player2,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist2",Player2,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",6)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist3",Player3,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	GlobalLT("Iacastbreach","LOCALS",5)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player3,2,SCRIPTINGSTATE6)
		CheckSpellState(Player3,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist3",Player3,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",6)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist4",Player4,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	GlobalLT("Iacastbreach","LOCALS",5)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player4,2,SCRIPTINGSTATE6)
		CheckSpellState(Player4,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist4",Player4,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",6)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist5",Player5,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	GlobalLT("Iacastbreach","LOCALS",5)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player5,2,SCRIPTINGSTATE6)
		CheckSpellState(Player5,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist5",Player5,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",6)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist6",Player6,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	GlobalLT("Iacastbreach","LOCALS",5)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	OR(2)
		CheckStatGT(Player6,2,SCRIPTINGSTATE6)
		CheckSpellState(Player6,BREACH_TRIGGERING_PHYSICAL_PROTECTION)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
		EquipMostDamagingMelee()
		CreateCreatureObjectDoor("S!twist6",Player6,0,0,0)  // Twisted Golem
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iadispelpot","LOCALS",0)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	OR(3)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iadispelpot","LOCALS",0)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	OR(3)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iadispelpot","LOCALS",0)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	OR(3)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",6)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iaremove","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Ialayene16","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene16","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Ialayene16","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene16","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Ialayene16","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene16","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Ialayene18","LOCALS",1)
	CheckStatGT(LastSeenBy(Myself),29,RESISTMAGIC)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene18","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Ialayene18","LOCALS",1)
	CheckStatGT(LastSeenBy(Myself),29,RESISTMAGIC)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene18","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Ialayene18","LOCALS",1)
	CheckStatGT(LastSeenBy(Myself),29,RESISTMAGIC)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene18","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!HPLT(Myself,1)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Ialayene01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Ialayene01","LOCALS",2)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Ialayene11","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene11","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Ialayene11","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene11","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Ialayene11","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene11","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Ialayene04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene04","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Ialayene04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene04","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	OR(2)
		!GlobalTimerNotExpired("Ialayenets","AR1008")  // Twisted Rune
		Global("Ialayene07","LOCALS",0)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(3)
		CheckStat(LastSeenBy(Myself),70,RESISTMISSILE)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
		CheckStatGT(LastSeenBy(Myself),89,RESISTSLASHING)
	GlobalLT("Ialayene03","LOCALS",4)
	HasItem("scrl7i",Myself)  // Death Spell
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene03","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl7i",LastSeenBy(Myself))  // Death Spell
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
	Global("Ialayene09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene09","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
	Global("Ialayene09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene09","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	InParty(LastSeenBy(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Ialayene26","LOCALS",1)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene26","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	InParty(LastSeenBy(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Ialayene26","LOCALS",1)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
THEN
	RESPONSE #100
		IncrementGlobal("Ialayene26","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),70,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iahorrid","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iahorrid","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),70,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iahorrid","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iahorrid","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),70,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iahorrid","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iahorrid","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Ialightning","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Ialightning","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Ialayene11","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Ialayene11","LOCALS",2)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Ialayene11","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Ialayene11","LOCALS",2)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		EquipMostDamagingMelee()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Ialayene11","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Ialayene11","LOCALS",2)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Ialightning","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Ialightning","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Ialightning","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Ialightning","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	Global("Iabhand","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iabhand","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	Global("Iabhand","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iabhand","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
		EquipMostDamagingMelee()
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	GlobalGT("Ialayene01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	GlobalGT("Ialayene01","LOCALS",0)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalGT("Ialayene01","LOCALS",0)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Ialayene01","LOCALS",0)
		SetGlobal("Ialayene04","LOCALS",0)
		SetGlobal("Ialayene07","LOCALS",0)
		SetGlobal("Ialayene09","LOCALS",0)
		SetGlobal("Ialayene11","LOCALS",0)
		SetGlobal("Ialayene15","LOCALS",0)
		SetGlobal("Ialayene16","LOCALS",0)
		SetGlobal("Ialayene18","LOCALS",0)
		SetGlobal("Ialayene21","LOCALS",0)
		SetGlobal("Ialayene24","LOCALS",0)
		SetGlobal("Ialayene25","LOCALS",0)
		SetGlobal("Ialayene26","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iaskins","LOCALS",0)
		SetGlobal("Iahorrid","LOCALS",0)
		SetGlobal("Ialightning","LOCALS",0)
		SetGlobal("Iacontin","LOCALS",0)
		SetGlobal("Ianoward","LOCALS",0)
		SetGlobal("Iapwkill","LOCALS",0)
		SetGlobal("Iadispelpot","LOCALS",0)
		SetGlobal("Iadispelpot1","LOCALS",0)
		SetGlobal("Iarefreshsi","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,75)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Ialayene21","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene21","LOCALS",1)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	HPPercentLT(Myself,75)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Range(LastSeenBy(Myself),3)
	Global("Ialayene21","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialayene21","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iauseitem","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,SEEINVISIBLE)
		AttackedBy(LastSeenBy(Myself),DEFAULT)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
		EquipMostDamagingMelee()
END

IF
	!GlobalTimerNotExpired("Iauseitem","LOCALS")
	!GlobalTimerNotExpired("Iawishcombo","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
END
