IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	See(NearestEnemyOf(Myself))
	Global("Interruptible","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Interruptible","LOCALS",1)
		SetInterrupt(FALSE)
		Continue()
END

IF
	Detect([PC])
	Global("Iatimer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobal("Iatimer","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(SecondNearest([PC]), 10))
	TriggerOverride([PC], Range(ThirdNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(SecondNearest([PC]), 10))
	TriggerOverride([PC], Range(FourthNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(SecondNearest([PC]), 10))
	TriggerOverride([PC], Range(FifthNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(ThirdNearest([PC]), 10))
	TriggerOverride([PC], Range(SecondNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(ThirdNearest([PC]), 10))
	TriggerOverride([PC], Range(FourthNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(ThirdNearest([PC]), 10))
	TriggerOverride([PC], Range(FifthNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(FourthNearest([PC]), 10))
	TriggerOverride([PC], Range(SecondNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(FourthNearest([PC]), 10))
	TriggerOverride([PC], Range(ThirdNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(FourthNearest([PC]), 10))
	TriggerOverride([PC], Range(FifthNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(FifthNearest([PC]), 10))
	TriggerOverride([PC], Range(SecondNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(FifthNearest([PC]), 10))
	TriggerOverride([PC], Range(ThirdNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(FifthNearest([PC]), 10))
	TriggerOverride([PC], Range(FourthNearest([PC]), 10))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range([PC], 10))
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range([PC], 10))
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range([PC], 10))
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range([PC], 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range([PC], 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range([PC], 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range([PC], 10))
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range([PC], 10))
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range([PC], 10))
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range([PC], 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range([PC], 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range([PC], 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range([PC], 10))
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range([PC], 10))
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range([PC], 10))
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range([PC], 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range([PC], 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range([PC], 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range([PC], 10))
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range([PC], 10))
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range([PC], 10))
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range([PC], 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range([PC], 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range([PC], 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT([PC],75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT([PC],90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),75,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(SecondNearest([PC]), 10))
	CheckStatLT([PC],80,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(ThirdNearest([PC]), 10))
	CheckStatLT([PC],80,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(FourthNearest([PC]), 10))
	CheckStatLT([PC],80,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC]) 
	TriggerOverride([PC], Range(FifthNearest([PC]), 10))
	CheckStatLT([PC],80,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range([PC], 10))
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
	CheckStatLT([PC],80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range([PC], 10))
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
	CheckStatLT([PC],80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range([PC], 10))
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
	CheckStatLT([PC],80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range([PC], 10))
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
	CheckStatLT([PC],80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range([PC], 10))
	CheckStatLT(SixthNearest([PC]),80,RESISTFIRE)
	CheckStatLT([PC],80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 10))
	CheckStatLT(SixthNearest([PC]),80,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		SpellNoDecRES("S!FISSUR", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Nearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Nearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Nearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Global("Iatimer","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Global("Iatimer","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Iatimer","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatimer","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!See([PC])
	!See([GOODCUTOFF])
	Global("anticheese","LOCALS",0)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HPPercentLT(Myself,100)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",1)
		SetGlobalTimer("chase2","LOCALS",TWO_ROUNDS)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	!See([PC])
	!See([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

