IF
	NumberOfTimesTalkedTo(0)
	Global("Iapcastts","GLOBAL",0)
	Detect([PC])
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
END

IF
	!Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	OR(5)
		AttackedBy([GOODCUTOFF],DEFAULT)
		AttackedBy([PC],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([PC],0)
		TookDamage()
THEN
	RESPONSE #100
		Enemy()
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	Detect([GOODCUTOFF])
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Ialord","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ialord","LOCALS",1)
		CreateCreatureObject("S!skelgr",Myself,0,0,0)  // Skeleton Grandlord
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	GlobalLT("Iadevil","LOCALS",3)
	!GlobalTimerNotExpired("devilsummon","LOCALS")
THEN
	RESPONSE #100
		IncrementGlobal("Iadevil","LOCALS",1)
		SetGlobalTimer("devilsummon","LOCALS",THREE_ROUNDS)
		ReallyForceSpellRES("SPWII32",Myself)  // Gate to Bone Devil
		CreateCreatureObjectDoor("S!bdevit",LastSeenBy(Myself),0,0,0)  // Bone Devil
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iamayor01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iamayor01","LOCALS",1)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Protection From Missiles)
		ReallyForceSpell(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
		ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
		ReallyForceSpell(Myself,CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Defensive Harmony)
		ReallyForceSpell(Myself,CLERIC_AID)  // SPPR201.SPL (Aid)
		ReallyForceSpell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant)
		ReallyForceSpell(Myself,CLERIC_GLOBE_OF_BLADES)  // SPPR725.SPL (Globe of Blades)
		ReallyForceSpell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iarynnplace","GLOBAL",2)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iarynnplace","GLOBAL",5)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("staf20",Myself,0,0,0)  // Staff of Rhynn +4
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure2","LOCALS",0)
	Global("Iafortitplace","GLOBAL",2)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iafortitplace","GLOBAL",4)
		SetGlobal("Iatreasure2","LOCALS",1)
		GiveItemCreate("belt09",Myself,0,0,0)  // Girdle of Fortitude
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iamayor04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iamayor04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_STORM_OF_VENGEANCE)  // SPPR722.SPL (Storm of Vengeance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See(Player1)
	LevelLT(Player1,20)
	Class(Player1,PALADIN_ALL)
	Range(Player1,12)
	!StateCheck(Player1,STATE_PANIC)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_CHARMED)
	!HasItemEquiped("hamm11",Player1)  // Runehammer +5
	!HasItemEquiped("sw1h32",Player1)  // Peridan +3
	!HasItemEquiped("S!sw04",Player1)  // Judgement Day +5
	!HasItemEquiped("S!sw11",Player1)  // Warlord's blade +5
	!HasItemEquiped("S!halb01",Player1)  // Dragon Lord +5
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		ApplySpellRES("SPINI66",Player1)  // No such index
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See("keldorn")  // Keldorn
	!Dead("keldorn")  // Keldorn
	LevelLT("keldorn",20)  // Keldorn
	Class("keldorn",PALADIN_ALL)  // Keldorn
	Range("keldorn",12)  // Keldorn
	!StateCheck("keldorn",STATE_PANIC)  // Keldorn
	!StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
	!StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
	!StateCheck("keldorn",STATE_STUNNED)  // Keldorn
	!HasItemEquiped("hamm11","keldorn")  // Runehammer +5
	!HasItemEquiped("sw1h32","keldorn")  // Peridan +3
	!HasItemEquiped("S!sw04","keldorn")  // Judgement Day +5
	!HasItemEquiped("S!sw11","keldorn")  // Warlord's blade +5
	!HasItemEquiped("S!halb01","keldorn")  // Dragon Lord +5
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		ApplySpellRES("SPINI66","keldorn")  // No such index
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	LevelLT(LastSeenBy(Myself),20)
	Range(LastSeenBy(Myself),12)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!HasItemEquiped("hamm11",LastSeenBy(Myself))  // Runehammer +5
	!HasItemEquiped("sw1h32",LastSeenBy(Myself))  // Peridan +3
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!halb01",LastSeenBy(Myself))  // Dragon Lord +5
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		ApplySpellRES("SPINI66",LastSeenBy(Myself))  // No such index
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	LevelLT(LastSeenBy(Myself),20)
	Range(LastSeenBy(Myself),12)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!HasItemEquiped("hamm11",LastSeenBy(Myself))  // Runehammer +5
	!HasItemEquiped("sw1h32",LastSeenBy(Myself))  // Peridan +3
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!halb01",LastSeenBy(Myself))  // Dragon Lord +5
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		ApplySpellRES("SPINI66",LastSeenBy(Myself))  // No such index
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	Range(LastSeenBy(Myself),12)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	Range(LastSeenBy(Myself),12)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaturning","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaturntime","LOCALS",FOUR_ROUNDS)
		SetGlobal("Iaturning","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	CheckStatLT(Myself,51,RESISTSLASHING)
	GlobalLT("Iamayor06","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iamayor06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	GlobalLT("Iadispel","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispel","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	GlobalLT("Iadispel","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispel","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	GlobalLT("Iadispel","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispel","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iagcommand","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	GlobalLT("Iamayor02","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iamayor02","LOCALS",1)
		SetGlobalTimer("Iagcommand","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iagcommand","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	GlobalLT("Iamayor02","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iamayor02","LOCALS",1)
		SetGlobalTimer("Iagcommand","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iagcommand","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	GlobalLT("Iamayor02","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iamayor02","LOCALS",1)
		SetGlobalTimer("Iagcommand","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See([PC.0.0.MAGE_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState([PC.0.0.MAGE_ALL],POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel([PC.0.0.MAGE_ALL],4)
	!HasBounceEffects([PC.0.0.MAGE_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SecondNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(SecondNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(ThirdNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(ThirdNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FourthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(FourthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FifthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(FifthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SixthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(SixthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTPIERCING)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iamayor05","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iamayor05","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)  // SPPR612.SPL (Bolt of Glory)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTPIERCING)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iamayor05","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iamayor05","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)  // SPPR612.SPL (Bolt of Glory)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See([PC.0.0.MAGE_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState([PC.0.0.MAGE_ALL],POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel([PC.0.0.MAGE_ALL],4)
	!HasBounceEffects([PC.0.0.MAGE_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SecondNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(SecondNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(ThirdNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(ThirdNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FourthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(FourthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FifthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(FifthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SixthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(SixthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState([PC],POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel([PC],4)
	!HasBounceEffects([PC])
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(SecondNearest([PC]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SecondNearest([PC]),4)
	!HasBounceEffects(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(ThirdNearest([PC]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(ThirdNearest([PC]),4)
	!HasBounceEffects(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(FourthNearest([PC]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FourthNearest([PC]),4)
	!HasBounceEffects(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(FifthNearest([PC]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FifthNearest([PC]),4)
	!HasBounceEffects(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckSpellState(SixthNearest([PC]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SixthNearest([PC]),4)
	!HasBounceEffects(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),10,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See([PC.0.0.MAGE_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState([PC.0.0.MAGE_ALL],POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel([PC.0.0.MAGE_ALL],4)
	!HasBounceEffects([PC.0.0.MAGE_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(SecondNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SecondNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(SecondNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(ThirdNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(ThirdNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(ThirdNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FourthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(FourthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FourthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(FourthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FifthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(FifthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FifthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(FifthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SixthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSDEATH)
	!CheckSpellState(SixthNearest([PC.0.0.MAGE_ALL]),POISON_EFFECT_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SixthNearest([PC.0.0.MAGE_ALL]),4)
	!HasBounceEffects(SixthNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #75
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
	RESPONSE #25
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See([PC])
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel([PC],4)
	!HasBounceEffects([PC])
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SecondNearest([PC]),4)
	!HasBounceEffects(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(ThirdNearest([PC]),4)
	!HasBounceEffects(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FourthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FourthNearest([PC]),4)
	!HasBounceEffects(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FifthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FifthNearest([PC]),4)
	!HasBounceEffects(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SixthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SixthNearest([PC]),4)
	!HasBounceEffects(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See([PC])
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel([PC],4)
	!HasBounceEffects([PC])
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SecondNearest([PC]),4)
	!HasBounceEffects(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(ThirdNearest([PC]),4)
	!HasBounceEffects(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FourthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FourthNearest([PC]),4)
	!HasBounceEffects(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FifthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FifthNearest([PC]),4)
	!HasBounceEffects(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SixthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SixthNearest([PC]),4)
	!HasBounceEffects(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See([PC])
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel([PC],4)
	!HasBounceEffects([PC])
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SecondNearest([PC]),4)
	!HasBounceEffects(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(ThirdNearest([PC]),4)
	!HasBounceEffects(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FourthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FourthNearest([PC]),4)
	!HasBounceEffects(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(FifthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(FifthNearest([PC]),4)
	!HasBounceEffects(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_POISON)  // SPPR411.SPL (Poison)
	See(SixthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!ImmuneToSpellLevel(SixthNearest([PC]),4)
	!HasBounceEffects(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),60,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON)  // SPPR411.SPL (Poison)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalLT("Iamayor03","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iamayor03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Ialord","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("Ialord","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Ialord","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iamayor01","LOCALS",0)
		SetGlobal("Iamayor02","LOCALS",0)
		SetGlobal("Iamayor03","LOCALS",0)
		SetGlobal("Iamayor04","LOCALS",0)
		SetGlobal("Iamayor05","LOCALS",0)
		SetGlobal("Iamayor06","LOCALS",0)
		SetGlobal("Ialord","LOCALS",0)
		SetGlobal("Iadevil","LOCALS",0)
		SetGlobal("Iadispel","LOCALS",0)
		SetGlobal("Iacommand","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Isturning","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Isturning","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Isturning","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Isturning","LOCALS")
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("Iapartycame","AR0206",1)  // Ghoul village (Temple District)
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

