IF
	AreaCheck("AR1100")  // Umar Hills
	GlobalGT("Iaswanmejob","GLOBAL",6)
	Global("Iasuicide","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iasuicide","LOCALS",1)
		DestroySelf()
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Detect([PC])
	Global("Iatimer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobal("Iatimer","LOCALS",1)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Iafissureplayer1","LOCALS",0)
		SetGlobal("Iafissureplayer2","LOCALS",0)
		SetGlobal("Iafissureplayer3","LOCALS",0)
		SetGlobal("Iafissureplayer4","LOCALS",0)
		SetGlobal("Iafissureplayer5","LOCALS",0)
		SetGlobal("Iafissureplayer6","LOCALS",0)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTFIRE)
	TriggerOverride(Player1, Range(Player2, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer1","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTFIRE)
	TriggerOverride(Player1, Range(Player3, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer1","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTFIRE)
	TriggerOverride(Player1, Range(Player4, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer1","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTFIRE)
	TriggerOverride(Player1, Range(Player5, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer1","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTFIRE)
	TriggerOverride(Player1, Range(Player6, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer1","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTFIRE)
	TriggerOverride(Player2, Range(Player1, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer2","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTFIRE)
	TriggerOverride(Player2, Range(Player3, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer2","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTFIRE)
	TriggerOverride(Player2, Range(Player4, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer2","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTFIRE)
	TriggerOverride(Player2, Range(Player5, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer2","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTFIRE)
	TriggerOverride(Player2, Range(Player6, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer2","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTFIRE)
	TriggerOverride(Player3, Range(Player1, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer3","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTFIRE)
	TriggerOverride(Player3, Range(Player2, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer3","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTFIRE)
	TriggerOverride(Player3, Range(Player4, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer3","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTFIRE)
	TriggerOverride(Player3, Range(Player5, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer3","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTFIRE)
	TriggerOverride(Player3, Range(Player6, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer3","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTFIRE)
	TriggerOverride(Player4, Range(Player1, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer4","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTFIRE)
	TriggerOverride(Player4, Range(Player2, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer4","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTFIRE)
	TriggerOverride(Player4, Range(Player3, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer4","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTFIRE)
	TriggerOverride(Player4, Range(Player5, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer4","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTFIRE)
	TriggerOverride(Player4, Range(Player6, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer4","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTFIRE)
	TriggerOverride(Player5, Range(Player1, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer5","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTFIRE)
	TriggerOverride(Player5, Range(Player2, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer5","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTFIRE)
	TriggerOverride(Player5, Range(Player3, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer5","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTFIRE)
	TriggerOverride(Player5, Range(Player4, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer5","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTFIRE)
	TriggerOverride(Player5, Range(Player6, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer5","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTFIRE)
	TriggerOverride(Player6, Range(Player1, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer6","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTFIRE)
	TriggerOverride(Player6, Range(Player2, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer6","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTFIRE)
	TriggerOverride(Player6, Range(Player3, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer6","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTFIRE)
	TriggerOverride(Player6, Range(Player4, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer6","LOCALS",1)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTFIRE)
	TriggerOverride(Player6, Range(Player5, 10))
THEN
	RESPONSE #100
		IncrementGlobal("Iafissureplayer6","LOCALS",1)
		Continue()
END

IF
	Global("Iafissureplayer1","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player1)
	    
END

IF
	Global("Iafissureplayer2","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player2)
	    
END

IF
	Global("Iafissureplayer3","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player3)
	    
END

IF
	Global("Iafissureplayer4","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player4)
	    
END

IF
	Global("Iafissureplayer5","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player5)
	    
END

IF
	Global("Iafissureplayer6","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player6)
	    
END

IF
	Global("Iafissureplayer1","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player1)
	    
END

IF
	Global("Iafissureplayer2","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player2)
	    
END

IF
	Global("Iafissureplayer3","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player3)
	    
END

IF
	Global("Iafissureplayer4","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player4)
	    
END

IF
	Global("Iafissureplayer5","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player5)
	    
END

IF
	Global("Iafissureplayer6","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player6)
	    
END

IF
	Global("Iafissureplayer1","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player1)
	    
END

IF
	Global("Iafissureplayer2","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player2)
	    
END

IF
	Global("Iafissureplayer3","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player3)
	    
END

IF
	Global("Iafissureplayer4","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player4)
	    
END

IF
	Global("Iafissureplayer5","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player5)
	    
END

IF
	Global("Iafissureplayer6","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player6)
	    
END

IF
	Global("Iafissureplayer1","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player1)
	    
END

IF
	Global("Iafissureplayer2","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player2)
	    
END

IF
	Global("Iafissureplayer3","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player3)
	    
END

IF
	Global("Iafissureplayer4","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player4)
	    
END

IF
	Global("Iafissureplayer5","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player5)
	    
END

IF
	Global("Iafissureplayer6","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player6)
	    
END

IF
	Global("Iafissureplayer1","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player1)
	    
END

IF
	Global("Iafissureplayer2","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player2)
	    
END

IF
	Global("Iafissureplayer3","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player3)
	    
END

IF
	Global("Iafissureplayer4","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player4)
	    
END

IF
	Global("Iafissureplayer5","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player5)
	    
END

IF
	Global("Iafissureplayer6","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player6)
	    
END

IF
	Global("Iafissureplayer1","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player1)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player1)
	    
END

IF
	Global("Iafissureplayer2","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player2)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player2)
	    
END

IF
	Global("Iafissureplayer3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player3)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player3)
	    
END

IF
	Global("Iafissureplayer4","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player4)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player4)
	    
END

IF
	Global("Iafissureplayer5","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player5)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player5)
	    
END

IF
	Global("Iafissureplayer6","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	See(Player6)
THEN
	RESPONSE #100
	    
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpellRES("S!FISSUR", Player6)
	    
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iainitial","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iainitial","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Nearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCRUSHING)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Nearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Nearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		
		SetGlobalTimer("Iaspell","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_IMPLOSION)  // SPPR728.SPL (Implosion)
		
END


IF
	See([PC])
	Exists("S!aurie3")  // Chief Inspector Auriel
	!Dead("S!aurie3")  // Chief Inspector Auriel
	See("S!aurie3")  // Chief Inspector Auriel
	RandomNumLT(6,2)
THEN
	RESPONSE #100
		AttackOneRound("S!aurie3")  // Chief Inspector Auriel
		AttackOneRound("S!aurie3")  // Chief Inspector Auriel
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	RandomNumGT(6,3)
	Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
	!See([PC])
	Exists("S!aurie3")  // Chief Inspector Auriel
	!Dead("S!aurie3")  // Chief Inspector Auriel
	See("S!aurie3")  // Chief Inspector Auriel
THEN
	RESPONSE #100
		AttackOneRound("S!aurie3")  // Chief Inspector Auriel
		AttackOneRound("S!aurie3")  // Chief Inspector Auriel
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	InMyArea(Player1)
	Exists("S!aurie3")  // Chief Inspector Auriel
	!Dead("S!aurie3")  // Chief Inspector Auriel
	See(NearestEnemyOf(Myself))
	CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		MoveToObject("S!aurie3")  // Chief Inspector Auriel
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Exists("S!aurie3")  // Chief Inspector Auriel
	!Dead("S!aurie3")  // Chief Inspector Auriel
	!See("S!aurie3")  // Chief Inspector Auriel
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

