IF
	Kit(LastSummonerOf(Myself),MAGESCHOOL_CONJURER)
	Global("conjurerbuff","LOCALS",0)
THEN
	RESPONSE #100
		ReallyForceSpellRES("s!smbuf1", Myself)
		SetGlobal("conjurerbuff","LOCALS",1)
		Continue()
END

IF
	Kit(LastSummonerOf(Myself),MAGESCHOOL_CONJURER)
	LevelGT(Myself, 10)
	Global("conjurerbuff","LOCALS",1)
THEN
	RESPONSE #100
		ReallyForceSpellRES("s!smbuf2", Myself)
		SetGlobal("conjurerbuff","LOCALS",2)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	Global("EnemySeen","LOCALS",0)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",1)
		Shout(ALERT)
END

IF
	Global("partyfled","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Shout(ALERT)
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Global("partyfled","LOCALS",0)
	!See([GOODCUTOFF])
	!See([PC])
	Allegiance(Myself,ENEMY)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!See([PC])
	!See([GOODCUTOFF])
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("EnemySeen","LOCALS",1)
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!See([PC])
	!See([GOODCUTOFF])
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Allegiance(Myself,ENEMY)
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!See([PC])
	!See([GOODCUTOFF])
	Global("EnemySeen","LOCALS",0)
	Global("anticheese","LOCALS",0)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HPPercentLT(Myself,100)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Shout(ALERT)
		SetGlobal("anticheese","LOCALS",1)
		SetGlobalTimer("chase2","LOCALS",TWO_ROUNDS)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	Global("EnemySeen","LOCALS",0)
	!See([PC])
	!See([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	Global("EnemySeen","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	Heard([ANYONE],ALERT)
	Global("EnemySeen","LOCALS",0)
	!See([PC])
	!See([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	Heard([ANYONE],ALERT)
	Global("EnemySeen","LOCALS",0)
	!See([GOODCUTOFF])
	See(LastHeardBy(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
		Shout(ALERT)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END
IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END
