IF
	Die()
THEN
	RESPONSE #100
		CreateVisualEffectObject("SPUNHOLY",Myself)
		DestroySelf()
END

IF
	Global("Iamoving","LOCALS",1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",0)
END

IF
	!Allegiance(Myself,ENEMY)
	Global("Iamoving","LOCALS",1)
	CombatCounter(0)
	See([PC])
	Range(LastSeenBy(Myself),6)
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaplanevil","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaplanevil","LOCALS",1)
		SetGlobalTimer("Iagblades","LOCALS",66)
		ReallyForceSpell(Myself,CLERIC_GLOBE_OF_BLADES)  // SPPR725.SPL (Globe of Blades)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(6)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		GlobalGT("Iapcastts","GLOBAL",0)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		StateCheck(Myself,STATE_PANIC)
		StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	ActionListEmpty()
	HPPercentLT(Myself,25)
	Global("DevaHeal","LOCALS",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("DevaHeal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("devaheal",Myself)  // Heal
END

IF
	ActionListEmpty()
	Global("Iaplanevil","LOCALS",0)
	!GlobalTimerNotExpired("Iagblades","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_GLOBE_OF_BLADES)  // SPPR725.SPL (Globe of Blades)
THEN
	RESPONSE #100
		SetGlobalTimer("Iagblades","LOCALS",66)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_GLOBE_OF_BLADES)  // SPPR725.SPL (Globe of Blades)
END

IF
	ActionListEmpty()
	Global("Iaarmor","LOCALS",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
THEN
	RESPONSE #100
		SetGlobal("Iaarmor","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		Spell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(3)
		See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD_ALL]))
	Range(LastSeenBy(Myself),6)
	Alignment(LastSeenBy(Myself),MASK_GOOD)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	HaveSpell(CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	HaveSpell(CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	HaveSpell(CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iamoving","LOCALS",0)
	!See(NearestEnemyOf(Myself))
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iamoving","LOCALS",1)
	!See(NearestEnemyOf(Myself))
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	HaveSpell(CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
END

IF
	!Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	HaveSpell(CLERIC_NEUTRALIZE_POISON)  // SPPR404.SPL (Neutralize Poison)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_NEUTRALIZE_POISON)  // SPPR404.SPL (Neutralize Poison)
END

IF
	!Allegiance(Myself,ENEMY)
	ActionListEmpty()
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See([PC])
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!Class(LastSeenBy(Myself),PALADIN_ALL)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
END

IF
	!Allegiance(Myself,ENEMY)
	ActionListEmpty()
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See(SecondNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!Class(LastSeenBy(Myself),PALADIN_ALL)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
END

IF
	!Allegiance(Myself,ENEMY)
	ActionListEmpty()
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See(ThirdNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!Class(LastSeenBy(Myself),PALADIN_ALL)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
END

IF
	!Allegiance(Myself,ENEMY)
	ActionListEmpty()
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HaveSpell(CLERIC_CURE_DISEASE)  // SPPR317.SPL (Cure Disease)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	StateCheck(LastSeenBy(Myself),STATE_DISEASED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_CURE_DISEASE)  // SPPR317.SPL (Cure Disease)
END

IF
	!Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See([PC])
	Range(LastSeenBy(Myself),3)
	HPPercentLT(LastSeenBy(Myself),25)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	HaveSpell(CLERIC_HEAL)  // SPPR607.SPL (Heal)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_HEAL)  // SPPR607.SPL (Heal)
END

IF
	!Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iadispel","LOCALS")
	ActionListEmpty()
	HaveSpell(CLERIC_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("Iadispel","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
END

IF
	!Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iadispel","LOCALS")
	ActionListEmpty()
	HaveSpell(CLERIC_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("Iadispel","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
END

IF
	!Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iadispel","LOCALS")
	ActionListEmpty()
	HaveSpell(CLERIC_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("Iadispel","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
END

IF
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	Global("Iamoving","LOCALS",0)
	!See(NearestEnemyOf(Myself))
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",1)
END

IF
	!Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iamoving","LOCALS",0)
	CombatCounter(0)
	!Detect(Player1)
	!Detect([PC])
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iamoving","LOCALS",1)
	!See(NearestEnemyOf(Myself))
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

