IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iapri01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapri01","LOCALS",1)
		ReallyForceSpell(Myself,CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
		ReallyForceSpell(Myself,CLERIC_BLESS)  // SPPR101.SPL (Bless)
		ReallyForceSpell(Myself,CLERIC_AID)  // SPPR201.SPL (Aid)
		ReallyForceSpell(Myself,CLERIC_SUMMON_FALLEN_DEVA)  // SPPR727.SPL (Summon Fallen Deva)
		ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
		ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Protection From Missiles)
		ReallyForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
		ReallyForceSpell(Myself,CLERIC_AURA_OF_FLAMING_DEATH)  // SPPR730.SPL (Aura of Flaming Death)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapri01","LOCALS",0)
	InMyArea(Player1)
	HPPercentLT(Myself,1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	Global("Iadukes","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadukes","LOCALS",1)
		CreateCreatureObject("S!kuoduk",LastSeenBy(Myself),0,0,0)  // Kuo-Toa Duke
		CreateCreatureObject("S!kuodu2",LastSeenBy(Myself),0,0,0)  // Kuo-Toa Duke
		CreateCreatureObject("kuopri01",Myself,0,0,0)  // Kuo-toan Priest
		CreateCreatureObject("kuomag01",Myself,0,0,0)  // Kuo-toan Wizard
		CreateCreatureObject("kuocap01",Myself,0,0,0)  // Kuo-toan Captain
		CreateCreatureObject("kuocap01",Myself,0,0,0)  // Kuo-toan Captain
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	Global("Iadukes","LOCALS",1)
	Dead("S!kuoduk")  // Kuo-Toa Duke
	Dead("S!kuodu2")  // Kuo-Toa Duke
	HasItem("minhp1",Myself)  // No such index
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		DestroyItem("minhp1")  // No such index
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iawoodlandsplace","GLOBAL",1)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iawoodlandsplace","GLOBAL",4)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("staf14",Myself,20,20,20)  // Staff of the Woodlands +4
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("minhp1",Myself)  // No such index
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	CheckStatLT(Myself,26,RESISTSLASHING)
	Global("Iapri18","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapri18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	See(Player1)
	LevelLT(Player1,20)
	Class(Player1,PALADIN_ALL)
	Range(Player1,12)
	!StateCheck(Player1,STATE_PANIC)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_CHARMED)
	!HasItemEquiped("hamm11",Player1)  // Runehammer +5
	!HasItemEquiped("sw1h32",Player1)  // Peridan +3
	!HasItemEquiped("S!sw04",Player1)  // Judgement Day +5
	!HasItemEquiped("S!sw11",Player1)  // Warlord's blade +5
	!HasItemEquiped("S!halb01",Player1)  // Dragon Lord +5
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		ApplySpellRES("SPINI66",Player1)  // No such index
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	See("keldorn")  // Keldorn
	!Dead("keldorn")  // Keldorn
	LevelLT("keldorn",20)  // Keldorn
	Class("keldorn",PALADIN_ALL)  // Keldorn
	Range("keldorn",12)  // Keldorn
	!StateCheck("keldorn",STATE_PANIC)  // Keldorn
	!StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
	!StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
	!StateCheck("keldorn",STATE_STUNNED)  // Keldorn
	!HasItemEquiped("hamm11","keldorn")  // Runehammer +5
	!HasItemEquiped("sw1h32","keldorn")  // Peridan +3
	!HasItemEquiped("S!sw04","keldorn")  // Judgement Day +5
	!HasItemEquiped("S!sw11","keldorn")  // Warlord's blade +5
	!HasItemEquiped("S!halb01","keldorn")  // Dragon Lord +5
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		ApplySpellRES("SPINI66","keldorn")  // No such index
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	LevelLT(LastSeenBy(Myself),20)
	Range(LastSeenBy(Myself),12)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!HasItemEquiped("hamm11",LastSeenBy(Myself))  // Runehammer +5
	!HasItemEquiped("sw1h32",LastSeenBy(Myself))  // Peridan +3
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!halb01",LastSeenBy(Myself))  // Dragon Lord +5
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		ApplySpellRES("SPINI66",LastSeenBy(Myself))  // No such index
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	LevelLT(LastSeenBy(Myself),20)
	Range(LastSeenBy(Myself),12)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!HasItemEquiped("hamm11",LastSeenBy(Myself))  // Runehammer +5
	!HasItemEquiped("sw1h32",LastSeenBy(Myself))  // Peridan +3
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!halb01",LastSeenBy(Myself))  // Dragon Lord +5
	!CheckSpellState(LastSeenBy(Myself),IMMUNE_FEAR)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		ApplySpellRES("SPINI66",LastSeenBy(Myself))  // No such index
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	Range(LastSeenBy(Myself),12)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobal("Iaattack","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	Range(LastSeenBy(Myself),12)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobal("Iaattack","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaturning","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaturntime","LOCALS",THREE_ROUNDS)
		SetGlobal("Iaturning","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(2)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	Global("Iadispel","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispel","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See([PC])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(ThirdNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	Global("Iapri02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapri02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_AERIAL_SERVANT)  // SPPR601.SPL (Aerial Servant)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iapri10","LOCALS",9)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri10","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iapri10","LOCALS",9)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri10","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iapri10","LOCALS",9)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri10","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iagcommand","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	GlobalLT("Iapri17","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri17","LOCALS",1)
		SetGlobalTimer("Iagcommand","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iagcommand","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	GlobalLT("Iapri17","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri17","LOCALS",1)
		SetGlobalTimer("Iagcommand","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iagcommand","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	GlobalLT("Iapri17","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri17","LOCALS",1)
		SetGlobalTimer("Iagcommand","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	HPPercentLT(Myself,40)
	!HPLT(Myself,1)
	Global("Iapri06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapri06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_HEAL)  // SPPR607.SPL (Heal)
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("minhp1",Myself)  // No such index
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	HPPercentLT(Myself,50)
	!HPLT(Myself,1)
	Global("Iapri06","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iapri06","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_CURE_CRITICAL_WOUNDS)  // SPPR502.SPL (Cure Critical Wounds)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iapri07","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapri07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iapri07","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapri07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	Global("Iapri08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapri08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_CONJURE_ANIMALS)  // SPPR604.SPL (Conjure Animals)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iapri11","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)  // SPPR612.SPL (Bolt of Glory)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iapri11","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)  // SPPR612.SPL (Bolt of Glory)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iapri11","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)  // SPPR612.SPL (Bolt of Glory)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	Global("Iapri09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iapri09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("minhp1",Myself)  // No such index
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	HPPercentLT(Myself,50)
	GlobalLT("Iapri03","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iapri03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Cure Serious Wounds)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	Global("Iapri09","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iapri09","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iapri07","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iapri07","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iapri07","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iapri07","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	Global("Iapri09","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iapri09","LOCALS",3)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	Global("Iapri09","LOCALS",3)
THEN
	RESPONSE #100
		SetGlobal("Iapri09","LOCALS",4)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Iapri01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("Iapri01","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Iapri01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iapri01","LOCALS",0)
		SetGlobal("Iapri02","LOCALS",0)
		SetGlobal("Iapri03","LOCALS",0)
		SetGlobal("Iapri06","LOCALS",0)
		SetGlobal("Iapri07","LOCALS",0)
		SetGlobal("Iapri08","LOCALS",0)
		SetGlobal("Iapri09","LOCALS",0)
		SetGlobal("Iapri10","LOCALS",0)
		SetGlobal("Iapri11","LOCALS",0)
		SetGlobal("Iapri12","LOCALS",0)
		SetGlobal("Iapri17","LOCALS",0)
		SetGlobal("Iapri18","LOCALS",0)
		SetGlobal("Iadispel","LOCALS",0)
		SetGlobal("Iacommand","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("kuobolt",Myself)  // Kuo-Toa Bolt +1
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	HasItem("kuobolt",Myself)  // Kuo-Toa Bolt +1
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),12)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),3)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("kuobolt",Myself)  // Kuo-Toa Bolt +1
	See(SecondNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("kuobolt",Myself)  // Kuo-Toa Bolt +1
	See(ThirdNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	OR(9)
		!See(Player1)
		!Class(Player1,PALADIN_ALL)
		!Range(Player1,12)
		StateCheck(Player1,STATE_PANIC)
		StateCheck(Player1,STATE_CONFUSED)
		StateCheck(Player1,STATE_HELPLESS)
		StateCheck(Player1,STATE_STUNNED)
		StateCheck(Player1,STATE_CHARMED)
		LevelGT(Player1,19)
	OR(8)
		!InParty("keldorn")  // Keldorn
		!See("keldorn")  // Keldorn
		!Range("keldorn",12)  // Keldorn
		StateCheck("keldorn",STATE_PANIC)  // Keldorn
		StateCheck("keldorn",STATE_CONFUSED)  // Keldorn
		StateCheck("keldorn",STATE_HELPLESS)  // Keldorn
		StateCheck("keldorn",STATE_STUNNED)  // Keldorn
		LevelGT("keldorn",19)  // Keldorn
	OR(8)
		!See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	OR(8)
		!See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
		!Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
		LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),19)
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
END

