IF
	Global("EnemySeen","LOCALS",0)
	Global("Iadoonce","LOCALS",0)
	HPPercentLT(Myself,100)
	InMyArea(Player1)
	!Detect([PC])
	!Detect([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("Iadoonce","LOCALS",1)
		Shout(ALERT)
		MoveToObject(Player1)
END

IF
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("Iashout","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iashout","LOCALS",1)
		Shout(ALERT)
		CreateCreatureObject("S!slassa",Myself,0,0,0)  // Assassin - Assassin
		CreateCreatureObject("slguard1",Myself,0,0,0)  // Slaver Guard
		CreateCreatureObject("slguard2",Myself,0,0,0)  // Slaver Guard
END

IF
	Allegiance(Myself,ENEMY)
	XPGT(Player1,799999)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("Iaapri01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaapri01","LOCALS",1)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		ReallyForceSpell(Myself,CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
		ReallyForceSpell(Myself,CLERIC_AID)  // SPPR201.SPL (Aid)
		ReallyForceSpell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant)
		ReallyForceSpell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
		ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
		ReallyForceSpell(Myself,CLERIC_STRENGTH_OF_ONE)  // SPPR312.SPL (Strength of One)
		ReallyForceSpell(Myself,CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
		ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
		ReallyForceSpell(Myself,CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
		ReallyForceSpell(Myself,CLERIC_HOLY_POWER)  // SPPR412.SPL (Holy Power)
		ReallyForceSpell(Myself,CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Serious Wounds)
		ReallyForceSpell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
		ReallyForceSpell(Myself,CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
		ReallyForceSpell(Myself,CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
		ReallyForceSpell(Myself,CLERIC_RIGHTEOUS_MAGIC)  // SPPR513.SPL (Righteous Magic)
		ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Protection From Missiles)
		ReallyForceSpell(Myself,CLERIC_CHAMPIONS_STRENGTH)  // sppr618.spl (Champion's Might)
		ReallyForceSpellRES("SPPR698",Myself)  // Blade Barrier
		ReallyForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
		EquipItem("SERIOUS")  // Cause Serious Wounds
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("Iaapri01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaapri01","LOCALS",1)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		ReallyForceSpell(Myself,CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
		ReallyForceSpell(Myself,CLERIC_AID)  // SPPR201.SPL (Aid)
		ReallyForceSpell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant)
		ReallyForceSpell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
		ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
		ReallyForceSpell(Myself,CLERIC_STRENGTH_OF_ONE)  // SPPR312.SPL (Strength of One)
		ReallyForceSpell(Myself,CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
		ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
		ReallyForceSpell(Myself,CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
		ReallyForceSpell(Myself,CLERIC_HOLY_POWER)  // SPPR412.SPL (Holy Power)
		ReallyForceSpell(Myself,CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Serious Wounds)
		ReallyForceSpell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
		ReallyForceSpell(Myself,CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
		ReallyForceSpell(Myself,CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
		ReallyForceSpell(Myself,CLERIC_RIGHTEOUS_MAGIC)  // SPPR513.SPL (Righteous Magic)
		ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Protection From Missiles)
		ReallyForceSpellRES("SPPR617",Myself)
		ReallyForceSpellRES("SPPR698",Myself)  // Blade Barrier
		ReallyForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
		EquipItem("SERIOUS")  // Cause Serious Wounds
END

IF
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iablackbloodplace","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("Iablackbloodplace","GLOBAL",5)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("blun22",Myself,0,0,0)  // Club +2, Blackblood
END

IF
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("POTN34",Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN34",Myself)  // Potion of Superior Healing
END

IF
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("EnemySeen","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("EnemySeen","LOCALS",0)
	Global("EnemySeen","AR0405",1)  // Slaver's Ship Building
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	See(NearestEnemyOf(Myself))
	Global("Iaexit2","AR0405",1)  // Slaver's Ship Building
	!GlobalTimerNotExpired("Iasummon","LOCALS")
	Detect([PC])
	Global("EnemySeen","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iasummon","LOCALS",FIVE_ROUNDS)
		CreateCreatureObject("S!slassa",LastSeenBy(Myself),0,0,0)  // Assassin - Assassin
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_SILENCED)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	GlobalLT("s!causeserious","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("s!causeserious","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Serious Wounds)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_SILENCED)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	GlobalLT("s!causeserious","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("s!causeserious","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Serious Wounds)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_SILENCED)
	Global("Iapcastts","GLOBAL",0)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	InMyArea(Player1)
	Global("Iapccloud","AR0405",1)  // Slaver's Ship Building
	GlobalLT("Iasweet","LOCALS",2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("Iapccloud","AR0405",0)  // Slaver's Ship Building
		Wait(2)
		IncrementGlobal("Iasweet","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_SILENCED)
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	!CheckSpellState(Myself,ARMOR_OF_FAITH)
	Global("Iaarmor","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaarmor","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	Range(LastSeenBy(Myself),12)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobal("Iaattack","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaturning","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaturntime","LOCALS",FOUR_ROUNDS)
		SetGlobal("Iaturning","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(5)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_SILENCED)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See([PC])
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(SecondNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(ThirdNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	Global("Iadispel","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadispel","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPPRI02",LastSeenBy(Myself))  // Dispel Magic
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iaapri08","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaapri08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iaapri08","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaapri08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iaapri08","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaapri08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	GlobalLT("Iacommand","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	See(ThirdNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("bull02",Myself)  // Bullet +1
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	GlobalTimerNotExpired("Isturning","LOCALS")
	HasItem("bull02",Myself)  // Bullet +1
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),12)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),2)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("bull02",Myself)  // Bullet +1
	See(SecondNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("bull02",Myself)  // Bullet +1
	See(ThirdNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("bull02",Myself)  // Bullet +1
	See(FourthNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("SERIOUS",Myself)  // Cause Serious Wounds
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
END

