IF
	Global("Iamonster","LOCALS",0)
	GlobalGT("Iammirrorjob","GLOBAL",2)
	GlobalLT("Iammirrorjob","GLOBAL",6)
	!AreaCheck("ARIA25")
THEN
	RESPONSE #100
		SetGlobal("Iamonster","LOCALS",1)
		CreateCreatureObject("S!elegwi",Myself,0,0,0)  // Elemental Golem
END

IF
	Global("Iamoving","LOCALS",1)
	OR(2)
		Detect(NearestEnemyOf(Myself))
		Detect(NearestEnemyOf(LastSummonerOf(Myself)))
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",0)
END

IF
	Global("Iamoving","LOCALS",1)
	CombatCounter(0)
	See([PC])
	Range(LastSeenBy(Myself),6)
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",0)
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Player1))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	OR(2)
		HasItem("S!swanq",Myself)  // No such index
		HasItem("S!gswan",Myself)  // No such index
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	OR(2)
		HasItem("S!swanq",Myself)  // No such index
		HasItem("S!gswan",Myself)  // No such index
	See(NearestEnemyOf(Player1))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(SecondNearestEnemyOf(Player1))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	!HasItemEquiped("immune4",LastSeenBy(Myself))  // No such index
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	OR(2)
		HasItem("S!swanq",Myself)  // No such index
		HasItem("S!gswan",Myself)  // No such index
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	OR(2)
		HasItem("S!swanq",Myself)  // No such index
		HasItem("S!gswan",Myself)  // No such index
	See(SecondNearestEnemyOf(Player1))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Player1))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	Global("Iamoving","LOCALS",0)
	!Detect(NearestEnemyOf(Myself))
	!Detect(NearestEnemyOf(LastSummonerOf(Myself)))
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",1)
END

IF
	ActionListEmpty()
	Global("Iamoving","LOCALS",0)
	CombatCounter(0)
	!Detect(Player1)
	!Detect(LastSummonerOf(Myself))
	!Detect([PC])
THEN
	RESPONSE #100
		SetGlobal("Iamoving","LOCALS",1)
END
