IF
	InMyArea(Player1)
	Global("Iasuicide","LOCALS",0)
	Dead("TOLGER")  // Tolgerias
THEN
	RESPONSE #100
		SetGlobal("Iasuicide","LOCALS",1)
		DestroySelf()
END

IF
	InMyArea(Player1)
	Global("Iasuicide","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iasuicide","LOCALS",2)
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
		Shout(99)
END

IF
	Allegiance(Myself,NEUTRAL)
	OR(2)
		Allegiance("TOLGER",ENEMY)  // Tolgerias
		InMyArea(Player1)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(4)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iatolmag01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolmag01","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_ARMOR)
		ReallyForceSpell(Myself,WIZARD_SHIELD)
		ReallyForceSpell(Myself,WIZARD_BLUR)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself, WIZARD_IMPROVED_INVISIBILITY)  // Improved Invisibility
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
		ReallyForceSpellRES("SPWI725",Myself)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Global("Iatolmag07","LOCALS",0)
	CheckStatLT(Myself,1,STONESKINS)
	HPPercentLT(Myself,100)
	!HPLT(Myself,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("Iatolmag07","LOCALS",1)
		DisplayString(Myself,29736)  // Contingency—Stoneskin
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	See(NearestEnemyOf(Myself))
	Global("Iatolmag05","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolmag05","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_MIRRORIMAGE)
	See(NearestEnemyOf(Myself))
	Global("Iatolmag06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolmag06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iatolmag03","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolmag03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI712", Myself)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iatolmag02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolmag02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI618", Myself)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iams3","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalLT("Iatolmag14","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag14","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iams3","LOCALS",FOUR_ROUNDS)
		SpellNoDec(Myself,WIZARD_MONSTER_SUMMONING_3)  // SPWI504.SPL (Monster Summoning III)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolmag16","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag16","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolmag16","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag16","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolmag16","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag16","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	GlobalLT("Iatolmag17","LOCALS",2)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag17","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	GlobalLT("Iatolmag17","LOCALS",2)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag17","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalLT("Iatolmag17","LOCALS",2)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag17","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalLT("Iatolmag18","LOCALS",4)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	GlobalLT("Iatolmag18","LOCALS",4)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	GlobalLT("Iatolmag18","LOCALS",4)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolmag18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	Global("Iatolmag04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolmag04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_STRENGTH)  // SPWI214.SPL (Strength)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Iatolmag01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("Iatolmag01","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Iatolmag01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatolmag01","LOCALS",0)
		SetGlobal("Iatolmag02","LOCALS",0)
		SetGlobal("Iatolmag03","LOCALS",0)
		SetGlobal("Iatolmag04","LOCALS",0)
		SetGlobal("Iatolmag05","LOCALS",0)
		SetGlobal("Iatolmag07","LOCALS",0)
		SetGlobal("Iatolmag14","LOCALS",0)
		SetGlobal("Iatolmag16","LOCALS",0)
		SetGlobal("Iatolmag17","LOCALS",0)
		SetGlobal("Iatolmag18","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	See(NearestEnemyOf(Myself))
	Global("Iatolmag04","LOCALS",1)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Heard([EVILCUTOFF],99)
	ActionListEmpty()
	!See(NearestEnemyOf(Myself))
	See(LastHeardBy(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END
