IF
	InMyArea(Player1)
	Global("Iasuicide","LOCALS",0)
	Dead("TOLGER")  // Tolgerias
THEN
	RESPONSE #100
		SetGlobal("Iasuicide","LOCALS",1)
		DestroySelf()
END

IF
	InMyArea(Player1)
	Global("Iasuicide","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iasuicide","LOCALS",2)
END

IF
	InMyArea(Player1)
	GlobalGT("BetrayedValygar","GLOBAL",0)
	Global("Iaringexploit","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	HasItem("ring33",Myself)  // Ring of the Ram
THEN
	RESPONSE #100
		SetGlobal("Iaringexploit","LOCALS",1)
		DestroyItem("ring33")  // Ring of the Ram
END

IF
	Global("Iadoonet","LOCALS",0)
	OR(3)
		Detect([GOODCUTOFF])
		Detect([PC])
		InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iadoonet","LOCALS",1)
		Enemy()
END

IF
	NumberOfTimesTalkedTo(0)
	Global("Iapcastts","GLOBAL",0)
	Detect([PC])
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
END

IF
	Global("Iatolger01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	HasItem("POTN34",Myself)
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN34X",Myself)
		DestroyItem("POTN34")
		Continue()
END

IF
	Global("Iatolger01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	HasItem("POTN33",Myself)  // Barbarian Essence
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN33X",Myself)  // No such index
		DestroyItem("POTN33")  // Barbarian Essence
		Continue()
END

IF
	Global("Iatolger01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	HasItem("POTN33",Myself)  // Barbarian Essence
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN33X",Myself)  // No such index
		DestroyItem("POTN33")  // Barbarian Essence
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iatolger01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger01","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		ReallyForceSpell(Myself,WIZARD_ARMOR)  // SPWI102.SPL (Armor)
		ReallyForceSpell(Myself,WIZARD_SHIELD)  // SPWI114.SPL (Shield)
		ReallyForceSpell(Myself,WIZARD_LUCK)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpellRES("SPWI522",Myself)  // Soul Armor
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
		ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
		ReallyForceSpellRES("SPWI725",Myself)  // Shield Mind and Body
		ReallyForceSpell(Myself,WIZARD_SUMMON_PLANATAR_EVIL)  // SPWI924.SPL (Summon Dark Planetar)
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Shout(99)
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iadoonce","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadoonce","LOCALS",1)
		Shout(99)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,30,RESISTMAGIC)
	Global("Iap1nr","GLOBAL",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,30,RESISTMAGIC)
	Global("Iap2nr","GLOBAL",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,30,RESISTMAGIC)
	Global("Iap3nr","GLOBAL",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,30,RESISTMAGIC)
	Global("Iap4nr","GLOBAL",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,30,RESISTMAGIC)
	Global("Iap5nr","GLOBAL",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,30,RESISTMAGIC)
	Global("Iap6nr","GLOBAL",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,30,RESISTMAGIC)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,30,RESISTMAGIC)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,30,RESISTMAGIC)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,30,RESISTMAGIC)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,30,RESISTMAGIC)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,30,RESISTMAGIC)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,30,RESISTMAGIC)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,30,RESISTMAGIC)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,30,RESISTMAGIC)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,30,RESISTMAGIC)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,30,RESISTMAGIC)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,30,RESISTMAGIC)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger02","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(4)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	GlobalLT("Iatolger04","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	HPPercentLT(Myself,75)
	!HPLT(Myself,1)
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iatolger26","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger26","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iatolger04","LOCALS",2)
	See(NearestEnemyOf(Myself))
	OR(2)
		Range(LastSeenBy(Myself),5)
		CheckStatLT(Myself,1,STONESKINS)
	OR(2)
		!GlobalTimerNotExpired("pfmw","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iatolger03","LOCALS",4)
	HasItem("scrl7o",Myself)  // Protection From Magical Weapons
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger03","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl7o",Myself)  // Protection From Magical Weapons
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See([PC])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(ThirdNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(ThirdNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Detect([PC])
	OR(2)
		!See([PC])
		!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",2)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player1)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",2)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player2)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",2)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player3)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",2)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player4)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",2)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player5)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",2)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player6)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iatolger06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iatolger06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",3)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	GlobalLT("Iaremove","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(3)
		CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	GlobalLT("Iatolger05","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger05","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HPPercentLT(Myself,75)
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Ianoward","LOCALS",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HPPercentLT(Myself,75)
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Ianoward","LOCALS",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HPPercentLT(Myself,75)
	See(ThirdNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Ianoward","LOCALS",0)
	Global("Iatolger02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iatolger07","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger07","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iatolger07","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger07","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iatolger07","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger07","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iatolger07","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger07","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Iatolger17","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Iatolger17","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Iatolger17","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Ianoward2","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Ianoward2","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Ianoward2","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iatolger08","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iatolger08","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iatolger08","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iatolger18","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPWI815",Myself)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Iatolger17","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatolger17","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Iatolger17","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatolger17","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	Global("Iatolger17","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatolger17","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
	Global("Iatolger09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(NearestEnemyOf(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
	Global("Iatolger09","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(NearestEnemyOf(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	Global("Iatolger19","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger19","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	Global("Iatolger19","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger19","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	Global("Iatolger19","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger19","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	Global("Iatolger16","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatolger16","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_HASTE)  // SPWI305.SPL (Haste)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("IaMinorSequencer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaMinorSequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
		ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),4)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolger22","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger22","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),2)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolger22","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger22","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolger22","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger22","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolger22","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger22","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolger22","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger22","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaacid","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolger23","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger23","LOCALS",1)
		SetGlobalTimer("Iaacid","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaacid","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolger23","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger23","LOCALS",1)
		SetGlobalTimer("Iaacid","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaacid","LOCALS")
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iatolger23","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger23","LOCALS",1)
		SetGlobalTimer("Iaacid","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iatolger24","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger24","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iatolger24","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger24","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iatolger24","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iatolger24","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Iatolger01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("Iatolger01","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	Global("Iatolger01","LOCALS",1)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatolger01","LOCALS",0)
		SetGlobal("Iatolger02","LOCALS",0)
		SetGlobal("Iatolger03","LOCALS",0)
		SetGlobal("Iatolger04","LOCALS",0)
		SetGlobal("Iatolger05","LOCALS",0)
		SetGlobal("Iatolger06","LOCALS",0)
		SetGlobal("Iatolger07","LOCALS",0)
		SetGlobal("Iatolger08","LOCALS",0)
		SetGlobal("Iatolger09","LOCALS",0)
		SetGlobal("Iatolger14","LOCALS",0)
		SetGlobal("Iatolger16","LOCALS",0)
		SetGlobal("Iatolger17","LOCALS",0)
		SetGlobal("Iatolger18","LOCALS",0)
		SetGlobal("Iatolger19","LOCALS",0)
		SetGlobal("Ianoward","LOCALS",0)
		SetGlobal("Ianoward2","LOCALS",0)
		SetGlobal("Iatolger22","LOCALS",0)
		SetGlobal("Iatolger23","LOCALS",0)
		SetGlobal("Iatolger24","LOCALS",0)
		SetGlobal("Iatolger26","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iadispelpot","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iatolger16","LOCALS",1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!See([PC])
	!See([GOODCUTOFF])
	Global("Iatolger01","LOCALS",0)
	Global("anticheese","LOCALS",0)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HPPercentLT(Myself,100)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",1)
		SetGlobalTimer("chase2","LOCALS",TWO_ROUNDS)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	Global("Iatolger01","LOCALS",0)
	!See([PC])
	!See([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase2","LOCALS")
	Global("anticheese","LOCALS",1)
	Global("Iatolger01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("anticheese","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

