IF
	!Allegiance(Myself,ENEMY)
	OR(2)
		Allegiance("bdturm01",ENEMY)  // Turmish Leader
		HPPercentLT("bdturm01",100)  // Turmish Leader
THEN
	RESPONSE #100
		Enemy()
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	!Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		TookDamage()
THEN
	RESPONSE #100
		Enemy()
		Shout(89)
		MoveToObject(Player1)
END

IF
	Heard([EVILCUTOFF],89)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Shout(89)
		Enemy()
END

IF
	Global("Iafirmag01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	HasItem("POTN33",Myself)  // Barbarian Essence
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN33X",Myself)  // No such index
		DestroyItem("POTN33")  // Barbarian Essence
		Continue()
END

IF
	Global("Iaturms01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	HasItem("POTN34",Myself)
THEN
	RESPONSE #100
		ReallyForceSpellRES("POTN34",Myself)
		DestroyItem("POTN34")
		Continue()
END

IF
	Global("Iaturms01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Exists("BDTURM01")
	!Dead("BDTURM01")
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		ReallyForceSpell("BDTURM01",WIZARD_IMPROVED_HASTE)
		Continue()
END

IF
	Global("Iaturms01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Exists("BDTURM02")
	!Dead("BDTURM02")
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		ReallyForceSpell("BDTURM02",WIZARD_IMPROVED_HASTE)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaturms01","LOCALS",0)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("Iaturms01","LOCALS",1)
		SetGlobalTimer("Iatpt","LOCALS",66)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		IncrementGlobal("Iaturmslvl2","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
		IncrementGlobal("Iaturmslvl4","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		IncrementGlobal("Iaturmslvl4","LOCALS",1)
		ReallyForceSpellRES("SPWI522",Myself)  // Soul Armor
		IncrementGlobal("Iaturmslvl5","LOCALS",1)		
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
		IncrementGlobal("Iaturmslvl5","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		ReallyForceSpellRES("SPWI725",Myself)  // Shield Mind and Body
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		ReallyForceSpellRES("SPWI804",Myself)  // Tenser's Partial Transformation
		IncrementGlobal("Iaturmslvl8","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
		IncrementGlobal("Iaturmslvl8","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_BLACK_BLADE_OF_DISASTER)  // SPWI915.SPL (Black Blade of Disaster)
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	!HPLT(Myself,1)
	HPPercentLT(Myself,75)
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Iaturms01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaturms01","LOCALS",2)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(3)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),49,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iaturms03","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaturms03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	CheckStatGT(Myself,0,SCRIPTINGSTATE9)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HasItem("blakblad",Myself)  // Black Blade of Disaster
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_BLACK_BLADE_OF_DISASTER)  // SPWI915.SPL (Black Blade of Disaster)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	GlobalLT("Iaturmslvl4","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl4","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,100)
	OR(2)
		!GlobalTimerNotExpired("pfmw","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iaturms13","LOCALS",5)
	HasItem("scrl9p",Myself)  // Absolute Immunity
THEN
	RESPONSE #100
		IncrementGlobal("Iaturms13","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9p",Myself)  // Absolute Immunity
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,60)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	Global("Iap2nr","GLOBAL",0)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	Global("Iap3nr","GLOBAL",0)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	Global("Iap4nr","GLOBAL",0)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	Global("Iap5nr","GLOBAL",0)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	Global("Iap6nr","GLOBAL",0)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,90)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player1)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player2)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player3)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player4)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player5)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player6)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,90)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player1)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player2)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player3)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player4)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player5)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player6)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,90)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player1)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player2)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player3)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player4)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player5)  // Power Word, Stun
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",Player6)  // Power Word, Stun
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_MIRRORIMAGE)
	GlobalLT("Iaturmslvl2","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HasItem("blakblad",Myself)  // Black Blade of Disaster
	See(NearestEnemyOf(Myself))
	Global("Iaturms19","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaturms19","LOCALS",1)
		DisplayStringHead(Myself,73139)  // Contingency—Fired
		ReallyForceSpellRES("SPWII41",Myself)  // Improved Invisibility
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("Iatpt","LOCALS")
	GlobalLT("Iaturms18","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturms18","LOCALS",1)
		SetGlobalTimer("Iatpt","LOCALS",72)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI804",Myself)  // Tenser's Partial Transformation
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
	GlobalLT("Iaturmslvl6","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
	GlobalLT("Iaturmslvl6","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
	GlobalLT("Iaturmslvl6","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(ThirdNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!GlobalTimerNotExpired("truesight","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Detect([PC])
	OR(2)
		!See([PC])
		!See([GOODCUTOFF])
	GlobalLT("Iaturmslvl6","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap1nr","GLOBAL",1)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap1nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player1,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iaturmslvl7","LOCALS",7)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player1)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap2nr","GLOBAL",1)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap2nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player2,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iaturmslvl7","LOCALS",7)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player2)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap3nr","GLOBAL",1)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap3nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player3,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iaturmslvl7","LOCALS",7)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player3)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap4nr","GLOBAL",1)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap4nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player4,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iaturmslvl7","LOCALS",7)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player4)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap5nr","GLOBAL",1)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap5nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player5,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iaturmslvl7","LOCALS",7)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player5)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap6nr","GLOBAL",1)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap6nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player6,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iaturmslvl7","LOCALS",7)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iacastbreach","LOCALS",5)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player6)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	GlobalLT("Iaturmslvl6","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),60)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),60)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),60)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),60)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),60)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),60)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	OR(3)
		LevelGT(LastSeenBy(Myself),8)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	GlobalLT("Iaturmslvl6","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl5","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl5","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl5","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl5","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl5","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl5","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",LastSeenBy(Myself))  // Power Word, Stun
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",LastSeenBy(Myself))  // Power Word, Stun
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",LastSeenBy(Myself))  // Power Word, Stun
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",LastSeenBy(Myself))  // Power Word, Stun
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",LastSeenBy(Myself))  // Power Word, Stun
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	GlobalLT("Iastun","LOCALS",2)
	HasItem("scrl8q",Myself)  // Power Word, Stun
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8q",LastSeenBy(Myself))  // Power Word, Stun
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iastun","LOCALS",2)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iastun","LOCALS",2)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iastun","LOCALS",2)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FourthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iastun","LOCALS",2)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(FifthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iastun","LOCALS",2)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SixthNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	GlobalLT("Iastun","LOCALS",2)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iacomet","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iacomet","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iacomet","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iacomet","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iacomet","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	GlobalLT("Iaturmslvl9","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl9","LOCALS",1)
		SetGlobalTimer("Iacomet","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iaturms06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaturms06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl5i")  // Greater Malison
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iaturms06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaturms06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl5i")  // Greater Malison
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iaturms06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaturms06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl5i")  // Greater Malison
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!Class(LastSeenBy(Myself),CLERIC_ALL)
	!Class(LastSeenBy(Myself),FIGHTER_ALL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iaturmslvl7","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!Class(LastSeenBy(Myself),CLERIC_ALL)
	!Class(LastSeenBy(Myself),FIGHTER_ALL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iaturmslvl7","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!Class(LastSeenBy(Myself),CLERIC_ALL)
	!Class(LastSeenBy(Myself),FIGHTER_ALL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iaturmslvl7","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl7","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iaturmslvl5","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl5","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iaturmslvl5","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl5","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("leat20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("sw2h14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquiped("S!leat03",LastSeenBy(Myself))  // Improved Corthala Family Armor
	!HasItemEquiped("S!sw22",LastSeenBy(Myself))  // Githzerai Blade +5
	!HasItemEquiped("S!sw21",LastSeenBy(Myself))  // Solemn Duty +3
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw04",LastSeenBy(Myself))  // Judgement Day +5
	!HasItemEquiped("S!sw07",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw08",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw09",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw10",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw11",LastSeenBy(Myself))  // Warlord's blade +5
	!HasItemEquiped("S!sw12",LastSeenBy(Myself))  // Warlord's blade +5
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iaturmslvl5","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl5","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaclight","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaturmslvl6","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl6","LOCALS",1)
		SetGlobalTimer("Iaclight","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaturmslvl8","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl8","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaturmslvl8","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl8","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaturmslvl8","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl8","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See(FourthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaturmslvl8","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl8","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See(FifthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaturmslvl8","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl8","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iawilting","LOCALS")
	See(SixthNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaturmslvl8","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl8","LOCALS",1)
		SetGlobalTimer("Iawilting","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),4)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	!GlobalTimerNotExpired("Iatouch","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),2)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iatouch","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaturmslvl3","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl3","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaturmslvl2","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl2","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaturmslvl2","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl2","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaconjspl","LOCALS")
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaturmslvl2","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl2","LOCALS",1)
		SetGlobalTimer("Iaconjspl","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl1","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl1","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl1","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl1","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	GlobalLT("Iaturmslvl1","LOCALS",7)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturmslvl1","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaturms01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaturms01","LOCALS",0)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalGT("Iaturms01","LOCALS",0)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaturms01","LOCALS",0)
		SetGlobal("Iaturmslvl4","LOCALS",0)
		SetGlobal("Iaturms03","LOCALS",0)
		SetGlobal("Iaturms04","LOCALS",0)
		SetGlobal("Iaturms05","LOCALS",0)
		SetGlobal("Iaturms06","LOCALS",0)
		SetGlobal("Iaturmslvl8","LOCALS",0)
		SetGlobal("Iaturms08","LOCALS",0)
		SetGlobal("Iaturms09","LOCALS",0)
		SetGlobal("Iaturmslvl2","LOCALS",0)
		SetGlobal("Iaturmslvl3","LOCALS",0)
		SetGlobal("Iaturmslvl1","LOCALS",0)
		SetGlobal("Iaturms13","LOCALS",0)
		SetGlobal("Iaturms14","LOCALS",0)
		SetGlobal("Iaturmslvl6","LOCALS",0)
		SetGlobal("Iaturmslvl9","LOCALS",0)
		SetGlobal("Iaturms17","LOCALS",0)
		SetGlobal("Iaturms18","LOCALS",0)
		SetGlobal("Iaturms19","LOCALS",0)
		SetGlobal("Iaturmslvl5","LOCALS",0)
		SetGlobal("Ianoward","LOCALS",0)
		SetGlobal("Ianoward2","LOCALS",0)
		SetGlobal("Iaturmslvl7","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iastun","LOCALS",0)
		SetGlobal("RemoveMagic","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	ActionListEmpty()
	HasItem("blakblad",Myself)  // Black Blade of Disaster
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	HasItem("blakblad",Myself)  // Black Blade of Disaster
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	HasItem("blakblad",Myself)  // Black Blade of Disaster
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	HasItem("blakblad",Myself)  // Black Blade of Disaster
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("blakblad",Myself)  // Black Blade of Disaster
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Heard([EVILCUTOFF],89)
	ActionListEmpty()
	!See([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Heard([EVILCUTOFF],89)
	ActionListEmpty()
	!See(NearestEnemyOf(Myself))
	See(LastHeardBy(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

