

IF
    ActionListEmpty()
    Global("IaCharge","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("IaCharge","LOCALS",0)
		ReallyForceSpellRES("S!CHARG6",Myself)  // No such index
	    Continue()
END


IF
	See(NearestEnemyOf(Myself))
	Global("EnemySeen","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("EnemySeen","LOCALS",1)
		Shout(89)
		Continue()
END

IF
    Global("Iapcastts","GLOBAL",1)
    Global("Iatsinvulner","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Iatsinvulner","LOCALS",1)
        ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
    Global("Iapcastts","GLOBAL",0)
    Global("Iatsinvulner","LOCALS",1)
THEN
    RESPONSE #100
        SetGlobal("Iatsinvulner","LOCALS",0)
        ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
    Allegiance(Myself,ENEMY)
    OR(2)
        Detect([PC])
        Detect([GOODCUTOFF])
    Global("partyfled","LOCALS",1)
THEN
    RESPONSE #100
        SetGlobal("partyfled","LOCALS",0)
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!GlobalTimerNotExpired("IaSeeCharacters","LOCALS")
	See(Player1)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar1SeenTimer","LOCALS",60)
		SetGlobal("IaChar1Seen","LOCALS",1)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!GlobalTimerNotExpired("IaSeeCharacters","LOCALS")
	See(Player2)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar2SeenTimer","LOCALS",60)
		SetGlobal("IaChar2Seen","LOCALS",1)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!GlobalTimerNotExpired("IaSeeCharacters","LOCALS")
	See(Player3)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar3SeenTimer","LOCALS",60)
		SetGlobal("IaChar3Seen","LOCALS",1)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!GlobalTimerNotExpired("IaSeeCharacters","LOCALS")
	See(Player4)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar4SeenTimer","LOCALS",60)
		SetGlobal("IaChar4Seen","LOCALS",1)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!GlobalTimerNotExpired("IaSeeCharacters","LOCALS")
	See(Player5)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar5SeenTimer","LOCALS",60)
		SetGlobal("IaChar5Seen","LOCALS",1)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!GlobalTimerNotExpired("IaSeeCharacters","LOCALS")
	See(Player6)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
THEN
	RESPONSE #100
		SetGlobalTimer("IaChar6SeenTimer","LOCALS",ONE_TURN)
		SetGlobal("IaChar6Seen","LOCALS",1)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!GlobalTimerNotExpired("IaSeeCharacters","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaSeeCharacters","LOCALS",ONE_ROUND)
		Continue()
END


IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	GlobalTimerExpired("IaChar1SeenTimer","LOCALS")
	Global("IaChar1Seen","LOCALS",1)
	!See(Player1)
THEN
	RESPONSE #100
		SetGlobal("IaChar1Seen","LOCALS",0)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	GlobalTimerExpired("IaChar2SeenTimer","LOCALS")
	Global("IaChar2Seen","LOCALS",1)
	!See(Player2)
THEN
	RESPONSE #100
		SetGlobal("IaChar2Seen","LOCALS",0)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	GlobalTimerExpired("IaChar3SeenTimer","LOCALS")
	Global("IaChar3Seen","LOCALS",1)
	!See(Player3)
THEN
	RESPONSE #100
		SetGlobal("IaChar3Seen","LOCALS",0)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	GlobalTimerExpired("IaChar4SeenTimer","LOCALS")
	Global("IaChar4Seen","LOCALS",1)
	!See(Player4)
THEN
	RESPONSE #100
		SetGlobal("IaChar4Seen","LOCALS",0)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	GlobalTimerExpired("IaChar5SeenTimer","LOCALS")
	Global("IaChar5Seen","LOCALS",1)
	!See(Player5)
THEN
	RESPONSE #100
		SetGlobal("IaChar5Seen","LOCALS",0)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	GlobalTimerExpired("IaChar6SeenTimer","LOCALS")
	Global("IaChar6Seen","LOCALS",1)
	!See(Player6)
THEN
	RESPONSE #100
		SetGlobal("IaChar6Seen","LOCALS",0)
		Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	See(FarthestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaNextCharge","LOCALS")
	CheckStatLT(LastSeenBy(Myself),100,RESISTCRUSHING)
THEN
	RESPONSE #100
		SetGlobal("IaCharge","LOCALS",1)
		SetGlobalTimer("IaBreakCharge","LOCALS",3)
		SetGlobalTimerRandom("IaNextCharge","LOCALS",8,13)
		ReallyForceSpellRES("S!CHARG4",LastSeenBy(Myself))
		ReallyForceSpellRES("S!CHARG1",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SpellNoDecRES("S!CHARG3",LastSeenBy(Myself))
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!CHARG6",Myself)
		ReallyForceSpellRES("S!CHARG5",LastSeenBy(Myself))
		SetGlobalTimer("IaBreakCharge","LOCALS",0)
	RESPONSE #0
	    Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	See(SecondFarthestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaNextCharge","LOCALS")
	CheckStatLT(LastSeenBy(Myself),100,RESISTCRUSHING)
THEN
	RESPONSE #100
		SetGlobal("IaCharge","LOCALS",1)
		SetGlobalTimer("IaBreakCharge","LOCALS",3)
		SetGlobalTimerRandom("IaNextCharge","LOCALS",8,13)
		ReallyForceSpellRES("S!CHARG4",LastSeenBy(Myself))
		ReallyForceSpellRES("S!CHARG1",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SpellNoDecRES("S!CHARG3",LastSeenBy(Myself))
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!CHARG6",Myself)
		ReallyForceSpellRES("S!CHARG5",LastSeenBy(Myself))
		SetGlobalTimer("IaBreakCharge","LOCALS",0)
	RESPONSE #0
	    Continue()
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	See(ThirdFarthestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaNextCharge","LOCALS")
	CheckStatLT(LastSeenBy(Myself),100,RESISTCRUSHING)
THEN
	RESPONSE #100
		SetGlobal("IaCharge","LOCALS",1)
		SetGlobalTimer("IaBreakCharge","LOCALS",3)
		SetGlobalTimerRandom("IaNextCharge","LOCALS",8,13)
		ReallyForceSpellRES("S!CHARG4",LastSeenBy(Myself))
		ReallyForceSpellRES("S!CHARG1",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SpellNoDecRES("S!CHARG3",LastSeenBy(Myself))
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ReallyForceSpellRES("S!CHARG6",Myself)
		ReallyForceSpellRES("S!CHARG5",LastSeenBy(Myself))
		SetGlobalTimer("IaBreakCharge","LOCALS",0)
	RESPONSE #0
	    Continue()
END

IF
	!GlobalTimerNotExpired("IaNextCharge","LOCALS")
	!GlobalTimerNotExpired("IaRunToCharge","LOCALS")
	See(FarthestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	!Range(LastSeenBy(Myself),7)
	!Range(ThirdNearest([ANYONE]),4)
	!GlobalTimerNotExpired("IaAction","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IaRunToCharge","LOCALS",10)
	    RunAwayFromNoInterrupt(LastSeenBy(Myself),20)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See([PC])
	OR(2)
		CheckStatLT([PC],75,RESISTPIERCING)
		CheckStatLT([PC],75,RESISTCRUSHING)
	!CheckStatGT([PC],2,SCRIPTINGSTATE6)
	Range([PC],3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound([PC])
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SecondNearest([PC]))
	OR(2)
		CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SecondNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(ThirdNearest([PC]))
	OR(2)
		CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(ThirdNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FourthNearest([PC]))
	OR(2)
		CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FourthNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FifthNearest([PC]))
	OR(2)
		CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FifthNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SixthNearest([PC]))
	OR(2)
		CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SixthNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(NearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(NearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SecondNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(ThirdNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FourthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FifthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),3)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SixthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See([PC])
	OR(2)
		CheckStatLT([PC],75,RESISTPIERCING)
		CheckStatLT([PC],75,RESISTCRUSHING)
	!CheckStatGT([PC],2,SCRIPTINGSTATE6)
	Range([PC],6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound([PC])
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SecondNearest([PC]))
	OR(2)
		CheckStatLT(SecondNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(SecondNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SecondNearest([PC]),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SecondNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(ThirdNearest([PC]))
	OR(2)
		CheckStatLT(ThirdNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(ThirdNearest([PC]),2,SCRIPTINGSTATE6)
	Range(ThirdNearest([PC]),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(ThirdNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FourthNearest([PC]))
	OR(2)
		CheckStatLT(FourthNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(FourthNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(FourthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FourthNearest([PC]),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FourthNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FifthNearest([PC]))
	OR(2)
		CheckStatLT(FifthNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(FifthNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(FifthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(FifthNearest([PC]),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FifthNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SixthNearest([PC]))
	OR(2)
		CheckStatLT(SixthNearest([PC]),75,RESISTPIERCING)
		CheckStatLT(SixthNearest([PC]),75,RESISTCRUSHING)
	!CheckStatGT(SixthNearest([PC]),2,SCRIPTINGSTATE6)
	Range(SixthNearest([PC]),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SixthNearest([PC]))
	RESPONSE #100
	    Continue()
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(FourthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(FifthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(SixthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(FourthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(FifthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	See(SixthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckSpellState(LastSeenBy(Myself),CONFUSION_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
    OR(2)
        CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
        !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)  // SPIN839.SPL (Confusion)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(NearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(NearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SecondNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(ThirdNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FourthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FifthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING)
		CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING)
	!CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SixthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(NearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(NearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SecondNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(ThirdNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FourthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FifthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SixthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(NearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(NearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SecondNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(ThirdNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FourthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FifthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	OR(2)
		CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SixthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END


IF
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	OR(2)
		CheckStatLT(NearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(NearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(LastSeenBy(Myself))
	RESPONSE #100
	    Continue()
END

IF
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	OR(2)
		CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	See(SecondNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(LastSeenBy(Myself))
	RESPONSE #100
	    Continue()
END

IF
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	OR(2)
		CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	See(ThirdNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(LastSeenBy(Myself))
	RESPONSE #100
	    Continue()
END

IF
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	OR(2)
		CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	See(FourthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(LastSeenBy(Myself))
	RESPONSE #100
	    Continue()
END

IF
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	OR(2)
		CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	See(FifthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(LastSeenBy(Myself))
	RESPONSE #100
	    Continue()
END

IF
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	OR(2)
		CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTPIERCING)
		CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING)
	!CheckStatGT(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE6)
	See(SixthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(LastSeenBy(Myself))
	RESPONSE #100
	    Continue()
END


IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
		SetGlobal("IaAllowRest","LOCALS",1)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	InMyArea(Player1)
	!See(Player1)
    Global("IaChar1Seen","LOCALS",1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(Player1)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	InMyArea(Player2)
	!See(Player2)
    Global("IaChar2Seen","LOCALS",1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(Player2)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	InMyArea(Player3)
	!See(Player3)
    Global("IaChar3Seen","LOCALS",1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(Player3)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	InMyArea(Player4)
	!See(Player4)
    Global("IaChar4Seen","LOCALS",1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(Player4)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	InMyArea(Player5)
	!See(Player5)
    Global("IaChar5Seen","LOCALS",1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(Player5)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	InMyArea(Player6)
	!See(Player6)
    Global("IaChar6Seen","LOCALS",1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(Player6)
END

IF
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("IaAllowRest","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("IaAllowRest","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END


IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(NearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	Range(SecondNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SecondNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	Range(ThirdNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(ThirdNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	Range(FourthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FourthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	Range(FifthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(FifthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	Range(SixthNearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		AttackOneRound(SixthNearestEnemyOf(Myself))
	RESPONSE #100
	    Continue()
END


IF
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("IaBreakCharge","LOCALS")
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		ReallyForceSpellRES("S!CHARG6",Myself)
		MoveToObject(LastSeenBy(Myself))
	RESPONSE #0
	    Continue()
END


IF
	Global("EnemySeen","LOCALS",0)
	Heard([EVILCUTOFF],89)
	!See([GOODCUTOFF])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("EnemySeen","LOCALS",0)
	Heard([EVILCUTOFF],89)
	!See(NearestEnemyOf(Myself))
	See(LastHeardBy(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

IF
	AttackedBy([ANYONE],DEFAULT)
	!See(LastAttackerOf(Myself))
	ActionListEmpty()
THEN
	RESPONSE #100
		MoveToObject(LastAttackerOf(Myself))
END
