IF
	NumberOfTimesTalkedTo(0)
	Detect([PC])
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iatalked","LOCALS",1)
		StartDialogueNoSet([PC])
END

IF
	NumberOfTimesTalkedTo(0)
	Detect([PC])
	GlobalGT("Iapcastts","GLOBAL",0)
	Global("Iatalked","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatalked","LOCALS",1)
		SetGlobal("Iatreasure","LOCALS",1)
END

IF
	Global("ThrallOrb","GLOBAL",2)
	Global("Iathralldie","AR0516",2)  // Planar Prison
	Global("Iasettimer","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iasettimer","LOCALS",1)
		SetGlobalTimer("Iatheygone","LOCALS",3)
END

IF
	Global("ThrallOrb","GLOBAL",2)
	Global("Iathralldie","AR0516",2)  // Planar Prison
	Global("Iasettimer","LOCALS",1)
	GlobalTimerExpired("Iatheygone","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Iasettimer","LOCALS",2)
END

IF
	GlobalLT("ThrallOrb","GLOBAL",2)
	!Global("Iasettimer","LOCALS",2)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("Iasettimer","LOCALS",2)
END

IF
	Global("Iakillthrall","AR0516",1)  // Planar Prison
	Global("Iathralldie","AR0516",0)  // Planar Prison
THEN
	RESPONSE #100
		SetGlobal("Iathralldie","AR0516",1)  // Planar Prison
		SetGlobalTimer("Iasunfire","LOCALS",3)
END

IF
	GlobalTimerExpired("Iasunfire","LOCALS")
	Global("ThrallOrb","GLOBAL",2)
	GlobalLT("asunfire","LOCALS",1)
	Global("Iathralldie","AR0516",1)  // Planar Prison
THEN
	RESPONSE #100
		SetGlobal("Iathralldie","AR0516",2)  // Planar Prison
		IncrementGlobal("asunfire","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		Kill("pthral07")  // Warden's Thrall
		Kill("pthral08")  // Thrall
		Kill("pthral09")  // Thrall
END

IF
	InMyArea(Player1)
	XPLT(Player1,2350000)
	Global("IaToneDown","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("IaToneDown","LOCALS",1)
		SetGlobal("Iarefreshsi","LOCALS",1)
		SetGlobal("Iawarden06","LOCALS",2)
		SetGlobal("Iawarden10","LOCALS",3)
		SetGlobal("Iawarden03","LOCALS",1)
		SetGlobal("Iawarden04","LOCALS",1)
		SetGlobal("Iawarden14","LOCALS",4)
		RemoveSpellRES("SPWI925")
		RemoveSpellRES("SPWI925")
END

IF
	Allegiance(Myself,ENEMY)
	OR(4)
		Detect([PC])
		Detect([GOODCUTOFF])
		Global("Iathralldie","AR0516",2)  // Planar Prison
		Global("Iatalked","LOCALS",1)
	Global("Prep","AR0516",0)  // Planar Prison
THEN
	RESPONSE #100
		SetGlobal("Prep","AR0516",1)  // Planar Prison
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
END

IF
	Allegiance(Myself,ENEMY)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	!Global("ThrallOrb","GLOBAL",2)
	Global("IaCells","AR0516",0)  // Planar Prison
THEN
	RESPONSE #100
		SetGlobal("IaCells","AR0516",1)  // Planar Prison
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iahound","LOCALS",0)
	Global("Iafhound","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iahound","LOCALS",1)
		SetGlobal("Iafhound","LOCALS",1)
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iahound","LOCALS",0)
	Global("Iafhound","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iahound","LOCALS",1)
		CreateCreatureObject("S!phound",LastSeenBy(Myself),0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",LastSeenBy(Myself),0,0,0)  // Planar Hound
		ApplySpellRES("SPINI30",Myself)  // No such index
END

IF
	See([PC])
	GlobalLT("ThrallOrb","GLOBAL",2)
	Global("Ianoorb","AR0516",0)  // Planar Prison
THEN
	RESPONSE #100
		SetGlobal("Ianoorb","AR0516",1)  // Planar Prison
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",Myself,0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",LastSeenBy(Myself),0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",LastSeenBy(Myself),0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",LastSeenBy(Myself),0,0,0)  // Planar Hound
		CreateCreatureObject("S!phound",LastSeenBy(Myself),0,0,0)  // Planar Hound
		CreateCreature("S!phound",[1711.1996],S)  // Planar Hound
		CreateCreature("S!phound",[1678.1971],S)  // Planar Hound
		CreateCreature("S!phound",[1707.2045],S)  // Planar Hound
		CreateCreature("S!phound",[1323.1922],S)  // Planar Hound
		CreateCreature("S!phound",[1763.1949],S)  // Planar Hound
		CreateCreature("S!phound",[1365.1971],S)  // Planar Hound
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		Detect([PC])
		Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,20,RESISTMAGIC)
	Global("Iap1nr","GLOBAL",0)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,20,RESISTMAGIC)
	Global("Iap2nr","GLOBAL",0)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,20,RESISTMAGIC)
	Global("Iap3nr","GLOBAL",0)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,20,RESISTMAGIC)
	Global("Iap4nr","GLOBAL",0)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,20,RESISTMAGIC)
	Global("Iap5nr","GLOBAL",0)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,20,RESISTMAGIC)
	Global("Iap6nr","GLOBAL",0)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,20,RESISTMAGIC)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,20,RESISTMAGIC)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,20,RESISTMAGIC)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,20,RESISTMAGIC)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,20,RESISTMAGIC)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,20,RESISTMAGIC)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player1)
	Class(Player1,MAGE_ALL)
	!CheckStat(Player1,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,20,RESISTMAGIC)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player2)
	Class(Player2,MAGE_ALL)
	!CheckStat(Player2,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,20,RESISTMAGIC)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player3)
	Class(Player3,MAGE_ALL)
	!CheckStat(Player3,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,20,RESISTMAGIC)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player4)
	Class(Player4,MAGE_ALL)
	!CheckStat(Player4,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,20,RESISTMAGIC)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player5)
	Class(Player5,MAGE_ALL)
	!CheckStat(Player5,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,20,RESISTMAGIC)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iapcastts","GLOBAL",0)
	See(Player6)
	Class(Player6,MAGE_ALL)
	!CheckStat(Player6,5,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,20,RESISTMAGIC)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden11","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
		ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Prep","AR0516",1)  // Planar Prison
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	CheckStat(Myself,0,SCRIPTINGSTATE7)
	See(NearestEnemyOf(Myself))
	OR(2)
		CheckStatGT(Myself,0,SCRIPTINGSTATE6)
		!Range(LastSeenBy(Myself),5)
	Global("Iarefreshsi","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iarefreshsi","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iasettimer","LOCALS",2)
	See(NearestEnemyOf(Myself))
	OR(2)
		Range(LastSeenBy(Myself),5)
		AttackedBy([GOODCUTOFF],RANGED)
	OR(2)
		!GlobalTimerNotExpired("pfmw","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iawarden02","LOCALS",5)
	HasItem("scrl7o",Myself)  // Protection From Magical Weapons
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden02","LOCALS",1)
		SetGlobalTimer("pfmw","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl7o",Myself)  // Protection From Magical Weapons
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	HPPercentLT(Myself,90)
	CheckStatLT(Myself,70,RESISTCRUSHING)
	See(NearestEnemyOf(Myself))
	GlobalLT("Iawarden20","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden20","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	Global("Iawarden08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iawarden08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	Allegiance(Myself,ENEMY)
	Detect([PC])
	Global("Iatreasure","LOCALS",0)
	Global("Iaring28place","GLOBAL",3)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iaring28place","GLOBAL",5)
		SetGlobal("Iatreasure","LOCALS",1)
		GiveItemCreate("ring28",Myself,1,1,1)  // Ring of Air Control
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	Global("Iapcastts","GLOBAL",0)
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	Global("Iapcastts","GLOBAL",0)
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	Global("Iapcastts","GLOBAL",0)
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialasso","LOCALS")
	See([PC])
	!Range(LastSeenBy(Myself),7)
	Range(LastSeenBy(Myself),13)
	!HasItemEquiped("S!halb01",LastSeenBy(Myself))  // Dragon Lord +5
THEN
	RESPONSE #100
		SetGlobal("Iahound","LOCALS",0)
		SetGlobalTimer("Ialasso","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPWII31",LastSeenBy(Myself))  // Magic Lasso
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialasso","LOCALS")
	See([PC])
	!Range(LastSeenBy(Myself),13)
	!HasItemEquiped("S!halb01",LastSeenBy(Myself))  // Dragon Lord +5
THEN
	RESPONSE #100
		SetGlobal("Iahound","LOCALS",0)
		SetGlobalTimer("Ialasso","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPWII30",LastSeenBy(Myself))  // Magic Lasso
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Ialasso","LOCALS")
	See(Player1)
	!Range(Player1,13)
	Range(Player1,30)
	!HasItemEquiped("S!halb01",Player1)  // Dragon Lord +5
THEN
	RESPONSE #100
		SetGlobal("Iahound1","AR0516",1)  // Planar Prison
		SetGlobalTimer("Ialasso","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpellRES("SPWII30",Player1)  // Magic Lasso
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iamorehounds","LOCALS")
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("Iatalked","LOCALS",1)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Iahound1","AR0516",1)  // Planar Prison
		SetGlobalTimer("Iamorehounds","LOCALS",FOUR_ROUNDS)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	HPPercentLT(Myself,75)
	!HPLT(Myself,1)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iawarden04","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iawarden04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(2)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	Global("Iawarden09","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden09","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap1nr","GLOBAL",1)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap1nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player1,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap1nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player1)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",4)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player1)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",4)
	HasItem("scrl6u",Myself)  // Breach
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	OR(2)
		CheckStatGT(Player1,2,SCRIPTINGSTATE6)
		CheckSpellState(Player1,HOPELESSNESS)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player1)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap2nr","GLOBAL",1)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap2nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player2,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap2nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player2)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",4)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player2)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",4)
	HasItem("scrl6u",Myself)  // Breach
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	OR(2)
		CheckStatGT(Player2,2,SCRIPTINGSTATE6)
		CheckSpellState(Player2,HOPELESSNESS)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player2)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap3nr","GLOBAL",1)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap3nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player3,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap3nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player3)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",4)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player3)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",4)
	HasItem("scrl6u",Myself)  // Breach
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	OR(2)
		CheckStatGT(Player3,2,SCRIPTINGSTATE6)
		CheckSpellState(Player3,HOPELESSNESS)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player3)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap4nr","GLOBAL",1)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap4nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player4,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap4nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player4)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",4)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player4)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",4)
	HasItem("scrl6u",Myself)  // Breach
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	OR(2)
		CheckStatGT(Player4,2,SCRIPTINGSTATE6)
		CheckSpellState(Player4,HOPELESSNESS)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player4)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap5nr","GLOBAL",1)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap5nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player5,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap5nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player5)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",4)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player5)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",4)
	HasItem("scrl6u",Myself)  // Breach
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	OR(2)
		CheckStatGT(Player5,2,SCRIPTINGSTATE6)
		CheckSpellState(Player5,HOPELESSNESS)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player5)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	Global("Iaspellstrike","LOCALS",0)
	GlobalGT("Iap6nr","GLOBAL",1)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","LOCALS",1)
		SetGlobal("Iap6nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DestroyItem("scrl9m")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		ForceSpell(Player6,WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	GlobalGT("Iap6nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player6)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	HasItem("scrl6u",Myself)  // Breach
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	GlobalLT("Iacastbreach","LOCALS",4)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player6)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iacastbreach","LOCALS",4)
	HasItem("scrl6u",Myself)  // Breach
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	OR(2)
		CheckStatGT(Player6,2,SCRIPTINGSTATE6)
		CheckSpellState(Player6,HOPELESSNESS)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl6u",Player6)  // Breach
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("RemoveMagic","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("RemoveMagic","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("RemoveMagic","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("RemoveMagic","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("RemoveMagic","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("RemoveMagic","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player1)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player2)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player3)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player4)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player5)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",5)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player6)  // Ruby Ray of Reversal
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",TEN_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	Global("Iawarden16","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden16","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iawarden12","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iawarden12","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	GlobalLT("Iawarden12","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	Global("Iawarden03","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!HPLT(Myself,1)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
THEN
	RESPONSE #100
		SetGlobal("Iawarden03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
END

IF
	Global("Iawarden03","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!HPLT(Myself,1)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
THEN
	RESPONSE #100
		SetGlobal("Iawarden03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
END

IF
	Global("Iawarden03","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!HPLT(Myself,1)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
THEN
	RESPONSE #100
		SetGlobal("Iawarden03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	OR(3)
		LevelGT(LastSeenBy(Myself),8)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	GlobalLT("Iawarden07","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Ianoward","LOCALS",0)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Ianoward","LOCALS",0)
	Global("Iawarden11","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	Range(LastSeenBy(Myself),5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	Global("Iawarden10","LOCALS",0)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	Global("Iawarden09","LOCALS",1)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden09","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		CheckStatGT(LastSeenBy(Myself),99,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),99,MAGICDAMAGERESISTANCE)
	Global("Iawarden15","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iawarden15","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(SecondNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(ThirdNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(FourthNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(FifthNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(SixthNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range([PC], 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range([PC], 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range([PC], 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range([PC], 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range([PC], 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	Range(FourthNearest([PC]),15)
	OR(4)
	    CheckStatLT([PC],50,RESISTFIRE)
	    CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	    CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	    CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	OR(4)
	    CheckStatLT([PC],50,RESISTMAGIC)
	    CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	    CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	    CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", Myself)
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	Range(FourthNearest([GOODCUTOFF]),15)
	OR(4)
	    CheckStatLT([GOODCUTOFF],50,RESISTFIRE)
	    CheckStatLT(SecondNearest([GOODCUTOFF]),50,RESISTFIRE)
	    CheckStatLT(ThirdNearest([GOODCUTOFF]),50,RESISTFIRE)
	    CheckStatLT(FourthNearest([GOODCUTOFF]),50,RESISTFIRE)
	OR(4)
	    CheckStatLT([GOODCUTOFF],50,RESISTMAGIC)
	    CheckStatLT(SecondNearest([GOODCUTOFF]),50,RESISTMAGIC)
	    CheckStatLT(ThirdNearest([GOODCUTOFF]),50,RESISTMAGIC)
	    CheckStatLT(FourthNearest([GOODCUTOFF]),50,RESISTMAGIC)
THEN
	RESPONSE #150
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", Myself)
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(SecondNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(ThirdNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(FourthNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(FifthNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC]) 
	TriggerOverride([PC], Range(SixthNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", [PC])
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range([PC], 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC])) 
	TriggerOverride(SecondNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range([PC], 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC])) 
	TriggerOverride(ThirdNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range([PC], 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC])) 
	TriggerOverride(FourthNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range([PC], 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC])) 
	TriggerOverride(FifthNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range([PC], 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC])) 
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
THEN
	RESPONSE #250
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	Range(FourthNearest([PC]),15)
	OR(4)
	    CheckStatLT([PC],90,RESISTFIRE)
	    CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	    CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	    CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	OR(4)
	    CheckStatLT([PC],50,RESISTMAGIC)
	    CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	    CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	    CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
THEN
	RESPONSE #200
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", Myself)
	RESPONSE #50
	    Continue()
END

IF
	HaveSpellRES("SPWI925")
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("IaComet","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	Range(FourthNearest([GOODCUTOFF]),15)
	OR(4)
	    CheckStatLT([GOODCUTOFF],90,RESISTFIRE)
	    CheckStatLT(SecondNearest([GOODCUTOFF]),90,RESISTFIRE)
	    CheckStatLT(ThirdNearest([GOODCUTOFF]),90,RESISTFIRE)
	    CheckStatLT(FourthNearest([GOODCUTOFF]),90,RESISTFIRE)
	OR(4)
	    CheckStatLT([GOODCUTOFF],50,RESISTMAGIC)
	    CheckStatLT(SecondNearest([GOODCUTOFF]),50,RESISTMAGIC)
	    CheckStatLT(ThirdNearest([GOODCUTOFF]),50,RESISTMAGIC)
	    CheckStatLT(FourthNearest([GOODCUTOFF]),50,RESISTMAGIC)
THEN
	RESPONSE #150
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaComet","LOCALS",TWO_ROUNDS)
		SpellRES("SPWI925", Myself)
	RESPONSE #50
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iawarden06","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iawarden06","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),5)
	Global("Iawarden10","LOCALS",2)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden10","LOCALS",3)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)  // SPCL900.SPL (Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	Global("Iawarden06","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden06","LOCALS",3)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Range(LastSeenBy(Myself),5)
	Global("Iawarden14","LOCALS",3)
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iawarden14","LOCALS",4)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iawarden13","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iawarden13","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iawarden13","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iawarden13","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iawarden13","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iawarden13","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden17","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden17","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden17","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden17","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden18","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden18","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden18","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden18","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden19","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden19","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden19","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden19","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iawarden19","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iawarden19","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Prep","AR0516",1)  // Planar Prison
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	Global("Prep","AR0516",1)  // Planar Prison
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	InMyArea(Player1)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Prep","AR0516",1)  // Planar Prison
THEN
	RESPONSE #100
		SetGlobal("prep","AR0516",0)  // Planar Prison
		SetGlobal("Iawarden02","LOCALS",0)
		SetGlobal("Iawarden03","LOCALS",0)
		SetGlobal("Iawarden04","LOCALS",0)
		SetGlobal("Iawarden05","LOCALS",0)
		SetGlobal("Iawarden06","LOCALS",0)
		SetGlobal("Iawarden07","LOCALS",0)
		SetGlobal("Iawarden08","LOCALS",0)
		SetGlobal("Iawarden09","LOCALS",0)
		SetGlobal("Iawarden10","LOCALS",0)
		SetGlobal("Iawarden11","LOCALS",0)
		SetGlobal("Iawarden12","LOCALS",0)
		SetGlobal("Iawarden13","LOCALS",0)
		SetGlobal("Iawarden14","LOCALS",0)
		SetGlobal("Iawarden15","LOCALS",0)
		SetGlobal("Iawarden16","LOCALS",0)
		SetGlobal("Iawarden17","LOCALS",0)
		SetGlobal("Iawarden18","LOCALS",0)
		SetGlobal("Iawarden19","LOCALS",0)
		SetGlobal("Iawarden20","LOCALS",0)
		SetGlobal("RemoveMagic","LOCALS",0)
		SetGlobal("Ianoward","LOCALS",0)
		SetGlobal("Iadispelpot","LOCALS",0)
		SetGlobal("Iarefreshsi","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		MoveToObject(Player1)
END

IF
	See(NearestEnemyOf(Myself))
	ActionListEmpty()
	Global("Iasettimer","LOCALS",2)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	ActionListEmpty()
	!Global("ThrallOrb","GLOBAL",2)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Global("Iathralldie","AR0516",2)  // Planar Prison
	Global("Iasettimer","LOCALS",2)
	Global("ThrallOrb","GLOBAL",2)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	!Global("ThrallOrb","GLOBAL",2)
	Global("Iatalked","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HPPercentLT(Myself,100)
	!Global("ThrallOrb","GLOBAL",2)
	Global("Iatalked","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatalked","LOCALS",1)
END

