
IF
	GlobalGT("YagaShuraHeart","GLOBAL",0)
	Global("Iapcastts","GLOBAL",0)
	HasItem("invulner",Myself)  // Ring
THEN
	RESPONSE #100
		DestroyItem("invulner")  // Ring
		Continue()
END

IF
	NumberOfTimesTalkedTo(0)
	Global("Iapcastts","GLOBAL",0)
	See([PC])
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
END

IF
	Global("YagaShuraSpawn","AR5203",1)  // Yaga-Shura's Camp
	Global("Iacreature","AR5203",2)  // Yaga-Shura's Camp
	Global("Iapcastts","GLOBAL",0)
	HasItem("sureHP1",Myself)  // Ring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		DestroyItem("sureHP1")  // Ring
		SetInterrupt(TRUE)
END

IF
	GlobalGT("YagaShuraHeart","GLOBAL",0)
	GlobalLT("YagaShuraHeart","GLOBAL",3)
	HPPercentLT(Myself,100)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	Global("Iayaga01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iayaga01","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	GlobalLT("Iacreature","AR5203",2)  // Yaga-Shura's Camp
	HasItem("sureHP1",Myself)  // Ring
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Detect([PC])
	Global("Iaitem","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaitem","LOCALS",1)
		GiveItemCreate("s!misc67",Myself,0,0,0)  // Blood of a Greater Bhaalspawn
		Continue()
END


IF
	HaveSpellRES("SPCL321")
	!CheckSpellState(Myself,BERSERKER_RAGE_FATIGUE) 
	!CheckSpellState(Myself,BERSERKER_RAGE) 
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SpellRES("SPCL321",Myself)  // Enrage
	RESPONSE #0
	    Continue()
END


IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player1) 
	TriggerOverride(Player1, Range(NearestAllyOf(Myself), 10))
	CheckStatLT(Player1,70,RESISTFIRE)
	CheckStatLT(NearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player1)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player1) 
	TriggerOverride(Player1, Range(SecondNearestAllyOf(Myself), 10))
	CheckStatLT(Player1,70,RESISTFIRE)
	CheckStatLT(SecondNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player1)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player1) 
	TriggerOverride(Player1, Range(ThirdNearestAllyOf(Myself), 10))
	CheckStatLT(Player1,70,RESISTFIRE)
	CheckStatLT(ThirdNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player1)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player2) 
	TriggerOverride(Player2, Range(NearestAllyOf(Myself), 10))
	CheckStatLT(Player2,70,RESISTFIRE)
	CheckStatLT(NearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player2)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player2) 
	TriggerOverride(Player2, Range(SecondNearestAllyOf(Myself), 10))
	CheckStatLT(Player2,70,RESISTFIRE)
	CheckStatLT(SecondNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player2)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player2) 
	TriggerOverride(Player2, Range(ThirdNearestAllyOf(Myself), 10))
	CheckStatLT(Player2,70,RESISTFIRE)
	CheckStatLT(ThirdNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player2)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player3) 
	TriggerOverride(Player3, Range(NearestAllyOf(Myself), 10))
	CheckStatLT(Player3,70,RESISTFIRE)
	CheckStatLT(NearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player3)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player3) 
	TriggerOverride(Player3, Range(SecondNearestAllyOf(Myself), 10))
	CheckStatLT(Player3,70,RESISTFIRE)
	CheckStatLT(SecondNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player3)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player3) 
	TriggerOverride(Player3, Range(ThirdNearestAllyOf(Myself), 10))
	CheckStatLT(Player3,70,RESISTFIRE)
	CheckStatLT(ThirdNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player3)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player4) 
	TriggerOverride(Player4, Range(NearestAllyOf(Myself), 10))
	CheckStatLT(Player4,70,RESISTFIRE)
	CheckStatLT(NearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player4)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player4) 
	TriggerOverride(Player4, Range(SecondNearestAllyOf(Myself), 10))
	CheckStatLT(Player4,70,RESISTFIRE)
	CheckStatLT(SecondNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player4)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player4) 
	TriggerOverride(Player4, Range(ThirdNearestAllyOf(Myself), 10))
	CheckStatLT(Player4,70,RESISTFIRE)
	CheckStatLT(ThirdNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player4)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player5) 
	TriggerOverride(Player5, Range(NearestAllyOf(Myself), 10))
	CheckStatLT(Player5,70,RESISTFIRE)
	CheckStatLT(NearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player5)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player5) 
	TriggerOverride(Player5, Range(SecondNearestAllyOf(Myself), 10))
	CheckStatLT(Player5,70,RESISTFIRE)
	CheckStatLT(SecondNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player5)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player5) 
	TriggerOverride(Player5, Range(ThirdNearestAllyOf(Myself), 10))
	CheckStatLT(Player5,70,RESISTFIRE)
	CheckStatLT(ThirdNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player5)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player6) 
	TriggerOverride(Player6, Range(NearestAllyOf(Myself), 10))
	CheckStatLT(Player6,70,RESISTFIRE)
	CheckStatLT(NearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player6)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player6) 
	TriggerOverride(Player6, Range(SecondNearestAllyOf(Myself), 10))
	CheckStatLT(Player6,70,RESISTFIRE)
	CheckStatLT(SecondNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player6)
	RESPONSE #100
	    Continue()
END
IF
	Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("IaAction","LOCALS")
    !GlobalTimerNotExpired("IaFissureTimer","LOCALS")
	See(Player6) 
	TriggerOverride(Player6, Range(ThirdNearestAllyOf(Myself), 10))
	CheckStatLT(Player6,70,RESISTFIRE)
	CheckStatLT(ThirdNearestAllyOf(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		SetGlobalTimer("IaFissureTimer","LOCALS",15)
		ForceSpellRES("S!FISSUR", Player6)
	RESPONSE #100
	    Continue()
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!GlobalTimerNotExpired("IaAction","LOCALS")
	HPPercentLT(Myself,75)
	See(NearestEnemyOf(Myself))
	Global("Iayaga05","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iayaga05","LOCALS",1)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,75)
	HasItem("potn55",Myself)  // Potion of Superior Healing
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn55",Myself)  // Potion of Superior Healing
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!GlobalTimerNotExpired("IaAction","LOCALS")
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,75)
	HasItem("potn52",Myself)  // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("Iagww","LOCALS")
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),10)
	GlobalLT("Iayaga02","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iayaga02","LOCALS",1)
		SetGlobalTimer("Iagww","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("IaAction","LOCALS",7)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("Iagww","LOCALS")
	See([PC])
	Range(LastSeenBy(Myself),10)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	Global("Iayaga02","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iayaga02","LOCALS",1)
		SetGlobalTimer("Iagww","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("IaAction","LOCALS",7)
		ForceSpell(Myself,WARRIOR_WHIRLWIND)  // SPCL900.SPL (Whirlwind Attack)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("Iacstrike","LOCALS")
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Range(LastSeenBy(Myself),10)
	GlobalLT("Iayaga04","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iayaga04","LOCALS",1)
		SetGlobalTimer("Iacstrike","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("IaAction","LOCALS",7)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (Critical Strike)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("Iacstrike","LOCALS")
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Range(LastSeenBy(Myself),10)
	Global("Iayaga04","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iayaga04","LOCALS",1)
		SetGlobalTimer("Iacstrike","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("IaAction","LOCALS",13)
		ForceSpell(Myself,WARRIOR_SMITE)  // SPCL909.SPL (Smite)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!GlobalTimerNotExpired("IaAction","LOCALS")
	!GlobalTimerNotExpired("Iacstrike","LOCALS")
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Range(LastSeenBy(Myself),10)
	Global("Iayaga04","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iayaga04","LOCALS",1)
		SetGlobalTimer("Iacstrike","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("IaAction","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_POWER_ATTACK)  // SPCL906.SPL (Power Attack)
END

IF
	!See([PC])
	!See([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Iayaga01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!See([PC])
	!See([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("Iayaga01","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!See([PC])
	!See([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Iayaga01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iayaga01","LOCALS",0)
		SetGlobal("Iayaga02","LOCALS",0)
		SetGlobal("Iayaga03","LOCALS",0)
		SetGlobal("Iayaga04","LOCALS",0)
		SetGlobal("Iayaga05","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTCRUSHING)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTCRUSHING)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTCRUSHING)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	AreaCheck("AR5203")  // Yaga-Shura's Camp
	GlobalGT("YagaShuraSpawn","AR5203",0)  // Yaga-Shura's Camp
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!See([PC])
	!See([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END
