IF
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		TookDamage()
	Allegiance(Myself,NEUTRAL)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Enemy()
		Shout(99)
		MoveToObject(Player1)
END

IF
	Exists("tarnor")  // Tarnor the Hatchetman
	!Dead("tarnor")  // Tarnor the Hatchetman
	Allegiance("tarnor",ENEMY)  // Tarnor the Hatchetman
	Allegiance(Myself,NEUTRAL)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Enemy()
		Shout(99)
		MoveToObject(Player1)
END

IF
	Exists("gaius")  // Gaius
	!Dead("gaius")  // Gaius
	Allegiance("gaius",ENEMY)  // Gaius
	Allegiance(Myself,NEUTRAL)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Enemy()
		Shout(99)
		MoveToObject(Player1)
END

IF
	Exists("tarnor")  // Tarnor the Hatchetman
	!Dead("tarnor")  // Tarnor the Hatchetman
	Allegiance("tarnor",NEUTRAL)  // Tarnor the Hatchetman
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Shout(99)
		ActionOverride("tarnor",Enemy())
END

IF
	Heard([EVILCUTOFF],99)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
		Shout(57)
END

IF
	Heard([EVILCUTOFF],57)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	Global("prep","LOCALS",0)
	!Class(Myself,INNOCENT)
	!See([GOODCUTOFF])
	!See([PC])
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Heard([EVILCUTOFF],99)
	!See(NearestEnemyOf(Myself))
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Heard([EVILCUTOFF],57)
	!See(NearestEnemyOf(Myself))
	InMyArea(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	See(NearestEnemyOf(Myself))
	Global("prep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("prep","LOCALS",1)
		ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Protection From Missiles)
		ReallyForceSpell(Myself,NPC_BLADE_BARRIER)  // SPPR698.SPL (Blade Barrier)
		ReallyForceSpell(Myself,CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Defensive Harmony)
		ReallyForceSpell(Myself,CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
		ReallyForceSpell(Myself,CLERIC_AID)  // SPPR201.SPL (Aid)
		ReallyForceSpell(Myself,CLERIC_BLESS)  // SPPR101.SPL (Bless)
		ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
		ReallyForceSpell(Myself, CLERIC_CHAMPIONS_STRENGTH)
		ReallyForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
		ReallyForceSpell(Myself,CLERIC_RIGHTEOUS_MAGIC)
		ReallyForceSpell(Myself,CLERIC_SLAY_LIVING)
		Shout(99)
END

IF
	See(NearestEnemyOf(Myself))
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapotion","LOCALS",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("POTN35",Myself)  // Potion of Magic Shielding
THEN
	RESPONSE #100
		SetGlobal("Iapotion","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN35",Myself)  // Potion of Magic Shielding
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iapcastts","GLOBAL",0)
	Global("Iapotion","LOCALS",1)
	HasItem("surehp1",Myself)  // Ring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ApplySpellRES("SPWII07",Myself)  // No such index
		DestroyItem("surehp1")  // Ring
		SetInterrupt(TRUE)
END

IF
	!HasItem("surehp1",Myself)  // Ring
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(3)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!StateCheck(Myself,STATE_HELPLESS)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	InMyArea(Player1)
	Global("Iapccloud","AR0701",1)  // The Sewers
	Global("Iawhosweet","AR0701",1)  // The Sewers
	GlobalLT("Iazorl03","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iapccloud","AR0701",0)  // The Sewers
		IncrementGlobal("Iazorl03","LOCALS",1)
		SetGlobal("Iawhosweet","AR0701",0)  // The Sewers
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
		MoveToObject(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,10,RESISTSLASHING)
	GlobalLT("Iafaith","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iafaith","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
END

IF
	HPPercentLT(Myself,50)
	!HasItem("surehp1",Myself)  // Ring
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("POTN52",Myself)  // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN52",Myself)  // Potion of Extra Healing
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	Range(LastSeenBy(Myself),12)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobal("Iaattack","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaturntime","LOCALS")
	GlobalLT("Iaturning","LOCALS",2)
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	Range(LastSeenBy(Myself),12)
THEN
	RESPONSE #100
		IncrementGlobal("Iaturning","LOCALS",1)
		SetGlobal("Iaattack","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Isturning","LOCALS",ONE_ROUND)
		Turn()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaturning","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaturntime","LOCALS",THREE_ROUNDS)
		SetGlobal("Iaturning","LOCALS",0)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(2)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iazorl02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iazorl02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iazorl02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iazorl02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	Global("Iazorl02","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iazorl02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)  // SPPR512.SPL (Greater Command)
END

IF
	Allegiance(Myself,ENEMY)
	!HasItem("surehp1",Myself)  // Ring
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HPPercentLT(Myself,70)
	GlobalLT("Iazorl05","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iazorl05","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Cure Serious Wounds)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	Alignment(LastSeenBy(Myself),MASK_GOOD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Iaunholy","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaunholy","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	Alignment(LastSeenBy(Myself),MASK_GOOD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Iaunholy","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaunholy","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iazorl01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iazorl01","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	Alignment(LastSeenBy(Myself),MASK_GOOD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Iaunholy","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaunholy","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	Alignment(LastSeenBy(Myself),MASK_GOOD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Iaunholy","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaunholy","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iazorl01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iazorl01","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
END

IF
	GlobalLT("Iazorl04","LOCALS",8)
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
THEN
	RESPONSE #100
		IncrementGlobal("Iazorl04","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	GlobalLT("Iazorl04","LOCALS",8)
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
THEN
	RESPONSE #100
		IncrementGlobal("Iazorl04","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	GlobalLT("Iazorl04","LOCALS",8)
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaholdp","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItemEquiped("shld25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquiped("sw1h27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("S!shld01",LastSeenBy(Myself))  // Delryn Family Legacy +4
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!Kit(LastSeenBy(Myself),INQUISITOR)
THEN
	RESPONSE #100
		IncrementGlobal("Iazorl04","LOCALS",1)
		SetGlobalTimer("Iaholdp","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iazorl01","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("Iazorl01","LOCALS",3)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Animate Dead)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iacommand","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iacommand","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("ring95",LastSeenBy(Myself))  // Ring
	!HasItemEquiped("S!ring09",LastSeenBy(Myself))  // Ring
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iacommand","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iacommand","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("prep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",EIGHTEEN_MINUTES)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("prep","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("prep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("prep","LOCALS",0)
		SetGlobal("Iazorl01","LOCALS",0)
		SetGlobal("Iazorl02","LOCALS",0)
		SetGlobal("Iazorl03","LOCALS",0)
		SetGlobal("Iazorl04","LOCALS",0)
		SetGlobal("Iafaith","LOCALS",0)
		SetGlobal("Iazorl05","LOCALS",0)
		SetGlobal("Iazorl06","LOCALS",0)
		SetGlobal("Iastrike","LOCALS",0)
		SetGlobal("Iaunholy","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("bull03",Myself)  // Bullet +2
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	HasItem("bull03",Myself)  // Bullet +2
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),12)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("bull03",Myself)  // Bullet +2
	See(SecondNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	HasItem("bull03",Myself)  // Bullet +2
	See(ThirdNearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),3)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
	!CheckSpellState(LastSeenBy(Myself),HOPELESSNESS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	OR(2)
		!GlobalTimerNotExpired("Isturning","LOCALS")
		Global("Iaattack","LOCALS",1)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	GlobalTimerNotExpired("Isturning","LOCALS")
	!See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
	See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
	!Range(LastSeenBy(Myself),12)
	Global("Iaattack","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaattack","LOCALS",1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

