IF
	Dead("sevpat03")  // Pooky
	Global("cried","LOCALS",0)
	ActionListEmpty()
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("cried","LOCALS",1)
		DisplayStringHead(Myself,11907)  // NO! Pooky... aughh!
END

IF
	Global("RiatavinFight","GLOBAL",1)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Global("RiatavinFight","GLOBAL",0)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		SetGlobal("RiatavinFight","GLOBAL",1)
END

IF
	!HasItem("surehp1",Myself)  // Ring
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,NEUTRAL)
	OR(8)
		HPPercentLT(Myself,100)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HitBy([GOODCUTOFF],CRUSHING)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([PC],0)
		TookDamage()
		SpellCastInnate([GOODCUTOFF],THIEF_SET_SNARE)  // SPCL412.SPL (Set Snare)
		SpellCastInnate([GOODCUTOFF],THIEF_SET_SPECIAL_SNARE)  // SPCL414.SPL (Set Special Snare)
	Global("RiatavinFight","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("RiatavinFight","GLOBAL",1)
		Enemy()
		Shout(151)
END

IF
	Allegiance(Myself,NEUTRAL)
	Detect([PC.0.0.THIEF_ALL])
	Range([PC.0.0.THIEF_ALL],5)
	Global("RiatavinFight","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("RiatavinFight","GLOBAL",1)
		Enemy()
		Shout(151)
END

IF
	Heard([EVILCUTOFF],151)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iaamon01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	HasItem("POTN33",Myself)
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN33X",Myself)
		DestroyItem("POTN33")
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaamon01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaamon01","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_ARMOR)  // SPWI102.SPL (Armor)
		ReallyForceSpell(Myself,WIZARD_SHIELD)  // SPWI114.SPL (Shield)
		ReallyForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
		ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
		ReallyForceSpellRES("SPWI522",Myself)  // Soul Armor
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
		ReallyForceSpellRES("SPWI725",Myself)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaamon01","LOCALS",1)
	Global("Iapcastts","GLOBAL",0)
	HasItem("surehp1",Myself)  // Ring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		DestroyItem("surehp1")  // Ring
		SetInterrupt(TRUE)
END

IF
	!Allegiance(Myself,ENEMY)
	Global("cried","LOCALS",1)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_SILENCED)
	Global("Iapcastts","GLOBAL",0)
	ActionListEmpty()
	CheckStatLT(Myself,1,STONESKINS)
	Global("Iaamon05","LOCALS",0)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Iaamon05","LOCALS",1)
		DisplayString(Myself,29736)  // Contingency—Stoneskin
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iaskin","LOCALS",0)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		SetGlobal("Iaskin","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	OR(2)
		Range(LastSeenBy(Myself),4)
		HPPercentLT(Myself,100)
	HasItem("scrl9c",Myself)  // Improved Mantle
	OR(2)
		!GlobalTimerNotExpired("absolute","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iaamon07","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon07","LOCALS",1)
		SetGlobalTimer("absolute","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9c",Myself)  // Improved Mantle
END

IF
	HPPercentLT(Myself,50)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(4)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,90)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,90)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,90)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(2)
		Global("cried","LOCALS",1)
		HPLT(Myself,20)
	Global("Iaamon06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaamon06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(SecondNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(ThirdNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(FourthNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(FifthNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(SixthNearest([PC]), 15))
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range([PC], 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range([PC], 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range([PC], 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range([PC], 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range([PC], 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT([PC],50,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),50,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),50,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(SecondNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(ThirdNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(FourthNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(FifthNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(SixthNearest([PC]), 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range([PC], 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range([PC], 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range([PC], 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range([PC], 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(SixthNearest([PC]), 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range([PC], 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],80,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState([PC],SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),80,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),80,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest([PC]), 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),80,RESISTMAGIC)
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),80,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(, 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(,90,RESISTFIRE)
	CheckStatLT(,50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(,STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(,0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(,WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(SecondNearest, 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(SecondNearest,90,RESISTFIRE)
	CheckStatLT(SecondNearest,50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(SecondNearest,0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(SecondNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(ThirdNearest, 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(ThirdNearest,90,RESISTFIRE)
	CheckStatLT(ThirdNearest,50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(ThirdNearest,0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(ThirdNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(FourthNearest, 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(FourthNearest,90,RESISTFIRE)
	CheckStatLT(FourthNearest,50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(FourthNearest,0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(FourthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(FifthNearest, 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(FifthNearest,90,RESISTFIRE)
	CheckStatLT(FifthNearest,50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(FifthNearest,0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(FifthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	TriggerOverride([PC], Range(SixthNearest, 15))
	CheckStatLT([PC],90,RESISTFIRE)
	CheckStatLT([PC],50,RESISTMAGIC)
	CheckStatLT(SixthNearest,90,RESISTFIRE)
	CheckStatLT(SixthNearest,50,RESISTMAGIC)
	!StateCheck([PC],STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT([PC],0,MINORGLOBE)
	!CheckStatGT(SixthNearest,0,MINORGLOBE)
	!CheckSpellState([PC],WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState([PC],SI_CONJURATION)
	!CheckSpellState(SixthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("Iachainsequencer[PC]","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", [PC])
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(, 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(,90,RESISTFIRE)
	CheckStatLT(,50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(,STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(,0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(,WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(SecondNearest, 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest,90,RESISTFIRE)
	CheckStatLT(SecondNearest,50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest,0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(ThirdNearest, 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest,90,RESISTFIRE)
	CheckStatLT(ThirdNearest,50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest,0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(FourthNearest, 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest,90,RESISTFIRE)
	CheckStatLT(FourthNearest,50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest,0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(FifthNearest, 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest,90,RESISTFIRE)
	CheckStatLT(FifthNearest,50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest,0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC]))
	TriggerOverride(SecondNearest([PC]), Range(SixthNearest, 15))
	CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest,90,RESISTFIRE)
	CheckStatLT(SixthNearest,50,RESISTMAGIC)
	!StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest,0,MINORGLOBE)
	!CheckSpellState(SecondNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSecondNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SecondNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(, 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(,90,RESISTFIRE)
	CheckStatLT(,50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(,STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(,0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(,WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(SecondNearest, 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest,90,RESISTFIRE)
	CheckStatLT(SecondNearest,50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest,0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(ThirdNearest, 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest,90,RESISTFIRE)
	CheckStatLT(ThirdNearest,50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest,0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(FourthNearest, 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest,90,RESISTFIRE)
	CheckStatLT(FourthNearest,50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest,0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(FifthNearest, 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest,90,RESISTFIRE)
	CheckStatLT(FifthNearest,50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest,0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([PC]))
	TriggerOverride(ThirdNearest([PC]), Range(SixthNearest, 15))
	CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest,90,RESISTFIRE)
	CheckStatLT(SixthNearest,50,RESISTMAGIC)
	!StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest,0,MINORGLOBE)
	!CheckSpellState(ThirdNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerThirdNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", ThirdNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(, 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(,90,RESISTFIRE)
	CheckStatLT(,50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(,STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(,0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(,WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(SecondNearest, 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest,90,RESISTFIRE)
	CheckStatLT(SecondNearest,50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest,0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(ThirdNearest, 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest,90,RESISTFIRE)
	CheckStatLT(ThirdNearest,50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest,0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(FourthNearest, 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest,90,RESISTFIRE)
	CheckStatLT(FourthNearest,50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest,0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(FifthNearest, 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest,90,RESISTFIRE)
	CheckStatLT(FifthNearest,50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest,0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([PC]))
	TriggerOverride(FourthNearest([PC]), Range(SixthNearest, 15))
	CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest,90,RESISTFIRE)
	CheckStatLT(SixthNearest,50,RESISTMAGIC)
	!StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FourthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest,0,MINORGLOBE)
	!CheckSpellState(FourthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFourthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FourthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(, 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(,90,RESISTFIRE)
	CheckStatLT(,50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(,STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(,0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(,WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(SecondNearest, 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest,90,RESISTFIRE)
	CheckStatLT(SecondNearest,50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest,0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(ThirdNearest, 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest,90,RESISTFIRE)
	CheckStatLT(ThirdNearest,50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest,0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(FourthNearest, 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest,90,RESISTFIRE)
	CheckStatLT(FourthNearest,50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest,0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(FifthNearest, 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest,90,RESISTFIRE)
	CheckStatLT(FifthNearest,50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest,0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([PC]))
	TriggerOverride(FifthNearest([PC]), Range(SixthNearest, 15))
	CheckStatLT(FifthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(FifthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest,90,RESISTFIRE)
	CheckStatLT(SixthNearest,50,RESISTMAGIC)
	!StateCheck(FifthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(FifthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest,0,MINORGLOBE)
	!CheckSpellState(FifthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerFifthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", FifthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(, 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(,90,RESISTFIRE)
	CheckStatLT(,50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(,STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(,0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(,WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(SecondNearest, 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SecondNearest,90,RESISTFIRE)
	CheckStatLT(SecondNearest,50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SecondNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SecondNearest,0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SecondNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SecondNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(ThirdNearest, 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(ThirdNearest,90,RESISTFIRE)
	CheckStatLT(ThirdNearest,50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(ThirdNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(ThirdNearest,0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(ThirdNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(ThirdNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(FourthNearest, 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FourthNearest,90,RESISTFIRE)
	CheckStatLT(FourthNearest,50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FourthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FourthNearest,0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FourthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FourthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(FifthNearest, 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(FifthNearest,90,RESISTFIRE)
	CheckStatLT(FifthNearest,50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(FifthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(FifthNearest,0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(FifthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(FifthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([PC]))
	TriggerOverride(SixthNearest([PC]), Range(SixthNearest, 15))
	CheckStatLT(SixthNearest([PC]),90,RESISTFIRE)
	CheckStatLT(SixthNearest([PC]),50,RESISTMAGIC)
	CheckStatLT(SixthNearest,90,RESISTFIRE)
	CheckStatLT(SixthNearest,50,RESISTMAGIC)
	!StateCheck(SixthNearest([PC]),STATE_NOT_TARGETABLE)
	!StateCheck(SixthNearest,STATE_NOT_TARGETABLE)
	!CheckStatGT(SixthNearest([PC]),0,MINORGLOBE)
	!CheckStatGT(SixthNearest,0,MINORGLOBE)
	!CheckSpellState(SixthNearest([PC]),WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest,WIZARD_SPELL_TURNING)
	!CheckSpellState(SixthNearest([PC]),SI_CONJURATION)
	!CheckSpellState(SixthNearest,SI_CONJURATION)
THEN
	RESPONSE #250
		IncrementGlobal("IachainsequencerSixthNearest([PC])","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", SixthNearest([PC]))
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	CheckStatGT(Myself,0,MINORGLOBE)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	Range(FourthNearest([PC]),15)
	OR(4)
	    CheckStatLT([PC],90,RESISTFIRE)
	    CheckStatLT(SecondNearest([PC]),90,RESISTFIRE)
	    CheckStatLT(ThirdNearest([PC]),90,RESISTFIRE)
	    CheckStatLT(FourthNearest([PC]),90,RESISTFIRE)
	OR(4)
	    CheckStatLT([PC],50,RESISTMAGIC)
	    CheckStatLT(SecondNearest([PC]),50,RESISTMAGIC)
	    CheckStatLT(ThirdNearest([PC]),50,RESISTMAGIC)
	    CheckStatLT(FourthNearest([PC]),50,RESISTMAGIC)
	OR(4)
	    !StateCheck([PC],STATE_NOT_TARGETABLE)
	    !StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
	    !StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
	    !StateCheck(FourthNearest([PC]),STATE_NOT_TARGETABLE)
THEN
	RESPONSE #200
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", Myself)
	RESPONSE #50
	    Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	CheckStatGT(Myself,0,MINORGLOBE)
	OR(2)
	    CheckStatGT(Myself,0,AURACLEANSING)
	    !GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	Range(FourthNearest([GOODCUTOFF]),15)
	OR(4)
	    CheckStatLT([GOODCUTOFF],90,RESISTFIRE)
	    CheckStatLT(SecondNearest([GOODCUTOFF]),90,RESISTFIRE)
	    CheckStatLT(ThirdNearest([GOODCUTOFF]),90,RESISTFIRE)
	    CheckStatLT(FourthNearest([GOODCUTOFF]),90,RESISTFIRE)
	OR(4)
	    CheckStatLT([GOODCUTOFF],50,RESISTMAGIC)
	    CheckStatLT(SecondNearest([GOODCUTOFF]),50,RESISTMAGIC)
	    CheckStatLT(ThirdNearest([GOODCUTOFF]),50,RESISTMAGIC)
	    CheckStatLT(FourthNearest([GOODCUTOFF]),50,RESISTMAGIC)
	OR(4)
	    !StateCheck([GOODCUTOFF],STATE_NOT_TARGETABLE)
	    !StateCheck(SecondNearest([GOODCUTOFF]),STATE_NOT_TARGETABLE)
	    !StateCheck(ThirdNearest([GOODCUTOFF]),STATE_NOT_TARGETABLE)
	    !StateCheck(FourthNearest([GOODCUTOFF]),STATE_NOT_TARGETABLE)
THEN
	RESPONSE #150
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWIJ01D", Myself)
	RESPONSE #50
	    Continue()
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	Global("Iachainlight","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iachainlight","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	Global("Iachainlight","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iachainlight","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	Global("Iachainlight","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iachainlight","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iaamon02","LOCALS",3)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Iaamon01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("Iaamon01","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Iaamon01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaamon01","LOCALS",0)
		SetGlobal("Iaamon02","LOCALS",0)
		SetGlobal("Iaamon03","LOCALS",0)
		SetGlobal("Iaamon04","LOCALS",0)
		SetGlobal("Iaamon05","LOCALS",0)
		SetGlobal("Iaamon07","LOCALS",0)
		SetGlobal("Iaamon08","LOCALS",0)
		SetGlobal("Iaamon09","LOCALS",0)
		SetGlobal("Iaamon10","LOCALS",0)
		SetGlobal("Iacastbreach","LOCALS",0)
		SetGlobal("Iaamon12","LOCALS",0)
		SetGlobal("truesight","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iaremove2","LOCALS",0)
		SetGlobal("Iaremove3","LOCALS",0)
		SetGlobal("Iastun","LOCALS",0)
		SetGlobal("Iaskin","LOCALS",0)
		SetGlobal("Iachainlight","LOCALS",0)
		SetGlobal("Iachainsequencer","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaamon10","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaamon10","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaamon10","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaamon12","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaamon12","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaamon12","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iaamon13","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaamon13","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Iaamon13","LOCALS",1)
	ActionListEmpty()
	!HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

