IF
	Dead("sevpat03")  // Pooky
	Global("cried","LOCALS",0)
	ActionListEmpty()
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("cried","LOCALS",1)
		DisplayStringHead(Myself,11907)  // NO! Pooky... aughh!
END

IF
	Global("RiatavinFight","GLOBAL",1)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Global("RiatavinFight","GLOBAL",0)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		SetGlobal("RiatavinFight","GLOBAL",1)
END

IF
	!HasItem("surehp1",Myself)  // Ring
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,NEUTRAL)
	OR(8)
		HPPercentLT(Myself,100)
		AttackedBy([GOODCUTOFF],DEFAULT)
		HitBy([GOODCUTOFF],CRUSHING)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([PC],0)
		TookDamage()
		SpellCastInnate([GOODCUTOFF],THIEF_SET_SNARE)  // SPCL412.SPL (Set Snare)
		SpellCastInnate([GOODCUTOFF],THIEF_SET_SPECIAL_SNARE)  // SPCL414.SPL (Set Special Snare)
	Global("RiatavinFight","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("RiatavinFight","GLOBAL",1)
		Enemy()
		Shout(151)
END

IF
	Allegiance(Myself,NEUTRAL)
	Detect([PC.0.0.THIEF_ALL])
	Range([PC.0.0.THIEF_ALL],5)
	Global("RiatavinFight","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("RiatavinFight","GLOBAL",1)
		Enemy()
		Shout(151)
END

IF
	Heard([EVILCUTOFF],151)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("partyfled","LOCALS",0)
END

IF
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iaamon01","LOCALS",0)
	Allegiance(Myself,ENEMY)
	HasItem("POTN33",Myself)
THEN
	RESPONSE #100
		ReallyForceSpellRES("PTN33X",Myself)
		DestroyItem("POTN33")
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaamon01","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaamon01","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_ARMOR)  // SPWI102.SPL (Armor)
		ReallyForceSpell(Myself,WIZARD_SHIELD)  // SPWI114.SPL (Shield)
		ReallyForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
		ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
		ReallyForceSpellRES("SPWI522",Myself)  // Soul Armor
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
END

IF
	Allegiance(Myself,ENEMY)
	Global("Iaamon01","LOCALS",1)
	Global("Iapcastts","GLOBAL",0)
	HasItem("surehp1",Myself)  // Ring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		DestroyItem("surehp1")  // Ring
		SetInterrupt(TRUE)
END

IF
	!Allegiance(Myself,ENEMY)
	Global("cried","LOCALS",1)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_SILENCED)
	Global("Iapcastts","GLOBAL",0)
	ActionListEmpty()
	CheckStatLT(Myself,1,STONESKINS)
	Global("Iaamon05","LOCALS",0)
	!HPLT(Myself,1)
THEN
	RESPONSE #100
		SetGlobal("Iaamon05","LOCALS",1)
		DisplayString(Myself,29736)  // Contingency—Stoneskin
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iaskin","LOCALS",0)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		SetGlobal("Iaskin","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	OR(2)
		Range(LastSeenBy(Myself),4)
		HPPercentLT(Myself,100)
	HasItem("scrl9c",Myself)  // Improved Mantle
	OR(2)
		!GlobalTimerNotExpired("absolute","LOCALS")
		CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iaamon07","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon07","LOCALS",1)
		SetGlobalTimer("absolute","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl9c",Myself)  // Improved Mantle
END

IF
	HPPercentLT(Myself,50)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_STUNNED)
	Global("Iapcastts","GLOBAL",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(4)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_STUNNED)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,90)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,90)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!CheckStat(Player1,1,SCRIPTINGSTATE5)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,90)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,90)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!StateCheck(Player2,STATE_STUNNED)
	!StateCheck(Player2,STATE_HELPLESS)
	!StateCheck(Player2,STATE_CONFUSED)
	!StateCheck(Player2,STATE_PANIC)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player2)  // True Sword of Arvoreen +5
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,90)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!StateCheck(Player3,STATE_STUNNED)
	!StateCheck(Player3,STATE_HELPLESS)
	!StateCheck(Player3,STATE_CONFUSED)
	!StateCheck(Player3,STATE_PANIC)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player3)  // True Sword of Arvoreen +5
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,90)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!StateCheck(Player4,STATE_STUNNED)
	!StateCheck(Player4,STATE_HELPLESS)
	!StateCheck(Player4,STATE_CONFUSED)
	!StateCheck(Player4,STATE_PANIC)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player4)  // True Sword of Arvoreen +5
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,90)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!StateCheck(Player5,STATE_STUNNED)
	!StateCheck(Player5,STATE_HELPLESS)
	!StateCheck(Player5,STATE_CONFUSED)
	!StateCheck(Player5,STATE_PANIC)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player5)  // True Sword of Arvoreen +5
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	Global("Iaremove3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,90)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!StateCheck(Player6,STATE_STUNNED)
	!StateCheck(Player6,STATE_HELPLESS)
	!StateCheck(Player6,STATE_CONFUSED)
	!StateCheck(Player6,STATE_PANIC)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,SCRIPTINGSTATE5)
	!HasItemEquiped("S!sw02",Player6)  // True Sword of Arvoreen +5
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iastun","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(2)
		Global("cried","LOCALS",1)
		HPLT(Myself,20)
	Global("Iaamon06","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaamon06","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // Spell Trigger—Fired
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("Iachainsequencerplayer1","LOCALS",0)
		SetGlobal("Iachainsequencerplayer2","LOCALS",0)
		SetGlobal("Iachainsequencerplayer3","LOCALS",0)
		SetGlobal("Iachainsequencerplayer4","LOCALS",0)
		SetGlobal("Iachainsequencerplayer5","LOCALS",0)
		SetGlobal("Iachainsequencerplayer6","LOCALS",0)
		Continue()
END


IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	TriggerOverride(Player1, Range(Player2, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer1","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	TriggerOverride(Player1, Range(Player3, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer1","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	TriggerOverride(Player1, Range(Player4, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer1","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	TriggerOverride(Player1, Range(Player5, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer1","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	TriggerOverride(Player1, Range(Player6, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer1","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	TriggerOverride(Player2, Range(Player1, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer2","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	TriggerOverride(Player2, Range(Player3, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer2","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	TriggerOverride(Player2, Range(Player4, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer2","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	TriggerOverride(Player2, Range(Player5, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer2","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	TriggerOverride(Player2, Range(Player6, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer2","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	TriggerOverride(Player3, Range(Player1, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer3","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	TriggerOverride(Player3, Range(Player2, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer3","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	TriggerOverride(Player3, Range(Player4, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer3","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	TriggerOverride(Player3, Range(Player5, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer3","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	TriggerOverride(Player3, Range(Player6, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer3","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	TriggerOverride(Player4, Range(Player1, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer4","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	TriggerOverride(Player4, Range(Player2, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer4","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	TriggerOverride(Player4, Range(Player3, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer4","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	TriggerOverride(Player4, Range(Player5, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer4","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	TriggerOverride(Player4, Range(Player6, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer4","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	TriggerOverride(Player5, Range(Player1, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer5","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	TriggerOverride(Player5, Range(Player2, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer5","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	TriggerOverride(Player5, Range(Player3, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer5","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	TriggerOverride(Player5, Range(Player4, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer5","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	TriggerOverride(Player5, Range(Player6, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer5","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	CheckStatLT(Player1,90,RESISTFIRE)
	CheckStatLT(Player1,90,RESISTMAGIC)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckStatGT(Player1,0,MINORGLOBE)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player1,WIZARD_SPELL_TURNING)
	TriggerOverride(Player6, Range(Player1, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer6","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	CheckStatLT(Player2,90,RESISTFIRE)
	CheckStatLT(Player2,90,RESISTMAGIC)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckStatGT(Player2,0,MINORGLOBE)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player2,WIZARD_SPELL_TURNING)
	TriggerOverride(Player6, Range(Player2, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer6","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	CheckStatLT(Player3,90,RESISTFIRE)
	CheckStatLT(Player3,90,RESISTMAGIC)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckStatGT(Player3,0,MINORGLOBE)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player3,WIZARD_SPELL_TURNING)
	TriggerOverride(Player6, Range(Player3, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer6","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	CheckStatLT(Player4,90,RESISTFIRE)
	CheckStatLT(Player4,90,RESISTMAGIC)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckStatGT(Player4,0,MINORGLOBE)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player4,WIZARD_SPELL_TURNING)
	TriggerOverride(Player6, Range(Player4, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer6","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	CheckStatLT(Player6,90,RESISTFIRE)
	CheckStatLT(Player6,90,RESISTMAGIC)
	CheckStatLT(Player5,90,RESISTFIRE)
	CheckStatLT(Player5,90,RESISTMAGIC)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(Player6,0,MINORGLOBE)
	!CheckStatGT(Player5,0,MINORGLOBE)
	!CheckSpellState(Player6,WIZARD_SPELL_TURNING)
	!CheckSpellState(Player5,WIZARD_SPELL_TURNING)
	TriggerOverride(Player6, Range(Player5, 15))
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencerplayer6","LOCALS",1)
		Continue()
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer1","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player1)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer2","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player2)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer3","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player3)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer4","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player4)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer5","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player5)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer6","LOCALS",6)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player6)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer1","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player1)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer2","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player2)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer3","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player3)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer4","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player4)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer5","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player5)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer6","LOCALS",5)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player6)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer1","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player1)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer2","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player2)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer3","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player3)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer4","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player4)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer5","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player5)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer6","LOCALS",4)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player6)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer1","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player1)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer2","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player2)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer3","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player3)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer4","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player4)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer5","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player5)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer6","LOCALS",3)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player6)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer1","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player1)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer2","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player2)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer3","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player3)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer4","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player4)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer5","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player5)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer6","LOCALS",2)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player6)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaoracle","LOCALS")
	See([PC])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("truesight","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("truesight","LOCALS",1)
		SetGlobalTimer("Iaoracle","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_ORACLE)  // SPWI515.SPL (Oracle)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaoracle","LOCALS")
	See(SecondNearest([PC]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("truesight","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("truesight","LOCALS",1)
		SetGlobalTimer("Iaoracle","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_ORACLE)  // SPWI515.SPL (Oracle)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove2","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove2","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iaremove2","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!StateCheck(Myself,STATE_HELPLESS)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Global("Iaremove2","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove2","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	GlobalLT("truesight","LOCALS",2)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaoracle","LOCALS")
	Detect([PC])
	!See([PC])
THEN
	RESPONSE #100
		IncrementGlobal("truesight","LOCALS",1)
		SetGlobalTimer("Iaoracle","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_ORACLE)  // SPWI515.SPL (Oracle)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iaamon08","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaamon08","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap1nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player1)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	Global("Iacastbreach","LOCALS",0)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap2nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player2)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	Global("Iacastbreach","LOCALS",0)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap3nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player3)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	Global("Iacastbreach","LOCALS",0)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap4nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player4)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	Global("Iacastbreach","LOCALS",0)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap5nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player5)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	Global("Iacastbreach","LOCALS",0)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	GlobalLT("Iareversal","LOCALS",3)
	GlobalGT("Iap6nr","GLOBAL",0)
	HasItem("scrl8g",Myself)  // Ruby Ray of Reversal
THEN
	RESPONSE #100
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		UseItem("scrl8g",Player6)  // Ruby Ray of Reversal
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	Global("Iacastbreach","LOCALS",0)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (Breach)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove3","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove3","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove3","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	See(SixthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove4","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove4","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	See(FifthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove4","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove4","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	See(FourthNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove4","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove4","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	See(ThirdNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove4","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove4","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	See(SecondNearest([PC]))
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove4","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove4","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iastun","LOCALS",2)
	See([PC])
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
	HPLT(LastSeenBy(Myself),90)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
	!CheckSpellState(LastSeenBy(Myself),PERFORM_RITUAL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("S!sw02",LastSeenBy(Myself))  // True Sword of Arvoreen +5
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	Global("Iaremove4","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iaremove4","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaamon03","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaamon03","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // Poseidon's Wrath +5
	GlobalLT("Iaamon03","LOCALS",2)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END


IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer1","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player1)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer2","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player2)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer3","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player3)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer4","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player4)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer5","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player5)
END

IF
	Global("Iachainsequencer","LOCALS",0)
	Global("Iachainsequencerplayer6","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,1)
	!StateCheck(Myself,STATE_HELPLESS)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iachainsequencer","LOCALS",1)
		SpellNoDecRES("SPWIJ01D", Player6)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	Global("Iachainlight","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iachainlight","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	Global("Iachainlight","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iachainlight","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	Global("Iachainlight","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iachainlight","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iaamon02","LOCALS",3)
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon02","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",0)
	Allegiance(Myself,ENEMY)
	Global("Iaamon01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("chase","LOCALS",TEN_ROUNDS)
		SetGlobal("partyfled","LOCALS",1)
END

IF
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Global("partyfled","LOCALS",1)
	GlobalTimerNotExpired("chase","LOCALS")
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	Global("Iaamon01","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	GlobalTimerExpired("chase","LOCALS")
	Global("partyfled","LOCALS",1)
	Global("Iaamon01","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaamon01","LOCALS",0)
		SetGlobal("Iaamon02","LOCALS",0)
		SetGlobal("Iaamon03","LOCALS",0)
		SetGlobal("Iaamon04","LOCALS",0)
		SetGlobal("Iaamon05","LOCALS",0)
		SetGlobal("Iaamon07","LOCALS",0)
		SetGlobal("Iaamon08","LOCALS",0)
		SetGlobal("Iaamon09","LOCALS",0)
		SetGlobal("Iaamon10","LOCALS",0)
		SetGlobal("Iacastbreach","LOCALS",0)
		SetGlobal("Iaamon12","LOCALS",0)
		SetGlobal("truesight","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iaremove2","LOCALS",0)
		SetGlobal("Iaremove3","LOCALS",0)
		SetGlobal("Iastun","LOCALS",0)
		SetGlobal("Iaskin","LOCALS",0)
		SetGlobal("Iachainlight","LOCALS",0)
		SetGlobal("Iachainsequencer","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaamon10","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaamon10","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!HasBounceEffects(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	GlobalLT("Iaamon10","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon10","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaamon12","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaamon12","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // Mordenkainen's Sword
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iaamon12","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iaamon12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	Global("Iaamon13","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaamon13","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),1,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	Global("Iaamon13","LOCALS",1)
	HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Global("Iaamon13","LOCALS",1)
	ActionListEmpty()
	!HasItem("melfmet",Myself)  // Melf's Minute Meteor
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

